### PR TITLE
[WIP] feat: add `openOnKeyPress` and `closeOnKeyPress` options for Dropdown

### PR DESCRIPTION
**Pull request by ncoden**
### Add options:
- **`openOnKeyPress`** - {string|boolean} [`'auto'`]
    Allows `space` or `enter` keys on the anchor to open the dropdown.
    If set to `auto` (default), this is enabled for all anchors but `<input>` and `<textarea>`
- **`closeOnKeyPress`** - {boolean} [`true`]
   Allows `escape` key to close the dropdown.

### ⚠️ Require:
- [x] https://github.com/zurb/foundation-sites/pull/10715 fix: prevent "space" on input to open dropdown (@Owlbertz)

### 🚧 Work in progress
- [x] `openOnKeyPress` and `closeOnKeyPress` options
- [ ] Unit tests
- [ ] Documentation

### CODE REVIEW

**Comment by Owlbertz** [comment]
What scenario do you image where this option would be something other than it will be when #10715 gets merged?

**Comment by ncoden** [comment]
You may want on a custom component to force/prevent `space` to open and focus the dropdown. I don't have a scenario in mind but I thinik this is possible, since not only `<input>` and `<textarea>` can receive keyboard interactions.

**Comment by DanielRuf** [comment]
Just docs and tests are to be done at the moment?

**Comment by ncoden** [comment]
Yes.

**Comment by DanielRuf** [comment]
Do we need a rebase?

**Comment by ncoden** [comment]
It's still WIP. I'll take care of this after v6.5 is fully release.

**Comment by SassNinja** [comment]
Doesn't seem to be relevant anymore or rather seems to have been done in the meantime

**Pull request closed without merging**
