### PR TITLE
Add .top-bar-title class

### PR DESCRIPTION
**Pull request by brettsmason**
Adds .top-bar-title class to the title as per issue [7907](https://github.com/zurb/foundation-sites/issues/7907).

### CODE REVIEW

**Comment by gakimball** [comment]
Awesome, thanks! :) Just one bit of feedback.

By referencing `$grid-column-gutter`, top bar has a dependency on the grid. Usually this doesn't matter, but we avoid having components reference each others' variables. Instead, can you add a dedicated variable for this? Maybe `$topbar-title-spacing`? That would be great.

**Comment by brettsmason** [comment]
@gakimball No problem I'll do that now. Do you think it should be padding or would margin make more sense?

**Comment by gakimball** [comment]
@brettsmason I don't know that it will make a difference, assuming people are never setting a background color on the thing. I suppose do margin to be safe.

**Comment by gakimball** [comment]
Thanks!

**Pull request merged**
