### PR TITLE
Docs: Grammatical changes to flexbox page

### PR DESCRIPTION
**Pull request by IamManchanda**
Current version

`Foundation components use a combination of floats, vertical alignment, table cells, and various other CSS hacks to get layouts looking right. These days, there's a better way... if you have the browser support!`

My Updated version 

`Foundation components use a combination of floats, vertical alignment, table cells, and various other CSS hacks to get layouts looking right. These days though, there's a better way... if you are happy with the below browser support!`

@ncoden @kball .... just a first ( **and safe** ) pull request .... 
if you happy with this change, approve and merge it, 
if you dont want this, simply close it :smiling_imp:

### CODE REVIEW

**Comment by IamManchanda** [comment]
Oh see i did a mistake @ncoden @kball .... why these other changes are showing up

**Comment by kball** [comment]
@IamManchanda As this is a docs change, it should target master, not develop... looking at this list of commits, I think what you're seeing is a gap between current master and develop; master has a bunch of docs updates that haven't been back-merged yet.

Closing - please reopen against `master`

**Comment by IamManchanda** [comment]
So you meant to say i should do this 

`$ git remote add upstream git@github.com:zurb/foundation-sites.git -b master`

instead of 

`$ git remote add upstream git@github.com:zurb/foundation-sites.git` ?

**Comment by kball** [comment]
@IamManchanda I don't think so... that would change your remote, but you should be able to check out any particular branch from the remote... and from what I can see you were branched from master.  Looking at the guide you said you followed, I believe the error was likely in step 3. We have a multibranch system, and our most common PRs (simple code fixes) are against develop, so that is the default branch. However, docs changes should go to master, so make sure you change the base to master

**Comment by IamManchanda** [comment]
yup just figured it out! Thanks a lot for your kind help :smiley:

**Pull request closed without merging**
