### PR TITLE
ci: add Snyk

### LINKED ISSUE #11638: [security] regular checks for commits and PRs using Snyk
## Description

We should run some checks with Snyk for every PR (new dependencies and vulnerabilities).

## Possible Solution

Integrate Snyk into our GitHub PR and commit checks.
https://snyk.io/
https://snyk.io/docs/github
https://snyk.io/docs/ci

Closes #11439.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This PR adds Snyk to the CI but we have to configure it regarding auth and the project on snyk.io @joeworkman

- Closes https://github.com/foundation/foundation-sites/issues/11638

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by joeworkman** [comment]
Do we still need this? I integrated Snyk into GH. This is causing the travis build to fail because it needs to authenticate with snaky.io.

**Comment by DanielRuf** [comment]
Snyk has also an integration on the marketplace and this is controlled at snyk.io afaik.

This should not be part of CI which is just for running the normal tests so far. All others services should use their respective integration.

**Comment by joeworkman** [comment]
All of that has been done already. I am close this PR then...

**Comment by DanielRuf** [comment]
Well, but the policy file might be needed.

cc @lirantal

**Comment by lirantal** [comment]
I indeed do see that there's a GitHub CI integration here which means it will break the build when new vulnerabilities are introduced in packages:
image

The GitHub integration could be considered a better approach because it will also provide you with:
- automatic pull requests open to upgrade vulnerable libraries
- automatic pull requests open to upgrade outdated libraries

However, those two bullets are dependent on whether you indeed turned these features on in the integration settings page so you should make sure that this happens indeed. The slight concern with them that is unique to this repository though is that you use multiple lockfiles and Snyk will probably just identify and pick one of them to relock when it suggests an upgrade.

kudos on stepping up the security level 👏

**Comment by DanielRuf** [comment]
> Snyk has also an integration on the marketplace and this is controlled at snyk.io afaik.

Please add/invite me to the org on snyk.io @joeworkman

> However, those two bullets are dependent on whether you indeed turned these features on in the integration settings page so you should make sure that this happens indeed.

**Pull request closed without merging**
