### PR TITLE
chore: various Travis tests improvements

### PR DESCRIPTION
**Pull request by ncoden**
Various cleaning & improvements for units & browserstack tests running with Travis-CI.

### Changes:
* bb41a66 use ENV for browserstack authentification
* 3407f06 use `browserstack-runner` as a devDependency
* a6e1428 move browserstack tests to its own Travis job
* 14b4e12 make headless-chrome tests run in all Travis environments (with `--no-sandbox`)

### Todo:
* [x] Update and complete BrowserStack browser list

### Note about the headless-chrome bug
Bug with the Linux sandbox SUID can appear or not depending on the runner Kernel version (see https://gist.github.com/ncoden/6e79cef6f62608fd9443ea2a601806bc). Using `no-sandbox` with chrome is generally not recommended for security reasons, but recommended in this case by Travis.

See:
* https://docs.travis-ci.com/user/chrome#Sandboxing
* travis-ci/travis-ci#8836
* GoogleChrome/puppeteer#515

### CODE REVIEW

**Comment by DanielRuf** [comment]
Using encrypted secrets with the Travis CLI would also be a viable solution imo.

**Comment by ncoden** [comment]
Actually I’ll change that. Keys cannot be encrypted or they are disabled for Pull requests. See the browserstack job:

**Comment by DanielRuf** [comment]
Hm, did they change that at Travis CI GmbH? https://blog.travis-ci.com/2013-06-10-secure-env-in-pull-requests

**Comment by DanielRuf** [comment]
Ah ok, seems there are some misunderstandings on my side. Not sure but other projects use encrypted values and also run browserstack tests when I create a PR from my forks afaik.

**Comment by ncoden** [comment]
@DanielRuf What are these projects ?

**Comment by DanielRuf** [comment]
These are mostly projects which use saucelabs. But interestingly they all show now this notice which I do not remember.

Probably because they often use the JWT addon.
https://docs.travis-ci.com/user/sauce-connect/

https://docs.travis-ci.com/user/jwt
> The JWT addon is deprecated and will be discontinued on April 17, 2018.

https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated

Hm, so no direct way through Travis CI to get these running on pull requests.

Not so great for most OS projects.

**Comment by ncoden** [comment]
Currently waiting for @rafibomb to give me access to our browserstack account.

**Comment by ncoden** [comment]
Got them (thanks @brettsmason).
You'll never imagine how hard it is to find a valid browser configuration with `browserstack-runner`. Their documentation is incomplete (not talking about `browserstack.json`), and even going into the code does not help you to understand what value they are expecting.

Anyway, we'll go for:
* Latest and previous versions of Chrome, Firefox, Opera, Safari (macOs), Edge (Windows)
* Internet Explorer 11, 10, 9
* Safari for iOS 11.0, 10.3, 9.3, 8.3, 7.1
* Android Browser for android 7.0, 6.0, 5.0, 4.4
* Latest version of IE Mobile

**Comment by DanielRuf** [comment]
So still some tests that fail.

Also related: https://github.com/zurb/foundation-sites/issues/11074

**Comment by ncoden** [comment]
> [x] Update and complete BrowserStack browser list

Done. We had 12 tests before (3 x 4), 18 now (1 x 18).

**Comment by ncoden** [comment]
> All tests done, failures: NaN.

Too much failures for BrowserStack, it gave up in counting them 😄

**Comment by DanielRuf** [comment]
> Too many failures for BrowserStack, it gave up in counting them

Oh, that is crazy.

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
