### PR TITLE
#11821 give deeplink-smudge a offset to prevent scrolling behind a fixed menu at top of page.

### LINKED ISSUE #11821: give deeplink-smudge a deeplink-offset to prevent scrolling behind a fixed menu at top of page.
## What is missing?

if i give a data-deeplink-smudge-offset to the accordeon i expect the page to scroll the accordeon in viewport minus this offset
...

## What is wrong now ?

Right now when you have a menubar that is FIXED  and the page scrolls up to scroll the accordeon into the top of the view it is hidden behind the menubar. When i'm able to give it a offset i can make sure all accordeons that scroll into view will not be hidden
...

## Possible Solution

Create an extra data propertie for **accordeons data-deeplink-smudge-offset** and add it to the animation that scrolls the element. 
` $('html, body').animate({ scrollTop: offset.top - deeplink-offset }, this.options.deepLinkSmudgeDelay);`
...

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): All
- Device, Operating System and version: All

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by Lefthandmedia**
…

## Description

...When using using deeplink smudge on a accordeon the requested anchor scrolls to the top of the page. If there is a sticky element at the top of the page (like a sticky navigation) the requested anchor is hidden when it scrolls to the top of the page. To prevent this you can add a data-attribute **data-deep-link-smudge-offset** to give the scroll up animation an offset to prevent this.

- Closes  https://github.com/foundation/foundation-sites/issues/11821

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [x] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by DanielRuf — APPROVED** [review]
LGTM

Thanks for your contribution to Foundation Sites

**Comment by Lefthandmedia** [comment]
Travis needs to do its work better. 
`The command "curl -o- -L https://yarnpkg.com/install.sh | bash" failed and exited with 1 during .`
has nothing to do with this PR

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/offset-data-deep-link-how-to/678/3

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-for-sites-6-6-2/1936/1

**Pull request merged**
