### PR TITLE
Fix data-click-open tooltip behavior

### PR DESCRIPTION
**Pull request by kball**
Fixes issue #8300.  Test added in tooltip docs

### CODE REVIEW

**Comment by designerno1** [comment]
if i click on the `tooltip will stay open` and then click again on the `tooltip will stay open` and then again on the `tooltip will stay open` it stays close.
On touch device if you hit `tooltip will stay open` multiple times it gets a weired behavor of sometimes show it sometimes close it or sometimes show and close it.
But i don't know if these multiple clicks are commen use

**Comment by kball** [comment]
interesting... I'll take a look

**Comment by kball** [comment]
@designerno1 I'm able to reproduce... but I can also reproduce in develop branch, so I think it is a different bug.  I'll see if I can find a quick fix

**Comment by designerno1** [comment]
@kball forget my `touch issue` checked again and it works. but the first happend again on click

**Comment by kball** [comment]
@designerno1 Yeah I see the click issue as well.  Its only there if you never 'defocus' the tooltip... clicking elsewhere and then back on the tooltip always seems to work.  I'm not seeing any obvious ways to address it, so since it isn't a regression my inclination is to file it as a separate issue and not have it be a blocker for this PR.  Thoughts?

**Comment by colin-marshall** [comment]
Agreed on merging this and opening a new issue for tooltip staying closed. I'll go ahead and do that since 3 of us seem to be in consensus on this.

**Pull request merged**
