### PR TITLE
chore: fix & update dependencies

### PR DESCRIPTION
**Pull request by ncoden**
### 📦  Fix & update package versions:
* **Use permissive selector for all compatible dependencies versions**
  We actually support jQuery `>= v2.2.0` and what-input `>= v4.1.0`. There is no point with using the "minor only" selector for dependencies when we do support older versions. See _Dependencies migrations_ below.
* **Update all devDependencies to latest versions**
  Using [David CLI](https://www.npmjs.com/package/david). See _DevDependencies migrations_ below.
* **Remove unused devDependencies**
  Remove `process-nextick-args`, `gulp-ruby-sass` and `vinyl-source-stream`
* **Update dependencies lockfiles**
  ~~Using [Synp](https://www.npmjs.com/package/synp) to get synchronized lockfiles~~
  Install depedencies with `yarn` (for `yarn.lock`) then generate `package-lock.json` with `npm i --lock-file-only`. Locked dependencies should be the sames but with the perfect lockfile format for each package manager.
* **Update required Node version to `v6.4.0`**
  Node v6.4.0 is required by `puppeteer` in `mocha-headless-chrome`. All others packages works with Node v4.0

### 🚀  New packages:
* **Switch from `babel-plugin-*` to `babel-preset-env`, `vinyl-source-stream`**
  This is now the recommended way to deal with babel plugins. This is better than simply updating babel plugins.

### 📝  Dependencies changelogs
* [x] **jQuery** `>=3.0.0` -> `>=2.2.0` (locked at `3.3.1`)
  There should not be any impact since Foundation was compatible with v2.2.0 all along. See https://jquery.com/upgrade-guide/3.0/#browser-support for reference.
* [x] **what-input**: `^4.1.3` -> `>=4.1.3` (locked at `5.0.5`)
  No migration needed. See https://github.com/ten1seven/what-input#changes-from-v4.

### 📝  DevDependencies migrations
* [x] **_package name_** _`old version`_ -> _`new version`_
  _the changes you made to migrate to the new version, if any_
 _[url to the release notes](https://example.com)_
* [x] **autoprefixer**            `^6.7.7` -> `^8.2.0`
* [x] **chalk**                   `^1.1.1` -> `^2.3.2`
* [x] **clipboard**               `^1.7.1` -> `^2.0.0`
  Rename `Clipboard` to `ClipboardJS` (see: https://github.com/zurb/foundation-docs/pull/33)
  Changelog: https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.0
* [x] **doiuse**                  `^2.6.0` -> `^4.1.0`
* [x] **gulp-add-src**            `^0.2.0` -> `^1.0.0`
* [x] **gulp-babel**              `^6.1.1` -> `^7.0.1`
* [x] **gulp-cache-bust**         `~1.0.2` -> `^1.3.0`
  Set the `basePath` option to target the used paths as required from v1.1.0
  Changelog: https://github.com/furzeface/gulp-cache-bust/releases/tag/1.1.0
* [x] **gulp-filter**             `^4.0.0` -> `^5.1.0`
* [x] **gulp-prompt**             `^0.2.0` -> `^1.0.1`
* [x] **gulp-replace**            `^0.5.4` -> `^0.6.1`
* [x] **gulp-rsync**              `^0.0.7` -> `0.0.8`
* [x] ~~**gulp-ruby-sass**~~          `^2.0.6` -> removed
* [x] **gulp-sass**               `^2.1.0` -> `^v4.0.1`
* [x] **gulp-uglify**             `^2.1.2` -> `^3.0.0`
* [x] **gulp-zip**                `^3.2.0` -> `^4.1.0`
* [x] **inquirer**                `^2.0.0` -> `^5.2.0`
* [x] **mocha**                   `^3.4.2` -> `^5.0.5`
* [x] **mocha-headless-chrome**      `^1.8.2` -> `^1.8.3`
* [x] ~~**process-nextick-args**~~    `^1.0.7` -> removed
* [x] **require-dir**             `^0.3.2` -> `^1.0.0`
* [x] **run-sequence**            `^1.1.4` -> `^2.2.1`
  Migrate all tasks to the new run-sequence API to ensure that the tasks are run in the right order 
  Changelog: https://github.com/OverZealous/run-sequence/blob/master/CHANGELOG.md
* [x] **sass-true**               `^2.2.2` -> `^4.0.0`
* [x] **sassy-lists**              `3.0.0` -> `^3.0.1`
* [x] **sinon**                  `^1.17.7` -> `^4.5.0`
* [x] **touch**                   `^1.0.0` -> `^3.1.0`
* [x] ~~**vinyl-source-stream**~~    `^1.1.0` -> removed
* [x] **webpack**                 `3.5.5`  -> `^4.5.0`
  Set new `mode` option to `development`
* [x] **webpack-stream**          `^3.2.0` -> `^4.0.3`
* [x] **yargs**                   `^6.6.0` -> `^11.0.0`

### ⚠️  Todo
* [x] Migrate devDependencies
* [x] Migrate to Webpack 4
* [x] Check checksums
* [ ] ~~Update Motion-UI for zurb/motion-ui#100~~ delayed to an other PR.

### CODE REVIEW

**Comment by DanielRuf** [comment]
`gulp-rsync` does not need the caret semver selector? Would be like a locked version in the current case.

**Comment by ncoden** [comment]
@DanielRuf This was set by `david`. I guess it's because `gulp-rsync` is still in a pre-release version `0.*` and according to SemVer, this is instable and API changes can happen in minor releases. So I would keep it like this.

**Comment by DanielRuf** [comment]
Got a few of these:

```
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-jd5MkIUlbbmb07nXH0DT3y7rDVtkzDi4XZOUVWAer8ajmF/DTSSbl5oNFyDOl/OXA33Bl79+ypHhl2pN20VeOQ== integrity checksum failed when using sha512: wanted sha512-jd5MkIUlbbmb07nXH0DT3y7rDVtkzDi4XZOUVWAer8ajmF/DTSSbl5oNFyDOl/OXA33Bl79+ypHhl2pN20VeOQ== but got sha1-9HPdR+AnegjijpvsWu6wR1HwuMk=. (128119 bytes)
```

Because of sha512 hashes but I guess sha1 is still used by default by npm.

**Comment by ncoden** [comment]
> [ ]  Check checksums

**Comment by DanielRuf** [comment]
```
Daniel@Daniel-MSI MINGW64 ~/GITHUB/foundation-sites (ncoden-chore/update-dependencies)
$ npm i
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 115 packages in 16.602s

Daniel@Daniel-MSI MINGW64 ~/GITHUB/foundation-sites (ncoden-chore/update-dependencies)
$ npm outdated
Package                Current         Wanted  Latest  Location
foundation-docs          0.2.1            git     git  foundation-sites
parker           1.0.0-alpha.0  1.0.0-alpha.0  0.0.10  foundation-sites
yargs                   11.0.0         11.1.0  11.0.0  foundation-sites
```

**Comment by DanielRuf** [comment]
The ajv issue might be an npm issue, see https://github.com/epoberezkin/ajv/issues/708

**Comment by DanielRuf** [comment]
```
$ npm i
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-jd5MkIUlbbmb07nXH0DT3y7rDVtkzDi4XZOUVWAer8ajmF/DTSSbl5oNFyDOl/OXA33Bl79+ypHhl2pN20VeOQ== integrity checksum failed when using sha512: wanted sha512-jd5MkIUlbbmb07nXH0DT3y7rDVtkzDi4XZOUVWAer8ajmF/DTSSbl5oNFyDOl/OXA33Bl79+ypHhl2pN20VeOQ== but got sha1-9HPdR+AnegjijpvsWu6wR1HwuMk=. (128119 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-wGUIVQXuehL5TCqQun8OW81jGzAWycqzFF8lFp+GOM5BXLYj3bKNsYC4daB7n6XjCqxQA/qgTJ+8ANR3acjrog== integrity checksum failed when using sha512: wanted sha512-wGUIVQXuehL5TCqQun8OW81jGzAWycqzFF8lFp+GOM5BXLYj3bKNsYC4daB7n6XjCqxQA/qgTJ+8ANR3acjrog== but got sha1-O7xCdd1YTMGxCAm4nU6LY6aednU=. (2194 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-9nCNoAOBCUahdG+uyqS1XBwS8u1YwXashUYt7T165b3MsDiLYqLMCFwhabzIET9qf0UTP2GLGYM48S9Ghtv/fQ== integrity checksum failed when using sha512: wanted sha512-9nCNoAOBCUahdG+uyqS1XBwS8u1YwXashUYt7T165b3MsDiLYqLMCFwhabzIET9qf0UTP2GLGYM48S9Ghtv/fQ== but got sha1-gJmtGeCMeBnbQf+cSjrE249QpvA=. (247000 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-YjuID3+QdvdqNB0fZmZKvb6hsGhlMFqkblgwB+yg6QiUI7dAoJzloThcMtkzjJj8/zbADF+ePPB4sWbWVOYjGw== integrity checksum failed when using sha512: wanted sha512-YjuID3+QdvdqNB0fZmZKvb6hsGhlMFqkblgwB+yg6QiUI7dAoJzloThcMtkzjJj8/zbADF+ePPB4sWbWVOYjGw== but got sha1-6sJkxfx3/y53kB43AQ7PQ5jiIWk=. (16583 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
 registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-RdyZWOKFxLoYZUYDTATEWDNFy06+FppokbfBfNd15vp8VyA8iiANYD+ZC3prIjqoVL+mEWSSPRi24FbayFDQxw== integrity checksum failed when using sha512: wanted sha512-RdyZWOKFxLoYZUYDTATEWDNFy06+FppokbfBfNd15vp8VyA8iiANYD+ZC3prIjqoVL+mEWSSPRi24FbayFDQxw== but got sha1-WNu+pCTgTn6TXetXZUzCP/ffwnw=. (23709 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-3MM3UjZ5p8EJrYpG7s+29HAI9G7sTzKEe4+w37Dg0QP7qL4XGsV+Q2xet2cE37AqdgN1OtYQB6Vl98YiPV3PgA== integrity checksum failed when using sha512: wanted sha512-3MM3UjZ5p8EJrYpG7s+29HAI9G7sTzKEe4+w37Dg0QP7qL4XGsV+Q2xet2cE37AqdgN1OtYQB6Vl98YiPV3PgA== but got sha1-4ijjOGuTh6RxAAemQfEnsAvkS1I=. (202723 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-jd5MkIUlbbmb07nXH0DT3y7rDVtkzDi4XZOUVWAer8ajmF/DTSSbl5oNFyDOl/OXA33Bl79+ypHhl2pN20VeOQ== integrity checksum failed when using sha512: wanted sha512-jd5MkIUlbbmb07nXH0DT3y7rDVtkzDi4XZOUVWAer8ajmF/DTSSbl5oNFyDOl/OXA33Bl79+ypHhl2pN20VeOQ== but got sha1-9HPdR+AnegjijpvsWu6wR1HwuMk=. (128119 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-zHo8v+otD1J10j/tC+VNoGK9keCuByhKovAvdn74dmxJl9+mWHnx6EMsDN4lgRoMI/eYo2nchAxniIbUPb5onw== integrity checksum failed when using sha512: wanted sha512-zHo8v+otD1J10j/tC+VNoGK9keCuByhKovAvdn74dmxJl9+mWHnx6EMsDN4lgRoMI/eYo2nchAxniIbUPb5onw== but got sha1-NEKlCPr8KFAEhv7qmUCWduTuWm8=. (5993 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
```

**Comment by DanielRuf** [comment]
```
[22:48:37] Supercollider: processed accessibility.html in 0.10 s
fs.js:648
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Daniel\GITHUB\foundation-sites\docs\pages\assets\css\docs.css'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.self.MD5 (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\cachebust\lib\cachebust.js:35:23)
    at Object.exports.busted (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\cachebust\lib\cachebust.js:64:40)
    at C:\Users\Daniel\GITHUB\foundation-sites\node_modules\gulp-cache-bust\index.js:47:40
    at C:\Users\Daniel\GITHUB\foundation-sites\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:513:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-sites@6.4.3 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-sites@6.4.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by DanielRuf** [comment]
We have t update the gulp tasks as `run-sequence` works different now.

**Comment by DanielRuf** [comment]
Fixed the wrongly calculated basePath of gulp-cache-bust. Also see https://github.com/furzeface/gulp-cache-bust/issues/17

I did not update all Gulp tasks but we may have to do it.
The order is not kept and we should use run-sequence in more places.

**Comment by ncoden** [comment]
@DanielRuf Thanks ! Did you checked changelogs or just repaired where there was errors ?
Please check (and add migrations notices) the devDependencies list above for the packages you checked.

**Comment by ncoden** [comment]
> return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

I got this error when switching between branch without reinstalling packages. Sometimes NPM do not reinstall everything and I have to delete `node_modules`.

**Comment by DanielRuf** [comment]
> Did you checked changelogs or just repaired where there were errors ?
> Please check (and add migrations notices) the devDependencies list above for the packages you checked.

Just checked the changes based on the current readme.

Will check all now.

**Comment by ncoden** [comment]
> Just checked the changes based on the current readme. Will check all now.

I can take care of the migrations. Please just update "DevDependencies migrations" with the changes you already made.

**Comment by DanielRuf** [comment]
Getting `Uncaught TypeError: Cannot read property 'getAttribute' of undefined` at http://localhost:3000/kitchen-sink.html

**Comment by ncoden** [comment]
Will look at this tomorrow

**Comment by DanielRuf** [comment]
Mh, do we need to call some callbacks in the deploy scripts? Not sure if the scripts run in the right order and in sync or async. The new run-sequence is so irritating =/

At least `test`, `start` and the other scripts so far work.

**Comment by DanielRuf** [comment]
> Getting Uncaught TypeError: Cannot read property 'getAttribute' of undefined at http://localhost:3000/kitchen-sink.html

It's an issue with the Magellan instance there.

**Comment by DanielRuf** [comment]
clipboard Clipboard => ClipboardJS https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.0
run-sequence https://github.com/OverZealous/run-sequence/blob/master/CHANGELOG.md

**Comment by DanielRuf** [comment]
gulp-cache-bust needs `basePath` set https://github.com/furzeface/gulp-cache-bust/issues/17
https://github.com/furzeface/gulp-cache-bust/pull/14/files#diff-168726dbe96b3ce427e7fedce31bb0bcR23

**Comment by DanielRuf** [comment]
Rest looks good so far 👍

**Comment by ncoden** [comment]
I'll have to verify all devDependencies changlogs anyway. Could ypu complete the PR message with what you already verfied  for now ?

**Comment by DanielRuf** [comment]
`deploy` generally seems to fail sometimes if I see it correctly. Can you reproduce this?

```
✖ 2 problems (0 errors, 2 warnings)

undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadInputSourceMapFromLocalUri (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\apply-source-maps.js:177:15)
    at extractInputSourceMapFrom (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\apply-source-maps.js:116:17)
    at fetchAndApplySourceMap (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\apply-source-maps.js:79:10)
    at doApplySourceMaps (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\apply-source-maps.js:57:14)
    at applySourceMaps (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\apply-source-maps.js:33:5)
    at Object.callback (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\read-sources.js:25:12)
    at doInlineImports (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\read-sources.js:200:25)
    at Object.callback (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\read-sources.js:324:14)
    at doInlineImports (C:\Users\Daniel\GITHUB\foundation-sites\node_modules\clean-css\lib\reader\read-sources.js:200:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-sites@6.4.4 deploy: `gulp deploy`
```

**Comment by DanielRuf** [comment]
Weird, `dist/css/foundation-float.css.map` and a few other have 0 bytes.

**Comment by DanielRuf** [comment]
> Weird, dist/css/foundation-float.css.map and a few other have 0 bytes and cause this.

Oh wow, disabled the realtime scanner of Windows Defender, now it seems to work. AV solutions are really bad in general.

**Comment by ncoden** [comment]
> * [x] Migrate devDependencies

There's only Webpack 4 to migrate now

**Comment by ncoden** [comment]
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("fade")) instead.

**Comment by DanielRuf** [comment]
> DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
> in Sass 4.0. Use call(get-function("fade")) instead.

I guess these are also part of the deprecations that we already saw in some issues because the Sass API has changed.

**Comment by ncoden** [comment]
> I guess these are also part of the deprecations that we already saw in some issues because the Sass API has changed.

True. But I don't remember seeing this one.

**Comment by ncoden** [comment]
> Getting Uncaught TypeError: Cannot read property 'getAttribute' of undefined at http://localhost:3000/kitchen-sink.html

I cannot reproduce it :/

**Comment by DanielRuf** [comment]
> I cannot reproduce it :/

Did you scroll a bit and then reload the page? Got it at least there but can also test later today again if it is still relevant.

**Comment by ncoden** [comment]
Ok I can reproduce it.

**Comment by DanielRuf** [comment]
> True. But I don't remember seeing this one.

At least I saw it in the chats with @hal869 
https://github.com/zurb/motion-ui/issues/99

**Comment by hal869** [comment]
> reproduce

Just fyi, still here ... noise, but no harm

**Comment by ncoden** [comment]
> * [x] Migrate to Webpack 4
> * [x] Check checksums

Done.

> * [ ] Update Motion-UI for https://github.com/zurb/motion-ui/pull/100

**Comment by ncoden** [comment]
The magellan bug is unrelated to this issue.

**Comment by DanielRuf** [comment]
> The magellan bug is not caused by this PR. I can reproduce it on develop.

Sure, just wanted to mention it and my other findings.

**Comment by ncoden** [comment]
> The magellan bug is not caused by this PR. I can reproduce it on develop.

@DanielRuf See https://github.com/zurb/foundation-sites/pull/11142

**Comment by ncoden** [comment]
* [ ] Update Motion-UI

I'll delay this to an other PR as there is some bugs I would like to resolve in Motion-UI before a release, and Dependabot is not happy with our dependencies still out-of-dates.

@DanielRuf Could you make a final review ?

**Comment by DanielRuf** [comment]
We could also update to webpack 4.5 probably ;-)

Ok, will do so.

**Comment by ncoden** [comment]
> We could also update to webpack 4.5 probably ;-)

True.

**Comment by ncoden** [comment]
Updated dependencies:
* [x] **gulp-sass**               `^2.1.0` -> `^v4.0.1`
* [x] **mocha-headless-chrome**      `^1.8.2` -> `^1.8.3`
* [x] **sass-true**               `^2.2.2` -> `^4.0.0`
* [x] **webpack**                 `3.5.5`  -> `^4.5.0`

Changes are only deprecation of node 4, bug fixes and new features. No migration is required.

**Review by DanielRuf — APPROVED** [review]
Compiled without any issues and kitchensink works. 👍

**Comment by ncoden** [comment]
Thanks @DanielRuf for the review. Good to merge. For now dependencies will be kept up-to-date by Dependabot (thx @dependabot)

**Pull request merged**
