### PR TITLE
chore: provide CJS, ESM and ES6+ bundles

### LINKED ISSUE #11502: [REGRESSION] Fails to minify
## What should happen?
 
Minifying Foundation's code in a React app should succeed, as it has in prior versions.
 
 
## What happens instead?
 
Minifying Foundation's code in a React app fails with the following error:
```
root@51106dca2935:/my-app# yarn build
yarn run v1.9.4
$ react-scripts build
Creating an optimized production build...
Failed to compile.
 
Failed to minify the code from this file: 
 
       ./node_modules/foundation-sites/js/foundation.core.utils.js:24 
 
Read more here: http://bit.ly/2tRViJ9
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@51106dca2935:/my-app# 
```
 
## Steps to Reproduce

How to reproduce:
1. Run `npx create-react-app my-app`
2. Run `cd my-app`
3. Run `yarn add jquery foundation-sites@6.5.0-rc.3`
4. Add `import 'foundation-sites';` to `src/index.js`
5. Run `yarn build`
 
## Context

 
I’d like to be able to use the latest version of Foundation in a React app. This is a regression, as my reproduction steps don't cause the error with Foundation 6.5.0-rc.2.
 
 
## Your Environment

- Foundation version(s) used: 6.5.0-rc.3
- Browser(s) name and version(s): N/A (problem occurs before a browser is involved)
- Device, Operating System and version: Tested in Docker containers `node:10` (Debian) and in `node:10-alpine`
- Link to your project: N/A
 
 
## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by ncoden**
## Description

Provide Foundation in various bundles formats so it can be easily imported and used in all environnements and build processes. This pull request add the following bundles:
* **`foundation.cjs.js` (CommonJS)**
  For older bundlers like Browserify or Webpack 1.

* **`foundation.esm.js` (ES5 in ES Modules)**
  For modern bundlers like Webpack 2+ or Rollup that will use ES Modules via static analysis to make some tree shaking.

* **`foundation.es6.js` (ES6+ in ES Modules)**
  Non-transpiled ES modules for those who want to transpile their code with their own configuration (e.g. for custom targets).

### Changes:
- generate transpiled ES5 (CJS, ESM) and ES6+ bundles at deploiement
- expose the transpiled ES5 bundle to `module`/`jspm`/`jsnext:main` entries
- expose the non-transpiled ES6 bundle to `esnext`

Related to https://github.com/zurb/foundation-sites/pull/11445#issuecomment-416346441
Closes https://github.com/zurb/foundation-sites/issues/11502

## Todo:
- [x] Add some documentation about the bundles.

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- ~~I have added tests to cover my changes (if relevant).~~

### CODE REVIEW

**Comment by ncoden** [comment]
screen shot 2018-09-20 at 23 04 10

Poke @DanielRuf

**Comment by ncoden** [comment]
@SassNinja This is intended. Webpack support the ESM format (and will use the `module` field) but not others ES6 features.

I can add something in the documentation like "in webpack, use the `esnext` field to get the es6+ bundle".

**Comment by ncoden** [comment]
@SassNinja I added the related `package.json` entries. I think that's enough. There's already links to the Webpack documentation and others useful articles in the documentation.

**Comment by mattbag** [comment]
Kudos for the doc page! Great work guys!
I was taking a look at the zurb template updates, is it in the pipeline for you?

**Comment by mattbag** [comment]
I do face more issues (might be because I am not a module expert):

- Case 1
```
import { Tabs } from 'foundation-sites/js/foundation.tabs';
const $tabs = new Tabs($('#tabs'));

import { Dropdown } from 'foundation-sites/js/foundation.dropdown';
const $dropdown = new Dropdown($('#myDropdown'));
```
This works, three shaking seems to be actioning. Only side effect, I have to id everything, as I don't have doc.foundation().

- Case 2
```
import 'foundation-sites';
$(document).foundation();
```
Doesn't work on build, probably .foundation() is three shaken? 
It must be because the bundle size is smaller than pluck import.

**Comment by DanielRuf** [comment]
See the explicit-pieces example file in the zurb template. This should point you to the solutions.

**Comment by DanielRuf** [comment]
Also see https://foundation.zurb.com/sites/docs/javascript.html

**Comment by mattbag** [comment]
You probably want this correction:
```
import { Tabs } from 'foundation-sites/js/foundation.tabs';
const $tabs = new Tabs($singleElement);
```
Because you're also using const, which is probably why it doesn't init multiple using classes selectors.

**Comment by DanielRuf** [comment]
> You probably want this correction:
> 
> ```
> import { Tabs } from 'foundation-sites/js/foundation.tabs';
> const $tabs = new Tabs($singleElement);
> ```
> Because you're also using const, which is probably why it doesn't init multiple using classes selectors.

Not sure what you mean as this is not directly related to the described issue. A string is not a DOM element.

I'm explicitely speaking about covering the use case in the docs in the components (string vs DOM element).

**Comment by mattbag** [comment]
Yes, the line you mentioned above, would solve the selector issue/confusion.

Still, the plugin won't init on a class selector with multiple instances. For that you still need $document.foundation(), right?

**Comment by bb-drummer** [comment]
@mattbag : you can do 

$(elements_selector).foundation()

to apply to specific elements only

**Comment by DanielRuf** [comment]
> Still, the plugin won't init on a class selector with multiple instances. For that you still need $document.foundation(), right?

No, this would need a forEach / each or for loop and every instance has to be initialized.

**Comment by DanielRuf** [comment]
> Yes, just wanted to know if the old way can be done, and if this is the right way:
> 
> ```
> import { Foundation } from 'foundation-sites/js/foundation.core';
> import { Tabs } from 'foundation-sites/js/foundation.tabs';
> $(document).foundation();
> ```

See the explicit pieces example in the js folder of the zurb template.

**Comment by ncoden** [comment]
@mattbag @DanielRuf 
> is there something outdated / inconsistent / wrong in the docs?

Yes. Foundation is based on jQuery and plugins expect a jQuery Element, not a string. Supporting string selector would results in any benefit for the user, and would only decrease the performance of Foundation (users would not be pushed to reuse their jQuery instances).

So there is something wrong in the docs.

**Comment by DanielRuf** [comment]
> So this is in the docs
> 
> ```
> import { Tabs } from 'foundation-sites/js/foundation.tabs';
> const $tabs = new Tabs('#tabs');
> ```

**Comment by DanielRuf** [comment]
See https://foundation.zurb.com/sites/docs/javascript.html

```
import Foundation from 'foundation-sites';
const $dropdown = new Foundation.Dropdown('#mydropdown');
// Or
import { Dropdown } from 'foundation-sites';
const $dropdown = new Dropdown('#mydropdown');
```

**Comment by DanielRuf** [comment]
> So there is something wrong in the docs.

Exactly.

**Comment by bb-drummer** [comment]
@mattbag 

> Yes, just wanted to know if the old way can be done, and if this is the right way:
> 
> ```
> import { Foundation } from 'foundation-sites/js/foundation.core';
> import { Tabs } from 'foundation-sites/js/foundation.tabs';
> $(document).foundation();
> ```

just noticed, i think you'll also have to do 

`Foundation.plugin(Tabs, 'Tabs');`

before the `$(document).foundation();` when importing from the "src"-files, otherwise the ".foundation()" routine would not recognize the 'tabs'...

```
import { Foundation } from 'foundation-sites/js/foundation.core';
import { Tabs } from 'foundation-sites/js/foundation.tabs';
Foundation.plugin(Tabs, 'Tabs');
$(document).foundation();
```

or import the component from the "dist"-files

```
import { Foundation } from 'foundation-sites/js/foundation.core';
import 'foundation-sites/dist/js/foundation.tabs';
$(document).foundation();
```

there are also two other caveats, if i remember correctly, in contrast to using `const $tabs = new Tabs('#tabs');`:
a) when using ".foundation()", it tries to instantiate any component that is loaded and matches a data-attribute)
and b) the routine tries to find any matching data-attribute on child elements also

**Comment by DanielRuf** [comment]
@bb-drummer @mattbag see https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js

**Comment by ncoden** [comment]
@DanielRuf I'll take care of this tomorrow. This is a small change in `foundation-docs`

**Comment by mattbag** [comment]
I have been using the explicit pieces for a long while, I thought, looking at that doc page section three shaking, it was changing/updating the way to use module imports. Thanks guys!

**Comment by bb-drummer** [comment]
@mattbag 
```
import { Dropdown } from 'foundation-sites/js/foundation.dropdown';
$('[data-dropdown]').each(function(el,index){
  new Dropdown($(this));
})
```
...will work because importing from the 'src' files will also import foundation's basics which are needed for the component respectively, so their import is **not** avoided
(this way, those four lines of code, alone, result in a file size of about 360kB, not minified)

**Comment by mattbag** [comment]
Is there a better way? To take advantage of three shaking I mean,
So far that's the best I could find...

**Comment by DanielRuf** [comment]
Not sure what you mean as this is normally how it works and it is dependent of your build tool (webpack config).

`import part from component` and the bundler should do the rest automatically.
You can easily verify this by writing a simple module which export multiple methods and just import one of them and check the emitted bundle.

**Pull request merged**
