### PR TITLE
Fixes to dropdown.js

### PR DESCRIPTION
**Pull request by coreysyms**
Fixes medium breakpoint issues, and left align "ignore" flag undefined js error

### CODE REVIEW

**Comment by dragthor** [comment]
My only concern is any additional call to adjust_pip.  This function is our top worse performing Zurb function when run through a profiler.  So much so... that whenever we do NOT need a pip with a dropdown... we simply (and literally) kill/override the function like this: Foundation.libs.dropdown.adjust_pip = function() {};

**Comment by dragthor** [comment]
@coreysyms You should be able to "cache" calls to the following in the "right" function (and save a few milliseconds):

this.outerWidth();
t.outerWidth();
t.outerHeight();

**Comment by rafibomb** [comment]
Hey guys! Love this one! @coreysyms already did some great work with dropdowns previously. Would you consider this PR ready for test and merge?

**Comment by rafibomb** [comment]
@coreysyms This is great! Are you able to resolve the merge conflicts?

@zurbchris Can we test this for merge?

**Comment by coreysyms** [comment]
Im going to clean up via the suggestions from @dragthor in the coming days, will post soon.

**Comment by zurbchris** [comment]
Please and thank you! I would love to improve the performance of this.

**Comment by zirconiumks** [comment]
such good stuff. @coreysyms, @zurbchris any updates on when this might be merged?

**Comment by rafibomb** [comment]
@coreysyms Jus checking in on this one - We're doing a patch on Foundation 5 this week and this is a really valuable add in you made. Were you able to update the PR with the feedback from @dragthor ? Let us know how we can support you!

**Comment by coreysyms** [comment]
Hang loose, my forks are all messed up since working with the different versions of 5 and 6.

**Comment by coreysyms** [comment]
@rafibomb Hey Rafi, I have not been in 5 in a while, but I'm confused now with which fork I need to be in

**Comment by zurbchris** [comment]
It's the V5 branch on the `foundation-sites` repo.

**Comment by coreysyms** [comment]
Sorry guys to jump PR's but this one is acting up in the desktop... take a look here https://github.com/zurb/foundation-sites/pull/7945

**Comment by gakimball** [comment]
Closing in favor of #7945

@coreysyms Thanks for updating your pull request :)

**Pull request closed without merging**
