### PR TITLE
fix: toggle dropdown if there is no focusable element inside

### PR DESCRIPTION
**Pull request by DanielRuf**
Closes https://github.com/zurb/foundation-sites/issues/10391

### CODE REVIEW

**Review by ncoden — APPROVED** [review]
LGTM 👍. I seen that when using the dropdown and it annoyed me as well.

It's good to go like this but it could be nice to have a `focus` option replacing `auto-focus` with:
* `true`: always focus the panel
* `"auto"`: (default) focus the panel if it contains any focusable element
* `"first"`: always focus the first focusable element
* `false`: never focus the panel

**Comment by DanielRuf** [comment]
> It's good to go like this but it could be nice to have a focus option replacing auto-focus with:

But this would be a new feature or not?

**Comment by ncoden** [comment]
> But this would be a new feature or not?

Yes this would be a new feature. So not in this PR. We still want to make "don't focus dropdown where ther's nothing in it" the default behavior for accessibility reasons.

**Comment by DanielRuf** [comment]
> It's good to go like this but it could be nice to have a focus option replacing auto-focus with:
> 
> true: always focus the panel
> "auto": (default) focus the panel if it contains any focusable element
> "first": always focus the first focusable element
> false: never focus the panel

How can we track this (as issue) at best so we do not forget it then?

**Pull request merged**
