### PR TITLE
make orbit pass w3c validator

### PR DESCRIPTION
**Pull request by pine3ree**
- `<figcaption>` must be enclosed in a `<figure>`
- `<button>`elements cannot be directly inside `<ul>` elements
- .orbit-container list and prev/next controls are grouped inside an .orbit-wrapper `<div>`, we should add a position:relative rule for it to keep controls vertically aligned

another simpler but less semantic way to achieve that is replacing ul, li elements with divs

### CODE REVIEW

**Review by ncoden — APPROVED** [review]
:+1:

**Comment by ncoden** [comment]
@pine3ree @rafibomb What is the status of this PR ?

**Comment by andycochran** [comment]
Nice. This is a great move in the right direction. It'd be nice if Orbit didn't rely on specific elements at all and only used classes. 

> another simpler but less semantic way to achieve that is replacing ul, li elements with divs

:+1: I'm not sure it's more semantic to put slides in a list.

**Comment by IamManchanda** [comment]
@kball @rafibomb what the status on it??

**Comment by rafibomb** [comment]
Looks good to me - I'll checkout and test!

**Comment by IamManchanda** [comment]
I dont know but i cant pull it now (maybe webpack update) ... 

```bash
Error: Cannot find module 'gulp-autoprefixer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/lampp/htdocs/zurb/fork/foundation-sites/gulp/customizer.js:16:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by rafibomb** [comment]
Testing now!

**Comment by kball** [comment]
@IamManchanda you may need to yarn i/npm i

**Comment by rafibomb** [comment]
Great PR @pine3ree !

@andycochran pushed up a test showing you can use generic div's since every element has a class - https://github.com/zurb/foundation-sites/commit/19a3688ff41274a92b897ddf6918c66a72aec2ae

**Comment by rafibomb** [comment]
Just realized - this will cause a bit of migration possibly. We'll need to document the updated classes that could break a previous build in the migration notes for release.

@pine3ree Can you write a short set of notes for that?

**Pull request merged**
