### PR TITLE
I-11441: Add cross-browser support for appearance

### LINKED ISSUE #11441: I-11441: appearance: none; on input tags is not cross browser
## What should happen?
The appearance property is used to either add or remove styling of an element using a platform-native styling based on the users' operating system's theme.

This property is applied to search, text, password, etc... using the mixin exposed by `util/_selector.scss`.  

For instance, input tags with attribute`type` set to `search` in WebKit browsers will, by default, be rendered with rounded corners.  

When `$global-radius` or `$input-radius` is set to zero, input tags of type search should have 90 degree corners.

## What happens instead?

Input tags of type search have rounded corners on iOS devices.

## Possible Solution
Add cross-browser styling support for appearance:
```css
        -webkit-appearance: none;
        -moz-appearance: none;
        -o-appearance: none;
        appearance: none;
```

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1.  Load foundation.min.css
2. Load foundation.min.js
3. Add input tag with type equal to search
4. Open page on iOS device
5. Observer round corners on search input

Alternatively, open https://jsfiddle.net/aorinevo/wLz9ovk1/3/ on an iOS device.

## Context

We have to add cross-browser appearance rules to our css.

## Your Environment

- Foundation version(s) used: 6.4.4-rc1
- Browser(s) name and version(s): Safari, iOS v11.4.1
- Operating System and version (desktop or mobile): mobile

## Checklist (all required):

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title is descriptive.
- [x ] The template is correctly filled.

### PR DESCRIPTION
**Pull request by aorinevo**
## Description

appearance property is used to remove default browser styling for certain html elements like input tags.  Some browsers, like Safari iOS do not support it.  This PR adds cross-browser support for appearance.

- Closes https://github.com/zurb/foundation-sites/issues/11441

## Motivation and Context

Adds cross-browser styling support for appearance property.

## Types of changes

- [ ] Documentation
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x ] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x ] There are no other pull request similar to this one.
- [x ] The pull request title is descriptive.
- [x ] The template is fully and correctly filled.
- [x ] The pull request targets the right branch (`develop` or `develop-v...`).
- [x ] My commits are correctly titled and contain all relevant information.
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly to my changes (if relevant).
- [x ] I have added tests to cover my changes (if relevant).
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
It is already there

https://github.com/zurb/foundation-sites/blob/develop/dist/css/foundation.css#L2376

**Comment by DanielRuf** [comment]
Also the others are not needed as these are for very old browsers.

**Comment by DanielRuf** [comment]
Keep in mind that we already use browserslist and a few other solutions to vendor-prefix such properties

**Review by ncoden — CHANGES_REQUESTED** [review]
Hi @aorinevo.

Foundation requires [Autoprefixer](https://github.com/postcss/autoprefixer) that will take care of all vender prefixes. See the [Sass installation documentation](https://foundation.zurb.com/sites/docs/sass.html#autoprefixer-required).

So this PR is not needed, please add autoprefixer to your project instead.

**Pull request closed without merging**
