### PR TITLE
Update off-canvas.md

### PR DESCRIPTION
**Pull request by web2client**
In ##Setup, data-off-canvas -> data-off-canvas-content
Add example for responsive off-canvas menus

### CODE REVIEW

**Comment by rafibomb** [comment]
Brian, thanks for the PR and we'll be reviewing the update and merging it soon! Always great to have more thorough docs!

**Comment by briantan888** [comment]
So after 6.1.1 is 6.2?

**Comment by rafibomb** [comment]
@briantan888 I like the idea of having a complete copy/paste solution. We don't think the docs is the best place to have it. What we can do is make a Building Block, then link it in the docs.

**Comment by rafibomb** [comment]
I made the building block here http://zurb.com/building-blocks/top-bar-with-off-canvas

**Comment by rafibomb** [comment]
Thanks Brian! Added your suggestions here: https://github.com/zurb/foundation-sites/commit/21026b4e99cc8fb97a6b6ed093a66d2d79977472

**Comment by briantan888** [comment]
Thanks Rafi for posting the example and adding content filler image.

**Pull request closed without merging**
