### PR TITLE
Fix button padding & dropdown menu line height

### PR DESCRIPTION
**Pull request by muhammetm**
Fix button padding & dropdown menu line height

### CODE REVIEW

**Comment by zurbrandon** [comment]
Is this a fix for buttons or the center class?

**Comment by muhammetm** [comment]
@zurbrandon  I updated the comment, it's for button padding and dropdown menu line height.

**Comment by andycochran** [comment]
Surely we can avoid `!important` here (which seems to address a separate issue).

**Comment by zurbrandon** [comment]
@muhammetm is there a way to do this same thing without an !important

**Comment by muhammetm** [comment]
@zurbrandon  I couldn't find a way, top bar's very specific selectors override button styles.

**Comment by andycochran** [comment]
Maybe add :not(.button) to the topbar styles?

**Comment by muhammetm** [comment]
What if it's a button with a custom class name created by mixin?

**Comment by andycochran** [comment]
Ack! I see the problem. Still, I'd still rather not have !important anywhere. Maybe using `.button` inside `.topbar .menu` is an app-specific edge case that requires custom style rules.

**Comment by gakimball** [comment]
Currently reviewing this. Can you highlight which top bar selectors are creating issues? I'd like to tackle this from the other direction, making top bar CSS more generic if possible.

**Comment by muhammetm** [comment]
It's getting overwritten by the selector below:

`.menu > li:not(.menu-text) > a {
    display: block;
    line-height: 1;
    padding: 0.7rem 1rem;
}`

capture

**Comment by gakimball** [comment]
@muhammetm You might consider using a `<button>` or `<input>` element instead. "Search" is an action, so either of those elements will be more appropriate than `<a>`. From an accessibility perspective, `<a>` is for links to other pages, while `<button>` and `<input>` perform actions on the current page.

**Comment by muhammetm** [comment]
I understand. It was just an example. There are cases when button is linked to another page, but it's not much of a big issue after all.

**Comment by gakimball** [comment]
@muhammetm It's definitely something we should try to fix, but adding `!important` to buttons, a component used in many places, is a little spooky.

We did cut back the specificity of that menu selector to `.menu > li > a`, but that's not enough for a single `.button` to win.

**Comment by muhammetm** [comment]
Yes, you are right about `!important`.

**Comment by gakimball** [comment]
Going to close this, as this isn't the way we want to solve this problem. We're aware it's an issue, however.

**Pull request closed without merging**
