### PR TITLE
Drilldown - add missing radix & eslint check

### PR DESCRIPTION
**Pull request by dragthor**
just being cautious.  surprised the linter did not pick this up

### CODE REVIEW

**Comment by dragthor** [comment]
Looks like Travis had a network error.  It rebuilt again and passed.

**Comment by dragthor** [comment]
I can also update the .eslintrc with radix check.  Warning or Error?

**Comment by kball** [comment]
@dragthor Yes please, update the .eslintrc... let's be string, Error, and then clean up any new things it turns up. :)

**Comment by dragthor** [comment]
radix added to .eslintrc as error.

**Comment by kball** [comment]
Merged! Thanks @dragthor

**Pull request merged**
