### PR TITLE
Fixed javascript source folder

### PR DESCRIPTION
**Pull request by grantcarthew**
Just fixing a doc issue.

### CODE REVIEW

**Comment by rafibomb** [comment]
Should be src/assets/js I think. Can you update?

**Comment by grantcarthew** [comment]
The module directory I have in my `node_modules` does not have src at all. The top level directories are `_vendor`, `assets`, `customizer`, `dist`, `js`, and `scss`. This is v6.4.3 of foundation-sites.

**Comment by kball** [comment]
👍

**Comment by kball** [comment]
Merged! Thanks @grantcarthew

**Pull request merged**
