### PR TITLE
Fix invalid characters in _accordion.scss and typography/_base.scss f…

### PR DESCRIPTION
**Pull request by zy4**
…rom issue #8554.

This bug affected compass on systems with no or wrong locale set.

### CODE REVIEW

**Comment by ncoden** [comment]
Can't it be fixed with `@charset "UTF-8";` at the top of each file ?

**Comment by zy4** [comment]
Why would you add that on top of each file when you can clean two of them from hidden characters? :)

**Comment by ncoden** [comment]
It is not hidden characters, but the minus sign showed when an accordion item is open (see http://foundation.zurb.com/sites/docs/accordion.html), different from a hyphen.

Hyphen: `-`
Long hyphen: `–` (used as minus sign)

**Comment by zy4** [comment]
You are right for the accordion (the other occurrence did not affect any element). I just changed it to an ISO coded char, using `&ndash;`. Hope this will fix it.

**Review by ncoden — APPROVED** [review]

**Pull request merged**
