### PR TITLE
ci: add SonarCloud config file

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This PR adds the config file for SonarCloud so we can add / enable it there to check the code for code smells and other issues.

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by SassNinja** [comment]
@DanielRuf who's gonna create the necessary account and when is the analysis supposed to be triggered?

**Comment by SassNinja** [comment]
doesn't make much sense to merge this PR until the config contains some content

**Comment by DanielRuf** [comment]
> doesn't make much sense to merge this PR until the config contains some content

The config can be empty by default which sets the default values.

**Comment by DanielRuf** [comment]
> @DanielRuf who's gonna create the necessary account and when is the analysis supposed to be triggered?

Someone with the proper rights (owner, admin) to add the application from the marketplace.

**Review by joeworkman — APPROVED** [review]

**Comment by joeworkman** [comment]
I started work on getting this configured.

**Pull request merged**
