### PR TITLE
Added variables to customize margins for checkbox, radio, select and …

### PR DESCRIPTION
**Pull request by uranuz**
My proposal for additional scss variables for margins customizations. Details are there:
https://github.com/zurb/foundation-sites/issues/8424

### CODE REVIEW

**Comment by uranuz** [comment]
Maybe also needed some changes to *form-error* and *foundation-form-fieldset* or else, but I'm not sure.

**Comment by SalahAdDin** [comment]
I think that this PR will go againt's new Foundation philosofies, but, :+1:

**Comment by uranuz** [comment]
I'm not familiar with new Foundation philosofy, so it's up to community responible people decide whether this approach appropriate. Maybe I should solve these problems another way. I would be interested to consider for alternatives.

**Comment by kball** [comment]
This is an API change, so the PR should be against v6.3.0 rather than develop.  Other than that, @andycochran or @brettsmason what are your thoughts on making this change in the scss?

**Comment by brettsmason** [comment]
@kball I understand the reasoning for wanting to implement additional control over this (though I havent had the need for this myself other than labels). The only thing I wondered is if the variables should be prefixed with form (so $form-checkbox-margin etc) just to make them really clear, but I'm not sure.

**Comment by andycochran** [comment]
Shouldn't these also be exposed in `_settings.scss`?

**Comment by brettsmason** [comment]
I'm pretty sure the `_settings.scss` file is generated by Octophant on each release so no need to add them to settings, but I could be wrong (I'm sure I remember Geoff saying this).

**Comment by rafibomb** [comment]
@brettsmason That's right! Octophant will update the settings file when we deploy a version or if you run `npm run deploy:settings` - so you're good!

**Comment by rafibomb** [comment]
@uranuz Can you point this to branch `v6.3` so we can merge it? Thanks!

**Comment by kball** [comment]
@andycochran @brettsmason how did you feel about this change?

**Comment by andycochran** [comment]
Only issue I see is the inconsistent variable prefixes.

**Comment by zurbrandon** [comment]
I'm not a fan of adding these, mainly since it's something that can be nearly as easy to change in css as it would be in the settings. Variables are great when a single variable changes many many things or some math occurs to make them more useful. 

This seems to just be moving code from one place to another.

**Comment by kball** [comment]
Based on @zurbrandon's comment I'm going to close this without merging.  If you'd like to reopen with an argument as to why this is adding more value/needed please do.

**Pull request closed without merging**
