### PR TITLE
docs: OffCanvas correct transition time details

### LINKED ISSUE #11666: OffCanvas transition-time value incorrectly listed as number instead of string
## Description

Currently, the information in the Sass reference for this option states the data should be a number and that number will be understood to be milliseconds: 

data-transition-time | number | null | Amount of time in ms the open and close transition requires. If none selected, pulls from body style.
-- | -- | -- | --

The `transition-time` attribute is passed directly to the element css (https://github.com/zurb/foundation-sites/blob/develop/js/foundation.offcanvas.js#L136) without appending the `ms` string to the value. The only way I was able to modify the value was by adding the units to the option as well (e.g. `100ms` or `.3s`).

## Possible Solution

The __Type__ value should be listed as `string` instead of `number` and the __Description__ updated to reference including the units in the configuration value. I would have submitted a pull request doing this, but the Reference sections don't appear to be a part of the repo (perhaps auto-generated from elsewhere in the repo?). If I'm wrong about this, please let me know and I'm happy to submit a pull request.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by noahheck**
## Description

Because `transitionTime` is passed directly to the element CSS, the value should include the appropriate units. This PR updates the auto-generated documentation for this.
...

- Closes #11666 

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by DanielRuf — APPROVED** [review]
LGTM

**Comment by ncoden** [comment]
Hi @noahheck 👋, thank you for your pull request!
Your fix is compatible with the in-development version of Foundation. Could you rebase your stuff on `develop` ?

```sh
git checkout docs/offcanvas-correct-transition-time-details
git rebase develop
```

Then force-push and change the base of your pull request to `develop`. Thank you!

- https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase
- https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by noahheck** [comment]
Hi @ncoden! I hope everything looks correct at this point. The rebase didn't quite work how I would have liked, so I simply recreated the change off of an up-to-date `develop` branch. Please let me know if you need anything else!

**Review by ncoden — APPROVED** [review]
LGTM 👍 
Thank you @noahheck

**Pull request merged**
