### PR TITLE
Refactor: remove yargs from Gulp customizer task

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This PR removes the `yargs` from the customizer with a small script which parses `process.argv`.

- Closes 

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by kball — APPROVED** [review]

**Comment by kball** [comment]
This change looks good but it is failing in CI for the latest version of node. Looking at other PRs, It looks like node-sass has been failing to build since latest version moved to v12. Will see if I can resolve that, but I don't think it should block this. Merging.

**Comment by DanielRuf** [comment]
> This change looks good but it is failing in CI for the latest version of node. Looking at other PRs, It looks like node-sass has been failing to build since latest version moved to v12. Will see if I can resolve that, but I don't think it should block this. Merging.

Yes it was always failing due to NodeJS not being compatible with NodeJS 12.

**Comment by DanielRuf** [comment]
@kball can you check if we can remove `yargs  now?

**Comment by kball** [comment]
@DanielRuf I think so yes we can

**Pull request merged**
