### PR TITLE
[WIP] feat: make header styling more flexible using placeholders

### PR DESCRIPTION
**Pull request by oxyc**
Based on @ncoden PR https://github.com/zurb/foundation-sites/pull/9500 and issue #9483.

There's been a few issues (#10918, #11195) about supporting more properties in the `$header-styles` map, but most of those use cases are not about applying different styles to different screen sizes, but just getting styles applied to all headers as well as the new header classes `.h1, .h2` etc. Therefore I don't think they belong in `$header-styles` but there should fit in somewhere for sure (eg. the use case of h1 having a different font-weight than h2-h6 comes up quite frequently on my projects).

Currently the only method is manually specifying each selector like so

```scss
h1, .h1,
h2, .h2,
h3, .h3,
h4, .h4,
h5, .h5,
h6, .h6 {
  text-decoration: underline
}
```

This is a bit tedious and if you ever wanted to eg. use the heading style for a different type of element or class, you would have to extend the class

```scss
select.filter {
  @extend .h1;
}
```

Extending classes is a terrible idea in my opinion and causes very difficult to find bugs. The main issue is how all [chained selectors gets applied](https://www.smashingmagazine.com/2015/05/extending-in-sass-without-mess/#what-happens-when-you-use-extend) as well. I put up a simple example illustrating the issue here: https://codepen.io/anon/pen/aGvpwG

Where I work we have a policy never to extend classes directly and always extend placeholders instead.

This PR would allow users to extend headers much more easily and I'd vote for the pattern being reused in many other parts of Foundation. Specifically buttons as I often end up wanting to reapply button styles to selectors I might not have control over (using WP for example).

Examples:

```scss
// Alternative to the first example posted in this message
%header {
  text-decoration: underline
}

// Apply an additional style to h1, .h1 as often requested in other issues.
%h1 {
  font-weight: 900;
}

// Applies the complete foundation + user styling of h1 headers.
select.filter {
  @extend %h1;
}
```

_Note: this is probably not mergable, the `_tmp.css` file is a stray file from ncodens PR and I'm mostly making this PR to illustrate my idea._

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
Hi @oxyc. I did not know we could define placeholders multiple times and this is a really great news for Foundation. 👏 

A common issue for all our components is people wanting to add some styles and configuration in components with complex selectors. As discussed in #9500, we cannot add support for all CSS3 properties in our configuration file. Our current architecture have reached its limits.

I agree with everything you said. Extending selectors is not a good practices. User should be able to fully customize our components and the best way to do it is via its own CSS code, but we must give him tools to do it correctly. Defining placeholders to let the user extending it as it will the same way he/she would include mixins is definitely the best solution. It give him/her the choice of freely customizing the components we provide (without settings required) or creating new ones from them.

So thank you, this is a really good PR (and first contribution). 🎉 

Sadly, you can see by the "SAVE SUFF" commit that it is based on incomplete "WIP" work. It must be cleaned, rebased and documented. So I propose you two options:
* I try to finish #9500 and include your commit in it after that.
* I try to finish #9500, merge it, and you open a new PR based on it after that.

What do you prefer ?

PS: Thank you for the good explanations, in 2 years around Foundation this is the best pull request message I ever seen 👍!

**Comment by ncoden** [comment]
> Note: this is probably not mergable, the _tmp.css file is a stray file from ncodens PR and I'm mostly making this PR to illustrate my idea.

Marking this as Work In Progress

**Comment by oxyc** [comment]
> I try to finish #9500 and include your commit in it after that.

Feel free to include it, it's mostly based on your work! I can help out next week if you don't have enough time but otherwise I don't need the contribution :)

**Review by DanielRuf — APPROVED** [review]
LGTM, what can we do next here?

**Comment by DanielRuf** [comment]
I guess we have to cleanup and rebase this one?

**Review by joeworkman — APPROVED** [review]

**Pull request closed without merging**
