### PR TITLE
build: add GitHub Actions - closes #11823

### LINKED ISSUE #11823: Migrate to GitHub Actions
## Description

A migration to GitHub Actions shoul result in faster an ore parallel builds as Travis CI is slow compared to this. Not yet sure if we can also test on macOS and Windows there (we might need the Travis CI action).

## Possible Solution

...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This PR prepares the migration to GitHub Actions. GitHub Actions is often faster and more flexible.

Closes #11823

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
To try it we have to merge these changes.

**Comment by DanielRuf** [comment]
We also have to set the secret variables for browserstack. See https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables

**Comment by DanielRuf** [comment]
> We also have to set the secret variables for browserstack. See [help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables)

@joeworkman

**Comment by joeworkman** [comment]
Sorry for the delay on this one.... want me to try and merge this in? We will need to add support for Snyk. I added this into Travis today actually. I am happy to move to GH Actions though if they will be faster.

**Comment by DanielRuf** [comment]
No, please do not yet merge this.

I still don't understand why you want to add it to the CI setup.
As Liran wrote this should not be needed when we use the marketplace app / integration for Snyk which should also work for PRs.

**Comment by DanielRuf** [comment]
> on 6 Oct 2019

Is this already done? If not please check this.

**Comment by joeworkman** [comment]
Adding it to the CI setup allows us to easy see how a PR will affect the branch once its merged in.

**Comment by DanielRuf** [comment]
You can enable that per project directly on snyk.io in the project settings.

Screenshot_20200205-072859

**Comment by DanielRuf** [comment]
Screenshot_20200205-073105

Screenshot_20200205-073124

**Review by joeworkman — APPROVED** [review]
I think that we are good to go with this. I think that we need to just merge it in order to verify that its all working.

**Comment by DanielRuf** [comment]
Did you already set the secret variables for browserstack?

https://github.com/foundation/foundation-sites/pull/11839#issuecomment-546839952

If so I would retrigger a GHA build to see if it works now.

**Pull request merged**
