### PR TITLE
Buttons - Heads up on social buttons building block!

### PR DESCRIPTION
**Pull request by IamManchanda**
I hope this sounds reasonable to the community 
http://foundation.zurb.com/building-blocks/blocks/social-buttons.html

-----------------------------------------------------------------------------------------------------------------

heads-up-social-buttons

### CODE REVIEW

**Comment by Deckluhm** [comment]
I fully agree that Building Blocks should be highlighted in the documentation but I think we need a more global approach or the documentation will quickly get messy.

**Comment by kball** [comment]
Agreed! We're actually in the process of figuring out a global approach to including building blocks in the documentation! @kwhchu maybe you can chime in with some of our thinking here... and maybe @Deckluhm and @IamManchanda can help provide community feedback...

If anyone else is interested in being involved in this process, please chime in!

(cc @rafibomb)

**Comment by rafibomb** [comment]
Here's how it was done in Foundation 5 - http://foundation.zurb.com/sites/docs/v/5.5.3/components/topbar.html Have to scroll to bottom of page.

I'd like to see the blocks highlighted in a section on the page. The sticky right side nav can link people to it.

Also - codepens of the code examples so people can play with it is on the roadmap.

**Comment by IamManchanda** [comment]
> Also - codepens of the code examples so people can play with it is on the roadmap.

:+1:  +1 @rafibomb

**Comment by rafibomb** [comment]
So we're all in agreement! Since this is on the Building Blocks roadmap we'll close it here. Thanks! https://github.com/zurb/building-blocks/projects/1

**Pull request closed without merging**
