### PR TITLE
ZeroClipboard replaced by clipboard.js

### PR DESCRIPTION
**Pull request by colin-marshall**
As requested in issue #7581.

### CODE REVIEW

**Comment by gakimball** [comment]
Awesome, thank you! Just one request, is it possible for you to target the `master` branch instead? I'd like to deploy this to the live docs once it's merged in.

**Comment by colin-marshall** [comment]
For sure. Since I merged from develop in this branch should I just start over with a new branch based off of master?

**Comment by gakimball** [comment]
Yeah, hopefully it's not too much work. If you can't sort it out, we're putting a patch out tomorrow anyway, but it would be awesome to get this out today.

**Comment by colin-marshall** [comment]
No trouble at all, I just wanted to make sure that's the best way to go about it so that a bunch of commits weren't merged prematurely into master.

**Comment by gakimball** [comment]
Right, yeah, we don't want that.

**Pull request closed without merging**
