### PR TITLE
Introducing a separate breadcrumbs line-height var

### PR DESCRIPTION
**Pull request by doertedev**
When having large paths in mobile layouts for small phone screens this
breadcrumb will most likely have a line break. For certain phones
you'll probably set a different line-height setting here.

### CODE REVIEW

**Comment by rafibomb** [comment]
We agree this could help - although we hesitate to add more variables. In this case it helps. Can clear the merge conflicts and we'll add it in? Thanks!

**Comment by rafibomb** [comment]
Thanks for the PR! Are you able to clear the merge conflicts so we merge it in?

**Comment by doertedev** [comment]
+1

**Comment by rafibomb** [comment]
Nice! Thanks!

**Pull request merged**
