### PR TITLE
fix: resolve invalid conflict resolution #11077 for v6.5

### LINKED ISSUE #11355: [Magellan] seems to be broken with 6.5.0-rc.1
Just noticed on the website that the Magellan feature doesn't seem to work on the online documentation at all. It worked with 6.4.3 docs. Using Firefox.

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

Wrong local variable `_this` was used.

- Closes #11355

## Motivation and Context

Fix the wrong local variable, should be `this` or `e.target`.

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `support/*`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
This comes from a merge conflict that was incorrectly resolved. This issue was already resolved in https://github.com/zurb/foundation-sites/pull/11076.

Take a look at the difference between:
- [The original pull request (#11077)](https://github.com/zurb/foundation-sites/pull/11077/files)
- [Its import in the derived 6.5 version (12822b4)](https://github.com/DanielRuf/foundation-sites/commit/12822b44785108aa3be923fcb4365ae77c0d3fc6)

The current PR is nice but you may rename it (and the commit too) to indicate that this is more a conflict resolution that a bug fix.

Something like:
> fix: resolve invalid conflict resolution #11077 for v6.5

What do you think ?

**Comment by DanielRuf** [comment]
> This comes from a merge conflict that was incorrectly resolved. This issue was already resolved in #11076.

I was not aware of this. So in general I can close this PR?

**Comment by DanielRuf** [comment]
Because this is wrong in 6.5.0 RC1.

**Comment by DanielRuf** [comment]
Well, I will fix the other line too. In general it is a bugfix. Your proposed commit message is not a clear and precise one as it does not describe the change imho.

**Comment by DanielRuf** [comment]
In general it is a bugfix. Your proposed commit message is not a clear and precise one as it does not describe the change imho.

**Comment by ncoden** [comment]
The commit title I proposed describe the purpose of the commit. We are not fixing a bug we just discovered in v6.5, we're re-applying a fix that was removed in a conflict resolution.

The code change and the reasons for it are kept in the same place: #11077.

**Comment by DanielRuf** [comment]
> Something like:
> 
> fix: resolve invalid conflict resolution #11077 for v6.5
> 
> What do you think ?

Done.

**Comment by ncoden** [comment]
Nice. Thank you 👍

**Comment by DaSchTour** [comment]
This would be more readable if lambdas and `e.target` would be used. This would allow to eliminate the `_this`;

**Pull request merged**
