### PR TITLE
Extend visibility classes

### PR DESCRIPTION
**Pull request by paxperscientiam**
I am working on a visibility test with intention to extend visibility classes in two ways:

* Boolean conjunction: EG: elements with the hypothetical class `.show-for-medium-and-landscape` would be visible *only* when the screen size is "small" *and* in "landscape" orientation. 

* Boolean exclusive disjunction: Elements with both `.show-for-medium` and `.show-for-landscape` should display *only* when either condition is true; element should be invisible when both are true and when both are false.

### CODE REVIEW

**Comment by ncoden** [comment]
Hi @paxperscientiam 

Could you give a set of cases where these features would be useful ?
I wonder if there would be enough people using these classes to worth the increased file size.

**Comment by paxperscientiam** [comment]
Hello @ncoden 

## conjunction
* show logo when small and landscape; hide logo in all other cases.
* show title-bar when small and portrait; show side-title-bar (what-have-you) when small and horizontal

## XOR
* harder to think of off the top of my head.

**Comment by JeremyEnglert** [comment]
Just throwing in my two cents, but I see value in these additional classes.

Is the "and" necessary though?

.show-for-medium-landscape says the same thing in less characters. Not a deal breaker either way, just a thought.

**Comment by jaysonbrown** [comment]
Deep linking doesn't seem to be working in the docs, also would this function only work on page load? I was hoping for deep-linking within the page without a refresh.

**Comment by paxperscientiam** [comment]
@JeremyEnglert It's a placeholder; but I do agree that identifiers should be kept short as possible without sacrificing semantics.

**Comment by paxperscientiam** [comment]
I have finally made some progress with this: "show-for-$size-osly" in conjunction with "show-for-$orientation" now works nicely (see new test hershttp://localhost:3000/visibility/index.html)

Could someone help me with ".hide-for-$size-only.hide-for-$orientation" programming? it seems like I would have to augment the breakpoint function; however, I'm unsure.

These style rules could be setup to be "opt-in" only (for sass users)s

**Comment by kball** [comment]
@IamManchanda @JeremyEnglert can you help @paxperscientiam get this across the line?

**Comment by IamManchanda** [comment]
Ohk @kball .... i will take a look as soon as possible from my side!

**Comment by IamManchanda** [comment]
I am confused here 

> **Boolean exclusive disjunction**: Elements with both `.show-for-medium` and `.show-for-landscape` should display *only* when either condition is true; element should be invisible when both are true and when both are false.
https://en.wikipedia.org/wiki/Truth_table#Exclusive_disjunction

Do you mean,

```html
<div class="show-for-medium show-for-landscape">
 I will be only showed when i am either on medium screen or a landspace orientation. 
 If i am on both, i will be hidden. If i am on none, i will be hidden
</div>
```

Is it so ?? and if yes why so ??

**Comment by DanielRuf** [comment]
> Is it so ?? and if yes why so ??

I guess because this does not change the old behavior.

What is the current state of this PR?

**Comment by paxperscientiam** [comment]
Sorry folks, I just don't know when I'll be able to work on this. It's been a while :/ 

Would anyone like to take over? If so, I'll close and you can just copy the code ... unless there's a builtin way for transferring PRs?

**Comment by DanielRuf** [comment]
We can also push changes to your brsnch if that is ok.

**Comment by paxperscientiam** [comment]
@DanielRuf Yes!

**Comment by DanielRuf** [comment]
@ncoden 

> I wonder if there would be enough people using these classes to worth the increased file size.

Closed because of this and the scope and rare use cases?

**Pull request closed without merging**
