### PR TITLE
ES6 classes

### PR DESCRIPTION
**Pull request by colin-marshall**
@gakimball with the exception of `foundation.core.js`, here are the rest of the JS components converted to ES6 classes.

### CODE REVIEW

**Comment by rafibomb** [comment]
Wow! 👍 You rock!

**Comment by zurbchris** [comment]
Holy hell man. Awesome.

**Comment by zurbrandon** [comment]
WOWSERS! This ROCKS!!!!

**Comment by gakimball** [comment]
wowwwwww

**Pull request merged**
