### PR TITLE
add checkboxes required validation

### PR DESCRIPTION
**Pull request by huchenme**
Originally Abide does not support checkboxes group required validation (or it might be a bug). I have added the validation for checkboxes and updated the documentation as well

### CODE REVIEW

**Comment by rossgzc** [comment]
+1! This would be incredibly useful :)

**Comment by Elyasin** [comment]
+1 Would be top.

**Comment by Akarienta** [comment]
Check this SO question, it is possible if you write your own abide validator: http://stackoverflow.com/questions/26890023/display-error-if-no-checkbox-is-checked-in-checkbox-group

**Comment by mikejoyceio** [comment]
+1

**Pull request closed without merging**
