### PR TITLE
Updated Orbit documentation: corrected invalid HTML5 code examples

### PR DESCRIPTION
**Pull request by jdoubleu**
A given code example isn't HTML5 valid.

For more, detailed information have a look at https://github.com/zurb/foundation-sites/issues/8270 please.

### CODE REVIEW

**Comment by gakimball** [comment]
Does it disrupt the existing styling of Orbit at all?

**Comment by jshdoubleu** [comment]
Yes, as expected, the figure disrupts the styling (see screenshot).
By default the figure tag has a margin and so it breaks a slide (and every image).

The buttons still work.

bildschirmfoto 2016-03-01 um 19 17 14

Please compare:
This is how it is with figure:
bildschirmfoto 2016-03-01 um 19 20 30
This is how it should be/is without figure:
bildschirmfoto 2016-03-01 um 19 21 29

**Comment by gakimball** [comment]
Hm, that makes it tricky then. The CSS would need some changes, but we don't want to break the visual styling for existing users.

If you can make the CSS work the same the old way and this new way, then we can work with that.

**Comment by jshdoubleu** [comment]
Okay, I'll try to fix it. Which branch should I take? `6.2-dev` or `develop` ?

**Comment by gakimball** [comment]
Do it on `develop`. We don't need the 6.2 branches now that 6.2 is out—I'll get rid of them soon.

**Comment by kball** [comment]
@jshdoubleu did you end up taking on the css changes?  Thanks

**Comment by jshdoubleu** [comment]
Sorry for the delay.

I found out, that the broken doc was caused by this commit 097677af1431f2f0616aa1de138bf9e90de1abc0.
There are already classes to prevent this "bug". Adding `orbit-figure` class to the figure tag removes the margin. But this information is still missing in the doc.

However this is not valid HTML5.

**Comment by Owlbertz** [comment]
Hi,
I took a look and noticed two things. First, this PR targets `master`, but should go into `develop`. Second, the layout is broken for me:
image
The focus currently lies on the slide. Notice that it's far too big and that the buttons are pretty misaligned.
(Ubuntu 14.04, Chrome)

Can someone else double check that?

**Comment by Owlbertz** [comment]
@jdoubleu Any update/comment on that?

**Comment by kball** [comment]
@Owlbertz purely docs updates can target master. However I'm a little confused - is this only an update to the example?  Or are there updates that need to happen to the actual component scss as well?

**Comment by jdoubleu** [comment]
To clarify I stumbled about the documentation of the orbit slider after my IDE marked the html invalid.

There were `button` tags inside a `ul` and the `figcaption` tags weren't placed inside a `figure` tag.

I cleaned up and corrected the markup and it broke. The buttons still worked properly but the `figcaptions` had a margin or padding which would crash the slider.

So I thought there must be a change in the scss. While trying to fix this problem I mentioned there was already a css class named `orbit-caption` which removes the margin. This class wasn't documented anywhere.

I updated the documentation to have valid html and use correct classes. I also tried out the changes locally and it worked for me.
Probably there were changes (e.g. the class was removed) while this issue has been reported.

Belonging issue: https://github.com/zurb/foundation-sites/issues/8270

I'm going to make further tests but haven't got an eye on this for a while.

**Comment by kball** [comment]
@jdoubleu when I check this out, the docs example is visually broken as noted by @Owlbertz.  Can you take a look again and address?  Thanks

**Comment by kball** [comment]
@jdoubleu were you able to take a look at the breakage noted above?  I'd still love to get this resolved

**Comment by jdoubleu** [comment]
Okay for me it breaks too. But this has something todo with the `figcaption` being positioned absolute.
I'm investigating this and propose a fix/correction.

**Comment by jdoubleu** [comment]
Closing because of https://github.com/zurb/foundation-sites/issues/8270#issuecomment-366439343 (https://github.com/zurb/foundation-sites/issues/8270#issuecomment-366457521)

**Pull request closed without merging**
