### PR TITLE
Added CSS declaration for table tfoot background

### PR DESCRIPTION
**Pull request by denisahac**
Fix for #8802

### CODE REVIEW

**Comment by designerno1** [comment]
looks good to me

**Comment by brettsmason** [comment]
@denisahac Thanks for the PR. I think looking at this a bit more we should add a `$table-foot-font-color` too, something like:

```
/// Default font color for footer.
/// @type Color
$table-foot-font-color: $body-font-color !default;
```

Would you be able to re-work this a bit to include this?

**Comment by denisahac** [comment]
@brettsmason can you please review my latest PR those included your request. Thanks

**Comment by brettsmason** [comment]
@denisahac Sorry for the delay in getting back to you, I've been away for a few days.
I think some of the declarations need re-ordering/changing a bit. On line 85 we are declaring `tfoot` to use the `thead` styling, and then overriding it a bit later. Something like this might be better do you think? (full mixin just to make it easier to explain).

```
@mixin -zf-table-children-styles($stripe: $table-stripe) {
  thead,
  tbody,
  tfoot {
    border: $table-border;
    background-color: $table-background;
  }

  // Caption
  caption {
    font-weight: $global-weight-bold;
    padding: $table-padding;
  }

  // Table head
  thead {
    background: $table-head-background;
    color: $table-head-font-color;
  }

  // Table foot
  tfoot {
    background: $table-foot-background;
    color: $table-foot-font-color;
  }

  // Table head and foot
  thead,
  tfoot {
    // Rows within head and foot
    tr {
      background: transparent;
    }

    // Cells within head and foot
    th,
    td {
      padding: $table-padding;
      font-weight: $global-weight-bold;
      text-align: #{$global-left};
    }
  }
  
  // Table rows
  tbody {
    tr {
      // If stripe is set to even, darken the even rows.
      @if $stripe == even {
        &:nth-child(even) {
          background-color: $table-striped-background;
        }
      }

      // If stripe is set to odd, darken the odd rows.
      @else if $stripe == odd {
        &:nth-child(odd) {
          background-color: $table-striped-background;
        }
      }
    }

    th,
    td {
      padding: $table-padding;
    }
  }
}
```

**Comment by denisahac** [comment]
Closing this PR in favor of #8877

**Pull request closed without merging**
