### PR TITLE
[Feature] Text utilities(vanilla helper classes)

### PR DESCRIPTION
**Pull request by IamManchanda**
Hello there!!

Just added some **simple but important** text utilities which i thought that deserves to be there within the core for the framework.

**TODO**: Quick (Fast & Furious) docs from my end if this is approved!

Special Note: Haven't added responsive variations for the same as i thought that's not needed but if you think different please please let me know.

@kball @rafibomb for review 

--------------------------------------------------------------------------------------------------------------------------

Here is the generated css classes 

```css
.text-hide { }
.text-truncate { }
.text-nowrap { }
.text-lowercase { }
.text-uppercase { }
.text-capitalize { }
```

-----------------------------------------------------------------------------------------------------------------

**Credits** ( where its due )
- Inspiration for `text-hide` => https://v4-alpha.getbootstrap.com/utilities/image-replacement/ 
- Inspiration for `text-truncate` => https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

### CODE REVIEW

**Comment by kball** [comment]
@tdhartwick @jnemeth @rafibomb as prototypers extraordinarios, what do y'all think of this type of helper?

**Comment by natewiebe13** [comment]
@kball, somewhat related to #9719, should the utility classes still be included in the `foundation-typography` mixin? Maybe there should be a separate mixin like `foundation-typography-prototype` in order to separate these out. Otherwise, we'll have to go in our projects and replace where we include `foundation-typography` with the 4 mixins it currently includes in order to not have these utility classes.

**Comment by IamManchanda** [comment]
#9736 opened by @natewiebe13 for discussion including this! 

Please keep this open but put it on hold!! @kball

**Comment by IamManchanda** [comment]
Closing ( Put on hold ), thanks to #9738 ( merged there also )

**Pull request closed without merging**
