### PR TITLE
Update Reveal to support touch devices better

### PR DESCRIPTION
**Pull request by Ne-Ne**
Based off this issue (https://github.com/zurb/foundation-sites/issues/7548), @gerardkcohen css.

Hopefully this should sort scroll issues.

### CODE REVIEW

**Comment by gakimball** [comment]
We'll need to do thorough browser testing on this, because the off-canvas CSS is fairly brittle and prone to cross-browser issues.

Would it be possible for you to take a look in Safari and Mobile Safari, if you can? Those two browsers tend to be the most problematic with off-canvas.

**Comment by Ne-Ne** [comment]
I have checked through changes and they seem fine.

The CSS was actually recommended via @gerardkcohen.

**Comment by zurbrandon** [comment]
Managed to pull this down and test it, but it appears to not function in safari at all. I'm getting the overlay for modals but not the modal it self. Are you seeing the same thing?

**Comment by Ne-Ne** [comment]
I must have been in a different branch. 

Will re-check when I find time. @zurbrandon what browser version were you running?

**Comment by kball** [comment]
Given the commentary above I'm going to close this.  Given the time lag I suspect @zurbrandon won't remember what the browser version was, but I'd check Safari 8 and Safari 9.  Please feel free to reopen after testing and bringing the branch up to date with develop.

**Pull request closed without merging**
