### PR TITLE
Fix for #10407 reveal content classes

### LINKED ISSUE #10407: Off-canvas and reveal-for-large ... bug
#### How to reproduce this bug:

There is a bug when using reveal-for-large and the off-canvas together. It displays as should for large screens and small screens. The column hides for medium screens as it should but the space does not shrink, leaving a blank space (extra margin-left). This issue is only in the new 6.4 xygrid version. Ive tried it on my own fresh installed projects and in codpen, foundation version 6 and 6.4 and it happens only in the 6.4.

#### What should happen:
the off canvas menu should shrink/hide on medium screens and lower and reveal on large screens only

#### What happened instead:
the off canvas shows for large, hides for small and medium, but in medium only it leaves a blank space (extra margin-left) and collapses only when in small screen size
#### Browser(s) and Device(s) tested on:
chrome, Microsoft Edge
#### Foundation Version(s) you are using:
6.4
#### Test case link:
[CodePen with Foundation 6.4.1, XY Flexbox grid](https://codepen.io/NoreagoCan/pen/dRaBoZ?editors=1000)

### PR DESCRIPTION
**Pull request by SassNinja**
This PR fixes https://github.com/zurb/foundation-sites/issues/10407

Due to performance improvements the reveal related classes get only updated if the param `hasReveal` is set to true. Since `_addContentClasses()` is calling `_removeContentClasses()` it must loop through that param what was missing. I've fixed this now!

### CODE REVIEW

**Comment by rafibomb** [comment]
@SassNinja Thanks for this! @IamManchanda @NoreagoCan can you help test this PR for merge?

**Comment by IamManchanda** [comment]
@rafibomb digging it in!

**Comment by brettsmason** [comment]
Pulled this down and ran the `reveal` visual test - can confirm this works correctly.
Looks good to merge from my point of view, thanks @SassNinja 😄

**Comment by IamManchanda** [comment]
Yup this works awesome! Merging it had a visual test myself too!

**Comment by IamManchanda** [comment]
Hey @SassNinja Although this was merged 
But me and @brettsmason had a deep look into it just now 
and 
theres something still buggy going on with `position-right`. If you resize the window to smaller screen, refresh and then increase size, it works fine
If you resize from large to smaller, it doesn't work correctly!

Can you look into it 
Visit => http://localhost:3000/offcanvas/offcanvas-reveal-modal-large.html

**Comment by IamManchanda** [comment]
The original bug reported with `position-left` works fine though!
But seems issue with `position-right`

**Comment by brettsmason** [comment]
@SassNinja @IamManchanda Looking at it more - it looks like once `off-canvas-content` has the class `has-reveal-left/right` they aren't being correctly removed on change of breakpoint. You will know more than me though, I'm a bit out of the loop on off canvas at the moment 😄

**Pull request merged**
