### PR TITLE
Removed Deprecated JS Component

### PR DESCRIPTION
**Pull request by ghost**
Orbit is deprecated, so i removed it from humans.txt file. Nothing special

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Why? Why you deprecated Orbit if Orbit is very useful? I try use other sliders but are very hard, i only need the all slider with the same height, but they put me the slider in different heights :'(

**Comment by atilkan** [comment]
I removed it from humans.txt file. It was just an example. You can use older foundation version if you really need it badly.

**Comment by gakimball** [comment]
Hm, I suppose for that line to make sense, it needs to include *every* JavaScript component, of which there are about a dozen.

I'm not really sure why we have a humans.txt there anyway, though. That file doesn't get copied to the Foundation marketing site or docs, and it's not meant to be used in Git repos. It's supposed to be at the root of a website where a robots.txt would be.

**Comment by gakimball** [comment]
Closing this in favor of just deleting the `humans.txt`, because this repository isn't a website, it's a codebase.

**Pull request closed without merging**
