### PR TITLE
Link description

### PR DESCRIPTION
**Pull request by smartm0use**
Fixed link description for CSS property `align-items`

### CODE REVIEW

**Comment by colin-marshall** [comment]
Looks good to me, but can you please target the master branch for changes to the docs? Thanks!

**Comment by rafibomb** [comment]
@colin-marshall 👍

@smartm0use Thanks for the PR! We deploy the docs form the master branch, are you able to point this over there and we'll merge for deploy

**Comment by smartm0use** [comment]
Done, thank you.
https://github.com/zurb/foundation-sites/pull/9113

**Comment by kball** [comment]
Merged the master version.

**Pull request closed without merging**
