### PR TITLE
Update composer.json for packagist.org

### PR DESCRIPTION
**Pull request by phpfui**
## Description
New github account (foundation) requires updates to composer.json

Someone will still have to submit it to packagist.org and depreciate the zurb version and link to the latest.

Thanks for continuing to support PHP and packagist.org

## Types of changes
- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] The pull request title and template are correctly filled.
- [X] The pull request targets the right branch (`develop` or `develop-v...`).
- [X] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by DanielRuf — APPROVED** [review]
Thank you for your contribution to Foundation Sites.

**Comment by DanielRuf** [comment]
Unfortunately someone else has grabbed it:

https://packagist.org/packages/foundation/foundation

**Comment by DanielRuf** [comment]
It seems there was nothing published under these names:

https://packagist.org/packages/zurb/foundation-sites
https://packagist.org/packages/founation/foundation-sites

Only https://packagist.org/packages/zurb/foundation

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-v6-6-1-shipped/67/1

**Comment by phpfui** [comment]
That was me.  I assumed Packagist accounts were linked to github some how,
but obviously not.

In any case, I would think in separating from Zurb you would want a
separate Packagist account not related to Zurb.  I'll reach out to the
author and see if they will release the name, as the package has 18
installs and no commits in 3 years, so assuming it is abandoned.

Bruce

**Comment by phpfui** [comment]
Reached out to shukrunor at gmail.  I'll let you know if I hear anything.

Bruce

**Comment by phpfui** [comment]
He said he is planning on using it. Pick another name and we can use that.  zfoundation maybe?

**Comment by phpfui** [comment]
He is going to help out.  Look for him on discord channel!

**Comment by DanielRuf** [comment]
> zfoundation

It is a community project now so no more `z`.

**Pull request merged**
