### PR TITLE
Fix #10229 - Add align item center to `.menu.simple`!

### LINKED ISSUE #10229: [Menu] Bug - Menu Text not working properly
Menu Text is just not working properly in develop branch / 6.4 RC

#### How to reproduce this bug:

1. Start [Visual Regression Tests](https://github.com/zurb/foundation-sites/wiki/Testing-Guide#visual-regression-tests)

2. Visit
   - http://localhost:3000/menu/menu-text-flex.html

#### What should happen:
menu-text-working

#### What happened instead:

menu-text

#### Foundation Version(s) you are using:

Develop Branch/6.4 RC

### PR DESCRIPTION
**Pull request by IamManchanda**
This fixes #10229

### CODE REVIEW

**Comment by IamManchanda** [comment]
to test this fix ... open visual tests and visit
http://localhost:3000/menu/menu-text-flex.html

**Comment by brettsmason** [comment]
@IamManchanda This seems to fix this and as far as I can see this shouldn't cause any issues.

I did notice looking a this that the `menu-text` mixin doesn't have any arguements, so the padding etc isn't independently changable, though I dont know if that matters, and is outside the scope of this fix... sorry off topic!

**Comment by IamManchanda** [comment]
@brettsmason you want to set an argumnet for this :arrow_double_down: 
https://github.com/zurb/foundation-sites/blob/9e922cd7b1d2de4fae25e3b08697f08f34b7a69b/scss/components/_menu.scss#L201

**Comment by brettsmason** [comment]
@IamManchanda No I meant this mixin: https://github.com/zurb/foundation-sites/blob/9e922cd7b1d2de4fae25e3b08697f08f34b7a69b/scss/components/_menu.scss#L330 but probably not needed.

**Pull request merged**
