### PR TITLE
Fix -zf-each-breakpoint without small

### LINKED ISSUE #9440: Bug -zf-each-breakpoint without small
### What happens

This code:
```scss
@include -zf-each-breakpoint($small: false) {
   // ...
}
```

Produce the following error
```log
➜  foundation-sites git:(develop) ✗ gulp sass:foundation
[10:46:41] Using gulpfile ~/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/gulpfile.js
[10:46:41] Starting 'sass:foundation'...
Error in plugin 'sass'
Message:
    scss/util/_mixins.scss
Error: argument `$map` of `map-remove($map, $keys...)` must be a map

       Backtrace:
       	scss/util/_mixins.scss:233, in function `map-remove`
       	scss/util/_mixins.scss:233, in mixin `-zf-each-breakpoint`
       	(...)
        on line 233 of scss/util/_mixins.scss
>>   @if not $small {
   ----------^
```

### Why

In `@mixin -zf-each-breakpoint` in [/scss/util/_mixin.scss:234](https://github.com/zurb/foundation-sites/blob/614d47210eaf17cbc0cf7421dabe4d1930aa2cf3/scss/util/_mixins.scss#L234):
```scss
  ...
  $map: $breakpoint-classes;

  @if not $small {
    $map: map-remove($map, $-zf-zero-breakpoint);
  }
  ...
```

But `$breakpoint-classes` is a list (by default: `(small, medium, large)`), not a map.

### PR DESCRIPTION
**Pull request by ncoden**
Fix #9440.

`$breakpoint-classes` is a list, not a map. Use `sl-remove()` from [SassyList](https://github.com/at-import/SassyLists) instead of `map-remove()` to remove the small breakpoint from `$breakpoint-classes`.

**Other changes:**
- Add `bower install` in Travis and README for consistency with the documentation. SassyList is only available on Bower.
- Rename `$map` to `$list`.
- Rename `$size` to `$name`. `$breakpoint-classes` contains breakpoint names, not sizes. Keep `$-zf-size` for compatibility.

---

⚠️  Require:
- [x] #9458

### CODE REVIEW

**Comment by kball** [comment]
Does this break folks who are using pure npm environments?

**Comment by ncoden** [comment]
Yes. SassyList in not in `npm`.

Otherwise, I can:
- Try to find an other library, but I looked for a long time to find this one
- Manually add the required function to Foundation, but there is a lot of stuff in Foundation that could be factorized with this library.
- Fork SassyList to add it to npm.

I'll also ask @HugoGiraudel to publish it to npm.

**Comment by HugoGiraudel** [comment]
I’d recommend not using SassyLists if you don’t need a lot of functions from it. If it’s only about `remove(..)`, I’d just implement it in Foundations Sites. If you need any help and/or review with the implementation, please be sure to ask. I’d be happy to give a hand. :)

**Comment by ncoden** [comment]
Thank you @HugoGiraudel, but its about one function _for now_. There is several functions implemented in Foundation to handle list and map, we will be able to factorize a lot of things later. 

Also, I don't like to see this code duplicated across projects. A library should rather always be used, it avoids bugs and makes maintenance easier.

In any cases, can you publish your repos on NPM ?

**Comment by HugoGiraudel** [comment]
The thing is I don’t maintain SassyLists anymore. So if you want to base the core of Foundation Sites on this, you’ll have to maintain it through PRs or move the code somewhere else. If you want to submit PRs, I’ll happily publish new versions for you on npm.

**Comment by HugoGiraudel** [comment]
+ sassy-lists@2.2.5

**Comment by ncoden** [comment]
@HugoGiraudel Yes, but do you know an other Sass library for list or maps ? :)
I didn't found it.

**Comment by HugoGiraudel** [comment]
As far as I can tell, SassyLists is by far the most comprehensive one. For maps, there is https://github.com/at-import/Sassy-Maps.

**Comment by ncoden** [comment]
Thank you. Isn't it someone else to maintain `at-import` packages ?

**Comment by HugoGiraudel** [comment]
Well, if it’s about discussing issues and merging PRs, I’m happy to do it. But I don’t have time to actively commit to SassyLists (like adding new functions and the like). So in a way, I guess I can still *maintain* it. Not push it forward though. :)

**Comment by ncoden** [comment]
This is a basic list library. I do not expect it to have new awesome features. There should only be someone to reply to PR and issues.

So @kball, what do you think ?

**Comment by kball** [comment]
So long as we can figure out the issue we've already been discussing about getting the dependencies working across the myriad of build environments, I'm fine with it.  It seems @HugoGiraudel is responsive and can do merges, we have enough sass folks in @zurb/yetinauts to implement any fixes/changes we end up needing.

**Comment by HugoGiraudel** [comment]
I just published `sassy-lists@3.0.0` for you guys. It uses `@error` instead of `@warn` + `@return null` (hence the breaking change). I also restructured the project a bit, and I moved the whole test suite to True so it’s easier to maintain.

**Comment by kball** [comment]
Merged!  Thanks @HugoGiraudel for helping out on getting the dependency in place and also with helping us think through how we package these up for distribution.

**Pull request merged**
