### PR TITLE
[Abide] submit form when validation is ok

### PR DESCRIPTION
**Pull request by viniciusban**
This closes:
- #7357 
- #7127

Actually, this fix was stolen from #7357 and nothing more.

### CODE REVIEW

**Comment by viniciusban** [comment]
@zurbchris @zurbrandon @arthurzurb could we make small corrections instead of waiting for v6.1?

**Comment by zzplab** [comment]
@gakimball Why was this pull request not included in 6.0.6 which came out today? Without it abide remains not working or is not working again.
I manually solved it in my own projects until now.
Solution was there longer time, see #7357 and with this pull request as well.

**Comment by viniciusban** [comment]
@zzplab I sent this PR exactly to isolate the solution.

It was merged yesterday by @zurbchris into `abide` branch. I hope they deliver it soon to the public.

**Comment by zzplab** [comment]
Hope so too, thanks!

**Comment by zurbchris** [comment]
Abide is getting an overhaul! All the features from pull requests (that made sense), and maybe a bit more.

**Comment by zurbchris** [comment]
Shouldn't be necessary with #7590. Submit pr's directly on the `abide` branch.

**Pull request closed without merging**
