### PR TITLE
fix: Fixed submenu bounce if nested

### PR DESCRIPTION
**Pull request by pascalknecht**
## Description
If you have a nested submenu where you want to have open submenus at the beginning.

```html
<ul>
  <li>
    <ul class="is-active">
      <li>
        <ul class="is-active">
          <li></li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```
Current behaviour:
The submenu will bounce up and come down again.

Desired behaviour:
The submenu will stay open and not bounce.

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [ ] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by ncoden** [comment]
Hi @pascalknecht 👋,

Thank you for your pull request. The next time, please open an issue too, with an easy way to reproduce the bug. I took care of this this time: https://codepen.io/ncoden/pen/BGrwQE.

**Review by ncoden — APPROVED** [review]
I split the line into several variables and added some comments to improve the readability. 

LGTM 👍. Thank you @pascalknecht!

**Comment by pascalknecht** [comment]
Hi @ncoden . Thanks for the feedback.
Glad my first pull request for foundation has been approved. How long does it usually takes for bugfixes like these to land in a release?

**Comment by ncoden** [comment]
It depends. v6.5.0 took 1 year to release, and v6.5.1 took 2 weeks 😉.

**Pull request merged**
