### PR TITLE
Adds HTML Starter Template - Fixes #7783

### LINKED ISSUE #7783: [Installation] HTML Starter Template Needed in Docs
Could there be added to the docs a HTML starter template for easy referencing?

### PR DESCRIPTION
**Pull request by andrewbiddinger**

### CODE REVIEW

**Comment by gakimball** [comment]
Nice! Was this pulled from one of our existing starter projects?

**Comment by andrewbiddinger** [comment]
Yes, it came from the starter template. I simplified it and removed "<script src="js/vendor/what-input.min.js"></script>" because that is not required to use foundation.

**Comment by gakimball** [comment]
@andrewbiddinger We'd prefer to have that in there, it's a key plugin to encourage folks to use our accessibility-friendly components, while being able to remove outlines.

**Comment by andrewbiddinger** [comment]
No problem @gakimball ! I upated that in: #7785

**Comment by gakimball** [comment]
Thanks :)

**Pull request merged**
