### PR TITLE
feat: optional black text on print #11546

### LINKED ISSUE #11546: Keep readability when printing light text on dark background
## What should happen?

When I set $print-transparent-backgrounds: false, light text on dark background should be readable.

## What happens instead?

The color of all text is set to black. Text on dark background gets unreadable.

## Possible Solution

Set color: black !important only if $print-transparent-backgrounds = true;
(Move line 24 of typography/_print.scss to line 20)

How to reproduce:
1. display any content that uses white text on a dark background (i.e. a button <a href="about.html" class="button">Learn More</a>)
2. set $print-transparent-backgrounds: false;
3. print the site (print backgroud on)

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Firfox 62, Chrome 69, Safari 12
- Device, Operating System and version: macOS Mojave

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by mameier**
Print readable text on background.

## Description

When background is printed, text should keep it's original color to stay readable.
Only set color to black if background is printed transparent.

- Closes #11546

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
Hi @mameier 👋,
Thank you for your pull request.

I understand why you proposed this change. Here is a preview of the Foundation documentation in print mode with and without your pull request:

| Before | After |
| ------ | ----- |
| screen shot 2018-10-19 at 13 14 41 |screen shot 2018-10-19 at 13 15 16 |

However, all the browsers I tested (Chrome, Firefox, Safari, on macOS and Window) disable background colors by default. In real printing conditions, the text is less visible:

screen shot 2018-10-19 at 13 21 59

**Comment by ncoden** [comment]
@mameier Will you have the time to take care of this (and squash commits) or should I open a new PR ?

**Comment by ncoden** [comment]
Closing in favor of https://github.com/zurb/foundation-sites/pull/11565.

**Comment by mameier** [comment]
your fix #11565 helps to fix my problem, thanks,
I agree with replacing my pull request with the one of ncoden.

Thanks.

**Pull request closed without merging**
