### PR TITLE
Fixes touch interactions for slider

### PR DESCRIPTION
**Pull request by Owlbertz**
Fixes the general touch support for slider plugin and I guess also for other plugins since the error seemed to affect all plugins there.

However, sliding still kinda bugs when vertical slider is used on touch devices (doesn't happen in Chrome emulation...) - I will fix that within the next days. 
Edit: Clicking the slider's track actually works well, just the dragging part needs some work.

### CODE REVIEW

**Comment by Silvester20** [comment]
Damn this is a nice one! Thanks for commiting!

Just curious, are you contracted by Zurb Foundation? If not they should :)

**Comment by Owlbertz** [comment]
Should be touch-usable now. Although the slider handle is quite hard to hit on touch. Maybe there should be some CSS making it bigger on small screens by default?

**Comment by Owlbertz** [comment]
@Silvester20 would you be able to test this one?

**Comment by rafibomb** [comment]
Thanks @Owlbertz We'll be testing this out! Would like to to get this into the next patch

**Comment by Silvester20** [comment]
@Owlbertz Yeah sure, but don't know how to test this. My site is using the foundation.min.js & foundation.min.css from the complete download package.

And I assume when I redownload the complete package the files doesn't have changed, still the same foundation.min.js as the release of 6.2.0, without your commits right?. So how can I test this?

**Comment by rafibomb** [comment]
@Silvester20 You can checkout the branch here: git checkout -b Owlbertz-touch-slider develop and pull those changes to test it. We'd love to see more people confirming the fix so we can merge it in faster.

**Comment by andycochran** [comment]
@Owlbertz—regarding "hard to hit on touch"—since small screen ≠ touch screen, we could use `what-input.js` to know when the user is trying to touch the slider and adjust the style with something like this: 
http://codepen.io/andycochran/pen/VaQzzz

**Comment by Owlbertz** [comment]
@andycochran Yeah, I had something like this on my mind as well. Looks promising.

**Comment by kball** [comment]
@Silvester20 were you able to test this out?  Alternatively, @andycochran can you try it out and see if it works as expected?

**Comment by andycochran** [comment]
@kball This is only a JS change, no CSS. So you'd be a better judge. Did we want this to address the "hard to hit on touch" problem, or should we document that in a separate issue?

**Comment by Owlbertz** [comment]
Since this fixes an actual issue I think the "convenience stuff" could be done later on, in a separate issue.

**Comment by kball** [comment]
k tested it out, seems good.  Merging.

**Comment by kball** [comment]
@Owlbertz does this fix any outstanding filed issues that you are aware of?

**Comment by Owlbertz** [comment]
At least #8666 which I recently referenced. I do believe there was something else reported by @Silvester20

**Comment by Silvester20** [comment]
I can only test this with a compiled javascript (*.js) file. But I trust you guys :)

**Comment by sjransom** [comment]
This seems to fix some touch issues I've been having. Have tested on latest iOS and Android, many thanks @Owlbertz

**Pull request merged**
