### PR TITLE
[WIP] Better Sass dependencies management

### LINKED ISSUE #9492: Refactor settings & import approach to allow dist/scss, better dependency management
Reference: https://github.com/zurb/foundation-sites/pull/9478

@ncoden please add more details

---

Our current workaround to use SCSS dependencies has a lot of problems:
- Dependencies are pushed on Git.
- Dependencies versions are pinned.
- Internal files and relations of dependencies are assumed.
- It is difficult to partially import the components (have to import `/vendor/...` too).

The goal is to move our current SCSS architecture into a real SCSS library. It require to:
- Compile all SCSS files and dependencies into a ready-to-use dist file (it is what #9478 did).
- Provide an easy way to import dependencies like [Eyeglass](https://github.com/sass-eyeglass/eyeglass), for the user who wants to import partials.
- Make the setting file be imported _after_ Foundation, so do not generate components or variable automatically, and wait for the ZF mixins and functions to be called.

### PR DESCRIPTION
**Pull request by ncoden**
From: https://github.com/zurb/foundation-sites/pull/9478
Fix: https://github.com/zurb/foundation-sites/issues/9492

#### Changes:
- [x] Revert #9430, #9458, #9469.
- [x] Provide a "ready-to-use" SCSS dist file `dist/scss/foundation.scss` with dependencies included.
- [x] Import Sass dependencies using [Eyeglass](https://github.com/sass-eyeglass/eyeglass). (require https://github.com/theJian/gulp-shopify-sass/issues/17)
- [ ] Remove `settings.scss` deps and ensure it can be imported _after_ Foundation.
- [ ] Update documentation

*Note to myself: the `_vendor` folder was a f stupid idea. Don't do that again !*

### CODE REVIEW

**Comment by kball** [comment]
@ncoden what is the current state of this PR?

**Comment by ncoden** [comment]
I have to:
- Finish a commit for `gulp-shopify-sass` (ensure it does not create bugs).
- Move some variable definitions in grids to mixins/functions.
- Update docs.

**Comment by ncoden** [comment]
Some news: I just added Eyeglass support for `gulp-shopify-sass`.
Still to do: Move variable definitions to mixins/functions and update docs.

**Comment by kball** [comment]
Coming back to this, @ncoden what was the status here?

**Comment by DanielRuf** [comment]
We have to rebase this PR. Is this still highly relevant when we switch to a pure webpack solution?

**Comment by joeworkman** [comment]
Going to close this one out and we can rethink this for F7.

**Pull request closed without merging**
