### PR TITLE
🚀  Release v6.5.1

### PR DESCRIPTION
**Pull request by ncoden**
# Foundation v6.5.1

This version fixes the distribution files for the JavaScript plugins that were generated for the wrong version (ongoing v6.6.0 instead of released v6.5.0) and provide various bug fixes and documentation updates.

**Note about this pull request:** As this version was built to have the best compatibility with `v6.4.4-rc1`, we used a dedicated branch and manually picked safe changes from the development branch `develop`, excluding API evolutions and breaking changes. These imported changes are the `Use pull request #xxx` commits you can see in this pull request. Development will continue on `develop` and will lead to a future release with all changes, including new features and breaking changes.

<br>

## Changes from [v6.5.0](https://github.com/zurb/foundation-sites/releases/tag/v6.5.0)

* 🐛  <samp>#11573</samp> - Ensure Dropdown label to have an ID for a11y (@ncoden, #11572)
* 🐛  <samp>#11579</samp> - Cleanup "is-active" class in AccordionMenu when closed (@ncoden, #11383)
* 🐛  <samp>#11581</samp> - Fix arrow color in clear dropdown Button (@ncoden, #11581)
* 📖  <samp>#11562</samp> - Cleanup an invalid beacon in Grid docs (@xeptore)
* 📖  <samp>#11564</samp> - Add missing doc for the "$print-hrefs" setting (@ncoden)
* 🚚  Reimport incorrectly imported patch for #11418 (16b8e38, previously 55e60ee).
* 🚚  Regenerate JavaScript plugins distribution files to reflect the new version.

<br>

## Contributors
* mbehboodian ([@xeptore](https://github.com/xeptore)) [1]
* Nicolas Coden ([@ncoden](https://github.com/ncoden)) [7]

Special thanks to:
* Daniel Ruf ([@DanielRuf](https://github.com/DanielRuf)) for his assistance in issues and his reviews of pull requests.
* Jeremy Englert ([@JeremyEnglert](https://github.com/JeremyEnglert)) for his assistance in issues.

<br>

## Release Checklist
- [x] Bump versions
- [x] Update lockfiles
- [x] Update dist files
- [x] Update SCSS settings file
▾
- [x] Update documentation
▾
- [x] Prepare release for npm
- [x] Prepare release for Composer
- [x] Prepare release for Meteor - _Must be published before the Git release for `.versions`_
- [x] Prepare release for Rails - _Must be published on [foundation-rails](https://github.com/zurb/foundation-rails)_
- [x] Prepare release for NuGet - _Must be published with [nuget-publish](https://www.npmjs.com/package/nuget-publish)_
▾
- [x] Released!

### CODE REVIEW

**Comment by ncoden** [comment]
Closes https://github.com/zurb/foundation-sites/issues/11583

**Comment by ncoden** [comment]
@DanielRuf @IamManchanda @JeremyEnglert 
Hi 👋, could I get your review on this ?

**Comment by JeremyEnglert** [comment]
I'll have time to review this Wednesday.

**Review by JeremyEnglert — APPROVED** [review]
This JS dist files look great.

**Pull request merged**
