### PR TITLE
[WIP] feat: add header classes and mixins

### PR DESCRIPTION
**Pull request by ncoden**
See: #9483

#### Changes:
- Add a class for each header (`.h1`, `.h2`...)
- Add `@mixin header` to generate basic header styles
- Add `@mixin header-style` to generate graphic header styles
- Use these mixins in `scss/typography/base`.

### CODE REVIEW

**Comment by kball** [comment]
@ncoden is it fair to say that these separated mixins (`header` and `header-style`) are separating the concepts of the reset & the graphical styles?   However, in the _generated css_ we still apply the graphical styles to the header elements themselves, not just the classes...

Given there is interest in moving all graphical styles into classes, do you think it makes sense to introduce a configuration setting (that we can gradually integrate/reference in more places) that restricts the application of graphical styles to only the classes and not the elements?

**Comment by ncoden** [comment]
@kball 
1/ I don't think the header mixins are separated from the base typography context. But I think having all the base typography in one large file is not a good idea. This file should be split into many mixins into many files, one per component or group of closely related components. So _for now_, I put these mixins into their own file.

2/ We still apply the graphical styles to the header elements, yes. Otherwise, it would be a breaking change. I never thought about removing the default styles, not until the v7. Do you think we should ?

3/ Yes, I think it makes sense... https://github.com/zurb/foundation-sites/pull/8718 😄

**Comment by brettsmason** [comment]
@ncoden somehow I didn't see this come up. Had a quick look and it looks great, amazing job!
I'll give it a proper test over the weekend 👍

**Comment by kball** [comment]
@brettsmason were you able to give this a test?

**Comment by DaSchTour** [comment]
I find this a bit confusing. For me it looks like styles are added for h1-h2 and than again for h1-h6 and .h1-.h6 and as header() includes header-style() it would include h1 h1, h1 h2 and so on.
I think there should be only one point where styles may possibly applied and not two.

**Comment by ncoden** [comment]
@DaSchTour 
> it looks like styles are added for h1-h2...

You mean h1-h6 ?

> ...and than again for h1-h6 and .h1-.h6 and as header() includes header-style() it would include h1 h1, h1 h2 and so on...

_Base_ styles (from `@mixin header`) and _default sizes_ (from `@mixin header-style` with `$styles:(), $base: true`) are included at :315, and _Breakpoint styles_ (from `@mixin header-style`  with `$base: false`) are included at :318. Nothing else. There is no duplicated properties.

> I think there should be only one point where styles may possibly applied and not two.

I agree with you. We should dynamically generate the base styles of the headers too. But I wonder if we should generate sort of _reset_ properties for standard headers (h1-h6) if they are not in the map, since normalize does not do it.

**Comment by DaSchTour** [comment]
@ncoden okay well, I see. I guess confusion came from the fact, that typography mixes resets and typography. Maybe that should be separated?

**Comment by ncoden** [comment]
@DaSchTour That should be separated, for typography and for all others components.

**Comment by kball** [comment]
@ncoden based on the comment above, do you want to separate for typography in this PR or is that a separate one, and this is ready to merge?

**Comment by ncoden** [comment]
@kball It requires a lot of work, a refactor 😄 !  (And that's not the subject of this PR). So I'll try do it later.

**Comment by kball** [comment]
@brettsmason you mentioned you were going to give this a test - did you? From your perspective are we good to merge?

**Comment by brettsmason** [comment]
@ncoden @kball Sorry for the delay I forgot about this over Christmas.

So I've had a bit of a play with this. One thing I noticed - we added `.h1, .h2` etc to the heading styles section, but they aren't included in the first headings bit. This means the generated classes dont contain the font family, style, colour etc. Not sure if we should include them there or not?

I need to try out the mixins later today so I'll get back to you on those once I work out how to use them correctly.

**Comment by ncoden** [comment]
> This means the generated classes dont contain the font family, style, colour etc

Right. @DaSchTour talked about a similar problem.

We can do something like this:
```scss
  %header {
    @include header();
  }

  // Headings styles
  @each $size, $headers in $header-styles {
    @include breakpoint($size) {
      @each $header, $header-defs in $headers {
        #{$header}, .#{$header} {
          @if $size == $-zf-zero-breakpoint {
            @extend %header;
          }
          @include header-style($header-defs);
        }
      }
    }
  }
```

We have to use a `%placeholder` here to do not duplicate styles across breakpoints (btw, there is a lot of places in the codebase where we should use it). However, this is just an example and there is better way to use it, like _inside_ the component with a `$extend` Boolean property.

**Comment by kball** [comment]
@ncoden what is the status of this PR?

**Comment by IamManchanda** [comment]
@kball @ncoden What's the state of this... I think we can close this .. No ??

**Comment by oxyc** [comment]
I still think is a very useful feature and I use something similar in my own projects all the time. 

I feel heading styles shouldn't be tied to the heading level. For instance, I only want one `<h1>`, but maybe I want all section headings of a page to be styled the same way. Or maybe the `<h1>` is in the hero banner, rather than the content area on some pages. Therefore I often use BEM instead as  I prefer to use `section__title`, `page__title`, `teaser__title` etc.  Having a `@mixin header-style` makes this easy.

On several occasions I've needed to style a non-header element as a heading (`<select>`, pagination, primary menu, button). Having a `%header` placeholder helps a lot.

I've had several designs where different heading levels have different font-families. `%header` makes it possible to reset the styling when I don't want the styling tied to the level (mentioned in my first use case).

**Comment by DanielRuf** [comment]
Definitely makes sense and is also helpful for good SEO.

**Comment by oxyc** [comment]
Today I learned you can define placeholders multiple times, enabling stuff like this:

```scss
  %header {
    @include header();
  }

  // Headings placeholders
  @each $size, $headers in $header-styles {
    @include breakpoint($size) {
      @each $header, $header-defs in $headers {
        %#{$header} {
          @include header-style($header-defs);
        }
      }
    }
  }

%h1 {
  text-transform: uppercase;
}

  // Headings styles
  @each $size, $headers in $header-styles {
    @include breakpoint($size) {
      @each $header, $header-defs in $headers {
        #{$header}, .#{$header} {
          @if $size == $-zf-zero-breakpoint {
            @extend %header;
          }
          @extend %#{$header};
        }
      }
    }
  }


.accordion-title { @extend %h1; }
```

**Comment by kball** [comment]
Closing old WIP PRs

**Pull request closed without merging**
