### PR TITLE
[Table] Don't at-root the inner table styles. Makes it impossible to namespace

### PR DESCRIPTION
**Pull request by tjhiggins**
Unsure the original reason for the @at-root, but this mixin gets set on the table anyways.

### CODE REVIEW

**Comment by gakimball** [comment]
I'd like to make this configurable instead. The reason we use @at-root is to keep the specificity lower. For example, the selector `thead` is better than `table thead`. *However*, that's not what you want if you're applying the mixin to a class.

You could add a parameter to the mixin like `$nest`. If it's `false`, it uses @at-root, and if not, it doesn't.

**Comment by tjhiggins** [comment]
@gakimball What would be the correct way to conditionally @at-root. Only thing that I can think of is another helper mixin.

**Comment by gakimball** [comment]
It'll look a bit messy, but yeah, that's a solution. It can be a private mixin, so we won't document it anywhere. The code structure will look something like this:

```scss
@mixin -zf-table-children-styles {
  // ...
}

@mixin table(
  $stripe: $table-stripe,
  $nest: false
) {
  @if $nest {
    @include -zf-table-children-styles;
  }
  @else {
    @at-root {
      @include -zf-table-children-styles;
    }
  }
}
```

**Comment by tjhiggins** [comment]
@gakimball Updated. Is this what you had in mind or should there be a global variable (table-nest) in _settings?

**Comment by gakimball** [comment]
Nah, no global variable is needed. Thanks for implementing the feedback! :)

**Comment by xzyfer** [comment]
It's worth nothing this usage of `at-root` is currently incompatible with LibSass.

**Pull request merged**
