### PR TITLE
🚀  Release v6.5.2

### PR DESCRIPTION
**Pull request by ncoden**
# Foundation v6.5.2

This version provide various bug fixes and improvements for Foundation 6.5, update the documentation and improve the test workflow.

**Note about this pull request:** As this version was built to have the best compatibility with `v6.4.4-rc1`, we used a dedicated branch and manually picked safe changes from the development branch `develop`, excluding API evolutions and breaking changes. These imported changes are the `Use pull request #xxx` commits you can see in this pull request. Development will continue on `develop` and will lead to a future release with all changes, including new features and breaking changes.

<br>

### Fixes and improvements
* 🐛  <samp>#11592</samp> - Fix an issue with Triggers utility when the plugin name is an object (@DanielRuf)
* 🐛  <samp>#11605</samp> - Import used Touch utility in Dropdown and Reveal (@ncoden, #11604)
* 🐛  <samp>#11606</samp> - Fix Accordion bouncing with active submenus on initialization (@pascalknecht)
* 🐛  <samp>#11622</samp> - Fix SmoothScroll ignoring the passed options (@ben-z, #11620)
* 🐛  <samp>#11634</samp> - Prevent the XY Grid container to override top/bottom margins (@HarwinBorger, #11633)
* 📖  <samp>#11608</samp> - Update CodePen test case templates to Foundation v6.5.1 (@ncoden)
* 📖  <samp>#11610</samp> - Add availability of features in the XY Grid doc (X/Y only or both) (@ncoden, #11601)
* 📖  <samp>#11619</samp> - Remove warning for abandoned deprecations in SCSS utilities (@ncoden, #10540)
* 📖  <samp>#11644</samp> - Update license and copyright notices to 2019 (@benhc123)
* 🚚  <samp>#11607</samp> - Revert to labelling Foundation as "with side effects" (@ncoden, #11586)
* 🚚  <samp>#11618</samp> - Fix names of modules for AMD/CommonJs (@ncoden, #11614)

### Internal
* 🛠️  <samp>#11595</samp> - Remove duplicate CSS properties in Grid examples (@DanielRuf)
* 🛠️  <samp>#11596</samp> - Remove unused background CSS properties in doc (@DanielRuf)
* 🛠️  <samp>#11597</samp> - Remove duplicate CSS properties in Progress bar (@DanielRuf)
* 🛠️  <samp>#11598</samp> - Remove duplicate CSS properties in Drilldown (@DanielRuf)
* 🛠️  <samp>#11636</samp> - Remove duplicate code in Nest utilities (@DanielRuf)
* 💻  <samp>#11538</samp> - Run tests on Linux, macOS and Windows (@DanielRuf)
* 💻  <samp>#11635</samp> - Run tests on latest Node.js version (@DanielRuf)

<br>

## Contributors
* Ben Holden-Crowther ([@benhc123](https://github.com/benhc123)) [1]
* Ben Zhang ([@ben-z](https://github.com/ben-z)) [3]
* Daniel Ruf ([@DanielRuf](https://github.com/DanielRuf)) [13]
* Harwin Borger ([@HarwinBorger](https://github.com/HarwinBorger)) [1]
* Nicolas Coden ([@ncoden](https://github.com/ncoden)) [17]
* Pascal Knecht ([@pascalknecht](https://github.com/pascalknecht)) [1]

<br>

## Release Checklist
- [x] Bump versions
- [x] Update lockfiles
- [x] Update dist files
- [x] Update SCSS settings file
▾
- [x] Update documentation
▾
- [x] Prepare release for npm
- [x] Prepare release for Composer
- [x] Prepare release for Meteor - _Must be published before the Git release for `.versions`_
- [x] Prepare release for Rails - _Must be published on [foundation-rails](https://github.com/zurb/foundation-rails)_
- [x] Prepare release for NuGet - _Must be published with [nuget-publish](https://www.npmjs.com/package/nuget-publish)_
▾
- [x] Released!

### CODE REVIEW

**Comment by ncoden** [comment]
> Hm, not sure if it is good to mix Yarn and npm commands.

I don't know. But it's the same on `develop`

> But weird that the Windows builds are nit green anymore. I'll contact the Travis XI team.

There is issues with Yarn+Windows on Travis. This, `There appears to be trouble with your network connection` times to times.

**Comment by glen-84** [comment]
Will this be released soon?

v6.4.3 is broken because of `main` pointing to ES6 code.
v6.5.1 is broken because of #11586.

😞

**Comment by ncoden** [comment]
@glen-84 See https://github.com/zurb/foundation-sites/issues/11586#issuecomment-438458366

We are waiting for Travis to pass, there is some issues with Window. This should be released by the end of the week.

**Comment by glen-84** [comment]
Are you running Windows locally, or another OS? I mean, is this specific to Travis CI, or a general issue with Windows builds?

I see that "Windows builds are in early access stage".

**Comment by glen-84** [comment]
> Error: Failed to launch chrome!
[0112/003942.079:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from C:\Users\travis\build\zurb\foundation-sites\node_modules\puppeteer\.local-chromium\win64-594312\chrome-win\chrome.dll: The specified module could not be found. (0x7E)

https://travis-ci.community/t/puppeteer-not-working-on-windows-container/354

It might be worth trying the latest version of Puppeteer?

**Comment by ncoden** [comment]
@glen-84 This is not related. See https://travis-ci.org/zurb/foundation-sites/jobs/478599448#L281

**Comment by glen-84** [comment]
I see.

It looks like *lots* of people are seeing this error ... https://github.com/yarnpkg/yarn/issues/4890 https://github.com/yarnpkg/yarn/issues/5259.

Is it worth trying `--network-timeout 1000000`?

... or switching to `npm`. 🙂 

Did you or @DanielRuf contact Travis support?

**Comment by DanielRuf** [comment]
> ... or switching to npm

npm has more and bigger issues.

**Comment by DanielRuf** [comment]
It is the Puppeteer issue.

https://travis-ci.org/zurb/foundation-sites/jobs/478599448#L290

`develop` has a newer version. So this should be fine to update and cherry-pick the update of the dependency @ncoden

**Comment by glen-84** [comment]
@ncoden Will you be able to try this soon?

**Comment by glen-84** [comment]
Is there anything that I can do to help?

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
