### PR TITLE
docs: update ZURB template JavaScript docs #10353

### PR DESCRIPTION
**Pull request by ncoden**
Changes:
* Add infos about webpack
* Add infos about Babel
* Update recommended import process
* Change list of useful resources

Closes https://github.com/zurb/foundation-sites/issues/10353

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
@ncoden - this looks great to me. 

Couple of notes:

- I noticed you used "Javascript", while most of the docs seem to use the camelcase "JavaScript"
- Should "Js" be "JS"?
- I see "Webpack" and "WebPack"
- The first sentence has an extra "and" in it. "Javascript is transpiled using **and** Babel (with the es2015 plugin) so you can use ES2015 features."
- Missing "s" in "compiles" - "...it manages all assets and dependencies for you and **compile** them into one single file..."

**Comment by ncoden** [comment]
I have really No Idea (and no opinion) about "Javascript"/"JavaScript"/"Webpack"/"WebPack". Thank you for the typo review. 👍

**Comment by JeremyEnglert** [comment]
No, no, no. Thank YOU for fixing these. Great work!

**Comment by ncoden** [comment]
So in the webpack [https://webpack.js.org/](site) and [repo](https://github.com/webpack/webpack) they say `webpack`, and [according to StackOverflow](https://stackoverflow.com/questions/3989731/is-it-javascript-or-javascript) and [Wikipédia](https://en.wikipedia.org/wiki/JavaScript) we should say `JavaScript`.

**Comment by ncoden** [comment]
@JeremyEnglert Fixed.

**Comment by JeremyEnglert** [comment]
Looks perfect!

**Pull request merged**
