### PR TITLE
[WIP] Add submenuToggle option to accordion menu

### LINKED ISSUE #7770: [Accordion Menu/Drilldown] Feature request/suggestions
I love the new menu system as a whole but would love to see a few enhancements to the accordion menu/drilldown menu for menus that have sub navigation to make it possible to click the sub-menu parent links - its the one thing stopping me using both of them.
### Drilldown

I would love to see an option (`data-options`?) that added the parent menu link as a link (copy?) in the sub-menu, so that it was clickable.
### Accordion Menu

Similar issue - it would be great if we could have an option to keep the link on the parent item and make the sub-menu toggle a separate element so that the parent link still works.
An example of what I mean is [here](http://samikeijonen.github.io/responsive-nav.js/demos/multiple-levels/index.html). There's also a writeup about it [here](https://foxland.fi/accessible-multi-level-dropdown-navigation/) if that helps.

I'd love to discuss this further and any other ideas! Unfortunately my JS skills are very limited so I can't do much to help in that area yet :disappointed:

### PR DESCRIPTION
**Pull request by brettsmason**
This is work in progress but I wanted to put a PR together so its not forgotten about!

This allows the parent menu link to function as a link.
It adds a separate `.submenu-toggle` button which now toggles the submenu display.

Still do to:
- [x] Decide on a styling path to define the `.submenu-toggle` visually. @andycochran I'd like to bounce some ideas I have off you on this 😄 
- [ ] Work out required keyboard navigation

This closes #7770 when complete.

### CODE REVIEW

**Comment by andycochran** [comment]
As discussed in #7770, the best way to style these submenu toggles is as split buttons. Visually, we simply need to put a vertical line between the link and the toggle button. With split buttons that's done via margin allowing the background to show through. But that won't here. We'd need to either introduce background colors or borders. 

We _could_ style Accordion Menu with the same borders as Accordion — which would allow us to put a line between the link and toggle button. For backwards compatibility, if you don't want borders or submenu toggles, just set the new `$accordionmenu-border` variable to `none`.

**Comment by brettsmason** [comment]
So I discovered by looking through the codebase that that responsive menu plugin is already setup to work with a `accordion-menu` class which isn't currently in use. This allows us to apply borders and backgrounds to correctly differentiate the submenu toggle.

I still need to tidy up the Sass and reorder it etc, but the concept now visually works.

**Comment by brettsmason** [comment]
@andycochran @kball I have added a demo with the styling I added to the `.accordion-menu` class here: http://brettmason.co.uk/submenu-toggle/accordion-dropdown-test/accordion-dropdown.html

I personally think the styling now looks fine.

However running this responsive menu test revealed a few things. 

- The classes on the parent `<li>` aren't being removed - eg `has-submenu-toggle is-dropdown-submenu-parent`. I dont think this is related to this PR, but does need to be fixed.

- The `submenu-toggle` button isn't being removed when shifting to the dropdown menu

**Comment by kball** [comment]
@brettsmason I think between your last push and mine the issues are addressed, but please test & confirm.

**Comment by brettsmason** [comment]
So the only thing missing is the keyboard navigation needs correcting if anyone is able to take a look at this? I will also amend the docs to include an example using the toggle as well as the `.accordion-menu` class.

**Comment by brettsmason** [comment]
@Owlbertz You're an accessibility wizard 😄
On the 2 points above do you have an opinion on the correct way to make this accessible?

**Comment by Owlbertz** [comment]
@brettsmason:
- `aria-expanded` should be placed on the `button` (see [spec](https://www.w3.org/TR/wai-aria/states_and_properties#aria-expanded).
- The button needs text if it does not contain any text itself. Of course it is always helpful to add additional information on what will happen.

Maybe @sethkane can correct me if I am wrong.

**Comment by sethkane** [comment]
Sorry @Owlbertz you are right the aria-expanded should be on the button "Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed."  Sorry for the delay work is crazy.

**Comment by brettsmason** [comment]
@Owlbertz @sethkane thanks a lot for your input 😄 
I have now added text for accessibility as well as set `aria-expanded` on the button. What I now cant work out is what sets the initial `aria-expanded` on the `<li>` element so I can remove it when this option is enabled - I cant see any code that does this unless I'm missing it...

The only remaining thing then is the keyboard navigation, which currently I have no clue how to sort!

**Comment by Owlbertz** [comment]
@brettsmason I pulled this down and had a look. Imho the `aria-controls` needs to be placed on the `button` rather than the `li` (as the `li` does nothing here).

**Comment by brettsmason** [comment]
@owlbertz great thanks for taking a look.

I'll look at adding the aria-controls to the button. If you take a look though, there is an aria-expanded on the list element, but I can't work out where it gets applied from! 

The keyboard nav just doesn't feel like it's right at the moment, and needs changing if the button is active.

**Comment by Owlbertz** [comment]
@brettsmason the `aria-expanded` that is set comes from [this line](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.nest.js#L32), seems like it is currently automatically applied during `reflow()`.

**Comment by brettsmason** [comment]
@Owlbertz Thanks for finding this for me, I was lost!

@kball What would be the best way to remove the `aria-expanded` if this option is enabled? I can remove it on init, but is that the right route?

Also I have no clue on the keyboard navigation, so will need help to get this implemented in time for 6.3, but I really want it included to pair with off canvas 😄

**Comment by kball** [comment]
Hmm good question @brettsmason.  I think this might actually tie into the discussion we were having here: https://github.com/zurb/foundation-sites/pull/9381#issuecomment-263344303 (cc @ncoden @diniscorreia @DaSchTour) about using data-attributes to specify children (and auto-applying in base cases)... right now the components pre-assume a ton about structure which works fine in base case but causes challenges in more complex cases.

It may be a little late in the cycle for this for 6.3, but what if we changed all of these menus to use data-attributes to specify child elements and then auto-applied them in the "basic" cases?  I think that would make it much easier to target the right elements for things like this aria attribute.

**Comment by brettsmason** [comment]
@kball I agree its probably a bit tough to get that sorted for 6.3.
In terms of getting this PR implemented into 6.3 do you think there's any way we could get something implemented so it could get included, even if its not perfect? The only remaining issues are `aria-expanded` and the keyboard nav.

**Comment by kball** [comment]
@brettsmason I think I've got the accessibility behaving properly now, though I'd love to get @Owlbertz or @sethkane to verify as they are more knowledgeable on accessibility than I am. On the keyboard nav... playing around with it now after merging develop into it, it actually seems to be working pretty well.

**Comment by brettsmason** [comment]
@kball awesome thanks. I think from memory navigating from submenu back up to parent should go to button first not list element, and parent list element shouldn't expand submenu. Turned everything off for today though so can't check.

**Comment by sethkane** [comment]
Sorry guys have been swamped at work, I will do my best to follow up with all my mentions tonight or tomorrow night at the latest.

**Comment by tsquez** [comment]
So just to be clear, `data-parent-link="true"` still does not work with the accordion menu?

**Comment by brettsmason** [comment]
@tsquez Unfortunately not. We ran out of time to get it finished (most of my time was spend on revamping off canvas) and there were still a few bugs to iron out.

I'll make sure it gets included in the next larger release though (6.4).

**Comment by tsquez** [comment]
@brettsmason - no worries amigo was just checking for a few users. Keep up the good work.

**Comment by nickroberts** [comment]
Great work, guys! Looking forward to being able to use this!

👍

**Comment by hadl** [comment]
Awesome work!

To fix https://github.com/zurb/foundation-sites/issues/8301 could you please move the "Foundation.Nest.Feather" call from the constructor to the _init method?
If you make this change, please check for the toggle-button before appending it. Otherwise you will get multiple "togglers" on every reInit() call.

Also remove the .is-active class inside the up() method. The reInit() will open all previously opened submenus if this class is present. 
Or is this an expected behaviour?

With those changes appending new submenus via js is working.

**Comment by kball** [comment]
I just brought this up to date with the current state of develop... it looks like it's working to me. @Owlbertz can you pull it down and verify the aria behavior is as we'd expect? If so I think we're good to go and can merge this for 6.4

**Comment by Owlbertz** [comment]
The interactive parts (attribute toggling and stuff) look good for me, but I feel like the whole thing behaves more like a tree than like a menu ([see this page](https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView)). This would mean that we need to change the `role` of the items slightly.

**Comment by kball** [comment]
Brought this up to date with develop... @Owlbertz can you confirm I didn't bork the merging of your tree logic in? (it wouldn't auto merge), and then lets get this sucker merged!

**Comment by Owlbertz** [comment]
@kball Looks good to me in terms of my latest PR regarding the `role="tree"` thing. However, I noticed that it is not possible to activate the links on root level via keyboard. Pressing enter just expands the sub-menu. I think the desired behavior would be the same as for mouse usage: toggling of the sub-menu only via the dedicated button and activating the links with the accordion title itself.

**Comment by Owlbertz** [comment]
Just adjusted that myself. Please check and then go for the merge!

**Comment by kball** [comment]
👍

**Comment by kball** [comment]
Woohoo! Took since November but we finally got this sucker in. Nice work @brettsmason @Owlbertz

**Comment by brettsmason** [comment]
Yay thanks guys for getting it across the line! 😁

**Comment by tsquez** [comment]
So `data-parent-link="true"` is working now? Sorry  haven't had a chance to try this yet but very anxious to do so.

**Comment by brettsmason** [comment]
@tsquez it will be included in 6.4! (RC out tomorrow I think)

**Comment by tsquez** [comment]
HECK YES!!! Great job amigo!

**Comment by cfabrice** [comment]
That's great but the pbl remains when used with responsive navigation like data-responsive-menu="accordion medium-dropdown" as mentionned in the "responsive navigation" part of the doc.
Or is it me ?

**Comment by tsquez** [comment]
@cfabrice the issue was corrected. If you would like you can see it in action here https://themeawesome.com/themes/wpforge/ - granted its a WordPress theme but it still works like it should.

**Comment by cfabrice** [comment]
Oh sorry, I was playing with the codepen of the official docs (https://codepen.io/IamManchanda/pen/jmxVPP) but it was calling in foundation 6.3 still !!!

**Pull request merged**
