### PR TITLE
tests: use husky to run tests before commits and pushes

### PR DESCRIPTION
**Pull request by DanielRuf**
We should force to run `npm test` on each commit / push.

Should we use `precommit` and `prepush` or just one of both?

Closes https://github.com/zurb/foundation-sites/issues/11042

The rest of it will be probably covered in future code quality related PRs for all devs.

### CODE REVIEW

**Comment by DanielRuf** [comment]
PS: I did not add the changed package-lock.json file but we may have to update it.

Also see #11046

**Review by ncoden — APPROVED** [review]
That's nice 🐶

Because a common rule in Git is that _the code should always run_, I guess we can use `precommit`. And `prepush` does not harm :).

**Comment by ncoden** [comment]
I seen #11046. I think I'll take care of adding it after manually upgraded all our dependencies to prepare v6.5.

**Comment by ncoden** [comment]
I just noticed this PR is number #11111 😄

**Comment by ncoden** [comment]
>  chore: add message for about Husky at precommit & prepush 

screen shot 2018-04-01 at 18 25 14

**Comment by DanielRuf** [comment]
This will probably not work on most Windows machines @ncoden, why not ouput it directly with Node.js?

**Comment by ncoden** [comment]
Ah, yeah...

**Comment by ncoden** [comment]
Actually, what would not run in Windows ?
The whole NPM environement with npm scripts is based on bash, and Windows users are invited to set by themselve the program to use for commands.

**Comment by DanielRuf** [comment]
bash can not be used in cmd and git is globally available on the path but bash isn't, just in the extra environment.

Will test later on my machine but it will not run afaik.

**Comment by DanielRuf** [comment]
```
$ npm run precommit

> foundation-sites@6.4.3 precommit C:\Users\Daniel\GITHUB\foundation-sites
> ./script/husky-precommit

Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-sites@6.4.3 precommit: `./script/husky-precommit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-sites@6.4.3 precommit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2018-04-01T19_34_49_592Z-debug.log
```

I'll provide a working solution.

**Comment by DanielRuf** [comment]
There you go =)

**Comment by ncoden** [comment]
Thanks 👍

**Comment by DanielRuf** [comment]
Oops, small copy paste error =/
Forgot to rename it in package.json.

**Comment by ncoden** [comment]
Fixed :)

**Comment by DanielRuf** [comment]
Actually had it prepared here but not commited anymore.

**Comment by ncoden** [comment]
Also, the Sass output is not colored anymore. Do you have an idea of what is causing this ?

**Comment by DanielRuf** [comment]
I guess this is because it is running in another context now and the color support is disabled there. I'm checking if we can use another linting solution here.

**Comment by DanielRuf** [comment]
Should be colored again now.

**Comment by DanielRuf** [comment]
Forcing the colors mode now by default. For sass-lint we might move to stylelint somewhere in the future.

**Comment by DanielRuf** [comment]
I guesset  I should set the setting to rebase by default here too.

Should I squash merge or rebase now and push force the last 3 commits as one?

**Comment by ncoden** [comment]
> 360380d chore: remove code test output

Please always put the context in your commits. "chore: remove code test output _in husky scripts_" 😉

**Comment by ncoden** [comment]
> Should I squash merge or rebase now and push force the last 3 commits as one?

Since no reviews are based on these, yes please do shash them ;).

**Comment by ncoden** [comment]
Side note: I really love this emoji 🐶

**Comment by ncoden** [comment]
I guess it's good to go 👍

**Pull request merged**
