### PR TITLE
[WIP]  fix fouc for drilldown menus #11770

### LINKED ISSUE #11770: FOUC for drilldown menus
## What should happen?

When the page loads, the drilldown sub-menus should not be briefly visible then hidden (FOUC)

## What happens instead?

When the page loads, the drilldown sub-menus are briefly visible then hidden (FOUC).

I've experience the issue on both Firefox 67 and Chromium 74 on LinuxMint 19.1. You can see this behavior on the [drilldown documentation site](https://foundation.zurb.com/sites/docs/drilldown-menu.html) if you scroll down to one of the examples and refresh the page a few times.

## Possible Solution

There is a suggestion to add the `.no-js` class to the `html` tag of the document in order to prevent the FOUC problem. Looking at the source for the [dropdown-menu component](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_dropdown-menu.scss#L165), the `.no-js` is specifically targeting child lists of the `.dropdown.menu`, but this doesn't exist in the stylesheet for the [drilldown menu](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_drilldown.scss).

In my project, adding the same CSS rule to the `.dropdown` effectively prevents the FOUC.

## Test Case and/or Steps to Reproduce (for bugs)

[Test Case](https://s.codepen.io/noahheck/debug/JqgXYV/NjMYzqgVJNOr): https://s.codepen.io/noahheck/debug/JqgXYV/NjMYzqgVJNOr

(refresh a few times in succession to see the issue; I think because there is so little content in the codepen, the issue doesn't appear very often; see the example on the Foundation documentation site for a more reliable example)

How to reproduce:
1. Go to the Foundation [drilldown documentation page](https://foundation.zurb.com/sites/docs/drilldown-menu.html#basics), scroll down to the first example and refresh the page a few times

## Context

The navigation sidebar for my app contains too many options to show at one time, and the drilldown component works great for organizing the options. The FOUC is just enough to look unprofessional.

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Firefox 67 & Chromium 74
- Device, Operating System and version: Linux Mint 19.1

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by noahheck**
The .no-js fix for preventing FOUC in other components doesn't seem to have been applied to the drilldown component. This results in FOUC for drilldown sub-menus. This applies the .no-js fix to child menus of the drilldown component to prevent the FOUC.

## Description

I added the `.no-js` FOUC fix to target the child menus of the drilldown component.

- Closes #11770 

## Types of changes

- [ ] Documentation
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] The pull request title and template are correctly filled.
- [X] The pull request targets the right branch (`develop` or `develop-v...`).
- [X] My commits are correctly titled and contain all relevant information.
- [X] I have updated the documentation accordingly to my changes (if relevant).
- [X] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @noahheck,

> The .no-js fix for preventing FOUC in other components doesn't seem to have been applied to the drilldown component

I checked some scss files and did not see `.no-js` there. Which fix do you mean? Your change would probably preent that the content is not displayed for users without JS which is bad for the accessibility.

**Comment by DanielRuf** [comment]
Hi @noahheck,

thanks for your contribution to Foundation Sites.

> The .no-js fix for preventing FOUC in other components doesn't seem to have been applied to the drilldown component

I checked some scss files and did not see `.no-js` there. Which fix do you mean? Your change would probably preent that the content is not displayed for users without JS which is bad for the accessibility.

**Comment by noahheck** [comment]
@DanielRuf 

Here is how the .no-js is applied in the dropdown-menu component: 

https://github.com/zurb/foundation-sites/blob/develop/scss/components/_dropdown-menu.scss#L165

**Comment by DanielRuf** [comment]
Ah ok.
We should still check if we can do it this way or if we have to adjust some attributes.
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.dropdown.js#L82

cc @Owlbertz

**Comment by JeremyEnglert** [comment]
So the potential issue here is if JS doesn't load, the menu is completely hidden. 

We've generally had users handle this type of behavior on their own, for example: https://foundation.zurb.com/sites/docs/responsive-navigation.html#preventing-fouc

@DanielRuf, thoughts?

**Comment by DanielRuf** [comment]
If we document it, it should be fine @JeremyEnglert.

**Comment by DanielRuf** [comment]
Closing as this should be handled by users depending on their requirements.

**Pull request closed without merging**
