### PR TITLE
fix: fix XY Grid responsive widths with shrink/auto #10891

### LINKED ISSUE #10891: auto and shrink cells are broken
### How to reproduce this bug:
Here is a link:
https://codepen.io/skotlinski1/pen/LQYOpN

### What should happen:
On large every cells should be 100% width (large-12) except 4th scenario where second cell on medium should be '3 units' long

### What happened instead:
Big mess instead, click on the link and see :-)

### Browser(s) and Device(s) tested on:
Safari 11.01, Chrome 63, Firefox 57, Opera 50

### Foundation Version(s) you are using:
6.4.3 and 6.4.4-rc1

### Test case link:
https://codepen.io/skotlinski1/pen/LQYOpN

### PR DESCRIPTION
**Pull request by ncoden**
Changes:
* add missing flex reset in XY Grid responsive cell widths
* add visual test for XY Grid reponsive widths

Closes #10891

### CODE REVIEW

**Comment by ncoden** [comment]
@DanielRuf @JeremyEnglert @brettsmason Could one of you review this ?

**Review by DanielRuf — APPROVED** [review]
LGTM, fixes the codepen examples.

**Comment by ncoden** [comment]
Thanks @DanielRuf.

With changes like that (adding a mixin somewhere), you can also check the diff in the generated CSS, to ensure that:
1. this does not add too much CSS.
2. this is the most efficient way to solve the problem.
3. this does not introduce specificity issues.

**Comment by DanielRuf** [comment]
But still wondering why `shrink` is needed here in the mixin. 🤔

**Comment by ncoden** [comment]
See: [scss/xy-grid/_cell.scss:58](https://github.com/ncoden/foundation-sites/blob/16e18da98942a7490d80603723245f93aea7ef9e/scss/xy-grid/_cell.scss#L58-L59)

This is the flex behavior we expect to get static width: do not grow, do not shrink, takes the width applied to it. Like at [scss/xy-grid/_cell.scss:51](https://github.com/ncoden/foundation-sites/blob/16e18da98942a7490d80603723245f93aea7ef9e/scss/xy-grid/_cell.scss#L51)

**Comment by DanielRuf** [comment]
A bit confusing at first with the `shrink` option but now I fully understand.

**Pull request merged**
