### PR TITLE
Added clipboard.js, removed ZeroClipboard

### PR DESCRIPTION
**Pull request by colin-marshall**
Fixed for merge to master instead of develop.

### CODE REVIEW

**Comment by gakimball** [comment]
Awesome, thanks :)

**Comment by colin-marshall** [comment]
No problem! Don't forget to merge master into develop to get this in the develop branch too.

**Comment by gakimball** [comment]
Yep, already done :) As part of our deploy process we always merge `master` into `develop` before tagging a release as well.

Thanks again for putting it together!

**Comment by zenorocha** [comment]
Awesome! Was it deployed already?

**Comment by gakimball** [comment]
Had some issues with our deploy process today, but it'll definitely get in tomorrow.

**Pull request merged**
