### PR TITLE
fix arrows direction and spacing in dropdown menus, fixes: #7037

### PR DESCRIPTION
**Pull request by imranomari**

### CODE REVIEW

**Comment by gakimball** [comment]
Just one comment on this. Instead of using `nth()` to find a padding value, you can use Foundation's `get-side()` function to pull out a more precise value.

```scss
// Second parameter is top, right, bottom, or left
get-side($menu-item-padding, top);
```

**Comment by zurbrandon** [comment]
Hey @imranomari we want to pull this in, but wanted to see if you can fix the issue @gakimball mentioned above.

**Comment by imranomari** [comment]
yes @zurbrandon, this commit 44c6a17 does exactly that, it's included in the pull request, sorry I didn't mention it when I pushed it.

**Comment by gakimball** [comment]
@imranomari Nice, thank you :) Because generic padding settings like that could have 1–4 values, `get-side()` allows us to account for anything and always get the same number.

**Pull request merged**
