### PR TITLE
chore: use test dependencies from node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

Currently the browser based Mocha testsuite does not directly use the dependencies (mocha, chai, sinon) from node_modules and uses manually copied versions which are outdated.

## Motivation and Context

This is needed to use the latest dependencies in browser and terminal context.

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `support/*`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
PS: The latest code throws
> npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

**Review by ncoden — APPROVED** [review]
👍 LGTM.

The `avg-keywords` issue is probably caused by `eslint` dependencies. See https://github.com/eslint/eslint/pull/10022. This should be resolved with eslint `v4.19.1`

Waiting for https://github.com/zurb/foundation-sites/issues/11074 to be resolved to merge, tests must pass.

**Comment by DanielRuf** [comment]
Don't we already use 4.19.1?

**Comment by ncoden** [comment]
Yes and I do not have this warning anymore when installing node modules, with both npm v5.2 ([logs](https://gist.github.com/ncoden/612b485508e91008f8d3ba14faa03944)) and npm v6.0 ([logs](https://gist.github.com/ncoden/4a75fde1f97ddfcce9b0ff2cdb3255e1)).

**Comment by DanielRuf** [comment]
Rebased the branch.

But still some failing tests (and new failing tests?) eg https://travis-ci.org/zurb/foundation-sites/jobs/372712412#L1175

**Comment by ncoden** [comment]
> Rebased the branch.

Please don't rebase in an open pull request, this break the history between commits and comments/reviews. Merge instead.

**Comment by ncoden** [comment]
> But still some failing tests 

Yes, but nothing new. See https://travis-ci.org/zurb/foundation-sites/jobs/372198260#L3680

**Pull request merged**
