### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by kball**
## Description
Updates a set of dependencies that were flagged by npm audit, as well as dependencies preventing builds/CI from working in node 12.

Removes an old (I think unused) gulp command that did stats on our generated CSS, as the dependency used was super old and causing problems. I did not see alternatives to the package, but since it was only used in 1 gulp task that I don't think has been used/touched in years I just removed.

If we think that gulp task is important I can look at forking/updating the package.

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by kball** [comment]
Sigh this now fails because some of the dependencies no longer support node 6. Given Node 6 is no longer a supported/maintained release (EOL was May 2019) how do we feel about ditching it?

**Comment by DanielRuf** [comment]
> Given Node 6 is no longer a supported/maintained release (EOL was May 2019) how do we feel about ditching it?

We can drop support for NodeJS 6.

Supporting 8, 10 and 12 is ok.

**Comment by DanielRuf** [comment]
But we should mention this in the changelog then.

Also do not forget to update `engines` in package.json and also the npm shrinkwrap and lock-file.

**Comment by kball** [comment]
@DanielRuf I've been out of the loop for a long time; do we have a way we're recording changelog relevant notes? A tag on the PR, or a doc/file somewhere I'm not seeing?

**Comment by SassNinja** [comment]
I've added milestone as I'm pretty sure it's helpful to see what's in the release

**Review by SassNinja — APPROVED** [review]

**Comment by DanielRuf** [comment]
@kball we have the commit lint rules (chore, fix, refactor, docs, ...: title)

**Pull request merged**
