### PR TITLE
docs: simplify & improve tooltip docs

### PR DESCRIPTION
**Pull request by ncoden**
Changes:
* remove useless attributes in Tooltip docs (they are added automatically)
* simplify and improve Tooltip examples: use shorter paragraphs & repositions tooltips

See #11054

### CODE REVIEW

**Comment by DanielRuf** [comment]
Which HEAD revision did you use for creating the branch? I guess this is still an old one without the new Chrome headless solution ;-)

**Comment by ncoden** [comment]
I thought I was up-to-date, but no :/

**Comment by ncoden** [comment]
Ah no sorry. This is `master`.

**Comment by DanielRuf** [comment]
> Ah no sorry. This is master. So tests are still broke on it.

A hright, sorry. Totally forgot that it is just in `develop` so far and we did not cherrypick the change from `develop` into `master`. My bad.

**Comment by DanielRuf** [comment]
> Ah right, sorry. Totally forgot that it is just in develop so far and we did not cherrypick the change from develop into master. My bad.

Should we wait until the final merge or cherrypick them before to have a working testsuite on both main branches?

**Comment by ncoden** [comment]
I guess we can cherry-pick. You can open a PR if you want.

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
