### PR TITLE
Include package.json in dist/assets

### PR DESCRIPTION
**Pull request by mattdsteele**
Module distribution was already discussed a little in #4710, but I'd like to kick-start one portion of it: make Foundation installable via npm. (My use case: I'm attempting to wean myself off Bower and install all dependencies via npm)

[npm allows Git repositories to be used as endpoints](https://docs.npmjs.com/files/package.json#github-urls), but the repo requires a valid `package.json`. This commit simply copies the existing `package.json` file into `dist/assets`.

You could publish specifically to npm but it's not strictly necessary (perhaps wait until F6?). For now, one could install Foundation as an npm dependency with this configuration:

```
"dependencies": {
  "foundation": "zurb/bower-foundation"
}
```

### CODE REVIEW

**Comment by gakimball** [comment]
I think we're going to get this in for our next deploy, which should be this week. We can start publishing to npm, but the directory structure will change with version 6.

**Comment by gakimball** [comment]
Also went ahead and changed the package name to `foundation-sites`, since somebody is using the `foundation` name on npm, but we need to push the new naming conventions for the frameworks. We'll do the same for Bower with version 6. 2a71b1c2f403d2cfb3a0d62168a79a5733b7a7d9

**Comment by mattdsteele** [comment]
Thanks! :+1:

**Comment by gakimball** [comment]
It's live now with version 5.2.2.

```bash
npm install foundation-sites
```

**Pull request merged**
