### PR TITLE
feat: add `dynamicHeight` option on Sticky to control container height changes #10846

### PR DESCRIPTION
**Pull request by ncoden**
Add option `dynamicHeight` on Sticky:
* **dynamicHeight** {boolean} [true] - If true (by default), keep the sticky container the same height as the element. Otherwise, the container height is set once and does not change.`

Closes https://github.com/zurb/foundation-sites/issues/10846

### CODE REVIEW

**Comment by ncoden** [comment]
Poke @colin-marshall ;)

**Comment by colin-marshall** [comment]
@ncoden yes I have been planning to revisit sticky. It really could use way more comments throughout.

**Comment by colin-marshall** [comment]
@ncoden I made a visual test and I'm still seeing the issue. Maybe I did something wrong though?

**Comment by ncoden** [comment]
@colin-marshall `dynamicHeight` is `true` by default. To resolve the issue, it must be set to `false`.

Also, there's commits in this branch that shouldn't be there. I'll open an other PR.

**Comment by ncoden** [comment]
Closing this in favor of https://github.com/zurb/foundation-sites/pull/10889 with a clean git history.

**Pull request closed without merging**
