### PR TITLE
Fix assignment to undeclared variable

### PR DESCRIPTION
**Pull request by bsa01**
Before submitting a pull request, make sure it's targeting the right branch:
- For documentation fixes, use `master`.
- For bug fixes, use `develop`.
- For new features, use the branch for the next minor version, which will be formatted `v6.x`.

If you're fixing a JavaScript issue, it would help to create a new test case under the folder `test/visual/` that recreates the issue and show's that it's been fixed. Run `npm test` to compile the testing folder.

Happy coding! :)

Fix ReferenceError: assignment to undeclared variable in strict mode

### CODE REVIEW

**Comment by Owlbertz** [comment]
Hi @bsa01,
thanks for that PR. If possible, please reference the issue you've fixed in the PR comment so that it becomes clear in the issue that there is already a PR, e.g. "This fixes #9004.".

**Comment by bsa01** [comment]
Sorry di not notiert that there is an open issue for. Should have used search function I guess. Sorry.

**Comment by jasonraimondi** [comment]
It would be great if we could get one (I have an existing PR at #8948) of these merged in. Every time I 'npm install' I need to manually go into the files and update it or else my sliders are broken.

**Comment by Owlbertz** [comment]
We are in discussion internally. The problem for me is that your PR changes the files in dist, which should not be the case for PRs. I think you can expect an answer tomorrow.

**Comment by rafibomb** [comment]
I agree - should be `src` then we can merge it

**Comment by rafibomb** [comment]
Also @jasonraimondi Does this PR cover the one you're submitting here? https://github.com/zurb/foundation-sites/pull/8948

**Comment by jasonraimondi** [comment]
@rafibomb Yep that should fix it. Will the change ultimately get built into the `dist/` folder?

**Comment by Owlbertz** [comment]
Yes, the changes will be included in the dist files once the team builds the next release (v6.2.4 in this case).

**Comment by Owlbertz** [comment]
@rafibomb Any specific reason you tagged this with 6.3 and not 6.2.4? Seems like a simple bug fix to me and thus should go into the 6.2.4 release. Moreover this is targeted to `develop` which would mean it's going to be in 6.2.4.

**Comment by kball** [comment]
Fixed in #8948

**Pull request closed without merging**
