### PR TITLE
Update tabs.md to fix link code.

### PR DESCRIPTION
**Pull request by jessgusclark**
Remove `/tabs/` from the link to Tab 2. Code as is throws JavaScript error, removing this fixes the tabs.

### CODE REVIEW

**Review by IamManchanda — APPROVED** [review]

**Comment by IamManchanda** [comment]
cc @kball for merge!

**Comment by jeromelebleu** [comment]
Hi @jessgusclark , which JavaScript error is thrown please? With that change, `data-tabs-target` and `href` are now the same. It was set to something else to illustrate the use of the `data-tabs-target`attribute, and I'm wondering if this documentation part is still obvious now... Is a simple `href="#"` could be used instead?

**Comment by jessgusclark** [comment]
@jeromelebleu it wasn't a javascript change it was an HTML change in the <li>. No JS error was thrown, there was no functionality executed. I would guess that `href="#"` wouldn't work since `#/tabs/panel2` didn't work. It would be something to test though.

**Comment by jeromelebleu** [comment]
The `data-tabs-target` attribute has precedence over the `href` one to identify the target, so it should work in both cases...

**Pull request merged**
