### PR TITLE
Added text input types function

### PR DESCRIPTION
**Pull request by ghost**
As per the request https://github.com/zurb/foundation/issues/5712

Accepts a custom selector, which defaults to 'input'. Can also accept a list of types if having all types is overkill.

Example:

``` scss
#{text-inputs( email url textarea, '.form-control')} {
    border-color: $oil;
    &:focus {
      border-color: $primary-color;
    }
}
```

### CODE REVIEW

**Comment by Grawl** [comment]
When `$all-text-input-types` is defined inside this function, I cannot get it for my own use or redefining it. I suggest to make it global and `!default`. PR maybe?

**Comment by gakimball** [comment]
@Grawl Why do you need to redefine it? Is something missing?

**Comment by Grawl** [comment]
@gakimball for a reason. I may want to add my custom-typed controls here. Or a class.

Now I just want to use these classes in my own code to do something different that Foundation do not have to do. But I have to copy them to my code.

**Comment by gakimball** [comment]
There's a finite number of valid values for `<input type>`, so `$all-text-input-types` is only going to contain those values.

If you're interested in targeting a class instead of `input[type=""]` to apply form styles, you can use the form mixins, like so:

```scss
.text-input {
  @include form-element;
}
```

Either way, Foundation 5 is at end-of-life, so we're no longer adding new features, just fixing bugs.

**Pull request merged**
