### PR TITLE
Abide that works. I hope.

### PR DESCRIPTION
**Pull request by zurbchris**
@viniciusban @designerno1 @briantan888 @milose @jamilservicos 
Would you folks take a look, see what you like/don't like. Submit any proposed changes directly to the `abide` branch. This will be merged in before the 6.1 release.

### CODE REVIEW

**Comment by designerno1** [comment]
i take a look later that day, and run it through my testcase

**Comment by viniciusban** [comment]
I'll test later, today.

**Comment by semikolon** [comment]
I'm going to try this today or tomorrow.

**Comment by designerno1** [comment]
the type of an input like email isn't checked against the options.patterns

**Comment by designerno1** [comment]
radio buttons does not work for me see
```html
<fieldset class="large-6 columns">
      <legend>Choose Your Favorite</legend>
      <input type="radio" name="pockets" value="Red" id="pocketsRed"><label for="pocketsRed">Red</label>
      <input type="radio" name="pockets" value="Blue" id="pocketsBlue"><label for="pocketsBlue">Blue</label>
      <input type="radio" name="pockets" value="Yellow" id="pocketsYellow"><label for="pocketsYellow">Yellow</label>
    </fieldset>
```

**Comment by zurbchris** [comment]
@designerno1 I commented elsewhere (#7196) on the radio buttons. 
For the type checking, oversight, simple fix.

**Comment by designerno1** [comment]
ok and question before?

**Comment by jamilservicos** [comment]
input email:
<input type="text" pattern="email" placeholder="Email" id="Email"
aria-describedby="Email" required>

Att.

Gervásio Júnior, (Jamil).

2015-12-17 18:25 GMT-03:00 designerno1 <notifications@github.com>:

**Comment by semikolon** [comment]
I ported this branch to a fork of the foundation-rails gem. Available here for testing: https://github.com/semikolon/foundation-rails

**Comment by designerno1** [comment]
pattern on textarea does not work?

**Comment by designerno1** [comment]
for me radio does not work or whats the markup?

**Comment by zurbchris** [comment]
The same as it was?

**Comment by designerno1** [comment]
ok it doesn't work ;-)

**Comment by zurbchris** [comment]
A little more specific please?

**Comment by briantan888** [comment]
Created pr #7628 

Required attribute for input radio does not make much sense. Proposed .radio-group wrapper container for radio require check. Function validateRadio is no longer needed.

    <label for="pokemonRadio">Pick one pokemon</label>
    <div id="pokemonRadio" class="radio-group" required>
      <input type="radio" name="pokemon" value="red">Red
      <input type="radio" name="pokemon" value="blue">Blue
      <input type="radio" name="pokemon" value="yellow">Yellow
    </div>
    <div class="form-error">Please pick one pokemon</div>

Similarly for checkbox, (though retain required check for individual checkbox input, probably not much use too ).
  
    <label for="pokemonCheckbox">Pick at least one pokemon</label>
    <div id="pokemonCheckbox" class="checkbox-group" required>
      <input type="checkbox" name="pokemon" value="red">Red
      <input type="checkbox" name="pokemon" value="blue">Blue
      <input type="checkbox" name="pokemon" value="yellow">Yellow
    </div>
    <div class="form-error">Please select at lease one pokemon</div>

**Comment by briantan888** [comment]
unable to bind 'valid.zf.abide' and 'invalid.zf.abide' for form. Is this the right way? only submit is triggered

    $("#myform").on('submit', function() {
      console.log("submit triggered");
      return false;
    });
    $("#myform").on('invalid.zf.abide', function() {
      console.log("invalid.zf.abide triggered");
    });
    $("#myform").on('valid.zf.abide', function() {
      console.log("valid.zf.abide triggered");
      // ajax post.
    });

**Comment by zurbchris** [comment]
Add form in there for full form events `on('formvalid.zf.abide', …`

**Comment by designerno1** [comment]
But we can check radio group without .radio-group with the given name attribute?

**Comment by briantan888** [comment]
But where do you specify the required attribute?

**Comment by briantan888** [comment]
on('formvalid.zf.abide',...) does not work either. I see from the js code that 'valid.zf.abide' is emitted (line 321)

**Comment by designerno1** [comment]
The required attribute could be specified in one radio button. I think there is no way in radios with same name to be 2 checked at same time. So  we can specify it in one radio of the group or in all

**Comment by briantan888** [comment]
Tried it. Didn't work. If I put "required" on one of the option, then "that" option must be checked. If I put required on all options, then validation will not get through. That is why I said "required" on radio input does not make sense.

          <label for="which_one_should_I_link_to">Monster Radio</label>
          <input id="monster1" name="monster" type="radio" value="red" required>
                <label for="monster1">Red</label>
          <div class="form-error">Must choose an option</div>
          <input id="monster2" name="monster" type="radio" value="blue" >
              <label for="monster2">Blue</label>
          <div class="form-error">Must choose an option</div>
          <input id="monster3" name="monster" type="radio" value="yellow" >
              <label for="monster3">Yellow</label>
          <div class="form-error">Must choose an option</div>

**Comment by designerno1** [comment]
i give it a try tomorrow using a different checkRequired and Validation function for Radio groups.
My plan is to check if a radio enters the function the whole group for a required attribute, and if required for a check.
maybe caching the groups on init i think because if we got a radio group with 10 input radios and the submit button is clicked the form validates all inputs and so the script has to run 10x10 times through the radio group required and checked function.
because of that i think of caching the groups on init in a array
thoughts?

**Comment by milose** [comment]
Using require on a single check-box makes sense i.e.: I agree.
But for individual radios - not at all.

**Comment by mediabeastnz** [comment]
Hi, i'm using 6.0.5 for a project and obviously there is this Abide issue. Is there a quick patch or download somewhere?

**Comment by briantan888** [comment]
@designerno1 validateInput for radio/checkbox are still needed for field-level validation, but validateForm can skip radio and checkbox elements, but loop radio-group and checkbox-group classes, but unnecessarily complicate the codes. IMO, why use 10 radio inputs when select-single is probably more effective and takes up less real-estate. :)

**Comment by zurbchris** [comment]
Ok, sorry for leaving you guys to the discussion without me. I've reverted the work on radio groups to what it was last week, because the pr's I had were not doing what we wanted them to do. However, the pattern matching is good and we'll keep that in there. As for the direction of the radio/checkbox issue, here's what a group should do:

 Check the overall group for a required attribute. If the group is named (and it should be), the parent of the named group would contain the required attribute. This should be a fieldset, but we shouldn't limit it to that. If the group is required, obviously only one of them *must* be checked, so on validation, make sure at least 1 input is :checked (could be more for a checkbox group). 
However, if a developer wants to require a *specific* radio/checkbox/whatever, placing the required attribute on that element would force it to ensure that it is in fact, :checked. 

I realize that for radios, more than one required statement would break the form, and that's ok, we're not quality control for other peoples markup.

I won't be able to get to this before ZURB goes on winter break, but it will be on my list of things for the new year. If someone can implement this feature over the break, I would love to see it and get it pulled in the next patch version. That being the case, I'll file an issue about this shortly. Thanks everyone for the input, feedback, and pull requests. Please, keep them coming.

**Comment by designerno1** [comment]
ok regrettable that it was only nearly what you are looking for

**Comment by briantan888** [comment]
The required attribute for checkbox grouping may be a problem when the checkboxes are embedded in switches. The proposed checkbox-group class eliminates that ambiguity. It also make group error highlighting straight forward.

**Comment by simar88** [comment]
Hi everyone, I'm using 6.1 and i'm unable to get  "formvalid.zf.abide" and "forminvalid.zf.abide" event.
Any fix at the moment?
Thanks in advance..

**Comment by briantan888** [comment]
I submitted a pr #7674 . You can apply this patch on validateForm to your foundation.js

**Comment by simar88** [comment]
Hi @briantan888 i've found that these two event are triggered only if is present the code:
<div data-abide-error class="alert callout" style="display: none;">
    <p><i class="fi-alert"></i> There are some errors in your form.</p>
  </div>

**Comment by briantan888** [comment]
Bug. Fixed in next release.

**Comment by eliotc1986** [comment]
What's the status of this radio button/radio button group abide issue? 
Using 6.1.1 and still can only validate a single radio button (multiple radio buttons with 'required' fail validation/ applying "required" to fieldset doesn't validate)

**Pull request merged**
