### PR TITLE
Add button expanded class for each breakpoint

### LINKED ISSUE #7570: [Button Proposal] add support for small-expanded...
it would be nice to have classes for expanded on small medium large etc

### PR DESCRIPTION
**Pull request by andycochran**
Closes #7570.

### CODE REVIEW

**Comment by gakimball** [comment]
Similar to [my comment here](https://github.com/zurb/foundation-sites/pull/7566#issuecomment-173040940), we aren't interested in having responsive versions of these button group features.

**Comment by DaSchTour** [comment]
Came across this while fighting with responsive buttons. Now I'll override `button-expand` mixin to prevent expanded buttons from my mobile template to create gigantic buttons on desktop. Why exactly this feature was rejected? I've seen this as a common pattern to have full width buttons for mobile and "normal" buttons for desktop.

**Comment by andycochran** [comment]
If it's to prevent bloat, perhaps the way forward (v7?) with features like this is settings vars to enable them? 

```scss
$responsive-expanded-button: true;
```
Maybe this could be resolved in the "Full menu rework" ticket #9421.

**Comment by DaSchTour** [comment]
I would like to just have the buttons there. I guess a lot of other features were added without such a configuration that add a lot of more "bloat". So maybe we could reconsider just this PR?

**Comment by IamManchanda** [comment]
I think this really makes sense specially as andy mentioned with 

```scss
$responsive-expanded-button: true; // maybe `false` by default
```

Reopening this and cc / @kball

**Comment by IamManchanda** [comment]
Also, 
Code Brevity => `expanded-large` is enough!

**Comment by DaSchTour** [comment]
Closing in favor of #10653

**Pull request closed without merging**
