### PR TITLE
Fix #11710 prototype spacing breakpoint specificity

### LINKED ISSUE #11710: Prototype - Spacing - Specificity issue when using breakpoints
## What should happen?

`medium-margin-top-0` should override `margin-top-2` on medium screens and larger.

## What happens instead?

`medium-margin-top-0` doesn't override `margin-top-2` on medium screens and larger due to specificity issues.

Classes are defined as follows:
```
.margin-top-0 {}
@media(/* medium breakpoint condition */) {
  .medium-margin-top-0{}
}

/* ... */

.margin-top-2 {}
@media(/* medium breakpoint condition */) {
  .medium-margin-top-2{}
}
```

## Possible Solution

Make sure all levels are defined for the given breakpoints before moving on to the next one.

to be as follows:
```
.margin-top-0{}
.margin-top-1{}
.margin-top-2{}

@media(/* medium breakpoint condition */) {
  .medium-margin-top-0{}
  .medium-margin-top-1{}  
  .medium-margin-top-2{}
}
```

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://mathieuhays.github.io/foundation-spacing-specificity-issue/

How to reproduce:
1. Using a similar setup as the starter project use the following setting line: `$global-prototype-breakpoints: $breakpoints;`
2. add the following classes together `margin-top-2 medium-margin-top-0`
3. Observe on a medium screen or larger

## Context

Settings line corresponding to the prototype breakpoints is set to the following:
`$global-prototype-breakpoints: $breakpoints;`

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Firefox 65.0.1
- Device, Operating System and version:  Mac Os 10.14.3
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by mathieuhays**
## Description

Fixes the specificity mentioned in #11710. Also makes sure `!important` is used consistently for the spacing classes.

- Closes #11710

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by DanielRuf — DISMISSED** [review]
`!important` just creates issues and should be avoided.

**Comment by mathieuhays** [comment]
Hi @DanielRuf, Thanks for looking at this.

The reason I added the `!important` stuff is because you already had all the spacing classes using it except `margin-0`, `margin-1`, etc..

Which means if you were to use `margin-top-2` and `medium-margin-0`, the medium class would not work.

**Comment by DanielRuf** [comment]
Seems we have no other solution as we use `!important` for many utility classes which makes it harder to overwrite them (duplicating classes to increase the specificity would not work in this case).

**Comment by rafibomb** [comment]
The philosophy of these "Functional CSS" classes is that a class is a more explicit or conscious decision to apply CSS to an element. So if all my cards are

```
.card {
  margin-bottom: $global-margin;
}
```

Except maybe one, than I can do an explicit override with `.margin-1`

I don't love adding !important to the CSS but I may be necessary and make sense in this case.

**Review by rafibomb — APPROVED** [review]

**Comment by mathieuhays** [comment]
Hi @IamManchanda, is there any chance you could review this PR? Thanks :-)

**Comment by rafibomb** [comment]
@mathieuhays Thanks for the PR!

**Pull request merged**
