### PR TITLE
issue #7265 - enable grid-column mixin to parse list/fraction (n of m)

### PR DESCRIPTION
**Pull request by TvrtkoM**
PR fixes issue #7265

### CODE REVIEW

**Comment by gakimball** [comment]
Can you verify that the tests for this function continue to pass? Run `npm start test:sass`.

**Comment by TvrtkoM** [comment]
Hi, I'm not sure now if I want this change in mixin. We already have a function grid-column (which is tested) and it can be used in some cases on width css property.

I've ran the tests with gulp test and got 3 unrelated fails

    Breakpoint converts a named breakpoint to an em value {
      ✗: Expected "(min-width: 40em)" to be "(min-width: 32em)";
      Test: Failed; }

    Breakpoint creates an only range out of a named breakpoint {
      ✗: Expected "(min-width: 40em) and (max-width: 63.9375em)" to be "(min-width: 32em) and (max-width: 63.9375em)";
      Test: Failed; }

    Text inputs creates a selector out of a list of text input types {
      ✗: Expected "[type='text'], [type='password']" to be ["[type=", "text", "], [type=", "password", "]"];
      Test: Failed; }

Note docs need to be fixed for grid-column mixin if this feature is not needed

**Comment by gakimball** [comment]
Yeah, I think there's another way to fix this. I'll write another comment in #7265.

**Comment by gakimball** [comment]
The fix ended up being a lot simpler—just remove the `$columns <= $grid-column-count` check. It doesn't affect the CSS output at all.

**Pull request closed without merging**
