### PR TITLE
Add browserstack api access

### PR DESCRIPTION
**Pull request by kball**
Adds browserstack username and key

### CODE REVIEW

**Review by IamManchanda — APPROVED** [review]

**Review by Deckluhm — COMMENTED** [review]
Mistake?

**Comment by kball** [comment]
Not a mistake - this is actually an open source account we got. @rafibomb set it up first which is why the accountname is that way, but it's registered under the foundation@zurb.com email address

**Comment by Deckluhm** [comment]
Oh ok, that's great!

Just wanted to be sure that wasn't a mistake (since API keys and more generally credentials are pretty sensitive info).

**Comment by kball** [comment]
Appreciate the check

**Comment by IamManchanda** [comment]
@kball so who all can do testing thanks to this?

**Pull request merged**
