### PR TITLE
Fix multiple sliders

### PR DESCRIPTION
**Pull request by coorasse**
Fix issue when multiple sliders are on the same page

### CODE REVIEW

**Comment by rafibomb** [comment]
Thanks for this. What issue is this fixing?

**Comment by zurbchris** [comment]
Also, it looks like you're removing the name spacing on the `change` event when you reassign it.

**Comment by coorasse** [comment]
You can see the issue in the demo page of foundation:

**Comment by coorasse** [comment]
I don't get the comment about name spacing, sorry.

**Comment by zurbchris** [comment]
Good fix, thanks!

**Comment by jlukic** [comment]
:+1:

**Pull request merged**
