### PR TITLE
fix: orbit component's transition end conflict issue

### PR DESCRIPTION
**Pull request by yanwsh**
orbit component's transition end should not be affected by its children's transition end.

## Description

For obit component, adding transition animation to each slide's child element. When user click child element and then click next slide, current slide will disappear and only show next slide. You can reproduce this issue [here](https://codepen.io/yanwsh/pen/gqWqeW). Click "slider 1" and then click "next arrow" button, you will see "slider 1" disappear and only have "slider 2" animation.

This is because there is a conflict between child's transition end and parent's transition end. Orbit slider only listen to `transitionend` event and can't figure out which event coming from. Add `stopPropagation` to prevent children's `transitionend` event propagate to parent.

You can verify the fix [here](https://codepen.io/yanwsh/pen/rPmbLw)

Let me know if you have any questions.  :blush:

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [x] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi, thanks for reporting this.

(Also I guess transitioning all properties is not what should happen.)

Can you provide a PR to show the exact changes?

**Comment by DanielRuf** [comment]
I see no slider in the codepen with the fix, can you check this?

**Comment by yanwsh** [comment]
Here is the issue.

When child contains transition (transition all or whatever) and you click on the slider, it will focus on the child element. Then, when you click "next slide", child will lose its focus and use transition to go back to original state. Then it will conflict with parent transition end event. 

Can you reproduce the issue with my [first link](https://codepen.io/yanwsh/pen/gqWqeW)? 

I think the fix link need take a while base on the network speed since it's not use CDN.

**Comment by yanwsh** [comment]
Let me know if you can't reproduce this issue. I will upload a video to clarify this issue.

**Comment by DanielRuf** [comment]
> adding transition animation to each slide's child element

This sounds like a custom requirement and use case.

A video would be probably help. Also please rebase the branch on our `develop` branch.

**Pull request closed without merging**
