### PR TITLE
Fixes button groups radius #8447

### PR DESCRIPTION
**Pull request by imabdulsal**
@rafibomb 
This PR fixes the issue #8447, and replaces the PR #8448, however it contains additional code that fixes the unstacked scenario.

### CODE REVIEW

**Comment by kball** [comment]
@andycochran @brettsmason @ncoden thoughts on this?

**Review by ncoden — APPROVED** [review]
:+1: Nothing to say

**Comment by andycochran** [comment]
Still not convinced this is the right move. All my thoughts are in #8447. But I'm not saying this should be rolled back. I think it solves an issue for everyone that wants rounded corners on the whole button group. Just remember, that's a design decision which makes assumptions. If I want a set of buttons, each with its corners rounded, I'll just have to override this with app-specific styles.

**Comment by DaSchTour** [comment]
I totaly agreey with @andycochran 
At the moment I use button groups with border-radius on every button.
So you can bet after I'll get the bug report from my project you'll see my PR changing this again 😆

**Comment by kball** [comment]
Its in 6.3, so we still have time to adjust... @DaSchTour and @andycochran do you want to take another pass on this?  Can we get something that straightforwardly supports both usecases?

**Comment by andycochran** [comment]
Could be as simple as: 
```sass
$buttongroup-radius-on-group: true !default;
```

**Comment by andycochran** [comment]
@kball On it. 😉

**Pull request merged**
