### PR TITLE
[Docs Update 2017] Navigation Section - Codepen's

### PR DESCRIPTION
**Pull request by IamManchanda**
Here are the codepen's for review!

**1. Menu**

- [x] Basic Menu - https://codepen.io/IamManchanda/pen/rmvXMX?editors=1000
- [x] Align Right - https://codepen.io/IamManchanda/pen/zwjgWv?editors=1000
- [x] Align center (flex only) - https://codepen.io/IamManchanda/pen/bWMXKQ?editors=1100
- [x] Menu Centered - https://codepen.io/IamManchanda/pen/BRxXxO?editors=1100
- [x] Menu Expanded - https://codepen.io/IamManchanda/pen/bWMXQO?editors=1100
- [x] Vertical Menu - https://codepen.io/IamManchanda/pen/YVLmBY?editors=1000
- [x] Simple Style - https://codepen.io/IamManchanda/pen/ZKogNb?editors=1000
- [x] Nested Style - https://codepen.io/IamManchanda/pen/vmrBOr?editors=1000
- [x] Active State - https://codepen.io/IamManchanda/pen/XRYrKp?editors=1000
- [x] Text - https://codepen.io/IamManchanda/pen/GmGRWp?editors=1000
- [x] Icons - https://codepen.io/IamManchanda/pen/OmEJQW?editors=1000
- [x] Icon Top - https://codepen.io/IamManchanda/pen/vmrYjN?editors=1000

**2. Dropdown Menu**

- [x] Horizontal - https://codepen.io/IamManchanda/pen/XRYWPO?editors=1000
- [x] Vertical - https://codepen.io/IamManchanda/pen/LyrYaE?editors=1000

**3. Drilldown Menu**

- [x] Basic Drilldown Menu - https://codepen.io/IamManchanda/pen/JNZodd?editors=1000
- [x] autoHeight - https://codepen.io/IamManchanda/pen/mmKyrw?editors=1000
- [x] ScrollTop Drilldown - https://codepen.io/IamManchanda/pen/jmKEwX?editors=1000  

**4. Accordion Menu**

- [x] Basic Accordion Menu - https://codepen.io/IamManchanda/pen/qmKEQr?editors=1000

**5. Top Bar**

- [x] Basic Top Bar https://codepen.io/IamManchanda/pen/eWrwKP?editors=1000
- [x] Advanced Layout with Responsive Toggler https://codepen.io/IamManchanda/pen/LymroM?editors=1100
- [x] Stacking - https://codepen.io/IamManchanda/pen/XRYbZa?editors=1000

**6. Responsive Navigation**

- [x] Responsive Menu - https://codepen.io/IamManchanda/pen/qmYKgJ?editors=1000
- [x] Responsive Menu (Drilldown Dropdown combo) - https://codepen.io/IamManchanda/pen/jmKPdM?editors=1100
- [x] Responsive Toggle - https://codepen.io/IamManchanda/pen/LymroM?editors=1100
- [x] Responsive Toggle with animation - https://codepen.io/IamManchanda/pen/KmepBg?editors=1100

**7. Magellan**

- [x] Basic Magellan - https://codepen.io/IamManchanda/pen/MmGEXo?editors=1100
- [x] Magellan with Sticky Navigation - https://codepen.io/ZURBFoundation/pen/gWKLqV?editors=1100

**8. Pagination**

- [x] Basic Pagination - https://codepen.io/IamManchanda/pen/BRxVmB?editors=1000
- [x] Centered Pagination - https://codepen.io/IamManchanda/pen/dWKYZb?editors=1000

**9. Breadcrumbs**

- [x] Basic Breadcrumb  - https://codepen.io/IamManchanda/pen/MmGeMx?editors=1000

### CODE REVIEW

**Comment by IamManchanda** [comment]
@kball There is a overview page too http://foundation.zurb.com/sites/docs/navigation.html.... 
What need to be done there .... All those examples covered here are in specific pages too ?
Do i need to add there too ??

BTW ... I dont understand why there is a specific overview page for navigation when we have kitchen sink ?

**Comment by IamManchanda** [comment]
@kball With https://github.com/zurb/foundation-docs/issues/12
and this [Codepen](https://codepen.io/ZURBFoundation/pen/gWKLqV?editors=1100) with example getting added why remove this below attached example entirely ..... We shouldn't have 3 sticky headers (top bar, search bar being other two !
screenshot from 2017-05-15 20-33-41

**Comment by kball** [comment]
Concur with your idea @IamManchanda. Extraneous example, and we already have many stickies in this new layout.

**Comment by IamManchanda** [comment]
Ohk removing it!

**Pull request merged**
