### PR TITLE
Fixed the dropdown pane's alignment in RTL mode #7560

### PR DESCRIPTION
**Pull request by imabdulsal**
This PR fixes the top and bottom dropdown pane's alignment in RTL mode #7560

### CODE REVIEW

**Comment by abdullahsalem** [comment]
@gakimball It's been long time since I sent this PR, there was no conflict but now there is..

**Comment by kball** [comment]
@abdullahsalem I'll worry about dealing with the conflict and hopefully get this in soon.  I need to get some test cases together for RTL to make sure we don't have any regressions or other issues (and to help us moving forward), and then I'll get this merged.  Thanks for putting this together.

**Comment by gakimball** [comment]
@kball To help us test RTL, I added a third CSS file, `foundation-rtl.css`, to the available assets. So you can load that the same way we're loading the flexbox-specific CSS in our visual tests. ba19d189c60f818971ea40f94d0e5495239e52c2

**Comment by kball** [comment]
OK, I pulled this fix over, built a test, verified this works and fixes the dropdown issues.  Going to close this PR as it was easier to do in a new branch than resolve the conflicts, but the change is in 6.2-stable.

**Comment by abdullahsalem** [comment]
Thanks @kball and @gakimball 
I've just noticed your replies.

**Comment by abdullahsalem** [comment]
@gakimball @kball I would appreciate it if you take a look at my comment [here](https://github.com/zurb/foundation-sites/commit/dec7a581bc6b879a7afc8ec3ae9752ba32b1358a). I haven't tested the new commits yet, but I believe that piece of code should be removed.

**Pull request closed without merging**
