### PR TITLE
fix width body after open reveal

### PR DESCRIPTION
**Pull request by Andrey9300**
The width of the body is changed when opening/closing the reveal.

### CODE REVIEW

**Comment by Owlbertz** [comment]
@Andrey9300 what about those travis test commits?

**Comment by Andrey9300** [comment]
@Owlbertz  I'm sorry, this is my first request, so I could not get from the travis test. I began to test on your own repository and not removed do not need commits.

**Comment by Owlbertz** [comment]
The Travis CI test sometimes fails because it cannot download all resources via NPM/Bower/..., you should be able to manually re-start the test by following the "Details" link next to the failed build.

However, could you please describe what your PR does and why you made it in a more detailed way?

**Comment by Andrey9300** [comment]
When we open the pop-up, for example directly on the website documentation http://foundation.zurb.com/sites/docs/reveal.html, the width of the <body> and changing the background like jumps at 17px. For clarity, we made pictures.
https://goo.gl/photos/rxGT4eRjuEXULax58

**Comment by Owlbertz** [comment]
This behavior is intended, because otherwise you could scroll the page under the Reval backdrop while the modal is opened.

**Comment by Andrey9300** [comment]
Okay, I thought it would be my first change, but not all the first time)

**Comment by Owlbertz** [comment]
Don't worry, contributing is always a good thing. Making this change in your project might be required, but the general use case is that the modal is in the focus and the scrolling should be disabled.

**Pull request closed without merging**
