### PR TITLE
@else should be placed on same line as previous curly brace

### PR DESCRIPTION
**Pull request by marcobiedermann**
http://sass-guidelin.es/#conditional-statements

### CODE REVIEW

**Comment by rafibomb** [comment]
Thanks! Standards are good - can't auto-merge this but we'll get it in soon.

**Comment by marcobiedermann** [comment]
I just got one question. What if there is a comment above the `@else` condition?
See https://github.com/zurb/foundation/blob/master/scss%2Ffoundation%2Fcomponents%2F_grid.scss#L54

**Comment by gakimball** [comment]
You could move the comment inside the block, and then you'd be able to pair all the `@else` blocks together.

**Comment by marcobiedermann** [comment]
Ok, I'll fix it soon

**Comment by gakimball** [comment]
Hey, really sorry for letting this get super stale! Now that Foundation 6 is out, we won't be making any more codebase improvements to Foundation 5. We're always looking for contributions to the new codebase, though :)

**Pull request closed without merging**
