### PR TITLE
 [RFR] Create 'disabled' state in tabs

### PR DESCRIPTION
**Pull request by thiagotomasi**
This PR add 'disabled' state in tabs compoments.
You can see more information about in issue #6089

### CODE REVIEW

**Comment by kball** [comment]
Foundation 5 is no longer accepting new features, only bugfixes.  If you'd like to reimplement this for Foundation 6 we'd happily accept a pull request.

**Comment by alexbohariuc** [comment]
Hey, would this be available in F6?

**Comment by DanielRuf** [comment]
> Foundation 5 is no longer accepting new features, only bugfixes. If you'd like to reimplement this for Foundation 6 we'd happily accept a pull request.

At least we could migrate the changes to v6 and implement them.

Do you want to provide a PR @alexbohariuc?

**Comment by alexbohariuc** [comment]
@DanielRuf - i'll do it today.

**Comment by alexbohariuc** [comment]
I’ll need a hint here, this is the first time i dig into the F6 js.

**Comment by DanielRuf** [comment]
> @DanielRuf - i'll do it today.

Awesome =)

> I’ll need a hint here, this is the first time i dig into the F6 js.

Any thing / specific question where we can help you with?

**Comment by alexbohariuc** [comment]
After looking better at the code, I'm guessing the condition would be this one:
`if ($elem.hasClass('disabled'))
            return;`
But i had no success implementing it.

**Comment by DanielRuf** [comment]
```diff
toggle_active_tab : function (tab, location_hash) {
+      if (tab.hasClass("disabled"))
+         return;
```

Not sure if the old PR was actually tested if it worked. Did you add it to the toogle_active_tab function and did you run `npm start`?

**Comment by alexbohariuc** [comment]
The js structure of the tabs is changed. It didn’t work this way.

**Comment by DanielRuf** [comment]
> The js structure of the tabs is changed. It didn’t work this way.

That's why we need a new PR for the current code. If you still want to provide a PR let us know. I'll try to find some time then and help you how this has to be done in the new component.

We might better discuss it in the new PR then or a new referenced issue.

**Pull request closed without merging**
