### PR TITLE
[Button] Feature: Adds .clear button

### PR DESCRIPTION
**Pull request by rafibomb**
Adds class to make a button clear (no background or border color)

For this common use case
screen shot 2017-02-01 at 2 38 51 pm

Also fixes missing variables in _settings.scss file other PR's.

### CODE REVIEW

**Comment by soumak77** [comment]
@rafibomb any idea when this PR will be merged?

**Comment by kball** [comment]
Merged! Will be in 6.4

**Comment by andycochran** [comment]
Since this new `button-clear()` mixin all but duplicates the `button-hollow-style()` mixin, would it make sense to instead pass a `$border-color` argument to `button-hollow-style()`? Then we could just include `button-hollow-style()` in `button-clear()` passing `transparent` as the border color.

**Comment by kball** [comment]
@rafibomb @soumak77 thoughts on @andycochran's suggestion?

**Comment by soumak77** [comment]
@kball any attempt to consolidate common code is a good idea.  If you don't wish to introduce a new variable to the `button-hollow-style` mixin, you can refactor the code so that `button-clear` and `button-hollow-style` use the same internal mixin, but expose only the variables needed to customize the clear/hollow styling.

**Comment by kball** [comment]
@soumak77 Do you want to take a pass on a PR doing exactly that? :)

**Comment by soumak77** [comment]
@kball Sorry, but I do not have the time to make those changes

**Pull request merged**
