### PR TITLE
fix: kitchen page validation #9900

### LINKED ISSUE #9900: [Kitchen Sink] Page does not validate
#### How to reproduce this bug:

1. Open page in BBEdit
2. Check syntax
3. View syntax errors

#### What should happen:

You should get a dialogue box that says "no syntax errors">

#### What happened instead:

Line 368: Value “exampleHelpText” for id attribute of element “<p>” must be unique.
Line 353: ID or Name value “exampleHelpText” was previously used here.
Line 465: Value “panel1d-heading” for id attribute of element “<a>” must be unique.
Line 457: ID or Name value “panel1d-heading” was previously used here.
Line 467: Value “panel1d” for id attribute of element “<div>” must be unique.
Line 459: ID or Name value “panel1d” was previously used here.
Line 473: Value “panel1d-heading” for id attribute of element “<a>” must be unique.
Line 457: ID or Name value “panel1d-heading” was previously used here.
Line 475: Value “panel1d” for id attribute of element “<div>” must be unique.
Line 459: ID or Name value “panel1d” was previously used here.
Line 862: Element “” requires that the attribute “alt” be specified.
Line 872: Element “” requires that the attribute “alt” be specified.
Line 898: Document type doesn't permit attribute “frameborder” within element “<iframe>”.
Line 898: Document type doesn't permit attribute “allowfullscreen” within element “<iframe>”.
Line 963: Value “exampleHelpText” for id attribute of element “<p>” must be unique.
Line 353: ID or Name value “exampleHelpText” was previously used here.
Line 983: Value “pokemonRed” for id attribute of element “<input>” must be unique.
Line 401: ID or Name value “pokemonRed” was previously used here.
Line 984: Value “pokemonBlue” for id attribute of element “<input>” must be unique.
Line 402: ID or Name value “pokemonBlue” was previously used here.
Line 985: Value “pokemonYellow” for id attribute of element “<input>” must be unique.
Line 403: ID or Name value “pokemonYellow” was previously used here.
Line 989: Value “checkbox1” for id attribute of element “<input>” must be unique.
Line 413: ID or Name value “checkbox1” was previously used here.
Line 990: Value “checkbox2” for id attribute of element “<input>” must be unique.
Line 414: ID or Name value “checkbox2” was previously used here.
Line 991: Value “checkbox3” for id attribute of element “<input>” must be unique.
Line 415: ID or Name value “checkbox3” was previously used here.
Line 1057: Element “” requires that the attribute “alt” be specified.
Line 1057: Element “” requires that the attribute “src” be specified.
Line 1104: Element “” requires that the attribute “alt” be specified.
Line 1198: Document type does not permit element “<button>” in content of element “<ul>”.
Line 1199: Document type does not permit element “<button>” in content of element “<ul>”.
Line 1464: Element “” requires that the attribute “alt” be specified.
Line 1544: Document type doesn't permit attribute “width” within element “<th>”.
Line 1546: Document type doesn't permit attribute “width” within element “<th>”.
Line 1547: Document type doesn't permit attribute “width” within element “<th>”.
Line 1623: Element “” requires that the attribute “alt” be specified.
Line 1631: Element “” requires that the attribute “alt” be specified.
Line 1639: Element “” requires that the attribute “alt” be specified.
Line 1940: Value of attribute “href” for element “<a>” is invalid; URL path needs encoding (“http://zurb.com/university/foundation-intro?utm_source=Foundation%20Docs&amp;utm_medium=Docs&amp;utm_content=Footer&amp;utm_campaign=Footer%20Upsell”).
Line 1945: Value of attribute “href” for element “<a>” is invalid; URL path needs encoding (“http://zurb.com/university/foundation-intro?utm_source=Foundation%20Docs&amp;utm_medium=Docs&amp;utm_content=Footer&amp;utm_campaign=Footer%20Upsell”).
Line 1945: In HTML 5 or XHTML, it's recommended to include a space before the trailing “/>” in empty XML elements.
Line 1945: Element “” requires that the attribute “alt” be specified.

### PR DESCRIPTION
**Pull request by decabeza**
## Description

This PR fix validation errors on Kitchen Sink page.

Using BBEdit validation appeared these validation errors:

**`104 Errors | 43 Warnings`**

Right now after the changes:

**`9 Errors | 43 Warnings`**

The file that has changed is `docs/pages/kitchen-sink.md` as a markdown file, I think the Errors/Warnings are not related to this kind of file extension and don't need to be changed/fixed.

**Errors**

```
~/source/foundation-sites/docs/pages/kitchen-sink.md:1: Document must begin with a DOCTYPE to be valid; checker will assume “HTML 5”.
~/source/foundation-sites/docs/pages/kitchen-sink.md:1: Document type does not permit character data here.
~/source/foundation-sites/docs/pages/kitchen-sink.md:761: Document type does not permit element “<body>” in content of element “<body>”.
~/source/foundation-sites/docs/pages/kitchen-sink.md:9: Close tag for element “</html>” omitted but document type doesn't permit it.
~/source/foundation-sites/docs/pages/kitchen-sink.md:9: Close tag for element “</body>” omitted but document type doesn't permit it.
```

These 5 are related with HTML validation and fails becuase this is a `.md` file.

```
~/source/foundation-sites/docs/pages/kitchen-sink.md:44: Document type does not permit element “<p>” in content of element “<label>”.
~/source/foundation-sites/docs/pages/kitchen-sink.md:793: Document type does not permit element “<button>” in content of element “<ul>”.
~/source/foundation-sites/docs/pages/kitchen-sink.md:794: Document type does not permit element “<button>” in content of element “<ul>”.
```

These 3 are related with the current syntax on Foundation and are necessary for the use of the framework, so maybe it's necessary to change the code before.

Also, there is an error about use `frameborder="0" allowfullscreen` on `<iframe>` tag, but for now YouTube embed code still using it.

**Warnings**

```
~/source/foundation-sites/docs/pages/kitchen-sink.md:9: Optional open tag for element “<html>” not specified.
~/source/foundation-sites/docs/pages/kitchen-sink.md:9: Optional open tag for element “<head>” not specified.
~/source/foundation-sites/docs/pages/kitchen-sink.md:9: Optional open tag for element “<body>” not specified.
```

These 3 are related with HTML validation and fails because this is a `.md` file.

The rest of the warnings (40) are like this one:

```
Value of attribute “src” for element “<img>” may be invalid; special characters in URL paths should be entity encoded (“%7B%7Broot%7D%7Dassets/img/...
```

It's because the images on the file use the `{{ root }}` variable for src attribute. I have searched but it seems there is no way to escape `{}` symbols on md files. 🤔 

- Closes https://github.com/foundation/foundation-sites/issues/9900

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Regarding YT embed codes (iframes):

Normally this is provided by YT and recommended so iframes are allowed to use the fullscreen API. Or did YT change the embed codes too?

**Comment by DanielRuf** [comment]
Hi @decabeza,
Oh wow, this is a big PR. Awesome! =)
Many thanks for your contribution.

I will try to find some time this weekend to review and test the changes.

Regarding YT embed codes (iframes):

Normally this is provided by YT and recommended so iframes are allowed to use the fullscreen API. Or did YT change the embed codes too?

**Comment by decabeza** [comment]
Hi @DanielRuf, a pleasure contribute to Foundation ❤️ 😌 

Regarding YT embed codes (iframes), effectively they still using  `frameborder="0" allowfullscreen` on the `<iframe>` tags so I just leave it and update the comment on PR.

**Review by DanielRuf — APPROVED** [review]
LGTM

**Pull request merged**
