### PR TITLE
Adding full height responsiveness to Orbit

### PR DESCRIPTION
**Pull request by chrissmejia**
Orbit has some problems with responsiveness, this push solve some of that problems.
1. Allow you to set your slider to height 100%.
2. Automatically center your's sliders
3. Adjust to fit perfectly in every screen (mobile, tablet, pc)
4. Don't trim the content if it takes more than the screen size.
5. Allow you to define a maximum height to looks good even in huge screens.
6. Provide several customisation over how this height works (you can add different extra padding for top or bottom, add or remove size e.g if you need to remove the top menu height).

You can see it working at:
http://52.6.143.233

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1: THis will be great, because, i trying use slick-slider but don't works fine, the thinks that i cauld make with orbit i can't make now with slider, change the caption background, margin, etc., center the slick block, it's crazy, and sad :'(

**Comment by zurbchris** [comment]
Orbit is deprecated in Foundation 5, but we're bringing it back for Foundation 6. Keep checking in for updates and thanks for your contribution.

**Comment by SalahAdDin** [comment]
@zurbchris It's really? You will come back Orbit?
:+1: 
But, now i'm using Owl Slider :'(

**Comment by chrissmejia** [comment]
That's really good news :)

**Pull request closed without merging**
