### PR TITLE
Issue 7904

### PR DESCRIPTION
**Pull request by sethkane**
Updated and enhanced the accessibility around reveals

### CODE REVIEW

**Comment by Owlbertz** [comment]
Thanks for the PR!
Just a last question: do we actually need lines 404 to 407 in `foundation.reveal.js`?

**Comment by sethkane** [comment]
No we don't need line 404-407 I am removing it now.

**Comment by sethkane** [comment]
Travis CI didn't complete how do I fix that or re run it?

**Comment by Owlbertz** [comment]
This happens sometimes when it fails to get the dependencies right.
I ran it again and now its passed. Going to merge this now, thanks again for your effort.

**Comment by sethkane** [comment]
Awesome, Let me know how I can continue to help!

**Comment by Owlbertz** [comment]
If you like to you can go ahead and test other components' accessibility as well. We're always interested in improvements here.

**Comment by sethkane** [comment]
@Owlbertz I am on it. I am very happy to help!

**Pull request merged**
