### PR TITLE
refactor: check and fails for missing DOM elements

### PR DESCRIPTION
**Pull request by ncoden**
## Description

Throw an error when the DOM elements that are required by components cannot be found, instead of letting the component crashing or going into a weird behavior.

### Changes
- Fail for OffCanvas `[data-off-canvas-content]`
- Fail for Slider `[data-slider-handle]
- Simplify and clean up OffCanvas methods.

### ⚠️ TODO
- [ ] Also check attributes that target an element.

Related to https://github.com/zurb/foundation-sites/issues/10684

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] The pull request title and template are correctly filled.
- [ ] The pull request targets the right branch (`develop` or `develop-v...`).
- [ ] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
`Error` correctly throws a real error and `console.error` just formats a console output.

https://developer.mozilla.org/en-US/docs/Web/API/console/error
https://console.spec.whatwg.org/#error
https://console.spec.whatwg.org/#logger
https://console.spec.whatwg.org/#loglevel-severity

First result for `throw Error vs console.error javascript`: https://stackoverflow.com/questions/25377115/what-is-the-difference-between-throw-error-and-console-error

**Comment by ncoden** [comment]
@DanielRuf Ahah, I perfectly know what these methods _does_. What I am looking for is documentation about their recommended usage. I know that raising an error is a good thing when something is wrong ("fails early"), but is this still true for DOM-based frameworks? Shouldn't we in this case let the component run the best it can and display errors in the console?

**Comment by SassNinja** [comment]
> Shouldn't we in this case let the component run the best it can and display errors in the console?

Imo that's exactly what we should do!

A `console.error` points out something is definitely wrong. 
But I wouldn't be that strict and stop execution. If the warning lights in a car are on it's up to the driver to decide if he fixes it or continues to drive.

**Comment by ncoden** [comment]
Note: If we throw an error in the component to stop its own programmatic ("Something is wrong, stop everything"), it will not break others components. Errors are cached and logged by the Foundation core.

**Comment by DanielRuf** [comment]
> Note: If we throw an error in the component to stop its own programmatic ("Something is wrong, stop everything"), it will not break others components. Errors are catch and logged by the Foundation core.

This should be fine then. In this case we can prevent wrongly used components if something is completely wrong / off.

**Comment by SassNinja** [comment]
This PR seems to include more changes than just implementing `throw new Error()`...

I still have the opinion the framework should do the best it can to keep running (and provide error message if appropriate) instead of throwing real errors. Though this might be topic of discussion.

Anyway I'm closing this PR because it has conflicts and should be discussed as issue first.

**Pull request closed without merging**
