### PR TITLE
Update sass.md

### PR DESCRIPTION
**Pull request by paxperscientiam**
Before submitting a pull request, make sure it's targeting the right branch:
- For documentation fixes, use `master`.
- For bug fixes, use `develop`.
- For new features, use the branch for the next minor version, which will be formatted `v6.x`.

If you're fixing a JavaScript issue, it would help to create a new test case under the folder `test/visual/` that recreates the issue and show's that it's been fixed. Run `npm test` to compile the testing folder.

Happy coding! :)

Suggestion to use DiffMerge for visualizing file differences. Instrumental for adapting _settings.scss changes.

### CODE REVIEW

**Comment by andycochran** [comment]
I'm not sure we should recommend specific third-party tools for Git workflows. 
@zurb/yetinauts, thoughts?

**Comment by rafibomb** [comment]
So I like this kind of information, and I think there is a better place than the documentation for it. Perhaps we start a page in the Wiki for workflow optimizations or a page in the docs specifically for this. 

@paxperscientiam Would love to hear some ideas where it would allow workflow optimizations to be shared in the community.

**Comment by rafibomb** [comment]
We also have a [foundation code syleguide](https://github.com/zurb/foundation-code-standards) which could be linked to from a page. Maybe it's a hub from Foundation to other resources?

**Comment by colin-marshall** [comment]
I think if the specific tool recommendation was changed to the more broad recommendation of simply using a "diff" tool this would be good to include in the docs.

**Comment by paxperscientiam** [comment]
@rafibomb I'm obsessed with efficiency -- to a fault. I would love to share my thoughts on workflow. Is the consensus that any related write-ups should submitted via PR to zurb/foundation-code-standards?

@colin-marshall I second that.

**Comment by kball** [comment]
Given the discussion above, going to close this.

**Pull request closed without merging**
