### PR TITLE
Fix documentation for OffCanvas#closed event

### PR DESCRIPTION
**Pull request by NeonArray**
The documentation incorrectly stated that the event triggers when opened instead of when it closes.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Please use the master branch for docs.

**Comment by ocularrhythm** [comment]
Right on

**Comment by DanielRuf** [comment]
It seems you have to rebase locally and force-push to the remote.

**Comment by ncoden** [comment]
@DanielRuf FYI we will get rid of the `master`/`develop` split by always pushing changes on `develop` and using `master` for stable releases only, like a standard GitFlow model.

**Comment by DanielRuf** [comment]
> @DanielRuf FYI we will get rid of the master/develop split by always pushing changes on develop and using master for stable releases only, like a standard GitFlow model.

Sounds good 👍

**Pull request closed without merging**
