### PR TITLE
Version 6.2

### PR DESCRIPTION
**Pull request by gakimball**
Here's what we're doing for Foundation for Sites 6.2.

**To install it into an existing project:**

``` bash
npm install zurb/foundation-sites#6.2
bower install zurb/foundation-sites#6.2
```

**Feature List:**
- [ ] Ship Joyride, which has already been written.
- [x] Add flexbox modes to components #7757
  - [ ] Add flexbox option to customizer
- [x] Update the JavaScript codebase to ES2015 #7758 
- [x] Flexible color palettes #7219 (specifically [this comment](https://github.com/zurb/foundation-sites/issues/7219#issuecomment-166990006))
- [x] `data-toggle-focus`, a variant of `data-toggle` that fires the events on element focus/blur instead of click. bf2cf1bb08d4238a48a5955ed10d01cb3ff54c39
- [x] `data-open`, `data-close`, and `data-toggle` can trigger multiple elements at once #7806
- [x] Upgrade the templates to Gulp 4 and ES6 zurb/foundation-zurb-template#28
  - [ ] We're collecting feeedback on the featureset of the ZURB Template at #7760
- [x] Place forms before buttons in the cascade. 9c2d18935c7d35c1ea603da3673e3993eb7c47a6
  - [x] And test it thoroughly.
- [x] Port `<input type="range">`, `<progress>`, and `<meter>` styles from Foundation for Apps.

We're going to ship it by the end of February.

### CODE REVIEW

**Comment by Silvester20** [comment]
Awesome list, can't wait for this release :)

Any plans to implement the "data-options: step"-option for the range slider? Really need this in the next version.

**Comment by SalahAdDin** [comment]
Come back old top bar style!

**Comment by gakimball** [comment]
@SalahAdDin You mean the Foundation 5 top bar?

**Comment by gakimball** [comment]
Working on merging `6.2` into `develop`. We're going to do an RC of 6.2 this week, and 6.2 will also be our next release.

**Comment by SalahAdDin** [comment]
@gakimball yes, i think that was very useful and easy to configure, now i have problem  for adapt my topbar to new style.

**Comment by gakimball** [comment]
@mschinis You're right, a range will be more useful.

**Comment by mschinis** [comment]
@gakimball I'll open a new PR to reflect the change. I believe anything from 2.1 onwards is reasonable as a range.

**Comment by gakimball** [comment]
@mschinis Don't allow for 3.x in the range; we haven't tested it yet.

**Comment by SalahAdDin** [comment]
Wait man, i did some fixes to Foundation, but i'm waiting for other fixes to make a PR for you.

**Comment by rafibomb** [comment]
@SalahAdDin Which PR's are you looking for? It could help us prioritize.

**Pull request merged**
