### PR TITLE
fixes #8603 removes e.stopImmediatePropagation(); from mouseenter event

### LINKED ISSUE #8603: [Dropdown Menu] hoverDelay leave pane reenter pane issue
an a dropdownmenu the first level has a submenu so the pane opens the items in the pane has no submenu.
if you leave the pane and reenter it within the hover delay the pane gets closed

### PR DESCRIPTION
**Pull request by designerno1**
fixes #8603 for me
removes e.stopImmediatePropagation(); from mouseenter event to provide mouseenter can bubble through and clear the timeout on re enter a pane

please take a look and discuss and explain the need of the e.stopImmediatePropagation();

### CODE REVIEW

**Comment by kball** [comment]
Good question.  I don't know why stopImmediatePropagation would be needed, and looking at the commit history isn't helpful because it was added as part of a massive commit without a useful commit message.  @colin-marshall @Owlbertz any ideas why this might be needed?  If not I say we go ahead and merge this.

**Comment by colin-marshall** [comment]
@designerno1 can you please reproduce #8603 in a CodePen? Just want to make sure I have the same syntax as you.

@kball is this worthy of a visual test?

**Comment by designerno1** [comment]
@colin-marshall 
https://codepen.io/designerno1/full/QNZVNw/

**Comment by kball** [comment]
@colin-marshall we're light on dropdown menu visual tests anyway, with all the current ones focused on rtl... this seems like it would be a good start to a basic set highlighting different option behaviors.

**Comment by colin-marshall** [comment]
@designerno1 thank you for the CodePen, it helped me understand the problem and why this fix works.

Only thing I would recommend before merging is converting your CodePen to a visual test in the repo. The only thing you need to change is the instructions for how it should behave normally. Something like `test/visual/dropdown-menu/submenu-mouse-reenter.html` would be great. Thanks!

**Comment by TejasQ** [comment]
+1! This is awesome!

**Pull request merged**
