### PR TITLE
[docs] 6.4.0 housekeeping

### PR DESCRIPTION
**Pull request by petecooper**
First pass. I'll come back to kitchen sink on another PR.

### CODE REVIEW

**Comment by IamManchanda** [comment]
Woah thats cool ... Nice work @petecooper ...

**Comment by petecooper** [comment]
Follow up with ImageOptim specifics:

screen shot 2017-06-27 at 23 14 55

screen shot 2017-06-27 at 23 15 01

That's all for this PR.

**Comment by rafibomb** [comment]
Wow @petecooper this is great! Thanks for the needed optimizations here!

**Comment by petecooper** [comment]
@rafibomb - no sweat, happy to help.

**Comment by petecooper** [comment]
@rafibomb @IamManchanda - is there a docs style guide, internal or public?

**Comment by gakimball** [comment]
@petecooper There's some basic stuff [here](https://github.com/zurb/foundation-code-standards/blob/master/documentation.md) but it hasn't been updated in a while—it could use some work from other collaborators.

Any specific questions you have?

**Comment by petecooper** [comment]
@gakimball Thank you - I'll take a closer look. No specific questions, just some proposals that may help uniformity overall.

**Comment by DanielRuf** [comment]
Maybe we can try to use the best availble tool. At least PNGGauntlet produces some better results:
image

ImageOptim is not the best out there ;-)

**Comment by petecooper** [comment]
Alright, @DanielRuf might be onto something here, so here's what I'm going to do:

* close this PR, with a view to…
* splitting the docs housekeeping into multiple PRs for sanity and avoid the current merge conflict
* using >1 image optimiser for maximum refreshment in another PR

**Pull request closed without merging**
