### PR TITLE
Dropdown explicit positioning

### PR DESCRIPTION
**Pull request by kball**
Create a fully explicit positioning model for Box a la Tether (CC issue #9989). Initially inspired by https://github.com/zurb/foundation-sites/issues/9799 for dropdown but should also work for tooltips.

This is WORK IN PROGRESS do not merge... checklist below

- [x] Set up explicit positioning and alignment
- [x] Create visual tests for full position and alignment
- [x] Get dropdown working when fully positioned and aligned
- [x] Add configuration for whether dropdown can overflow container or not.
- [x] Create visual tests for adjustments on overflows (IN PROGRESS)
- [x] Get dropdown to adjust properly when positioned and alignment overflows (IN PROGRESS)
- [x] Get dropdown to adjust properly when not positioned or aligned and defaults overflow
- [x] Create/verify tests for prior behavior of dropdown
- [ ] Create tests for Box.ImNotTouchingYou to make sure the new implementation over Box.OverlapArea is 100% compatible.
- [x] Get as many cases of prior behavior to be 'automatically' determined as possible, to ease migration
- [x] Update tooltip to use new Box methods.
- [x] Add tooltip positioning visual tests
- [x] Document new positioning approaches

### CODE REVIEW

**Comment by IamManchanda** [comment]
@kball i tweaked a bit with visual testing and i think overflow has its issues .... apart from it looks good !

**Comment by IamManchanda** [comment]
@kball i added a test case ... is this the right behaviour what's happening??

**Comment by kball** [comment]
@IamManchanda good question... as currently constructed, the overflow/repositioning only checks 1 way if you set the position. IE if you set position top or bottom it will only look for left/right overflow, and if you set position left/right it will only look for top/bottom overflow.

I'm not sure that's the right behavior... however it is more consistent with past behavior.

I haven't yet implemented the all position all alignment overflow checking (that I want for cases where position is auto anyway), so once I do maybe we can look at how that behavior works and see if it's better...

One other outstanding question is... what if there is *no* way to lay out the dropdown without an overflow? What should behavior be?  I could make cases for defaulting to the original position/alignment, or for trying to find the "least overflow" case... what do you think?

**Comment by IamManchanda** [comment]
@kball => Trying to find the "least overflow" case

**Comment by kball** [comment]
OK I think to do least overflow case we'll just need to modify the box ImNotTouchingYou to return the overlap amount rather than just true/false. I don't think I'll have time today to push this forward but probably tomorrow

**Comment by kball** [comment]
OK I just pushed updates that get all of the overflow adjusting working "as expected". It feels magical, and is kind of awesome.  Need to add a bunch of tests for previous behavior and make sure that we're backwards compatible as much as possible... 

One outstanding question for me is... I'm confident we want to be backwards compatible for dropdowns themselves... if you've gone through work to get your dropdown to lay out the way you want, it should continue to do so... and our "base cases" should work right...

What I'm wondering is how much to worry about to maintaining backwards compatibility for Box.GetOffsets (which was always kinda hokey and automagical) or if we can just update tooltip as well (the only internal client that uses Box) and more or less wave our hands with Box.GetOffsets... with a "decent attempt" at backwards compatibility.  

Or maybe put it back to the old code, which has a lot of duplication/overlap with the new Box.GetExplicitOffsets, and put a deprecation warning in that it's obsolete and will be removed in 6.5.  Actually, after writing through these, I think that is probably the best option... update tooltip to also use GetExplicitOffsets, revert GetOffsets to original state, and add a deprecation warning.

Any @zurb/yetinauts want to chime in on this approach?

**Comment by IamManchanda** [comment]
Will test it out tonight for sure... Yup magical coz we didn't had to rely on other plugins like tether and create one more dependency for the users!

**Comment by IamManchanda** [comment]
Updating tooltip also make sense

**Review by IamManchanda — APPROVED** [review]
Approving current changes .... tested it out .... had some browser testing too
1. Windows 10 (IE, Edge, Safari, Firefox, Chrome, Opera, Yandex)
2. Mac Sierra (Safari, Firefox, Chrome, Opera, Yandex)
3. Ubuntu 16 (Chrome, Firefox, Chromium, Ubuntu)

This looks good and awesome!

**Comment by kball** [comment]
OK, got a first pass of tooltip working with the new positioning model... or at least, the new positioning logic (refactored to share logic with dropdown). Need to put together some visual tests for tooltip the same way we did on dropdown, but it's at least working for the cases in the docs already.

Also fixed up some dropdown cases based on our other tests and docs. I think we're looking good, but @rafibomb has some existing implemented cases we want to pull into the docs to make sure they behave correctly backwards.

**Comment by IamManchanda** [comment]
Hey @kball i added test case but it seems like buggy .... fetching `data-alignment` in the opposite direction!
Can you check!

**Comment by kball** [comment]
Ah interesting... there's two pieces here. 

The first is that tooltips are treating vOffset and hOffset differently than dropdowns (I ran into this a little bit and hacked around it for the centered case, but these tests highlight that I actually need to separate the concept of the offset that leaves space for the nub (applied in your *position* axis, but not in the your *alignment* axis) from the concept of hOffset and vOffset which are a way to manually nudge things around.

The second is that we need to actually reposition the nub based on alignment (probably by applying `align-x` classes.

**Comment by kball** [comment]
OK, fixed tooltip and got it working as we'd like it. The outstanding pieces of this are to test against some more existing cases (particularly in dropdown) to verify backwards compatibility and document the explicit usecase.

@rafibomb can you help get those two pieces across the line?

**Comment by kball** [comment]
We could probably merge for the RC even without those 2 pieces, as functionality-wise I believe this is now complete.

**Comment by IamManchanda** [comment]
Ohk @kball .... have updated the docs! 
When that nub is fixed ... good to merge i guess!!

**Comment by kball** [comment]
nub aligned... @rafibomb is working on getting me another good testcase and then I think this is good

**Comment by kball** [comment]
I think this is good to go! Merging

**Pull request merged**
