### PR TITLE
Components settings

### PR DESCRIPTION
**Pull request by andreamk**
Added the variable map "$components_setting " in global , with which you can enable the foundation components.

### CODE REVIEW

**Comment by rafibomb** [comment]
Wow - intersting approach! How does this improve on the current method of controlling includes in app.scss?

**Comment by andreamk** [comment]
Hello
I'm developing a wordpress plugin that allows to change the settings in the backend .

Add the components in an array improves two things .
1 ) You no longer need to modify the inclusions and it changes only the file settings.scss
2 ) you can create external components that depend on the active modules .

for example, in an external scss (wordpress theme scss) you can do this 

` @if (not foundation_component_enabled("forms")) {
  	input {
            box-sizing : border-box;
            width: 100%;
        } 
  }`

**Comment by andreamk** [comment]
It also solves a problem of inconsistency .

include "flex-grid" and set "$global-flexbox" false I think is a possible error.
With the $components-settings you can replace 
`@if $global-flexbox {`
with
`@if (foundation_flex_grid_enabled()) {`
removing any possibility of error

**Comment by andycochran** [comment]
Ooh. This *is* interesting. What do the @zurb/yetinauts think? 
(It's a major change tho, so it'd need to target the `v6.3` branch.)

**Comment by rafibomb** [comment]
Yeah - this is a big change! @andreamk Can you point this at branch `v6.3`? In the meantime I'll get some more eyes on it see how we can fit it in!

**Comment by colin-marshall** [comment]
Haven't had a chance to test this out, but it seems logical to me to consolidate this into `_settings.scss`. I'm all for it!

**Comment by andreamk** [comment]
hello
I don't understand how to point the pull request at branch 6.3

**Comment by brettsmason** [comment]
@andreamk unfortunately the only way as far as I know is to close this PR and open a new one, targetting the 6.3 branch.

**Comment by Owlbertz** [comment]
Yes, but please perform a merge of v6.3 into your feature branch locally before opening the PR.

**Comment by andreamk** [comment]
Ok

**Pull request closed without merging**
