### PR TITLE
Fixed #9766

### LINKED ISSUE #9766: Positioning of dropdown is not correct when two buttons open the same dropdown
#### How to reproduce this bug:

1. Create two buttons that both point to the same dropdown code using example markup on http://foundation.zurb.com/sites/docs/dropdown.html
2. Click your first button
3. Click your second button

#### What should happen:
The dropdown pane should appear in the right place depending on which button was clicked. This is the expected behavior based on previous versions of Foundation.

#### What happened instead:
The dropdown only appears next to the first button, regardless of which button has been pressed

#### Test case:
https://codepen.io/anon/pen/ygQoVj

### PR DESCRIPTION
**Pull request by hikouki**
Hi! ✈️ 

Changed Dropdown panes so that it is arranged with the position of primary anchor as a reference.

It may not be a beautiful code... 😨 
What would you do if you were me?

### CODE REVIEW

**Comment by kball** [comment]
Hi @hikouki,
Thanks for the PR!  I think this is broadly the right approach, but what I'd love to see is if we can solve this without storing the data on the DOM object itself, but rather store a reference to the current/primary in the javascript itself... we're moving towards more of a state-driven approach to the javascript and planning to abstract the DOM interactions behind and interface, so the more we can keep this as pure JS state the better.

**Comment by hikouki** [comment]
I'll try! 👍

**Comment by hikouki** [comment]
I tried. :)
How does it?

**Comment by kball** [comment]
Looks great @hikouki! Would you be able to add a visual test or an example in the docs that we can use to straightforwardly test the behavior?

**Comment by hikouki** [comment]
Leave it to me!

**Comment by hikouki** [comment]
I did it. 🍣

**Comment by kball** [comment]
Merged! Thanks @hikouki, sorry for the slow turnaround

**Pull request merged**
