### PR TITLE
Closes #9825 - Updated Issue Template with 6.3.1 release codepen's

### LINKED ISSUE #9825: Please Update pens! [6.3.1]
I have made the updated pens!

```markdown
<!-- Please only file either bugs or any feature request that you would like to suggest for Foundation on GitHub. If you've got a more general question about how to use Foundation, we can help you on the Foundation Forum: http://foundation.zurb.com/forum -->

#### How to reproduce this bug:

1. Step one
2. Step two
3. Step three

#### What should happen:

#### What happened instead:

#### Test case:

<!-- Give us a link to a CodePen or JSFiddle that recreates the issue. -->

- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)
```

cc / @kball @rafibomb

### PR DESCRIPTION
**Pull request by IamManchanda**
Closes #9825
Forwarded from #9826 due to wrong branching naming issues .... **apologies**!

----------------------------------------------------------------------------------------------------------

Listing below the added codepen's also so that you can review the pens if any changes required

6.3.0
- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

6.3.1
- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

### CODE REVIEW

**Comment by IamManchanda** [comment]
@kball  - Is it the right branch to push.... 
I added `develop` instead of `master` because its the default branch of this repo!

As always, Totally confused of these branches n all :smile:

**Comment by IamManchanda** [comment]
@Deckluhm As advised by you, i have updated motion ui to latest version => **1.2.2** in my codepens

**Comment by Owlbertz** [comment]
Looks good to me, but I am not sure about the change of the comment. So I'd like to have @kball or @rafibomb have a look.

**Comment by IamManchanda** [comment]
@Owlbertz i dont think there is anything to be unsure, i guess github issues is for both bugs and feature. Isn't it ??

Before
> Please only file bugs with Foundation on GitHub. If you've got a more general question about how to use Foundation, we can help you on the Foundation Forum: http://foundation.zurb.com/forum

After
> Please only file either bugs or any feature request that you would like to suggest for Foundation for Sites on GitHub. If you've got a more general question about how to use Foundation, we can help you on the Foundation Forum: http://foundation.zurb.com/forum

**Comment by rafibomb** [comment]
I made some edits - looks good!

**Comment by IamManchanda** [comment]
@rafibomb 

screenshot-zurb-630

**Pull request merged**
