### PR TITLE
chore: clean components & focus after tests

### LINKED ISSUE #11074: [Dropdown] tests: activeElement is the body in IE11
The test in IE(11) on browserstack throws an assertion error at https://github.com/zurb/foundation-sites/blob/4903223479b67cd9a4266ee1cd8be12ae1c65b13/test/javascript/components/dropdownMenu.js#L71

This is because IE focusses the body element after this.
What should we do here?

Probably related: https://allyjs.io/tutorials/mutating-active-element.html

### PR DESCRIPTION
**Pull request by ncoden**
## Description

After tests are run, any HTML added must be removed as the DOM is shared with others tests. Otherwise, there can be side effects on others tests.

This is what happened with `DropdownMenu`, where one drodown that was not removed made an other tests failing by changing the way the browser should handle the focus.

- Closes https://github.com/zurb/foundation-sites/issues/11074

### Changes
* ensure html and components are cleared after DropdownMenu tests.
  They was not cleared as `$html` and `plugin` were re-defined in tests, overriding already created `$html` and `plugin` and making them not being cleared.
* removed toggler triggers after Toggler tests
* clear focus after all tests involving focus

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `support/*`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> where one drodown that was not removed made an other tests failing by changing the way the browser should handle the focus.

Thought https://github.com/ncoden/foundation-sites/blob/814d2e55f2313675c558d2d520b423bf02a79b4e/test/javascript/components/dropdownMenu.js#L45 already does this.

**Comment by ncoden** [comment]
> This does not fix it and produces new issues as far as I can see.

True. I don't know why I got this working when testing...

**Comment by ncoden** [comment]
The "works alone but not after others tests" only means that something is not cleared correctly, in tests or components.

**Comment by ncoden** [comment]
Edit: The bug seems to be caused by the test just above:

```
Dropdown: keyboard events Dropdown does not focus Dropdown when anchor is an input 
```

Without this test, everything works fine. With this test only, we got the focus bug.

screen shot 2018-04-28 at 00 44 02

**Comment by ncoden** [comment]
> [Windows 7, Internet Explorer 9.0] Error: "does not find focusable elements with negative tabindex" failed, expected {} to equal 0
> (...)
> -- https://travis-ci.org/zurb/foundation-sites/jobs/372449224#L1236

This was not introduced by this PR. See tests for for `develop`: https://travis-ci.org/zurb/foundation-sites/jobs/372198260#L4883

**Comment by ncoden** [comment]
@DanielRuf 
> Do we not need the comment here?

See https://github.com/zurb/foundation-sites/pull/11210#commitcomment-28774749. Do you want me to add these comments back ?

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
