### PR TITLE
fix: camelCase all events

### PR DESCRIPTION
**Pull request by DanielRuf**
Fixes https://github.com/zurb/foundation-sites/issues/10155

### CODE REVIEW

**Comment by DanielRuf** [comment]
This will be a breaking change in 6.4.4.

**Comment by ncoden** [comment]
> Be consistent in the event naming is good, but not enough useful to be a breaking change, not in a pre-v7 version.
> -- https://github.com/zurb/foundation-sites/issues/10155#issuecomment-367248848

Also there should be no breaking change in patch versions (`v6.4.4`). So at least `v6.5.0` but I'm not sure this is useful.

**Comment by DanielRuf** [comment]
The docs and event names should be consistent then when this would be merged as we use camelCase for all other components. Not yet sure if already in 6.5 or 7.

**Comment by ncoden** [comment]
> This branch has conflicts that must be resolved

**Comment by ncoden** [comment]
> camelcase the event names of the dropdownMenu, offCanvas and smoothScroll

Aren't _all_ events in camelCase now ?

**Comment by DanielRuf** [comment]
> Aren't all events in camelCase now ?

Not sure what you mean. https://github.com/zurb/foundation-sites/issues/10155#issuecomment-368420674

**Comment by ncoden** [comment]
I mean: the PR can be simply called `make all events in camelCase` if so.

**Comment by ncoden** [comment]
> remove spaces 

Please always commit with a context (like `style: remove useless spaces in offCanvas`) to avoid polluting the git history.

**Comment by DanielRuf** [comment]
> I mean: the PR can be simply called make all events in camelCase if so.

A now it made 'click'.

**Comment by DanielRuf** [comment]
> Please always commit with a context (like style: remove useless spaces in offCanvas) to avoid polluting the git history.

Ok. Will write them down again tomorrow. Will keep this in mind for the next commit / PR.

**Review by ncoden — APPROVED** [review]
* [x] Components looks fine
* [x] Tests pass (in local)
* [x] Events are correct in the documentation (with https://github.com/zurb/foundation-docs/pull/24)

So LGTM !

Thank you @DanielRuf.

**Review by colin-marshall — APPROVED** [review]
Good to go!

**Pull request merged**
