### PR TITLE
fixed issue #7831

### PR DESCRIPTION
**Pull request by isapir**
based on https://stackoverflow.com/a/13891717/968244

### CODE REVIEW

**Comment by isapir** [comment]
For the time being, you can see a working example at https://beta.100candles.com/items.htm (WIP otherwise) -- where each item thumbnail opens a Reveal.

**Comment by kball** [comment]
First off, thanks for taking a pass at this! A couple pieces of feedback:

1. Testing within the docs or the visual tests with this branch on iOS opening and closing a modal seems to blow away the scroll position... it doesn't on your example, so not exactly sure what's going on there; do you have the ability to do any testing with an iOS device or other thoughts on what might be going on?

2. I'd rather consolidate the logic from this into the existing `is-reveal-open` class being applied to html rather than adding another one... those classes are attempting (though imperfectly) to create the same behavior you're doing here, so we should fix them rather than augment

**Comment by isapir** [comment]
@kball ,

>Testing within the docs or the visual tests with this branch on iOS opening and closing a modal seems to blow away the scroll position... it doesn't on your example, so not exactly sure what's going on there; do you have the ability to do any testing with an iOS device or other thoughts on what might be going on?

Fortunately all I had to do was to pass a "mobile" user-agent in order to reproduce this issue.  I removed the "mobile-specific" code since it is not needed, and that issue is resolved.

>I'd rather consolidate the logic from this into the existing is-reveal-open class being applied to html rather than adding another one... those classes are attempting (though imperfectly) to create the same behavior you're doing here, so we should fix them rather than augment

I have consolidated the `.disable-scroll` class into `.is-reveal-open`, but the fix required to set the class on `html` rather than `body`.  That is not a problem in itself, but now the Travis test cases fail because they expect `body.is-reveal-open` rather than `html.is-reveal-open`

I am not sure where the test cases are located, and if I am even able to submit an update to them, so here is the stack traces of the failures:

```  2 failing
  1) Reveal open() adds class to body:
     AssertionError: expected { Object (length, prevObject, ...) } to have class 'is-reveal-open'
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/chai.js:874
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/chai-jquery.js:102
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/chai.js:4027
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/js-tests.js:1761
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:5206
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:5014
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:8201
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:8269
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:362
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:157
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:8270
      at open (file:///home/travis/build/zurb/foundation-sites/_build/assets/js/foundation.js:9129)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/js-tests.js:1765
      at callFnAsync (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4234)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4177
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4661
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4790
      at next (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4581)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4591
      at next (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4523)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4559
      at timeslice (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:12326)

  2) Reveal close() does not remove class from body if another reveal is open:
     AssertionError: expected { Object (length, prevObject, ...) } to have class 'is-reveal-open'
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/chai.js:874
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/chai-jquery.js:102
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/chai.js:4027
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/js-tests.js:1894
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:5206
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:5014
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:8201
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:8269
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:362
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:157
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:8270
      at finishUp (file:///home/travis/build/zurb/foundation-sites/_build/assets/js/foundation.js:9228)
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7236
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:3317
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:3447
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7079
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7405
      at schedule (file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:6783)
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7428
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7418
      at Animation (file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7156)
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7262
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:4401
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:4443
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:362
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:157
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:4445
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7273
      at file:///home/travis/build/zurb/foundation-sites/node_modules/jquery/dist/jquery.js:7375
      at close (file:///home/travis/build/zurb/foundation-sites/_build/assets/js/foundation.js:9195)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/js-tests.js:1900
      at callFnAsync (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4234)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4177
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4661
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4790
      at next (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4581)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4591
      at next (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4523)
      at file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:4559
      at timeslice (file:///home/travis/build/zurb/foundation-sites/test/javascript/lib/mocha.js:12326)
```

**Comment by isapir** [comment]
@kball , I hope that you're not giving this patch a lower priority because the test cases fail -- the problem here is with the test cases, which should be updated.

**Comment by isapir** [comment]
p.s. The demo website is not updated with the current patch so you can not see it there, but if you build it you will see that I addressed both issues that you cited.

**Comment by isapir** [comment]
@kball can you please review this PR?  I've addressed the points that you made and I'm concerned that by the time it will be reviewed the code base will change and it will not be easy to merge.

As I wrote above,the "test case failures" reported by Travis are due to a change in the structure, so the test cases should be updated accordingly.

Thank you.

**Comment by kball** [comment]
Sorry for the delay on this, have been very busy and not had much time for Foundation. This is looking great! I'll fix the unit tests & merge

**Pull request merged**
