### PR TITLE
docs: improve installation and setup documentation

### PR DESCRIPTION
**Pull request by ncoden**
Improve documentation of installation and setup. See list of commit and previews below for more informations.

### CODE REVIEW

**Comment by ncoden** [comment]
## Installation

screenshot-2018-1-15 installation foundation for sites 6 docs

## Starter Projects

screenshot-2018-1-16 starter projects foundation for sites 6 docs

**Comment by ncoden** [comment]
@IamManchanda @brettsmason @Owlbertz @JeremyEnglert Any thoughts on this ?

**Comment by brettsmason** [comment]
@ncoden Great job!
I just compared your screenshots with the current live docs and they are a huge improvement 👍

**Comment by JeremyEnglert** [comment]
Awesome work, @ncoden! Looks great.

**Comment by IamManchanda** [comment]
Superb work... Looks AWESOME

**Comment by ncoden** [comment]
Thank you @brettsmason @JeremyEnglert @IamManchanda.
So I guess it's ready to merge.

**Pull request merged**
