### PR TITLE
feat: add `dynamicHeight` option on Sticky to control container height changes #10846 (2)

### LINKED ISSUE #10846: Problem with Sticky Navigation - Foundation 6.4.3
Hi I wanted to make it known that the Sticky element in foundation 6.4.3 does not work so well. I refer with precision to the sticky navigation. When you scan the page the elements immediately below the navbar snap and hop.

I tested this issue on Firefox, Chrome and Safari in desktop version and It is visible on your own
https://codepen.io/IamManchanda/pen/aWaJpM?editors=1010

### PR DESCRIPTION
**Pull request by ncoden**
Add option `dynamicHeight` on Sticky:
* **dynamicHeight** {boolean} [true] - If true (by default), keep the sticky container the same height as the element. Otherwise, the container height is set once and does not change.`

Closes https://github.com/zurb/foundation-sites/issues/10846
Previous PR: https://github.com/zurb/foundation-sites/pull/10875

### CODE REVIEW

**Comment by ncoden** [comment]
@colin-marshall Could you review this please ? :)

**Review by DanielRuf — APPROVED** [review]
LGTM https://codepen.io/DanielRuf/pen/Gxvzxo?editors=1010

**Comment by felipe-spengler-osf** [comment]
Hello @DanielRuf @ncoden, is this part of current sticky? I don't see anything mentioned on the current documentation and is exactly what I need, in my case I need the container to stay with the initial height instead of being recalculated.
Thanks!

**Comment by felipe-spengler-osf** [comment]
Hi. Checking a little deeper I noted this is available on the Sticky own JS from the current release, but when I try to build my custom package on https://foundation.zurb.com/sites/download/#customizeFoundation, the custom build come as 6.5.1 and the Sticky there doesn't have dynamicHeight option.

I imagina this is not intended?

**Comment by DanielRuf** [comment]
Hi @felipe-spengler-osf ,

The customizer probably uses an outdated version.

Alternatively you can manually download the needed files from the CDNs.

**Pull request merged**
