### PR TITLE
Fixed keyboard access for accordion menu.

### LINKED ISSUE #8352: [Accordion Menu] not tabbable/keyboard navigatable
**How can we reproduce this bug?**

1. Tab through webpage tab sequence
2. focus will hit first item of accordian-menu, at which point, tab (and backwards tab/alt+tab) no longer work.
3. left/right arrow keys will open and close that first level item dropdown, however up/down arrows do not work, so keyboard can never access the submenu items, by either up/down or tab

**What did you expect to happen?**
functionality of keyboard should match the standard accordian. Aka, tab sequence should not be interrupted, and tab key should continue to navigate to the (other) visible links/focus points. up/down arrows should also enable user to navigate the menu items, in same manner that a user an do so in standard accordian.

**Test case**

http://foundation.zurb.com/sites/docs/accordion-menu.html
http://foundation.zurb.com/sites/docs/accordion.html

### PR DESCRIPTION
**Pull request by Owlbertz**
Set tabindex before setting focus.
Fixes #8352.

### CODE REVIEW

**Comment by gakimball** [comment]
Going to put together a test case and then I'll merge.

**Comment by gakimball** [comment]
I'm not able to trigger actual links in the menu with the Enter or Space keys, can you take a look?

**Comment by Owlbertz** [comment]
Yeah, I noticed this a while back already. I think this is related on how the Menus are designed, since the trigger is the `li` and not the `a`. I adjusted the selectors and this should be fine now.

**Comment by gakimball** [comment]
Thanks!

**Pull request merged**
