### PR TITLE
fix: open Drilldrown with the currently opened (sub)menu height #11416

### LINKED ISSUE #11416: F6.5 Drilldown Submenu height calculation wrong when toggled
I'm using the Drilldown Menu in combination with Responsive Navigation and Top Bar. 

## What should happen?
When Drilldown is closed and reopened after navigating to a submenu, height for ".is-drilldown"
should be height of ".is-drilldown-submenu.is-active"

## What happens instead?
seems that height for ".is-drilldown" is recalculated from "ul.drilldown".
This results in overlapping active Submenu over Main Menu, if Main Menu is heighter
than Submenu

## Test Case and/or Steps to Reproduce

Test Case:
https://codepen.io/magic77/pen/vagxYL

How to reproduce:
1. Scale your browser down to see the toggle Button
2. Open Mobile Menu, and click "Produkte OPEN ME"
3. Click "Produkte 2 OPEN ME"
4. Close and reopen Mobile Menu

## Your Environment

- Foundation version(s) used: 6.5.0-rc.2
- Browser(s) name and version(s): Chrome 67.0.3396.99
- Operating System and version (desktop or mobile): Mint Linux 18.3, Desktop

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

### PR DESCRIPTION
**Pull request by ncoden**
## Description

When a Drilldown submenu is opened, then the whole Drilldown is closed and reopened, the submenu is still there but the Drilldown takes the height of the main menu.

This pull request fix this bug by using the active (sub)menu height when the Drilldown height is recalculated.

### Changes
- Save the currently opened sub-menu as `$currentMenu`
- When calculating the Drilldown wrapper height, use the currently opened menu height instead of the primary menu.

- Closes https://github.com/zurb/foundation-sites/issues/11416

## ⚠️ ToDo
- [x] Add unit tests

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [ ] ~~I have updated the documentation accordingly to my changes (if relevant).~~
- [x] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ncoden** [comment]
I fixed a bug on initialization and added unit tests for the Drilldown resizing in the following cases (when toggled):
- Opened
- Opened then closed
- Opened, shown a submenu, closed then reopened.

**Comment by Owlbertz** [comment]
Will have a look asap.

**Comment by Owlbertz** [comment]
Ok, I checked this but it kinda feels like it still has some issue...

What I did:
1. Open http://localhost:3000/drilldown-menu.html
2. Go to autoHeight version.
3. Open Item 3 -> Item 3E
4. Close menu using `ESC`
5. Open Item 3
-> Now level 3 is already visible (which I assume is a separate bug as it is already present in the docs)
-> Despite level 3 is already visible, the menu only has the height of level 2 (everything below Item 3EE isn't visible).

Did I get something wrong or is there actually something odd with the menu?

**Comment by ncoden** [comment]
@Owlbertz I tested it on `develop` and I have the same error. This is definitely something we should fix but it's not related to this pull request.

**Comment by Owlbertz** [comment]
@ncoden while this is true, I am struggling reproducing the issue you fixed with the PR. Maybe you could give some more info on how to reproduce?

**Comment by ncoden** [comment]
@Owlbertz See https://github.com/zurb/foundation-sites/issues/11416

> 1. Scale your browser down to see the toggle Button
> 2. Open Mobile Menu, and click "Produkte OPEN ME"
> 3. Click "Produkte 2 OPEN ME"
> 4. Close and reopen Mobile Menu

**Review by Owlbertz — APPROVED** [review]
Looks good to me.

**Comment by Owlbertz** [comment]
Sorry, didn't get the referenced issue. With the example provided the issue becomes pretty obvious.

**Comment by ncoden** [comment]
Thank you for the review @Owlbertz :)

I asked you a review because you worked on the Drilldrown before. Do you want me to poke you on future pull requests for others components ?

**Pull request merged**
