### PR TITLE
docs: use span for text in Progress Bar - closes #10490

### LINKED ISSUE #10490: [Progress Bar] With Text HTML Semantics Incorrect
There is a semantic issue with the [Progress Bar With Text](http://foundation.zurb.com/sites/docs/progress-bar.html#with-text).

A paragraph tag isn't allowed inside a span tag. Block elements (ex: `<p>`) can't be nested inside inline block elements (ex: `<span>`).

The simplest way to fix this is next span tags.

__Example:__
```
<div class="progress" role="progressbar" tabindex="0" aria-valuenow="20" aria-valuemin="0" aria-valuetext="25 percent" aria-valuemax="100">
  <span class="progress-meter" style="width: 25%">
    <span class="progress-meter-text">25%</span>
  </span>
</div>
```

Thoughts?

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This PR changes the markup from `p` to `span`.

- Closes #10490

We also have to update the embedded codepen.

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by andycochran — APPROVED** [review]
LGTM!

**Review by SassNinja — APPROVED** [review]
I noticed `<p>` gets `line-height: 1.6` (from `_base.scss`) whereas `<span>` doesn't.
As result the example progressbar's height has been reduced by 1px.

However since this is not related to the actual progressbar component (and span is semantically correct) it shouldn't matter.

Therefore it looks good to me 👍

**Comment by DanielRuf** [comment]
> ** continuous-integration/travis-ci ** Expected — Waiting for status to be reported

Well, there should be a green status, not a yellow one =/

**Comment by andycochran** [comment]
Travis might need a kick?

**Comment by DanielRuf** [comment]
> Travis might need a kick?

It is green at https://travis-ci.com/foundation/foundation-sites/builds/130534536

**Pull request merged**
