### PR TITLE
[6.2][ES2015] Add babel to gulp pipeline

### PR DESCRIPTION
**Pull request by colin-marshall**
To get #7758 going.

### CODE REVIEW

**Comment by gakimball** [comment]
Thanks for being on top of it! :)

Instead of the `es2015` preset, can we load only the plugins for features we're going to use? This might help keep us reigned in as we rework the codebase. (Our starter projects will probably just use the `es2015` preset, but we need to limit our codebase to only features that don't require polyfills.)

Here's the list. Each one has a matching Babel plugin:
- Fat arrows
- Classes
- Multiline strings
- Template strings
- Destructuring
- Default function parameters
- Trailing function parameters
- Spread parameters
- Let and const

**Comment by colin-marshall** [comment]
Here are the plugins I came up with that match the features list you provided. Could use some help on the ones with question marks. 

* Fat Arrows = [es2015-arrow-functions](http://babeljs.io/docs/plugins/transform-es2015-arrow-functions)
* Classes = [es2015-classes](http://babeljs.io/docs/plugins/transform-es2015-classes)
* Multiline Strings = [es2015-template-literals](http://babeljs.io/docs/plugins/transform-es2015-template-literals) ???
* Template Strings = [es2015-template-literals](http://babeljs.io/docs/plugins/transform-es2015-template-literals)
* Destructuring = [es2015-template-literals](http://babeljs.io/docs/plugins/transform-es2015-destructuring
)
* Default function parameters = [es2015-parameters](http://babeljs.io/docs/plugins/transform-es2015-parameters)
* Trailing function parameters = ???
* Spread parameters = [es2015-spread](http://babeljs.io/docs/plugins/transform-es2015-spread) ???
* Let and const = [es2015-block-scoping](http://babeljs.io/docs/plugins/transform-es2015-block-scoping/) and/or [es2015-block-scoped-functions](http://babeljs.io/docs/plugins/transform-es2015-block-scoped-functions)???

**Comment by gakimball** [comment]
All of those look fine. As for `es2015-block-scoped-functions`, from the readme:

> Babel plugin to ensure function declarations at the block level are block scoped.

That sounds like it doesn't require a polyfill, so that's fine.

**Comment by colin-marshall** [comment]
@gakimball PR is updated with plugins.

**Comment by gakimball** [comment]
Nice, thank you :)

**Pull request merged**
