### PR TITLE
Enabling floated dropdown alignment

### PR DESCRIPTION
**Pull request by Owlbertz**
As requested in https://github.com/zurb/foundation-sites/issues/7392.
Makes dropdown play nice with floating.

Basically my former solution merged into the current state of development.

### CODE REVIEW

**Comment by ncoden** [comment]
:+1: need

**Comment by kball** [comment]
Looks good to me.

**Comment by ncoden** [comment]
Thanks

**Comment by dobromir-hristov** [comment]
So if my trigger is NOT floated, I cannot horizontally align the dropdown? Why on earth would you hard code the horizontal positioning to a float class.... a simple check for a horizontal align class on dropdown after the anchor would have been enough. That way it would have still be compatible with float classes, but a user could align it to his needs without floating the trigger. Yes I know i can override the float class in my own css, but is it necessary?

**Pull request merged**
