### PR TITLE
Changed `$foundation-palette` to `$button-palette`

### LINKED ISSUE #10576: .button-group color palette
In file `.button-group.scss`, line 210, iteration should be over $button-palette instead of $foundation-palette.

https://github.com/zurb/foundation-sites/blob/373344ecdcbd29c0c00a26d98e92dfb6d99f214c/scss/components/_button-group.scss#L210

### PR DESCRIPTION
**Pull request by RudolfBos**
Fixes #10576

### CODE REVIEW

**Review by ncoden — APPROVED** [review]
Thank you @RudolfBos 👍
Welcome among the Foundation contributors ;)

**Comment by ncoden** [comment]
@RudolfBos For your next pull request, you can push your work to a dedicated branch (like `fix/use-button-palette-for-button-group-10576`. So you can continue working on your `develop` branch without polluting your pull requests.

**Comment by RudolfBos** [comment]
Thx @ncoden! Will do that next time.

**Comment by IamManchanda** [comment]
@RudolfBos You can look at https://github.com/zurb/foundation-sites/issues/10576#issuecomment-353864163 if you have any doubts for the same ;)

**Pull request merged**
