### PR TITLE
tests: run tests on latest stable and LTS releases of Node.js

### PR DESCRIPTION
**Pull request by DanielRuf**
Currently trying to run the testsuite on all Node.js versions (4 and up).

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
I think we should rather try to run on:
* Latest node versions
* All LTS https://github.com/nodejs/Release

**Comment by ncoden** [comment]
```
node_js
- "lts/*"
- "stable"
```

I did not know we could do that. That's nice :D

**Comment by DanielRuf** [comment]
> Latest node versions
> All LTS https://github.com/nodejs/Release

So 9 and ``

> I did not know we could do that. That's nice :D

Pretty well documented and many aliases =) https://github.com/creationix/nvm/blob/master/nvm.sh#L756

**Comment by ncoden** [comment]
hmmm actually this resolves only the latest stable version and the latest LTS version. We may should have a static list of stable and LTS versions we want to test.

So:
```yml
node_js:
- stable
- lts/carbon
- lts/boron
- lts/argon
```

**Comment by DanielRuf** [comment]
> - lts/argon

This is Node.js 4 ;-)

**Comment by DanielRuf** [comment]
4, 6 and 8 are LTS, 9 is stable

**Comment by DanielRuf** [comment]
And I already changed that in the last commit. Thought Travis or nvm is so clever to use all of them but `lts/*` is just the newest LTS.

**Comment by ncoden** [comment]
> This is Node.js 4 ;-)

Yes, and according to the doc:
> Your Node.js version must be 4.0 or higher.
> -- https://github.com/zurb/foundation-sites/blob/develop/README.md

**Comment by ncoden** [comment]
> And I already changed that in the last commit

I seen that just after yes ;)

**Comment by DanielRuf** [comment]
puppeteer does not work on Node.js 4 and https://github.com/zurb/foundation-sites/commit/a57cbe18376d5507ac5378f9f32622964c12bf7c

**Comment by DanielRuf** [comment]
Reference for `lts/*`: https://github.com/creationix/nvm/blob/8e6201b5b143c43f39103a7f9036dda8fd0c02c6/test/fast/Unit%20tests/mocks/nvm_make_alias%20LTS%20alias%20calls.txt

**Comment by DanielRuf** [comment]
https://travis-ci.org/zurb/foundation-sites/builds/348388271?utm_source=github_status&utm_medium=notification

**Comment by ncoden** [comment]
Yeah, puppeteer require node 6.4 (https://github.com/GoogleChrome/puppeteer/blob/master/package.json#L8)

**Pull request merged**
