### PR TITLE
Form emits `valid.fndtn.abide` when there are no validatable fields 

### LINKED ISSUE #6901: Form ought to emit `valid.fndtn.abide` when there are no validatable fields
This issue is follow-up to the original issue #6881 Abide throws an error if form has no validatable fields, and will be accompanied by a pull request within a couple hours.

The original issue #6881 is still an improvement, because prior to that Abide was simply throwing a JavaScript error in this case: **a form that hides its validatable elements before submission**

However, we identified a paradox that made it very difficult to actually implement such a form without hacking our way around Abide's blocking of the original form `submit` event.

So, the solution to the original issue #6881 was fine in that it prevented a JavaScript error. However, the failure to emit `valid.fndtn.abide` was caused by a totally separate oversight in how Abide identifies the form element to which the validation belongs.

The expected enhanced behavior would still *skip validation,* but then it would also still emit the `valid.fndtn.abide` event.

### PR DESCRIPTION
**Pull request by charneykaye**
closes #6901

### CODE REVIEW

**Comment by rafibomb** [comment]
Thanks for this! We'll be testing for merge soon.

**Comment by charneykaye** [comment]
Hiya @rafibomb please let me know if there's anything I can do here to help.

**Comment by rafibomb** [comment]
Hi - thanks for the PR! It looks like this go caught in out Foundation 6 release cycle. 

We still want this to go into Foundation 5 and we'll be pushing a patch next week. Are you able to re submit on the V5 branch so we can get it in? Thanks!

**Comment by charneykaye** [comment]
Thanks @rafibomb - created #7335 and closing this one.

**Pull request closed without merging**
