### PR TITLE
fix: check for activeElement before calling blur() on it

### LINKED ISSUE #11213: tests: failing unit tests in IE11 due to blur() being called on null / undefined
## Expected Behavior

The unit tests should successfully run in IE11

## Current Behavior

A few unit tests fail due to `blur()` being called on null / undefined.

> TypeError: Die Eigenschaft "blur" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
   at Anonymous function (js-tests.js:2340:13)

## Possible Solution

Check if `document.activeElement` is defined at all.

How to reproduce:
1. run the unit tests in IE11 by opening the generated index.html in tests/javascript

## Your Environment

- Foundation version(s) used: develop
- Browser(s) name and version(s): IE11
- Operating System and version (desktop or mobile): Windows 10

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

Replaces https://github.com/zurb/foundation-sites/pull/11214

- Closes https://github.com/zurb/foundation-sites/issues/11213

## Motivation and Context

Fixes the unit tests in IE11 on Windows 10.

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `support/*`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [x] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

## ⚠️ Require:
- #11259 test: minimize interchange debouce test race condition

### CODE REVIEW

**Comment by ncoden** [comment]
Tess are subject to race conditions with this PR (as discussed in #11214). Waiting for #11259 to merge.

**Comment by DanielRuf** [comment]
Mh, we still have the focus / blur issue on IE. Didn't we already fix this? On IE11 is is body.

https://github.com/zurb/foundation-sites/issues/11074

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11275

**Comment by DanielRuf** [comment]
Hm, event with the change Android 4.4 fails:
https://travis-ci.org/zurb/foundation-sites/jobs/392125882#L1133

**Comment by DanielRuf** [comment]
I guess their devices are too slow.

**Comment by DanielRuf** [comment]
Sigh https://travis-ci.org/zurb/foundation-sites/jobs/392135487#L1116

**Comment by ncoden** [comment]
@DanielRuf I already tried on your branch the changes with this PR https://github.com/zurb/foundation-sites/pull/11333 and it works. There's just the browserstack runner bug.

**Comment by DanielRuf** [comment]
> @DanielRuf I already tried on your branch the changes with this PR #11333 and it works. There's just the browserstack runner bug.

What about the linked lines? Firefox and Android 4.4?

**Comment by ncoden** [comment]
@DanielRuf They still happen time to time. I was only talking about the fails due to timeouts.

**Comment by ncoden** [comment]
I made some tests and this PR (with a9334ad) introduce the following error:
```
[Windows 8.1, Firefox 60.0] Error: "closes the targeted submenu" failed, uncaught exception: AssertionError: expected { Object (0, length, ...) } to be hidden (:0)
```

See https://www.travis-ci.org/ncoden/foundation-sites/jobs/392158100

With `a9334ad`, tests always fails. The same branch with `a9334ad` reverted never get this error (I ran the tests 5 times)

**Comment by DanielRuf** [comment]
> With a9334ad, tests always fails. The same branch with a9334ad never fails (I ran the tests 5 times)

And IE11 does not fail then if we revert this? Initially we needed this for IE11 and a few other browsers due to the debouncing behavior and race conditions.

Revert it if this resolves the issues.

**Comment by ncoden** [comment]
Initially we needed this because of:
> TypeError: Die Eigenschaft "blur" eines undefinierten oder Nullverweises kann nicht abgerufen werden.

But I never seen this error in our tests. So unless you can reproduce it on browserstack and send me a link I think we can close this PR.

**Comment by ncoden** [comment]
Racing conditions and tests for debouncing were resolved in others PRs.

**Pull request closed without merging**
