### PR TITLE
Correct documentation for Submit buttons

### PR DESCRIPTION
**Pull request by phpfui**
## Description
Correct documentation for 6.6 for correctly functioning submit buttons.

## Types of changes
- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by SassNinja** [comment]
@phpfui thanks for your contribution

however I don't get the purpose of this PR as it doesn't make sense to me to replace `type="button"` with `class="submit"``

what exactly is currently incorrect in your eyes?

**Comment by DanielRuf** [comment]
The problem is that we use `$.submit()` which does not work in jQuery with `type="submit"`. A `type="button"` is the same. This is a general flaw in jQuery that was never fixed.

See https://github.com/foundation/foundation-sites/issues/11935 and the linked posts and issues.

**Comment by phpfui** [comment]
Daniel is correct about the JQuery issue.  Turns out type="submit" has issues with submitting that they can't / won't fix.  See the end of the thread in the Discourse forum for complete details.  This way of coding a submit button works great where as other ways fail for a variety of reasons.

My concern is maybe there should be a dedicated section or explicit code listed for a submit button.  It is kind of hidden in the text and not very visible, but I did not want to make big changes, and this is where it seemed to fit.

Also not sure why one test is failing.  Should just be a documentation change.  In my projects, I find I often have to rerun specific tests on the same commit to get them to pass.

**Comment by DanielRuf** [comment]
> Also not sure why one test is failing.

Not a test but a complete job, this is a configuration issue with Browserstack for the browser tests on our side.

I have already pinged @joeworkman about this.

https://travis-ci.com/foundation/foundation-sites/builds/148310912

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/multiple-submit-buttons-in-version-6-6-1/1658/2

**Comment by DanielRuf** [comment]
Hi @phpfui,

please create a separate branch next time as it is an anti-pattern to push from your develop to our develop and this often breaks.

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
Thanks for your contribution to Foundation Sites @phpfui

**Comment by phpfui** [comment]
Yes I realized that after I did it. Sorry about that.

**Comment by lirael** [comment]
@DanielRuf maybe this should be added to the changelog too? I've just spent a while trying to figure out why my submit btns don't work anymore 🙃

**Comment by DanielRuf** [comment]
Hi @lirael,

good catch. I will check which release introduced this.

**Comment by DanielRuf** [comment]
Hi @lirael,

good hint. I will check which release introduced this.

**Comment by lirael** [comment]
@DanielRuf thanks! 
for me it happens when I upgrade to v6.6.0 from v6.5.3

**Comment by DanielRuf** [comment]
https://github.com/foundation/foundation-sites/commit/f237c0ffeb0d82b63410deebdd8cc9ef4943ebde

Is this sufficient regarding the submit buttons @lirael?
https://github.com/foundation/foundation-sites/releases/tag/v6.6.0

We'll refactor this in Foundation v7.

**Comment by lirael** [comment]
@DanielRuf I think `type=submit` should be removed too, to make it work. Not sure about `type=button`. 

Just for the future reference, what I figured in my tests: if a button has a `name` attr, it cannot have `type=submit`, but should have `.submit` instead. 
But maybe there are some other problems about them too.

**Comment by DanielRuf** [comment]
> @DanielRuf I think `type=submit` should be removed too, to make it work. Not sure about `type=button`.

I think it depends on the markup and what we have in the documentation. I have added the `type="submit"` part. I guess we have some corner cases there that we have to fix and rethink in v7. As long as there are workarounds and solutions it should be ok.

Sorry for the trouble and problems caused by this change.

> Just for the future reference, what I figured in my tests: if a button has _any_ `name` attr, it cannot have `type=submit`, but should have `.submit` instead.

Interesting observation, thanks for letting us know.

> But maybe there are some other problems about them too.

Not sure, these are probably issues in `jQuery.submit()`. See the **Additional Notes** section at https://api.jquery.com/submit/ (similar issues are known and marked as wontfix in jQuery for many years).

See also https://bugs.jquery.com/ticket/4652, https://github.com/jquery/jquery/issues/2321#issuecomment-102667799, https://stackoverflow.com/a/14175782/753676

**Comment by phpfui** [comment]
While this change is in the migration list, and it is explained in a callout under Basics for Buttons, it is still probably not obvious enough.  Perhaps a submit button example might help others. I know examples are the primary way I learn things. Seeing something in action is a lot faster than reading about it and having to imagine code that does that.

@DanielRuf if you think an example is a good idea, I can submit another PR, this time branched correctly!

**Comment by DanielRuf** [comment]
> @DanielRuf if you think an example is a good idea, I can submit another PR, this time branched correctly!

An example in the docs is a great idea.

**Comment by phpfui** [comment]
[https://github.com/foundation/foundation-sites/pull/12068](https://github.com/foundation/foundation-sites/pull/12068)

@DanielRuf let me know if you have other ideas for more clarity.

**Pull request merged**
