### PR TITLE
adds support for equalizeByRow - Responsive Equalizer

### PR DESCRIPTION
**Pull request by designerno1**
Responsive Equalizer
a very helpful feature for example for Block Grid or Elements that are stack on mobile but should be equalized on medium or large, but medium ist different rows to large

i make a commit with doc examples to show the features

### CODE REVIEW

**Comment by designerno1** [comment]
2. commit are docs examples but the have to be worked over.
Only to show the feature

**Comment by zurbchris** [comment]
OOOoooooohhhh WEEEeeeeeeee, that's a doozie. I'll have a look.

**Comment by designerno1** [comment]
maybe some parts can be refined, i take a deeper look tomorrow.
i wrote the feature for the old version and adapted it to the new-eq.
i have to check some parts in the new version but that's only code reduction and better code.

**Comment by zurbchris** [comment]
:open_mouth: This is hoooooooooOOOOOOTTT! Visually speaking. I haven't yet checkout out the code.

**Comment by designerno1** [comment]
i think in code:
array handling could be improved (it's little tricky in JS)
offset().top performance on each element could be faster ;-) i checked native offsetTop but this isn't really faster

**Comment by zurbchris** [comment]
Would love to merge this. I played a bit with the methods used, and while offsetTop gives some unexpected results, `el.getBoundingClientRect().top` works great.

**Comment by zurbchris** [comment]
```js
      var elOffsetTop = ~~(this.$watched[i].getBoundingClientRect().top);
```
this is pretty hot.

**Comment by zurbchris** [comment]
Switching to getBoundingClientRect and using native js Array.map shaved off a few ms in chrome console profiler, not much, but something.
I'm going to apply those changes, merge this in, and merge it to 6.1

**Comment by rafibomb** [comment]
@designerno1 Thanks for your help on the Framework! We want to mail you a Yeti shirt! Email foundation at zurb .com and we'll set you up!

**Comment by rafibomb** [comment]
@designerno1 I found your address! Sending you a shirt!

**Pull request merged**
