### PR TITLE
chore: simplify GitHub templates

### PR DESCRIPTION
**Pull request by ncoden**
## Description

Simplify the GitHub pull request and issues templates so they are easier and quicker to fill.

### Changes
- Adapt the templates to non-monospace fonts
- Add some spacing
- Reduce the number of asked questions
- Reduce the number of required checks

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- ~~I have updated the documentation accordingly to my changes (if relevant).~~
- ~~I have added tests to cover my changes (if relevant).~~
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> Adapt the templates to non-monospace fonts

Can you clarify this (what this means / solves)?

**Comment by SassNinja** [comment]
@ncoden since you're reworking the github template, what do you think about removing all checkboxes?

In particular the checklist is quite annoying imo as you usually tick all boxes anyway. A comment to remind the reporter on this should also do the job.

I really like how webpack does it when you create a new issue
https://github.com/webpack/webpack/issues

Do you think we can adapt this?

**Comment by ncoden** [comment]
> Adapt the templates to non-monospace fonts

@DanielRuf By default, GitHub use a "proportional" font, which mean that every character takes a different space according to its shape. Two lines with the same number of characters (but different) will not be aligned and will not end at the same position.

So the following examples in monospace (when using Refined Github for example):
screen shot 2018-08-21 at 21 29 20

...is actually displayed like that on GitHub vanilla:
screen shot 2018-08-21 at 21 28 52

In this pull request, I changed the way comments I displayed so they is no ending characters.

Monospace:
screen shot 2018-08-21 at 21 33 24

Proportional (not perfect but much better).
screen shot 2018-08-21 at 21 33 47

**Comment by ncoden** [comment]
> since you're reworking the github template, what do you think about removing all checkboxes?

I agree with you that it can be quite annoying for us. This is stuff we already know and we do not want to loose time filling an issue

However, I think that this stuff is very helpful to newcomers and folks that do not contribute to the Open Source on a regular basis. We had a lot of badly formatted issues/pull requests before. Not that much since we added the checklist (new issues are most of the time correctly filled now).

> A comment to remind the reporter on this should also do the job.

Sadly I don't think this is enough. People tends to be bored by long texts and recommendations when there is no interaction possible or something to fill.

I removed many items in the checklists for issues and pull requests. I think that asking the user to read CONTRIBUTING.md, follow the template, formatting its commit correctly and checking the branch he want to open the pull request on isn't too much asked.

> I really like how webpack does it when you create a new issue

Yeah I like this too. This was generated (any maybe adapted a bit) with https://www.talater.com/open-source-templates. I used it too for the old version of our templates.

**Review by DanielRuf — APPROVED** [review]

**Comment by ncoden** [comment]
@SassNinja I am merging this as this is going in the "no/less checkbox" direction. But we can continue discussing about removing them completly, I gave my arguments above.

**Pull request merged**
