### PR TITLE
Fix select focus state

### PR DESCRIPTION
**Pull request by serg0x**
I gave the dropdown select boxes the same behaviour, like the normal input fields for the good overall consistency.

### CODE REVIEW

**Comment by gakimball** [comment]
Why not select both `:hover` and `:focus`? Adding the focus state makes sense, but we'd also like to keep the hover state most likely.

**Comment by serglo** [comment]
Easy, because standard form elements also have no hover effect see http://foundation.zurb.com/docs/components/forms.html

**Comment by rafibomb** [comment]
I get the visual consistency aspect of it, but isn't a better interaction to have the visual queue on hover?

**Comment by serglo** [comment]
Than we need to add hover states to all other form elements, because right now only dropdown element has hover state.

**Comment by tdhartwick** [comment]
Thanks!

**Pull request merged**
