### PR TITLE
Global font size and rem/em calculation

### PR DESCRIPTION
**Pull request by gakimball**
This pull request addresses #7021, #7500, and others. With these changes, the base font size can be shifted up or down without affecting any `rem` or `em` based lengths, such as the `.row` width, or the widths of breakpoints.

Here are the changes:
- Removed `$rem-base`.
- `rem-calc()` references `$base-font-size` for rem calculation.
- `-zf-bp-to-em()` always uses a 16px base when calculating breakpoint widths.

Still need to figure out what migration process would be necessary.

### CODE REVIEW

**Comment by tjhiggins** [comment]
+1 Not sure about fix, but having the same problem with breakpoints being incorrect.

**Comment by jensengelmann** [comment]
I don't understand the following lines (https://github.com/zurb/foundation-sites/commit/3391c30fd72ffd69756f182f21904353c6d0b81e#diff-53036f9871421f19686387c09cc9e13cR37):

```scss
$base: $global-font-size;

@if unit($base) == '%' {
  $base: 16px;
}
```

Maybe I'm wrong, but you're checking if ```$global-font-size``` ist a percentage value and then set the base to ```16px```. What if I'm setting ```$global-font-size: 75%``` - the base for them rem-calculation should then be ```12px```.

In my opinion you have to convert the percentage value to the corresponding pixel values... someting like:

```scss
// base is 75%
@if unit($base) == '%' {
  $base:($base/100%) * 16px;
  //now base is 12px (.75 * 16)
}
````

Not tested - don't know if the syntax is right.

**Comment by gakimball** [comment]
@jensengelmann Good catch, I implemented that change: 4b718ad8da5552fb5abb1c051087d9748771b185

Last thing to do is figure out how backwards-compatible this change is.

**Comment by gakimball** [comment]
Alright, this change is totally backwards-compatible. All you'll need to do when you upgrade is move the `$global-font-size` variable above any references to `rem-calc()`, so the correct value is used.

**Pull request merged**
