### PR TITLE
Add parentLink option to drilldown

### PR DESCRIPTION
**Pull request by brettsmason**
Add parentLink option to drilldowns (false by default).
This prepends the parent link to the submenu.

### CODE REVIEW

**Comment by rafibomb** [comment]
Thanks @brettsmason! - Plenty of people looking for this feature. Are you able to clear the merge conflict so we can add it in today? We'd like this to be part of the 6.2 RC . Thanks!

**Comment by brettsmason** [comment]
Hey @rafibomb I'll see what I can do, though I might just create a new PR if that's OK (not sure on how to solve conflicts yet, still learning git!). I'll have a look in a few hours when I'm home.

**Comment by rafibomb** [comment]
Thanks Brett! Looking forward to getting this in as it will help lots of people!

**Comment by rafibomb** [comment]
Reference issue https://github.com/zurb/foundation-sites/issues/7770

**Comment by brettsmason** [comment]
@rafibomb I forgot to ask - which branch is the correct target for a PR at the moment? I've been out of the loop for a few weeks!

**Comment by rafibomb** [comment]
6.2-dev would be destination since it will go into the RC and get tested more thoroughly. Thanks!

**Comment by brettsmason** [comment]
@rafibomb I've created a new PR with the fix as it was easier for me to do, hope thats OK!
[8178](https://github.com/zurb/foundation-sites/pull/8178).

**Comment by kball** [comment]
Closed in favor of #8178

**Pull request closed without merging**
