### PR TITLE
Always prevent default on down arrow on the dropdown menu

### PR DESCRIPTION
**Pull request by rykener**
Fixes Issue #10444

### CODE REVIEW

**Comment by kball** [comment]
So if I understand this correctly, in the last-child case what will happen is $nextElement will be an empty jquery object, so that part of the code will do nothing, while the prevent default will still fire preventing the page from scrolling.

I think this makes sense, but would love to get @Owlbertz's opinion as our expert on keyboard nav and accessibility

**Comment by Owlbertz** [comment]
Can't currently pull this down and check it out, but based on the diff I'd say this makes sense.

**Comment by shonin** [comment]
That's correct @kball. I just decided it would be best to use the same logic that arrowing up uses. 

On arrow up, the `$prevElement` isn't an empty jquery object (it's the last item in the list), but that is a separate issue that is not as critical as this one.

**Comment by kball** [comment]
Great. Merged! Thank you @shonin, and congrats on first merged PR

**Pull request merged**
