### PR TITLE
[Reveal] Feature Request: Make appendTo("body") configurable #9046

### PR DESCRIPTION
**Pull request by phifa**
PR for #9046

### CODE REVIEW

**Comment by Owlbertz** [comment]
This looks very good from a functional perspective.
Maybe some @zurb/yetinauts should have a look and check if this should go into develop or in the v6.3 branch as this is is an API change, although it should be completely downwards-compatible from what I see.
Also, in order to follow coding guidelines, please substitute the `"` (double quotes) you put around the default value with `'` (single quotes).
Nonetheless, thanks for the quick action so far!

**Comment by phifa** [comment]
ok, cool. i am glad, as i am not too experienced. Does the "data" usage need to be implemented as well? Really looking forward to having this in 6.3

**Comment by Knight-Yoshi** [comment]
You need to change the `_this.options.appendTo` to `this.options.appendTo` the `_this` they are using is a variable with `this` assigned to it. That is done when `this` is used inside of a callback function, like an event. In _this_ case it's not necessary.

**Comment by Owlbertz** [comment]
@phifa upon further inspection I saw that you seem to use a (very) old version of Foundation. You are still using the `prototype` approach, which has been replaced by introducing the ES6 syntax (with Babel).
Could you please check your Foundation version number? I.e. in the `package.json` file.

**Comment by phifa** [comment]
ok, i did it again, and made sure i have the latest repo available. sorry for that. i am just getting into git: 

https://github.com/zurb/foundation-sites/pull/9094

**Comment by kball** [comment]
closing this in favor of #9094

**Pull request closed without merging**
