### PR TITLE
fix: fire Magellan update event only where there is a change

### PR DESCRIPTION
**Pull request by coreysyms**
Fix for #9068 and #10384. Fires update only where there is a change.

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
Looks good 👍, but I think the code readibility could be improved. The Magellan code is already difficult to read, let's try to not make it worst ;)

**Comment by ncoden** [comment]
@coreysyms Also, could you submit PR from a branch on your own fork, instead of the main Foundation repo ? ;)

**Comment by ncoden** [comment]
@coreysyms I fixed a bug (the event was not fired anymore when the active link were reset), and refactored the function.

@colin-marshall or @JeremyEnglert  Could you take a look at this please ?

**Comment by ncoden** [comment]
There should be no breaking changes or new features, so I plan this for `v6.4.4`.

**Comment by DanielRuf** [comment]
lgtm

**Comment by DanielRuf** [comment]
Do we still need this branch here?

**Comment by ncoden** [comment]
@DanielRuf No. Nice catch

**Pull request merged**
