### PR TITLE
the cb is missed in this._setWrapperHeight() so the current cb logic …(foundation.orbit.js)

### PR DESCRIPTION
**Pull request by simongcc**
Sorry for previous failed attempts, finally I understand how to PR it right.
Since it was already a while ago, it is related to my previous opened PR #8755 
The callback logic is being added but the callback option and parameter is missed so I am here to add it back.

### CODE REVIEW

**Comment by kball** [comment]
Looking at this, I think I understand what you're trying to accomplish, but would actually rather we fire an event so that folks using an indirect instantiation (e.g. using data attributes in the html) can still set up a listener.  Can you replace the callback option with a new event being fired at the same point in the lifecycle?

**Comment by DanielRuf** [comment]
> Can you replace the callback option with a new event being fired at the same point in the lifecycle?

Definitely a good idea.

@kball how should we name the event?

**Review by DanielRuf — CHANGES_REQUESTED** [review]
We should trigger an event to support unobstrusive and asynchronous, reactive implementations.

**Comment by kball** [comment]
This PR is stale and the requested changes were not made. Just going to close it out.

**Comment by simongcc** [comment]
@kball Sorry for having not been a while, what should I do with the stale PR?

**Comment by kball** [comment]
@simongcc no worries; the entire project has all been stale for a while, but some of the community is making a push to revive it. 

Based on the feedback from the original PR, if you'd like to pick it back up please rework it to trigger an event instead of use a callback, and then reopen/open a new PR.

**Pull request closed without merging**
