### PR TITLE
Clean up slider logic and fix bug with top end

### PR DESCRIPTION
**Pull request by kball**
Fixes issue discovered in QA with top end of slider.  Also cleans up slider logic to be more readable.

### CODE REVIEW

**Comment by brettsmason** [comment]
@kball I can confirm this fixes the issue in the QA I reported :+1:

**Comment by designerno1** [comment]
@kball 
this makes it better for drag but unusable for touch android

**Comment by kball** [comment]
@designerno1 nice catch, I'll dig into it

**Comment by kball** [comment]
@designerno1 updated and I believe it resolves on android.  Touch slider on android feels a little clunky to me but going back to the initial RC it feels clunky there too, and in 6.2.1 it was broken entirely, so I think this is good enough.  Can you try it out again?

**Comment by designerno1** [comment]
@kball 
now it works on android with touch
but jumps back on drag from top to bottom
keyboard go to top with up arrow works also fine

**Comment by kball** [comment]
Ah the jump makes sense... ok still tinkering.  The discrepancy between the real events and faked event stuff is a pain.

**Comment by kball** [comment]
@designerno1 Got another pass on this.  This feels kinda clunky, but after mucking around a bit I couldn't figure out how to do the better solution (fixing the touch util faked events), and this seems to be working now both on my android test device and the non-android browsers I've tested

**Comment by designerno1** [comment]
now works by drag
but still buggy on android swipe and touch move

**Comment by kball** [comment]
@designerno1 Was it working in those cases before?  If not, I'd like to merge this and open those as a separate issue to tackle

**Comment by designerno1** [comment]
@kball 
yeah in the v6.2.2 branch touch on vertical slider works great

**Comment by kball** [comment]
ok I'll keep pounding on it then

**Comment by kball** [comment]
@designerno1 one more fix in for an issue on android 6, but I'm not sure exactly what behavior you're seeing still on this branch that isn't there on v6.2.2.  Can you explain more what you mean by swipe as distinct from drag for the vertical slider?  Thanks

**Comment by designerno1** [comment]
@kball 
with drag i mean click and hold mouse and move
with swipe i mean touch hold and pull up
with touch i mean tap on slider to move

**Comment by designerno1** [comment]
@kball 
now it looks goog on chrome,edge,firefox, android 6
awesome

**Pull request merged**
