### PR TITLE
Make Tabs' active class names configurable

### PR DESCRIPTION
**Pull request by simshaun**
Hi,

I'm creating a tabbed interface using only the minimal syntax required for Tabs to work (foregoing the default Tabs styling). However, I need to be able to use different _active_ class names than the Tabs javascript expects.

This PR makes the _active_ class name configurable for both the tab links and tab panels.

### CODE REVIEW

**Comment by simshaun** [comment]
Note: Travis failed because it couldn't download PhantomJS.

**Comment by rafibomb** [comment]
This is a valuable PR!

**Comment by rafibomb** [comment]
Anyway you can point this to v6.3? Trying to follow a standard of point releases and features. Thanks!

**Comment by simshaun** [comment]
Opened a new PR pointed at v6.3.  https://github.com/zurb/foundation-sites/pull/9018

**Pull request closed without merging**
