### PR TITLE
Fixes #9151 - Drilldown event issue

### LINKED ISSUE #9151: [Drilldown Menu] Wrong JS events listed in Documentation
The Javascript events in the documentation for the Drilldown Menu appear to be wrong. I tried the open event, which is listed in the docs as 'open.zf.drilldownMenu', but nothing was happening when I set up a listener for it. Using 'open.zf.drilldown' however, worked as intended. This was with version 6.2.3.

### PR DESCRIPTION
**Pull request by IamManchanda**
Updated by mistake ... Correcting now!
Closes #9151

### CODE REVIEW

**Comment by rafibomb** [comment]
Not sure why we should remove the word menu, can you explain?

**Comment by IamManchanda** [comment]
See #9151 

> The event name is still open.zf.drilldownMenu in docs, and needs to be open.zf.drilldown
>
> Looks like it was fixed in f7e63fd by changing the docs title, but then the title was changed back 72844c8 for consistency. That probably reintroduced the issue.

**Comment by rafibomb** [comment]
Oh wow, the event is tied to the name in the docs? We will likely want to decouple that in the future.

Sounds good for now - thanks @IamManchanda !!

**Comment by IamManchanda** [comment]
Then again... this shows why good commit messages are very important!

Your welcome @rafibomb ... please request you to deploy it soon also... thank you

Thanks @shready for helping us figure it out... thumbs up!

**Pull request merged**
