### PR TITLE
chore: update eslint/gulp-eslint to v4

### PR DESCRIPTION
**Pull request by colin-marshall**
I updated my global eslint to v4 and started seeing this error from SublimeLinter:
`Unexpected top-level property "ecmaVersion"`

Caused by this line:
https://github.com/zurb/foundation-sites/blob/develop/.eslintrc#L2

That setting is already present and in the correct place on this line:
https://github.com/zurb/foundation-sites/blob/develop/.eslintrc#L20

Figured I might as well update eslint/gulp-eslint for foundation-sites while I was at it.

### CODE REVIEW

**Comment by ncoden** [comment]
I'm testing it.
@colin-marshall Did you checked for breaking changes between v3 and v4 ?

**Review by ncoden — APPROVED** [review]
See https://www.diffchecker.com/SLxCxCEC

So LGTM. There's still a lot of work to do (but I don't think it's a good idea to get into it now), but not more.

**Comment by colin-marshall** [comment]
@ncoden Are you talking about all the warnings and the errors that we need to take care of (Or adjust the lint rules to ignore)?

**Comment by ncoden** [comment]
Yes. In theory we should take care of them, but right now (at the end of v6) it is too much work for too small benefits.

**Comment by ncoden** [comment]
On v7 we should use Prettier with the Github integrations :)

**Pull request merged**
