### PR TITLE
chore: adjust text in issue templates

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

Replace `pull request` with `issue report`.

- Closes 

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by SassNinja** [comment]
I've restarted the failed travis jobs

However I think you've to merge the latest develop branch into this branch (node 6 shouldn't be tested anymore)

**Comment by DanielRuf** [comment]
I'll rebase.

**Review by SassNinja — APPROVED** [review]
👍

**Comment by webuxr** [comment]
Any reason this has not yet been merged and closed?

**Comment by SassNinja** [comment]
@webuxr no reason

I simply wasn't aware someone is waiting for this minor text adjustment 😄 

I've merged it now

**Pull request merged**
