### PR TITLE
[slider] 2-way binding to input

### PR DESCRIPTION
**Pull request by sdhull**
- If you want to have a number input to show the value of the slider, changing the value of the input is reflected in slider position
- Minor fix for inner slider style (inherit rounded corners)

### CODE REVIEW

**Comment by sdhull** [comment]
So the CSS fix addresses this issue:
screen shot 2015-03-03 at 9 51 11 pm

**Comment by sdhull** [comment]
And then the js changes enable this:

changing input changes slider

**Comment by sdhull** [comment]
One thing to note is that this call `slider.foundation("slider", "set_value", $(this).val());` does not perform very well. I couldn't figure out a better way to do it though.  Just calling `self.set_value` updates the values of all the sliders on the page.

**Comment by rgarver** [comment]
:+1:

**Comment by scudco** [comment]
:+1:

**Comment by sdhull** [comment]
Sigh. I have to resolve some conflicts. But I'm not gonna bother unless a maintainer indicates some interest. Anybody home?

**Comment by rafibomb** [comment]
Yup, we're merging in PR's this week. Can you resolve the merge conflicts so we can add it in? Thanks!

**Comment by sdhull** [comment]
Done!

**Comment by rafibomb** [comment]
Steve, great work! Email foundation at zurb .com so we can mail you some Yeti stickers!

**Pull request merged**
