### PR TITLE
Adding a top/bottom functionality to zurb offcanvas with push,overlap and submenu

### PR DESCRIPTION
**Pull request by tomsah**
You can see the adding functionality in action on this demo page

http://tomsah.co.uk/offcanvas-demo/

Please let me know if any improvement is needed or more need to be done.

very best

### CODE REVIEW

**Comment by gakimball** [comment]
This looks really nice! How does it work with the multi-level menu?

**Comment by rafibomb** [comment]
This really cool! I'm going to pull this in. We can add the documentation. 

The top and bottom menu's don't work with the multi-level feature. Is this something you can tackle?

**Comment by rafibomb** [comment]
I added this to the docs - https://github.com/zurb/foundation/commit/f5670747c6525858a475e48239b21c206bbd09bc

**Comment by tomsah** [comment]
Hello Zurb Team,

I have send the first draft for the top and bottom off canvas and i am
really happy to see it live.
I can see you guys did improved it a lot too, good work!!!!

I am sorry I could not help more to fix sub menu and documentation
but I was working on a big Drupal site using foundation theme and it took
all of my time. (I will send you the link of the site as soon as it is
finish.)

i was wondering if there is anyway to get a recommendation from you guys on
linked in
https://uk.linkedin.com/pub/thomas-salah/54/17a/611

or any sort of justification that i participate to Zurb project.

This will be great for my curriculum as a junior front end to carry on.

Many thanks for taking my code and make it better.
I am looking forward to help you more in the very near future.

Thomas

**Comment by rafibomb** [comment]
@tomsah Thanks for this great PR! We want you to be part of the Foundation 6 private release team. Email rafi at zurb .com to be part of it!

**Pull request merged**
