### PR TITLE
additions for vertical menu and top icons

### PR DESCRIPTION
**Pull request by DaSchTour**
Make combination of vertical menu and top icons work
added border and background hover

### CODE REVIEW

**Comment by rafibomb** [comment]
This looks good - is there a test case we can add for this to make it stays fixed? Any issue to reference?

**Comment by rafibomb** [comment]
Since there are new variables and it will need a migration, can you please point this to the v6.3 branch? We'll merge from there, thanks!

**Comment by DaSchTour** [comment]
Is there any simple way to make this PR point to 6.3? Or do I need to create a new branch and a new PR?

**Comment by andycochran** [comment]
It's probably easiest to check out `v6.3`, make a new branch, redo the work (sorry), and submit a new PR.

**Comment by DaSchTour** [comment]
new PR #8723

**Pull request closed without merging**
