### PR TITLE
Fixed deploy:dist and deploy:plugins tasks

### PR DESCRIPTION
**Pull request by imabdulsal**
Fixed the gulp tasks: `deploy:dist` and `deploy:plugins`, so the output will be:
- `dist/`: Compiled files.
  - `css/`: Compiled CSS files. Includes minified and unminified files.
  - `js/`: Concatenated JavaScript files. Includes minified and unminified files.
    - `plugins/`: Standalone JavaScript plugins.

Look at this for more details #8863 
### Note :exclamation:

This PR is a replacement for that PR #8862

### CODE REVIEW

**Comment by abdullahsalem** [comment]
Hi @rafibomb ,
In this merged PR #8863, I added the `plugins/` folder to the **Package Content** section, in the **Installation** [page] (http://foundation.zurb.com/sites/docs/installation.html#package-contents). 
And in this new PR, I fixed these deployment tasks: `deploy:dist` and `deploy:plugins`, to make the `dist` folder exactly looks like what has been written in the **Package Content**.

So at the end, both **Package Content** and `dist` **folder** should look like:
- `dist/`: Compiled files.
  - `css/`: Compiled CSS files. Includes minified and unminified files.
  - `js/`: Concatenated JavaScript files. Includes minified and unminified files.
    - `plugins/`: Standalone JavaScript plugins.

**Comment by abdullahsalem** [comment]
To see the correct results, you have to run these tasks:
- `build`
- `deploy:dist`
- `deploy:plugins`

Otherwise, I think you probably cannot figure out the changes.

**Review by ncoden — APPROVED** [review]

**Comment by kball** [comment]
Seems good to me, but we'll probably want to write a migration note upon release.

**Comment by jwatkin** [comment]
The Basic template for v6.3.0-rc1 isn't completely built by default following a CLI "foundation new" command. The css folder is missing. The index.html won't have working styles out of the box. After issuing a "foundation build" command, the css folder is generated and the index.html works. However, there is no "dist" directory as referenced in the latest release notes. Instead, the css and js folders are installed at the root level of the project as in prior versions. This was installed via npm on Windows 7.

**Comment by kball** [comment]
@jwatkin thanks for trying this out!  I don't think we're going to have a project level "dist" folder inside the templates, this is the framework itself... For trying the basic template, can you try out this branch (not yet merged - we're still tweaking some final stuff in 6.3): https://github.com/zurb/foundation-sites-template/tree/v6.3

**Pull request merged**
