### PR TITLE
Reveal space close

### PR DESCRIPTION
**Pull request by Owlbertz**
Addresses #9782.

Refactored the component to not use special keyboard listening for opening and closing.
Normal event triggering with `click` event being emitted using space and enter is used now.
Added test for clicking close button.

Asking for some feedback as I removed the whole special keyboard handling for enter and space... @kball @jmsfwk

### CODE REVIEW

**Comment by kball** [comment]
Checking out this branch, what I'm seeing is that now following the behavior in #9782 (open reveal with close button, tab to close button, hit space) what happens now is that the modal closes (good!) but I've lost focus, in fact my keyboard focus appears to be nowhere and I'm unable to navigate with the keyboard.

**Comment by Owlbertz** [comment]
That's correct, I missed the part where focus should be moved back to the anchor when the modal is closed.
I came up with a solution by simply moving focus back to the anchor within `close()`, but that will cause the outline to show - which I know will annoy most people when using a mouse.

My question is now on how to progress with that. In my opinion there are these options:
- Check with JavaScript and what input if the focus should be moved to the anchor. However, what is the default case if what input is not present?
- Always move back focus on close and disable outline for links like we do for buttons already via CSS:
```CSS
 [data-whatinput='mouse'] button {
    outline: 0; }
```
- Use buttons in the docs as anchors to encourage correct usage here. As the trigger does not lead to another page, using a button instead would be semantically correct imho. This way the existing CSS (see above) would apply when always setting back focus on `close()`.

I prefer the last suggestion.

**Comment by kball** [comment]
@Owlbertz I don't see any reason not to go with the last suggestion. Go for it!

**Comment by Owlbertz** [comment]
@kball I updated the PR.

**Comment by kball** [comment]
Beautiful, works like a charm!

**Pull request merged**
