### PR TITLE
Simplify expanded menus

### LINKED ISSUE #7192: Simplify expanded menus
Expanded menus are using quantity queries to define the item widths. This generates a lot of unnecessary CSS output. There is no need to define a width if table-layout: fixed is used.

Here’s a little demo: http://codepen.io/anon/pen/zvQXQq

### PR DESCRIPTION
**Pull request by slavanga**
Fixes #7192

### CODE REVIEW

**Comment by andycochran** [comment]
Why `table-layout: fixed` instead of `auto`?

**Comment by slavanga** [comment]
Because the auto-width mixin will output a large amount of unneeded CSS.
See: https://github.com/zurb/foundation-sites/blob/develop/dist/foundation.css#L2279-L2293

Setting ```table-layout: fixed``` will equalize the items just as well.

**Comment by gakimball** [comment]
@slavanga Thanks for putting this together! What browsers were you able to test in?

**Comment by gakimball** [comment]
Also, we use the auto layout mixin on button groups as well, if you're interested in implementing it there as well.

**Comment by andycochran** [comment]
Sorry, I was confused (was thinking about inline menus). :+1:

**Comment by slavanga** [comment]
@gakimball This method is basically supported in every browser that can handle table display ([caniuse] (http://caniuse.com/#feat=css-table))

**Pull request merged**
