### PR TITLE
Fix scrolling issue with reveal on ios

### PR DESCRIPTION
**Pull request by kball**
Fixes https://github.com/zurb/foundation-sites/issues/8628 and https://github.com/zurb/foundation-sites/issues/7548

### CODE REVIEW

**Comment by kball** [comment]
@zurb/yetinauts anyone else with an ios device to test that can verify this and merge?

**Comment by designerno1** [comment]
LGTM
Tested on my DEV Ipad 1

**Comment by Owlbertz** [comment]
I checked with an iPhone 5 with the following results:

The close button's position is somewhat odd when there is a large heading:
image1

Scrolling inside the modal works much better now, but there is a small issue; the modal itself can be scrolled down by about 50px:

img_1432

**Comment by kball** [comment]
@Owlbertz I could not find a way to disable the slight 'bounce' amount of scroll in the browser, only the general scroll... based on your feedback and @designerno1's I'm going to call this good enough because it moves the ball forward, though it would be nice to do further refinement.

**Pull request merged**
