### PR TITLE
Add arrow color variables to menu components

### PR DESCRIPTION
**Pull request by brettsmason**
Adds arrow color variables to dropdown menu, drilldown and accordion menu. I recently tried to change the arrow colors in a recent project but found I wasn't able to, hence this!

### CODE REVIEW

**Comment by zurbchris** [comment]
I like this idea @gakimball what do you think?

**Comment by gakimball** [comment]
I figured this would be requested eventually, thanks for putting it together!

Can you resolve the merge conflicts?

**Comment by brettsmason** [comment]
@gakimball Any pointers on how to do that? Sorry I'm pretty new to using Git and haven't worked out how to do that yet...

**Comment by gakimball** [comment]
In the folder of your Foundation fork, run this:

```bash
# Adds a remote reference to the official repo
git remote add foundation https://github.com/zurb/foundation-sites.git

# Downloads references to branches
git fetch foundation

# Merge the "develop" branch of Foundation into your work
git merge foundation/develop
```

I *think* that works.

**Comment by brettsmason** [comment]
thanks @gakimball I hope I've done that correctly! This and [7514](https://github.com/zurb/foundation-sites/pull/7514) will be a big help in my current project :smiley:

**Comment by gakimball** [comment]
@brettdewoody Yep! Now I can merge it automatically, thanks :)

**Pull request merged**
