### PR TITLE
Changed the switch and paddle dimensions to be fully dynamic.

### PR DESCRIPTION
**Pull request by imabdulsal**
This PR contains the following major changes:
- Changed the switch `width`, paddle `width` and paddle `left` to be dynamic.(1)
- Fixed the initial value of the paddle's `top` and `left` properties.(2)
- Removed the `switch-size` mixin's parameters: `$width` and `$paddle-width`.(3)
- Changed the `switch-size` mixin's parameter: `$height` to `$switch-height`. (4)

(1)
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR83
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR84
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR85
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR86
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR171
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR172
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR173
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR174

(2)
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR114
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR115

(3)
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acL164
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acL166

(4)
https://github.com/abdullahsalem/foundation-sites/commit/53c81217fd92eda1cab9b955696955824bd336d5#diff-aac94c109452cecf4dabe6b7d26702acR167

### CODE REVIEW

**Comment by kball** [comment]
@andycochran or @brettsmason can you take a look at this?

**Comment by andycochran** [comment]
😍  This is really great! Only one note I can think of:  `$paddle-left-active` isn't semantic. Would something like `$paddle-active-offest` be better?

**Comment by abdullahsalem** [comment]
You're right, @andycochran! That would be more semantic and generic.
Done!

**Comment by kball** [comment]
Merged!  Were there any open issues this addressed?

**Comment by abdullahsalem** [comment]
@kball There was only this PR #8804 that guided me to the issue.

**Pull request merged**
