### PR TITLE
Fix "media-object-section" mixin

### PR DESCRIPTION
**Pull request by R4c00n**
Fix `media-object-section` mixin in order to work when compiling with
Compass.

### CODE REVIEW

**Comment by tjhiggins** [comment]
+1

**Comment by gakimball** [comment]
Closing in favor of #7349 which is a slightly cleaner solution.

**Comment by IllusionPerdu** [comment]
@gakimball the  https://github.com/zurb/foundation-sites/pull/7349 generate this css
```css
  .media-object-section:last-child:not( + &:first-child) {
```
this genrate the good css

**Comment by R4c00n** [comment]
@gakimball PR #7349 is causing a bug that was fixed a few days ago. Therefore the $selector variable was introduced in #7270, but it was used a little wrong. This PR #7346 is fixing the issue by wrapping the Variable in #{}, like it it is done multiple times in the foundation core.

**Pull request closed without merging**
