### PR TITLE
[Docs Update 2017] Kitchen Sink - Codepen's

### PR DESCRIPTION
**Pull request by IamManchanda**
Apart from PR, 
Here are the Codepen's for Review!

- [x] Abide - https://codepen.io/IamManchanda/pen/qmoKbK?editors=1000
- [x] Accordion - https://codepen.io/IamManchanda/pen/WjzKqa?editors=1000
- [x] Accordion Menu - https://codepen.io/IamManchanda/pen/XREPVK?editors=1000
- [x] Badge - https://codepen.io/IamManchanda/pen/JNvKZj?editors=1000
- [x] Breadcrumbs - https://codepen.io/IamManchanda/pen/MmGeMx?editors=1000
- [x] Button - https://codepen.io/IamManchanda/pen/ybjagd?editors=1000
- [x] Callout - https://codepen.io/IamManchanda/pen/XRqjxj?editors=1000
- [x] Close Button - https://codepen.io/IamManchanda/pen/dWepJz?editors=1000
- [x] Drilldown Menu - https://codepen.io/IamManchanda/pen/mmLrZz?editors=1000
- [x] Dropdown Menu - https://codepen.io/IamManchanda/pen/jmxVPP?editors=1000
- [x] Dropdown Pane - https://codepen.io/IamManchanda/pen/QvrGGj?editors=1000
- [x] Equalizer - https://codepen.io/IamManchanda/pen/mmLBEa?editors=1000
- [x] Flex Grid - http://codepen.io/ZURBFoundation/pen/dWmVax?editors=1000
- [x] Responsive Embed - https://codepen.io/IamManchanda/pen/MmGEbb?editors=1000
- [x] Float Classes - https://codepen.io/IamManchanda/pen/zwjEPP?editors=1000
- [x] Forms - https://codepen.io/IamManchanda/pen/jmxGGr?editors=1000
- [x] Grid - https://codepen.io/IamManchanda/pen/rmvEBJ?editors=1100
- [x] Interchange - https://codepen.io/IamManchanda/pen/xdjXYj?editors=1000
- [x] Label - https://codepen.io/IamManchanda/pen/VbxMXq?editors=1000
- [x] Magellan - https://codepen.io/IamManchanda/pen/MmGEXo?editors=1100
- [x] Media Object - https://codepen.io/IamManchanda/pen/NjMaEr?editors=1000
- [x] Menu - https://codepen.io/IamManchanda/pen/bWMMzZ?editors=1000
- [x] Off-canvas - https://codepen.io/IamManchanda/pen/oWdrLR?editors=1000
- [x] Orbit - https://codepen.io/IamManchanda/pen/zwjjgN?editors=1100
- [x] Pagination - https://codepen.io/IamManchanda/pen/BRxVmB?editors=1000
- [x] Progress Bar - https://codepen.io/IamManchanda/pen/YVLvvB?editors=1000
- [x] Responsive Menu - https://codepen.io/IamManchanda/pen/qmYKgJ?editors=1100
- [x] Responsive Toggle - https://codepen.io/IamManchanda/pen/LymroM?editors=1000
- [x] Reveal - https://codepen.io/IamManchanda/pen/RVyBPw?editors=1000
- [x] Slider - https://codepen.io/IamManchanda/pen/xdjJVm?editors=1000
- [x] Sticky - https://codepen.io/IamManchanda/pen/ZKodJR?editors=1000
- [x] Switch - https://codepen.io/IamManchanda/pen/dWejpx?editors=1000
- [x] Table - https://codepen.io/IamManchanda/pen/eWrjQx?editors=1000
- [x] Tabs - https://codepen.io/IamManchanda/pen/qmYygE?editors=1000
- [x] Thumbnail - https://codepen.io/IamManchanda/pen/EmLexY?editors=1000
- [x] Title Bar - https://codepen.io/IamManchanda/pen/qmYMZZ?editors=1100
- [x] Toggler - https://codepen.io/IamManchanda/pen/LymJLb?editors=1000
- [x] Tooltip - https://codepen.io/IamManchanda/pen/pPVOdm?editors=1100
- [x] Top Bar - https://codepen.io/IamManchanda/pen/eWrwKP?editors=1000
- [x] Visibility Classes - https://codepen.io/IamManchanda/pen/vmjqVG?editors=1100

### CODE REVIEW

**Comment by IamManchanda** [comment]
Looping Rafi also for review!

**Comment by kball** [comment]
These are looking good... for the abide one I would put the `data-abide-error` inside the row/column so it's contained by the grid.

Accordion menu doesn't look like it's laying out properly... (submenus breaking out of the column) I suspect it is a flex mode bug, I'd file that as a bug and replace this example with a float grid one.

**Comment by IamManchanda** [comment]
@rafibomb ..... As advised by you.... i have added the video codepen container .... Did i did it right way .... KIndly check ??

**Comment by kball** [comment]
Looks like the right way. Thanks @IamManchanda!

**Comment by IamManchanda** [comment]
Just to be on the safer side (#10025) .... I have added all the navigation things on float grid instead of flexbox... hope that's ohk ??

**Comment by IamManchanda** [comment]
This is done @kball @rafibomb .... I have added the details also. Please review the PR and the codepens!

**Pull request merged**
