### PR TITLE
feat: add z-index to the Close Button

### PR DESCRIPTION
**Pull request by ncoden**
## Description

We cannot ensure the Close Button to always be on top of others elements. This pull request add a `z-index` of `10` to the Close Button, as well as the `$closebutton-z-index` setting to customize it.

- Related to https://github.com/zurb/foundation-sites/issues/11544

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- ~~I have added tests to cover my changes (if relevant).~~

### CODE REVIEW

**Comment by SassNinja** [comment]
@ncoden you haven't add the new variable to the `_settings.scss` – I think it should be updated as well, shouldn't it?

**Comment by ncoden** [comment]
@DanielRuf `_settings.scss` is automatically generated at each release

**Comment by DanielRuf** [comment]
> @DanielRuf `_settings.scss` is automatically generated at each release

Wrong person ;-) And I know this ;-)

**Comment by SassNinja** [comment]
> `_settings.scss` is automatically generated at each release

my bad, then everything fine 👍

**Pull request merged**
