### PR TITLE
Change radius of input-groups to use $input-radius

### PR DESCRIPTION
**Pull request by DaSchTour**
I think this is a way better solution. I don't think that there are many users that would like to have different radius on input than on input-groups.

### CODE REVIEW

**Comment by rafibomb** [comment]
That's a good point - like it!

**Comment by rafibomb** [comment]
Restarting travis for merge

**Comment by rafibomb** [comment]
Since this is a "breaking change" - can you point the PR to branch `v6.3`? We're keeping that for features or things that need migration.

**Comment by DaSchTour** [comment]
New PR #9116

**Pull request closed without merging**
