### PR TITLE
chore: remove deprecated mixins

### PR DESCRIPTION
**Pull request by DanielRuf**
`$responsive-embed-ratio`, `foundation-flex-video` and `flex-video` are deprecated and should be already removed in 6.4.

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
I guess you can also remove `grid-column-uncollapse` and `grid-col-uncollapse`. I added their deprecation warnings 2 years ago 😢.

**Comment by DanielRuf** [comment]
Ok, will do so later. In this and change the title or in a separate PR?

**Comment by ncoden** [comment]
It's simpler and more appropriate there to change the title: that's the same type of change and for the same reasons.

**Comment by DanielRuf** [comment]
Sorry, forgot to do it at work.

**Review by ncoden — APPROVED** [review]

**Comment by DanielRuf** [comment]
> https://travis-ci.org/zurb/foundation-sites/jobs/357814088#L2987

Did someone change the access to Browserstack? Currently the tests fail due to this.

**Comment by ncoden** [comment]
@DanielRuf The access key changed. I'm waiting for @rafibomb to get access to a new key, and I'm working on removing the key from the repo.

**Comment by ncoden** [comment]
@DanielRuf I'm priotizing bug fixs and tests for `v6.5.0`, keeping new features for later. Could you please take a look at the last PRs without reviews ?

**Pull request merged**
