### PR TITLE
Add updateHistory option to magellan

### PR DESCRIPTION
**Pull request by jfurler**
https://github.com/zurb/foundation-sites/issues/10832

### CODE REVIEW

**Comment by ncoden** [comment]
Thank you @jfurler for the PR.

It makes me think about _why_ we currently use `pushState` instead of `replaceState`. I found no reasons to support this. Actually, I found a lot of reasons why we should **not** use `pushState` and even discourage.
* Scrolling on the page is a __passive__ interaction. We do not expect it to be recorded or to have side-effects (others than loading things).
* Taking a quick look to the entire page may result in being locked in 10/15/20 history states.

So I disabled `updateHistory` by default, and added some documentation.

**Comment by Owlbertz** [comment]
I think it is good that we have an option to switch between `replaceState()` and `pushState()`.
While you are right that `replaceState()` would most likely be the preferred option, I can imagine huge one-paged websites that tend to have different section with sub-page character, so removing this option might be wrong. However, I would be ok with making `updateState()` the default option.

**Comment by ncoden** [comment]
@Owlbertz You mean `replaceState()` instead of `updateState()`, right ?

**Comment by Owlbertz** [comment]
Uhm, yes!

**Comment by ncoden** [comment]
Ok. So we can merge this ?
There will be a warning in the release notes.

**Comment by Owlbertz** [comment]
I haven't pulled this down, but codewise it looks ok. Only thing I have to mention is that feature detection is only done for `window.history.pushState()` and never for `window.history.replaceState()` - but I assume that the existence of the former also gives information of the latter.

**Comment by jfurler** [comment]
@Owlbertz I copied the logic from the "reveal" module, so yeah I just assumed the check was safe.

I only made `updateHistory` true by default to avoid a change in behaviour, but if you guys are happy with default false then that's fine with me :)

**Pull request merged**
