### PR TITLE
fix: trigger reflow / layout thrashing - closes #11943

### LINKED ISSUE #11943: Reveal animation in doesn't work in 6.6.1
## What should happen?

Reveal opening should be animation with animation that set in a data attribute.

## What happens instead?

Only reveal closing is animated. 

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

https://jsfiddle.net/fxrwdvbe/ - 6.6.0 works
https://jsfiddle.net/L9tvkg07/ - 6.6.1 doesn't work

## Your Environment

- Foundation version(s) used: 6.6.1
- Browser(s) name and version(s): Chrome 78.0.3904.108
- Device, Operating System and version: Win 10 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This fixes #11943. Unfortunately I was not aware of the effect by the line that I have removed which is needed to trigger a reflow / layout thrashing. See https://gist.github.com/paulirish/5d52fb081b3570c81e3a

- Closes #11943

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/orbit-slider-breaks/75/4

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/orbit-slider-breaks/75/11

**Review by joeworkman — APPROVED** [review]
Good call. I did some reading on this and found this good article as well ... https://medium.com/better-programming/how-to-restart-a-css-animation-with-javascript-and-what-is-the-dom-reflow-a86e8b6df00f

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/megamenu-byrafi-doesnt-work-properly-after-update/1872/2

**Comment by m-vo** [comment]
Is this going to be released anytime soon? 

The orbit slider is currently unusable (slides getting stuck after a few interactions). I can confirm that this PR fixes the issue.

**Comment by SimonMayerhofer** [comment]
@m-vo have a look at [patch-package](https://www.npmjs.com/package/patch-package). It's easy to add that fix with that until a new version of foundation is released.

**Comment by DanielRuf** [comment]
Exactly. @joeworkman can you cut a new release?

**Comment by DanielRuf** [comment]
Also see https://github.com/foundation/foundation-sites/pull/11944.patch

**Comment by joeworkman** [comment]
Yes. I will work on getting a release out the door today. I will do a quick once over for low hanging fruit to get in there as well.

**Pull request merged**
