### PR TITLE
Set toggle button "title" to submenuToggleText

### PR DESCRIPTION
**Pull request by danbrellis**
When a user hovers over the toggle button, there should be a title attribute to indicate what will happen if they click the button. Adds a "title" attribute to the toggle button set to "_this.options.submenuToggleText"

### CODE REVIEW

**Review by IamManchanda — APPROVED** [review]
LGTM but a SEO guy might think different ... 

cc @rafibomb @kball !

**Comment by kball** [comment]
Given that the text is already visible *within* the button I'm not understanding the value of adding the title attribute, can you clarify?

**Comment by danbrellis** [comment]
The text inside the button is wrapper in a `span.submenu-toggle-text`, which, according to /scss/components/_accordion-menu.scss includes the `element-invisible` mixin. So, on most screens, that text is not visible.

**Comment by kball** [comment]
Got it. Sounds good, merging. Thanks @danbrellis! And Congrats on first contribution!

**Pull request merged**
