### PR TITLE
Magellan issue #7308 bug fix

### PR DESCRIPTION
**Pull request by rawiki**
Modified function _updateActive() to stop first magellan menu item being rendered active before it reaches anchor point. Scrolling above the anchor point will also remove any active classes. If someone can guide me in writing a test I'll be happy to do that.

### CODE REVIEW

**Comment by rafibomb** [comment]
@colin-marshall Are you able to check this one out?

**Comment by andycochran** [comment]
Nice, @rawiki! Here's the [Visual Regression Tests](https://github.com/zurb/foundation-sites/wiki/Testing-Guide#visual-regression-tests) how-to. 

Does this PR help with any other [Magellan bugs](https://github.com/zurb/foundation-sites/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20magellan) besides #7308?

**Comment by rawiki** [comment]
Thanks @andycochran, my first free day in a while so sorry for the delay. I've added the visual test. This PR is specifically for the #7308 bug.

**Comment by kball** [comment]
@colin-marshall or @Owlbertz can either of you take a look at this?  Thanks

**Comment by Owlbertz** [comment]
I think I can get into it by end of the week.

**Review by Owlbertz — CHANGES_REQUESTED** [review]
Looks good from a bug-fix perspective.
Unfortunately it will break the script if `options-deepLinking` is set to true (see https://github.com/zurb/foundation-sites/pull/8949/files#diff-7582d2bf8d15b4b929dca7bfe59cee46R145).

Also dist files have been modified, which should not be the case for PRs.

**Comment by kball** [comment]
@rawiki can you take a look at the change request by @Owlbertz?  I'd love to merge this for 6.2.4 but we're getting close to the cutoff for that.

**Comment by rawiki** [comment]
Hi, @kball sure, I'll have time after Friday.

**Comment by kball** [comment]
@rawiki did you by chance get to look at this?  Would love to get it merged.  Thanks!

**Comment by rawiki** [comment]
@kball I've just got around to it, been so busy with work. I've submitted a new pull request with only the js and visual test file updated. This now works with deep linking. 

- Magellan issue #7308 - deep linking support #9243

**Pull request closed without merging**
