### PR TITLE
Remove extraneous reference to 'girl!' in Foundation Zurb Template. Fixes #10663. 

### LINKED ISSUE #10663: Suggestion: Remove throwaway reference to "girl!" in Foundation Zurb Template
I am a brand-new Foundation user giving it a go for the first time. I came here because I wanted to note the double-take I did upon initially spotting this section on the default Foundation Zurb Template that's generated when you spin up a new project (and that repo said this repo is the right place to file issues). 

screen shot 2017-09-19 at 1 30 30 pm

I understand that this is just meant to be a "light" and "fun" heading, but... none of the other headings have this "light" and "fun" "narrator" tone, they are simply declarative. I don't really see much use for this throwaway reference and can only see it doing inadvertent harm. I'd be happy to file a PR to fix it or to go deeper into why I feel that way depending on the response this issue receives. Thanks.

### PR DESCRIPTION
**Pull request by ajpiano**
As per @kball. Thanks!

### CODE REVIEW

**Comment by ajpiano** [comment]
@rafibomb Another contributor (@bkall) said they would happily accept this fix in the linked issue #10663. Please let me know if there is an issue with the PR otherwise this seems like overzealous triage.

**Comment by IamManchanda** [comment]
Its @kball :p

**Comment by IamManchanda** [comment]
Guys to be honest 
I don't feel anything bad in this phrase.

**Comment by ajpiano** [comment]
Is it helping? Do any of the other headings on the `customizer/index.html` make any reference to any people whatsoever? Does a mention of a heretofore unaddressed "girl" in any way make it clearer that there are a lot of Zurb components? 

I certainly don't think that the original inclusion had any malicious or "bad" intent, but I don't really see the reasoning in insisting that it remain in perpetuity just because it's already there.

**Comment by IamManchanda** [comment]
It's there from starting actually!

**Comment by ajpiano** [comment]
How is that relevant?

**Comment by SassNinja** [comment]
I share the opinion of @IamManchanda because I don't see anything negative in the `girl` either but a funny comment.

I think most developers know funny code comments (in particular in large projects).

Personally I don't care if some dummy content is not consistent unless it's not production code or insulting. That `girl` doesn't make any difference in understanding the framework and I'm pretty sure almost no one will abandon foundation because of it.

However, I guess this discussion takes more time than this change is worth and since @kball has agreed to it I don't see a problem in removing the `girl`.

Maybe @rafibomb can explain why he closed this PR?

**Comment by ajpiano** [comment]
From a purely editorial standpoint, all of the copy on this page addresses the developer in the second person. If the conceit is that this header is also addressing the developer, what is the point of bringing up the developer's gender? If the conceit is that this header is just making a reference to a particular idiomatic usage of "girl!" as it is used by different groups of people, I don't understand how reference makes sense given the tone of the rest of the page. 

I am about to go to bed, but at the risk of ripping off a scab just as the wound appears to be healing, I would posit that you've helped me make my point. There is nothing negative in the word "girl." What's negative is promulgating the notion that references to women in software projects are intended to be "funny."

**Comment by ajpiano** [comment]
It's surely not my intent to stir up a whole mess here either and as you also said, it has no impact on users and really can only help with consistency and being a bit more inclusive. As far as I can tell the only thing missing for consistency's sake is an exlcamation mark, which I will push momentarily :)

**Comment by kball** [comment]
So... I agree on with @ajpiano on this one - I think that while for many this is going to be innocuous, it can still come off as propagating the "brogrammer" meme, which to me is extremely harmful.  I would reopen this except github is not letting me do so due to the force push.

@rafibomb are you strongly opinionated on this and want to make an argument for the `girl!` example? Otherwise I'm inclined to cherry-pick this commit in and make it happen.

**Pull request closed without merging**
