### PR TITLE
🚀  Release v6.5.0

### PR DESCRIPTION
**Pull request by ncoden**
# Foundation v6.5.0

foundation-release-6-5-0

It's happening! Foundation 6.5.0 is out now and is ready for production use! This release is based on `v6.5.0-rc.4` and simply provides additional fixes in the documentation and an improved test flow.

### Note about this pull request
As this version was built to have the best compatibility with `v6.4.4-rc1`, we used a dedicated branch and manually picked safe changes from the development branch `develop`, excluding API evolutions and breaking changes. These imported changes are the `Use pull request #xxx` commits you can see in this pull request. Development will continue on `develop` and will lead to a future release with all changes, including new features and breaking changes.

### Release Checklist
- [x] Bump versions
- [x] Update lockfiles
- [x] Update dist files
- [x] ~~Update SCSS settings file~~
▾
- [x] Update documentation
▾
- [x] Prepare release for npm
- [x] Prepare release for Composer
- [x] Prepare release for Rails
  * ⚠️  Must be published on https://github.com/zurb/foundation-rails
- [x] Prepare release for Meteor
  * ⚠️  Must be published before the Git release for `.versions`
- [x] Prepare release for NuGet
  * ⚠️  Must be published with https://www.npmjs.com/package/nuget-publish
▾
- [x] Released!

## Changes from [v6.5.0-rc.4](https://github.com/zurb/foundation-sites/releases/tag/v6.5.0-rc.4)

* 📖  <samp>#11545</samp> - Fix plugins instantiation examples in Javascript docs (@ncoden)
* 📖  <samp>#11548</samp> - Fix "Converts" misspelling in `-zf-bp-serialize` docs (@joshwhatk)
* 📖  <samp>#11549</samp> - Make Callout closable in the first Close Button example (@ncoden)
* 🚨  <samp>#11550</samp> - Run Sass unit tests in the Travis CI flow (@ncoden)
* 🚨  <samp>#11560</samp> - Run tests on Node 6, 8, 10 and stable (@DanielRuf)
* 💻  <samp>#11560</samp> - Update dependencies (2018-10-24) (@ncoden)

## Contributors
* Daniel Ruf ([@DanielRuf](https://github.com/DanielRuf)) [1]
* Josh Friend ([@joshwhatk](https://github.com/joshwhatk)) [1]
* Nicolas Coden ([@ncoden](https://github.com/ncoden)) [5]

Special thanks to:
* Daniel Ruf ([@DanielRuf](https://github.com/DanielRuf)) for his assistance in issues and his reviews of pull requests.
* Kai Falkowski ([@SassNinja](https://github.com/SassNinja)) for his assistance in issues and his reviews of pull requests.
* Katerina Limpitsouni (https://undraw.co) for the assets used in the illustration.

### CODE REVIEW

**Review by SassNinja — APPROVED** [review]
lgtm!

finally the final v6.5.0 :)

**Review by SassNinja — APPROVED** [review]

**Review by DanielRuf — APPROVED** [review]
LGTM

**Comment by bgarrant** [comment]
How close is this to release? Looks great!

**Comment by ncoden** [comment]
@bgarrant Planned for tomorrow 😉

**Comment by DanielRuf** [comment]
Seems there is a new issue related to Node.js 11.

**Comment by ncoden** [comment]
@DanielRuf It's the same issue. I have to import what we fixed in `develop` in there.

**Comment by DanielRuf** [comment]
> @DanielRuf It's the same issue. I have to import what we fixed in `develop` in there.

Ah ok, thought it was already fixed here (in this PR) and it was a regression after the other issue.

**Comment by ncoden** [comment]
Ready for the release.

**Comment by bgarrant** [comment]
Can’t wait. Thanks so much.

**Pull request merged**
