### PR TITLE
Drilldown parent fix

### LINKED ISSUE #10803: Drilldown with parent links doesn't allow for proper use of keyboard 'Enter' key
#### How to reproduce this bug:

1. Create a basic drilldown component with data-parent-link set to true.
2. Add a valid href attribute to a submenu parent item.
3. Navigate to that parent item using keyboard. Press 'Enter'.
4. Navigate to the newly opened submenu parent item with a valid href. Press 'Enter' again.
 
#### What should happen:
1. When the submenu opens, the focus should be set on the submenu parent.
2. Pressing 'Enter' on the submenu parent item should take you to the location in its href attribute.

#### What happened instead:
1. When the submenu opens, focus is set incorrectly on the first submenu child.
2. Pressing 'Enter' on the submenu parent item makes it act like the 'Back' button.

#### Browser(s) and Device(s) tested on:
All browsers.

#### Foundation Version(s) you are using:
Any version. Codepen example is using 6.3.1.

#### Test case link:

- [CodePen with Foundation 6.3.1](https://codepen.io/dbombine/pen/XgwOrZ)

### PR DESCRIPTION
**Pull request by Owlbertz**
Implemented suggestion of @dbombine in #10803.

Closes #10803

### CODE REVIEW

**Review by ncoden — APPROVED** [review]
I don't like the way it is implemented (with selectors and a lot of assumptions about the HTML architecture), but the whole framework is like that, this is standard jQuery and I don't see how it could be improved.

I may have this impression because I dev only in Ember for 2 months and we don't deal with the DOM in that framework.

Anyway. LGTM 👍

**Comment by Owlbertz** [comment]
Yeah, I am not really happy with the way I done it, too. But as you said the whole framework works like that. This wasn't the case when we started Foundation 6 I guess, but became more and more this way as more collaborators opened PRs. However, let's hope we can keep it cleaner with F7.

**Comment by DaSchTour** [comment]
@ncoden I feel your pain. We need to stop using jQuery 😉 while currently working on an angular project I hate looking into old jQuery code more and more.

**Comment by IamManchanda** [comment]
Same here guys ;)

**Pull request merged**
