### PR TITLE
Option to close drop menu on leaf anchor links click (As per #9015)

### PR DESCRIPTION
**Pull request by sujayjaju**
Adding `data-close-on-click-inside` to handle menu leaf element clicks. #9015

### CODE REVIEW

**Comment by kball** [comment]
HI @sujayjaju can you separate this PR into 2 separate ones, as they deal with unrelated functionality?  Thanks

**Comment by sujayjaju** [comment]
@kball I have updated this PR.

**Comment by kball** [comment]
Great, thanks!  This looks good.

**Comment by rbayliss** [comment]
I think this has caused some broken behavior on mobile - dropdowns close themselves when you try to scroll through them using touch events.  See #9293

**Comment by litalboa** [comment]
I have the same problem i tried to write "data-close-on-click-inside", but maybe i'm using it wrong. 
i have put it here: 
<li><a href="{{url('about')}}">About</a> 
       <ul class="nested dropdown menu" data-close-on-click-inside> 
              <li><a href="/about#our-story">Our Story</a></li> 
              <li><a href="/about#team">Team</a></li> 
              <li><a href="/about#news">In the news</a></li>
       </ul>
</li>

as you can see there is an anchor on the page and on for mobile users the menu is not closing automatically so they have to click the menu in order to close it.
what can i do?

**Pull request merged**
