### PR TITLE
fix: properly pass Event as object

### LINKED ISSUE #11714: [Orbit] doesn't slide manually
On previous versions it was possible to slide with a smartphone. This is actually not possible. Even on the documentation page: https://foundation.zurb.com/sites/docs/orbit.html

It was very usefull, so will it be fixed??

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This correctly passes the Event properties as pure object.

- Closes #11714

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [x] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
I think we should add some unit test here.

**Comment by DanielRuf** [comment]
@kball it seems we can not trigger the `touch` events manually, see the commented unit test.

So how can we test it from the outside?
Not sure where this is filtered.
I guess `addEventListener` vs `on` in `util.touch` are different.

**Comment by FuelAgency** [comment]
We're new to the Foundation framework but have been frustrated by the swipe issue on our first application! We thought it was us ;)
Any idea what the time frame is likely to be before we see a fix rolled out that we can apply? Thx.

**Comment by DanielRuf** [comment]
@FuelAgency you can basically use https://github.com/zurb/foundation-sites/pull/11716.patch or https://github.com/zurb/foundation-sites/pull/11716.diff to apply and create a new Foundation build until this is merged.

**Comment by FuelAgency** [comment]
What's the Zurb release schedule like? Do you imagine a fix for the broken swipe features will be out anytime soon within the main Release? Cheers.

**Comment by DanielRuf** [comment]
@FuelAgency theoretically you can apply these changes with `patch` or `patch-package`.

I do not know what the current plans for Foundation Sites are. I would currently recommend to try Tachyons and Tailwind with other small libraries like Swiper.

I'm not actively contributing to this project anymore.

**Comment by FuelAgency** [comment]
If @ncoden has left Zurb, maybe someone else needs to be tagged as a Reviewer in order to get this merged and released? Am I the only one who is shocked such a breaking change could remain in place for so long?

**Comment by joebcc** [comment]
Has this issue been addressed? Any update from Zurb?

**Comment by DanielRuf** [comment]
Hi @joebcc,

As you can see there is no progress.

**Review by DanielRuf — COMMENTED** [review]
Seems to solve the linked issue, see https://github.com/zurb/foundation-sites/issues/11714#issuecomment-496376494

**Comment by gruenewiese** [comment]
Dear Daniel Ruf,
frist, thank you very much for addressing this problem.

But unfortunately it doesn't work for me.
I changed the two lines in js/foundation.util.touch.js
and updated js/foundation.orbit.js with your changes.

I tested it with the example slider from https://foundation.zurb.com/sites/docs/orbit.html

I use
jQuery v3.2.1
Foundation v6.5.1
iOS 12.3.1 – Safari

But I still cannot swipe.

Is there anything i forgot to do?
Can I do anything?

**Comment by DanielRuf** [comment]
Hi @gruenewiese,

Can you share a codepen which reproduces this?

**Review by kball — APPROVED** [review]

**Pull request merged**
