### PR TITLE
fix: Ensure drilldown has the right height inside of responsive top b…

### PR DESCRIPTION
**Pull request by Buddierdl**
…ar when toggled #11759

Fixed the _back function so that $currentMenu is updated to the root menu if the current menu doesn't have a parent submenu.

## Description

...

- Closes 

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @Buddierdl,

Thanks for finding this bug and especially for providing the PR.

**Comment by Buddierdl** [comment]
Glad to help. It is my first PR and bug report so I hope I did everything right.

**Comment by Buddierdl** [comment]
How do I get this merge approved?

**Comment by DanielRuf** [comment]
Hi @Buddierdl,

Can you rebase so that the latest changes are included and we get a fresh CI build?

**Comment by Buddierdl** [comment]
@DanielRuf Done. Can it be merged now?

**Comment by DanielRuf** [comment]
> @DanielRuf Done. Can it be merged now?

Awesome, I'll try to check it in the next days and give a review.

**Review by joeworkman — APPROVED** [review]

**Pull request merged**
