### PR TITLE
Restyle clearing captions

### PR DESCRIPTION
**Pull request by emullaraj**
This restyle makes possible adding all kind of elements in the clearing captions. It makes possible also adding captions on the heading images ;)

### CODE REVIEW

**Comment by rafibomb** [comment]
Like the idea of being more generic. We'll test it soon to pull in.

**Comment by rafibomb** [comment]
I want to pull this in. Can you resolve the merge conflicts?

**Comment by emullaraj** [comment]
That is perfect, but i found a couple of mistakes in the overall
integration with foundation so I need to fix them in the project and I will
resubmit everything once again. It should take me a couple of days.

Thank you,
Eno

**Comment by rafibomb** [comment]
Thanks! looking forward to it!

**Comment by rafibomb** [comment]
@emullaraj Are you able to clear the conflicts so we can merge? Thank you!

**Pull request closed without merging**
