### PR TITLE
[Button Group] Add vertical button group!

### PR DESCRIPTION
**Pull request by IamManchanda**
Simple & Sweet
This just adds the below Sass/CSS....
Looking to migrate from => `stacked`

```scss
&.vertical {
  #{$child-selector} {
    display: block;
  }
}
```

### CODE REVIEW

**Comment by rafibomb** [comment]
How does this differ from http://foundation.zurb.com/sites/docs/button-group.html#stacking ? Are you proposing we change the classname?

**Comment by IamManchanda** [comment]
Yeah... We are using vertical in menu....  Grid etc then why this is it different in buttons ?

**Comment by IamManchanda** [comment]
Also, we should rename the responsive classes 

`vertical`, `medium-vertical`, `large-vertical`
`horizontal, `medium-horizontal`, `large-horizontal`

instead of `stacked-for-small` ... it shouldnt be handled the way visibility classes are handled!!!

**Comment by kball** [comment]
If this is replacing stacked it seems like this PR is incomplete...

**Comment by IamManchanda** [comment]
Yeah incomplete because i needed a word from you guys first ??

**Comment by IamManchanda** [comment]
@kball As per our discussion sometime back on this ... i am adding this to 6.5!

**Comment by kball** [comment]
@IamManchanda is this something you have any interest in picking back up and bringing across the finish line?

**Comment by SassNinja** [comment]
I'm closing this as it
- is a breaking change (when replacing `stacked-for-xxxx`)
- doesn't fix any open issue
- is rather something for v7

**Pull request closed without merging**
