### PR TITLE
Add dropdown background

### PR DESCRIPTION
**Pull request by ncoden**
Add `$dropdown-background` config to allow to customize dropdown background color.

The default background value is the same (`$body-background`).

### CODE REVIEW

**Comment by ncoden** [comment]
@colin-marshall @kball

**Comment by kball** [comment]
Seems reasonable to me.  What do you think @andycochran @brettsmason ?

**Comment by ncoden** [comment]
BTW should I always tag someone on PR ? If yes, who, `@random()` ?

**Comment by kball** [comment]
Good question @ncoden.  I don't think you should need to, we've just had a big backlog build up recently with the foundation for emails launch, some other ZURB projects, and figuring out some transitions in personel.  One of the hopes of expanding the Yetinaut program is to reduce this type of volatility.

**Comment by brettsmason** [comment]
@kball no problems with it here, it makes sense. One question, do we need to add variables to the settings file? I'm sure I remember Geoff saying that the file is generated each patch. Would be good to know for future issues/Pls.

**Comment by andycochran** [comment]
Agreed. :+1: This looks good / would also like clarification on `_settings.scss` (this also came up in #8431).

**Comment by kball** [comment]
@brettsmason and @andycochran yes the _settings.scss is autogenerated as a part of our packaging/deploy process.  I don't think it hurts to update it as a part of the PR, but it shouldn't be necessary.

**Pull request merged**
