### PR TITLE
Closes #10203, update docs with current drilldown menu examples!

### LINKED ISSUE #10203: [Drilldown Menu] not working at all in 6.4
http://foundation.zurb.com/sites/6.4.0-rc/docs/drilldown-menu.html drilldown is not working at all in 6.4.

### PR DESCRIPTION
**Pull request by IamManchanda**
Closes #10203 
Update docs as per #9670 !

PS: The newly created Visual tests are running fine!

cc @kball

### CODE REVIEW

**Comment by kball** [comment]
@IamManchanda can you take a look at the drilldown visual tests too?

And I'm pondering... since drilldown requires the class to work, should we have a (configurable, but default on) JS option that will auto-add drilldown class if it doesn't exist?

**Comment by IamManchanda** [comment]
> @IamManchanda can you take a look at the drilldown visual tests too?
Doing it now 

> And I'm pondering... since drilldown requires the class to work, should we have a (configurable, but default on) JS option that will auto-add drilldown class if it doesn't exist?

Yes it will be great sir!

**Comment by IamManchanda** [comment]
There you go @kball ... i have updated the visual tests :)

**Comment by brettsmason** [comment]
@IamManchanda Does the drilldown menu now require the `nested` class to work?

**Comment by IamManchanda** [comment]
Nopes not needed i just added this for the sake of responsive menu! @brettsmason

**Pull request merged**
