### PR TITLE
Orbit Using MUI fade in fade out feature instead of moving from left or right [Added Animation Option]

### PR DESCRIPTION
**Pull request by simongcc**
```
 Orbit.defaults = {
     /**
     * motion-ui animation, may use fade in fade out other than only moving from left or right
     * @option
     * @example true
     */
     fadeOnly: false,
```

...

```
if (this.options.useMUI) {
       // added fade option here, maybe use Switch Case is better if there is different kind of animation other than Moving From and Fade In (more than 2 options)
        if(this.options.fadeOnly) {
          Foundation.Motion.animateIn($newSlide.addClass('is-active').css({ 'position': 'absolute', 'top': 0    }), 'fade-in', function () {
            $newSlide.css({ 'position': 'relative', 'display': 'block' }).attr('aria-live', 'polite');
          });

          Foundation.Motion.animateOut($curSlide.removeClass('is-active'), 'fade-out', function () {
            $curSlide.removeAttr('aria-live');
            if (_this.options.autoPlay && !_this.timer.isPaused) {
              _this.timer.restart();
            }
            //do stuff?
          });
        } else {
          ... // original moving from feature
        }

      } else {
```

...

### CODE REVIEW

**Comment by simongcc** [comment]
I think the fadeOnly can be more generalized as "animationType" for future proof such as
```
animationType: "fade"...
animationType: "slideIn"...
... any other kind
```

**Comment by ncoden** [comment]
Hi @simongcc.

You are trying here to merge `v6.2.2` from `master`. Did you forgot to choose your repo branch when you created this PR ?

**Comment by simongcc** [comment]
Hi @ncoden I did choose a branch but I am not sure which one to choose, I just follow the example to choose. Sorry if I have messed up the things since I am pretty new in submitting the code. For I don't have too much time after work to play or look deeply in how to do it. 
Please let me know what I should do that I will try to avoid. Thanks for your time.

**Comment by ncoden** [comment]
@simongcc Please create a new PR from `simongcc:develop` (or the branch on which you made modifications) to `zurb:develop`. Ensure you local branchs are up-to-date.

**Pull request closed without merging**
