### PR TITLE
fix: add missing foundation.js reference comment

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This PR adds the missing foundation.js reference comment again

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by SassNinja — COMMENTED** [review]
I don't get the purpose of this change...
what does it fix or rather what is it intended for?

**Comment by DanielRuf** [comment]
@SassNinja in 6.4.3 it was still there and it is helpful as reference for users to link / reference the full foundation.js file.

See https://github.com/foundation/foundation-sites/blob/v6.4.3/docs/layout/default.html#L85

**Comment by DanielRuf** [comment]
I should probably move it after the vendor bundle.

**Review by joeworkman — APPROVED** [review]
LGTM

**Comment by DanielRuf** [comment]
> I should probably move it after the vendor bundle.

**Comment by DanielRuf** [comment]
Not so quick ;-)

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-v6-6-1-shipped/67/1

**Pull request merged**
