### PR TITLE
Rework Button Group to not use borders

### PR DESCRIPTION
**Pull request by andycochran**
This PR implements margin for the space between buttons, instead of faking it with borders. It also nixes the use of table display & floats, instead using `inline-block`. 

Let me know if you have feedback. 

Woot!
-Andy

Related issues: #7665, #7844

### CODE REVIEW

**Comment by andycochran** [comment]
Also makes button group spacing look good on backgrounds not matching `$body-background`.

**Comment by andycochran** [comment]
Remedies these border-radius isses: 
screen shot 2016-01-20 at 12 39 01 pm
screen shot 2016-01-20 at 12 42 11 pm

**Comment by gakimball** [comment]
Does `font-size: 0` get around the extra whitespace created by `display: inline-block`?

**Comment by andycochran** [comment]
Exactly. The buttons have a space character's width between them. If the font size is zero, that space disappears.

**Comment by gakimball** [comment]
One piece of feedback, the sizing classes shouldn't print inside the `button-group()` mixin—they should stay in the CSS output. Otherwise you're tightly coupled to those sizing class names (and class chaining) when using the mixin.

**Comment by andycochran** [comment]
D'oh! I'll work on that. Thanks, @gakimball.

**Comment by andycochran** [comment]
@gakimball Take a look. You'll notice I redid the button group sizes like this: 
```scss
@each $size, $value in $button-sizes {
  &.#{$size} #{$buttongroup-child-selector} { font-size: $value; }
}
```
This allows user-defined button sizes. 

A similar method could be used for all button sizing. For instance, lines 197–199 in `_button.scss` could be… 
```scss
@each $size, $value in $button-sizes {
  &.#{$size} { font-size: $value; }
}
```
instead of… 
```scss
&.tiny     { font-size: map-get($button-sizes, tiny); }
&.small    { font-size: map-get($button-sizes, small); }
&.large    { font-size: map-get($button-sizes, large); }
```

Caveat: It adds a `.default` button size class. 
Thoughts?

**Comment by gakimball** [comment]
Definitely interested in that. You can remove `default` from the map on the fly using `map-remove()`.

```scss
@each $size, $value in map-remove($button-sizes, default) {
}
```

**Comment by andycochran** [comment]
@gakimball Done. This'll close #7665, #7844, ~~and #7972~~.

**Comment by gakimball** [comment]
@andycochran Solid, thanks so much for putting it together!

**Comment by slavanga** [comment]
The font-size: 0 trick doesn't work in the android browser pre Jellybean.
http://codepen.io/stowball/pen/LsICH

**Comment by andycochran** [comment]
@slavanga We decided in https://github.com/zurb/foundation-sites/issues/7665#issuecomment-172625174 that this was acceptable fallout in oder to fix a few other bugs in all browsers.

**Comment by slavanga** [comment]
@andycochran Alright, that sounds reasonable.

**Pull request merged**
