### PR TITLE
Mixins css triangle

### PR DESCRIPTION
**Pull request by esanzgar**
## Description

Some improvements to the css-triangle.

Rules are more specific and less verbose

- Closes 

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] The pull request title and template are correctly filled.
- [ ] The pull request targets the right branch (`develop` or `develop-v...`).
- [ ] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Review by DanielRuf — COMMENTED** [review]
We need this verbose code, for example for rtl support. And we only want to set the needed properties. Also `inset` is missing now.

**Comment by esanzgar** [comment]
My understanding is that all the borders become transparent except the one that is visible (which is solid). Does it matter the style of the rest of the borders if they become transparent?

**Comment by esanzgar** [comment]
Shouldn't be better to supply the four values for the border-color, just to avoid any default value?

**Comment by DanielRuf** [comment]
Not sure what you mean, all the properties are already different. See the order of their values.

**Review by rafibomb — DISMISSED** [review]
I'll check this out but seems to work. Need to test with RTL

**Review by joeworkman — APPROVED** [review]

**Pull request merged**
