### PR TITLE
ES6 Template Literals

### PR DESCRIPTION
**Pull request by colin-marshall**
I went through all of the JavaScript files and searched for `+ '`, `+'`,  `+ "`,  `+"`, `' +`, `'+`, `" +`, and `"+` to find places where I could replace concatenation with template literals.

Be forewarned, this is my first time using ES6/Babel and I was not sure if template literals are allowed everywhere I used them. I also have not had a chance to go through every component to verify they still work after migrating to template literals.

### CODE REVIEW

**Comment by andycochran** [comment]
@colin-marshall It looks like you've used backticks instead of straight quotes.

**Comment by gakimball** [comment]
This is awesome!

A quick way to test this is by thumbing through the Kitchen Sink page in the documentation.

**Comment by colin-marshall** [comment]
@gakimball good call on the Kitchen Sink. Found a typo in one of the templates in Tabs so I fixed that, and everything appears to work like it should. I also rebased the PR with the 6.2 branch to get the fix you just put in for one of the two merge conflicts, and now the build is passing.

**Comment by gakimball** [comment]
Nice, thanks for that :)

**Pull request merged**
