### PR TITLE
Fixs - for grid media query positions(centerde - uncentered) in case …

### PR DESCRIPTION
**Pull request by mohamedfawzi**
There is a problem present in grid specifically in columns position.
In case i want make my columns position centered in case small and uncentered in case medium and try many examples similar, the problem appear. 
I solved a big parts of the problem but  i need some help.

### CODE REVIEW

**Comment by eu-slack** [comment]
Hi @mohamedfawzi, I've suggested a possible solution here #10052 
It's a very simple workaround, but I hope it can help you :wink:

**Comment by Seanom** [comment]
A lot of this pull request appears to be formatting amends, I'd suggest cleaning that up so it's just the code being changed. 
I struggled to see what was being amended here.

**Comment by DanielRuf** [comment]
Hi @mohamedfawzi, can you still need some help with this? Please let us know how we can solve this together.

**Review by DanielRuf — COMMENTED** [review]
Can you rebase the PR?

**Pull request closed without merging**
