### PR TITLE
feat: add opening methods to responsiveAccordionTabs #10953

### LINKED ISSUE #10953: Collapsing Responsive-accordion Tabs? (Foundation 6)
So I'm having a really hard time figuring out why I can't collapse my accordion tabs using the Foundation 6.3 responsive tabs. The javascript provided in the foundation docs only seems to work with regular accordion setup and not the responsive-accordions tabs. 

Is this a bug with the responsive accordions? Does anyone know of a reason why this does not work or a possible solution to get responsive accordion-tabs to collapse initial load?

#### How to reproduce this bug:
1. Use the responsive accordion setup
> https://foundation.zurb.com/sites/docs/responsive-accordion-tabs.html
2. Use the javascript to close accordion: `$('#element').foundation('up', $target);`
> https://foundation.zurb.com/sites/docs/accordion.html#up

#### What should happen:
Responsive accordion-tabs should close.

#### What happened instead:
Nothing

#### Browser(s) and Device(s) tested on:
Testing on Chrome / Safari/ Firefox - Mac OS

#### Foundation Version(s) you are using:
Foundation v6.3.1

#### Test case link:
CODE PEN TO DEMONSTRATE:
https://codepen.io/jinch/pen/RQxQNG

### PR DESCRIPTION
**Pull request by ncoden**
Changes:
* make ResponsiveAccordionTabs using its options 
* add open/close/toggle methods to responsiveAccordionTabs

Closes #10953

Note: `open/toggle` methods are not supported in tabs mode.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Will test tomorrow.

**Comment by DanielRuf** [comment]
Seems fine so far. But what about `historyHandled` and `firstTime`?

**Comment by ncoden** [comment]
I still need to work on this. At least to improve the API for tabs. It is a bit difficult to understand what you need to pass to `open` between the tab and accordion markum.

So I'll take a look at `historyHandled` and `firstTime` too.

**Comment by DanielRuf** [comment]
Do we also need some unit tests then?

**Comment by ncoden** [comment]
Yes, there's never enough unit tests ;)

**Comment by DanielRuf** [comment]
> So I'll take a look at historyHandled and firstTime too.

Any news on this?

**Comment by ncoden** [comment]
No, just need some time to work on this.

**Comment by DanielRuf** [comment]
Is `data-active-collapse="true"` also relevant here?

**Comment by DanielRuf** [comment]
Bump =)

**Comment by ncoden** [comment]
I seen your message but as you can see this is new features planned for `v6.6.0` so I'll not spend more time on this for now. There's enough work with getting `v6.5.0` released.

Thx for the bump anyway =)

**Comment by DanielRuf** [comment]
Ah ok, was not quite clear from the changes in the comment section, only on the right side.

**Review by DanielRuf — APPROVED** [review]
Tested with patch-package in 6.4.3, works great.

**Comment by ayyobro** [comment]
doot. Would be cool to have this merged soon!

**Comment by kball** [comment]
@DanielRuf it looks like you reviewed and tested this, is it good to merge?

**Comment by DanielRuf** [comment]
Not sure but a few things are missing but I think it can be merged as it implements most of the currently missing things.

https://github.com/zurb/foundation-sites/pull/10961#issuecomment-367491518

**Comment by kball** [comment]
OK based on prior comment going to merge this

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-for-sites-v6-6-0-is-here-farout/30/1

**Pull request merged**
