### PR TITLE
Chinese and Japanese are not RTL scripts.

### PR DESCRIPTION
**Pull request by wangcheng**
## Description

Chinese and Japanese are not RTL scripts.

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @wangcheng,

thanks for reporting this.
Please provide a working codepen so we can reproduce it.

Maybe you forgot to set the `dir` and `lang` attributes in your HTML:
https://get.foundation/sites/docs/rtl.html

> You'll need to make a few changes to your markup to get the Javascript components working nice and smooth. In the <html> tag, you'll need to add a dir attribute with a value of rtl. Here's what your <html> tag should look like:

> 
> <html class="no-js" lang="ar" dir="rtl">

**Comment by DanielRuf** [comment]
Hi @wangcheng,

thanks for reporting this.
Please provide a working codepen so we can reproduce it.

Maybe you forgot to set the `dir` and `lang` attributes in your HTML:
https://get.foundation/sites/docs/rtl.html

> You'll need to make a few changes to your markup to get the Javascript components working nice and smooth. In the <html> tag, you'll need to add a dir attribute with a value of rtl. Here's what your <html> tag should look like:

```
<!-- This example is for a right-to-left Arabic layout -->
<html class="no-js" lang="ar" dir="rtl">
```

**Comment by DanielRuf** [comment]
Hi @wangcheng,

thanks for reporting this.
Please provide a working codepen so we can reproduce it.

Maybe you forgot to set the `dir` and `lang` attributes in your HTML:
https://get.foundation/sites/docs/rtl.html

> You'll need to make a few changes to your markup to get the Javascript components working nice and smooth. In the <html> tag, you'll need to add a dir attribute with a value of rtl. Here's what your <html> tag should look like:

```html
<!-- This example is for a right-to-left Arabic layout -->
<html class="no-js" lang="ar" dir="rtl">
```

**Comment by DanielRuf** [comment]
Hi @wangcheng,

Wikipedia has the following text passage about this:

> Right-to-left can also refer to Text direction TDleft.svg top-to-bottom, right-to-left (TB-RL or TBRL) scripts such as Chinese, Japanese, and Korean, though in modern times they are also commonly written Text direction LTRdown.svg left to right. Books designed for predominately TBRL vertical text open in the same direction as those for RTL horizontal text: the spine is on the right and pages are numbered from right-to-left.

**Comment by DanielRuf** [comment]
Hi @wangcheng,

Wikipedia has the following text passage about this:

> Right-to-left can also refer to Text direction top-to-bottom, right-to-left (TB-RL or TBRL) scripts such as Chinese, Japanese, and Korean, though in modern times they are also commonly written Text direction LTRdown.svg left to right. Books designed for predominately TBRL vertical text open in the same direction as those for RTL horizontal text: the spine is on the right and pages are numbered from right-to-left.

**Comment by DanielRuf** [comment]
Hi @wangcheng,

Wikipedia has the following text passage about this:

> Right-to-left can also refer to Text direction top-to-bottom, right-to-left (TB-RL or TBRL) scripts such as Chinese, Japanese, and Korean, though in modern times they are also commonly written Text direction left to right. Books designed for predominately TBRL vertical text open in the same direction as those for RTL horizontal text: the spine is on the right and pages are numbered from right-to-left.

**Comment by SassNinja** [comment]
> though in modern times they are also commonly written Text direction left to right

@DanielRuf I'd say the point is on Chinese & Japanese websites it's LTR so the docs are probably misleading 

imo it's ok to remove those two languages from the RTL docs

**Review by SassNinja — APPROVED** [review]

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> so the docs are probably misleading

You are right.

**Comment by wangcheng** [comment]
@DanielRuf I think the "direction" we are talking about here is the "flow direction" inside a line. In this case Chinese (or other east-Asia scripts that can be written vertically) is not RTL.

CSS has another property `writing-mode` to control the lines should be laid horizontally or vertically. It is a diifferent concept with `direction`.

In fact the reason I noticed this doc is [a browser extension is "missled" by it](https://github.com/rNeomy/reader-view/pull/61), causing the extension not handling Chinese pages properly.

**Comment by DanielRuf** [comment]
Thanks for your contribution to Foundation Sites @wangcheng

**Pull request merged**
