### PR TITLE
chore: fix ES5/ES6 Foundation imports

### PR DESCRIPTION
**Pull request by ncoden**
### Changes:
* Build Foundation as an UMD module
* Make `js/entry/foundation.js` an ESM entry point.
* Delete unused `dist/js/npm.js`

See commits for more details.

### Entry points:
* `dist/js/foundation.js`: [UMD](https://github.com/umdjs/umd) (browser-compatible) entry point [**default**]
* `js/entries/foundation.js`: [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) (es6) entry point

### ✅ Closes:
* https://github.com/zurb/foundation-sites/issues/10852 Using foundation 6 js with brunch and npm instead of bower and webpack (@fmj02)
* https://github.com/zurb/foundation-sites/issues/10774  Precompile the library to CommonJS (@ShadyXV)
* https://github.com/zurb/foundation-sites/issues/10800 Webpack LibraryTarget - export UMD (@tomm1996)

### ➡️ Related to:
* https://github.com/zurb/foundation-sites/pull/10849 pkg.main should be an es5 module not es6 (@iainbeeston)
* https://github.com/zurb/foundation-sites/pull/10782 Precompile the library to CommonJS (@ShadyXV)
* https://github.com/zurb/foundation-sites/issues/10336 jQuery.foundation() is not a function (@voogieJames)
* https://github.com/zurb/foundation-sites/issues/10645 ReferenceError: Can't find variable: exports (@melcarthus)
* https://github.com/zurb/foundation-sites/issues/10723 zurb foundation unknown word error (@dhisharma)
* https://github.com/zurb/foundation-sites/issues/10910 Couldn't find preset "es2015" relative to directory (@bonovski)

### CODE REVIEW

**Comment by ncoden** [comment]
@fmj02 @ShadyXV @tomm1996 @iainbeeston @ShadyXV @voogieJames @melcarthus @dhisharma

Could you confirm this does solve (or does NOT solve) you issue ?

To test this branch locally, run:
```bash
# Get this PR branch
git fetch git@github.com:ncoden/foundation-sites.git chore/es5-pkg-main:ncoden/chore/es5-pkg-main
git checkout ncoden/chore/es5-pkg-main

# Build Foundation distribution
$(npm bin)/gulp deploy:dist
$(npm bin)/gulp deploy:plugins

# Use the local build in your project
npm link # create a "foundation-sites" alias to this local repo
cd path/to/your/project
npm link foundation-sites # use the local repo in your project
```

Now, you should be able to use in your project:
```js 
import Foundation from 'foundation-sites';
import { Foundation } from 'foundation-sites';
import { Abide, Orbit } from 'foundation-sites';
```
OR
```js
const Foundation  = require('foundation-sites');
```
OR
```html
<script type="text/javascript" src="path/to/foundation.js"></script>
```

**Comment by fmj02** [comment]
Your branch doesn't exist anymore.

**Comment by ncoden** [comment]
@fmj02 I just tested and `git fetch git@github.com:ncoden/foundation-sites.git chore/es5-pkg-main:ncoden/chore/es5-pkg-main` works.

**Comment by fmj02** [comment]
I was looking at the wrong repo. I'm going to test it now.

**Comment by fmj02** [comment]
So all this does for now is changing entry point to `foundation-sites/dist/js/foundation` so I don't have to type this manually? I still can't choose what js plugins I want to use when using CommonJS?

**Comment by ncoden** [comment]
This changes the default entry point to `foundation-sites/dist/js/foundation`, and make it a "UMD" module, which allow you to import all or part of Foundation.

Like: 

```scss
import { Orbit } from 'foundation-sites';
```

**Comment by fmj02** [comment]
Does it work with `require` ?

**Comment by ncoden** [comment]
Yes it does. I updated my comment.

**Comment by fmj02** [comment]
Great work @ncoden ! 💯 🍾

**Comment by ncoden** [comment]
@fmj02 Did you tested this is your own build ? Does it work as expected ?

**Comment by fmj02** [comment]
Seems to work fine. 

```
const Foundation = require('foundation-sites/dist/js/plugins/foundation.core.js');
const Orbit = require('foundation-sites/dist/js/plugins/foundation.orbit.js');
```

**Comment by ncoden** [comment]
Yes but this is not changed by this PR.

This PR should allow you use use: `var Foundation = require('foundation-sites');`

**Comment by fmj02** [comment]
What do you mean, so this will work only on your branch?

**Comment by ncoden** [comment]
I mean that this PR does not change the way plugins are generated. So importing them now should work like before. What this PR solves is your ability to `require('foundation-sites)` in a non-ES6 environment. Once this branch is merged (and released in a new version), you will be able to `require('foundation-sites')` the official Foundation package.

**Comment by fmj02** [comment]
https://github.com/ncoden/foundation-sites/commit/565a60f448559b5079e60664fe69354192abbd42

It changes to generate to umd so that is fine.

**Pull request merged**
