### PR TITLE
fix margin and height on align-right menus

### PR DESCRIPTION
**Pull request by andycochran**

### CODE REVIEW

**Comment by andycochran** [comment]
Fixes #8102.

**Comment by kball** [comment]
@andycochran I'm triaging all of our old PRs, and I'd like to get this merged in, do you have an example you can add as a visual regression test (https://github.com/zurb/foundation-sites/wiki/Testing-Guide#visual-regression-tests) so we can quickly verify across devices, and bring the PR up to date with current develop?  Thanks!

**Comment by andycochran** [comment]
@kball I'm closing this. Looks like work has been done since I did this that changes the method from floats to table-cell (add flexbox method was added). So I think this PR is unnecessary now.

**Comment by kball** [comment]
Awesome, thanks @andycochran

**Pull request closed without merging**
