### PR TITLE
Extend equalizer to add a class to determine whether its the tallest …

### PR DESCRIPTION
**Pull request by ochorocho**
…or one of the smaller elements to be able to select them using css.
i had 2 elments in 2 columns and wanted the smaller element to be positioned on top (z-index) of the taller one automatically.

### CODE REVIEW

**Comment by gakimball** [comment]
With the release of Foundation 6 in late November last year, we're no longer adding new features to Foundation 5.

**Comment by ochorocho** [comment]
@gakimball, ok thanks. if i redo this for foundation 6 will this make it to the core or is it just minor feature no one would use?

**Comment by gakimball** [comment]
Admittedly we weren't sure what the use-case was. What were you using it for?

**Comment by ochorocho** [comment]
in my case i had 2 elements, a picture and a text element. I wanted the smaller element always lying on top of the taller one. So i needed to give a higher z-index for the smaller element.
Both elements are dynamic depending on the text length/image height.


```html
<div class="row" data-equalizer="">
    <div style="height: 400px; display: block;" class="small-12 medium-6 large-6 columns taller" data-equalizer-watch="">
      <div class="image vcenter">
        <div class="historyDate">April ‘15</div>
        <img src="Images/historie_motorrad.jpg">
      </div>
    </div>
    <div style="height: 400px; display: block;" class="small-12 medium-6 large-6 columns smaller" data-equalizer-watch="">
      <div class="text vcenter">
        <h3 class="upper">
          Lorem ipsum et dolor
          <strong class="size-12">Consectetuer</strong>
          <div class="underline alignLeft"><div class="line"></div></div>
        </h3>
        <div class="description">
          <div class="text-orange">Duis autem vel eum iriure dolor in</div>
          Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing.
          <div class="icons small-text-center">
            <a href="#"><i class="icon size-14 facebook"></i></a>
            <a href="#"><i class="icon size-14 fi-social-twitter"></i></a>
            <a href="#"><i class="icon size-14 instagram"></i></a>
            <a href="#"><i class="icon size-14 youtube-play"></i></a>
          </div>
        </div>
        <div class="year">
          2015
        </div>
      </div>
    </div>
  </div>
```

Example:
bildschirmfoto 2016-01-20 um 18 00 47

Thanks.

**Comment by gakimball** [comment]
Ah okay. Very interesting, but likely still too specific a use case for us.

In Foundation 6 it's easier to initialize plugins programmatically, so you could do this check yourself first, apply the "taller" class, and then turn on Equalizer.

```js
var $container = $('.container')
var $children = $container.find('.children');
var $tallest;
// Compare heights of $children...
$tallest.addClass('.is-tallest');

// ...now turn on Equalizer
new Foundation.Equalizer($container);
```

**Comment by ochorocho** [comment]
thanks, this helps :+1:

**Pull request closed without merging**
