### PR TITLE
Add inline-svg icon support

### PR DESCRIPTION
**Pull request by artursopelnik**

### CODE REVIEW

**Comment by denisahac** [comment]
Not everyone would like to have an SVG tangled up with their HTML. If someone wants to have an SVG supported in the menu, then they can just add their own styles without messing up the core ZF.

What are those other commits in this pull request? I think they're unrelated to this **Add inline-svg icon support** commit you'd like to address.

**Comment by artursopelnik** [comment]
We use [svg-icon-system ](http://danburzo.ro/svg-icon-system/) for our client project. Currently we add (svg-support) for menu-icons in own styles but why not make it global ...
---
You're right. Only the **Add inline-svg icon support** commit is important.

**Comment by kball** [comment]
The addition of SVG seems reasonable to me, but please resubmit with a clean branch that contains only that commit difference.

**Comment by artursopelnik** [comment]
Look at this: https://github.com/zurb/foundation-sites/pull/8683

**Pull request closed without merging**
