### PR TITLE
[Reveal] Fix closing when Motion UI is used

### PR DESCRIPTION
**Pull request by jeromelebleu**
Thanks to #9653, when closing a modal, it now checks if there is another opened one before removing the `is-reveal-open` class from `body`. It works when jQuery is used to hide the elements - since its behavior has been modified - but no longer with Motion UI.

As the `finishUp` function is called before the modal is actually closed, the `is-reveal-open` class is never removed - since `$('.reveal:visible').length === 0` [here](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L415) will always be false.

This PR purpose one way to fix it by hiding the modal first then the overlay. Nevertheless, it will change the current closing behavior - the overlay and the modal are hidden at the same time. If it should remain like that, there are other ways to fix it, fortunately!

I believe that a unit or visual test should also be given, but I didn't learn how to write that yet...

### CODE REVIEW

**Comment by kball** [comment]
Hmm... @jeromelebleu I think it would probably be better to maintain the behavior of closing at the same time. Having them animate out sequentially is a little odd... you mentioned there were other ways to fix, can you take a crack at one of those?

**Comment by jeromelebleu** [comment]
@kball I've updated this patch to maintain the original behavior of closing at the same time. I've just attached the `finishUp` function to the modal closing instead as it will hide the modal. Is it better?

**Comment by IamManchanda** [comment]
Looks cool to me!!!

**Comment by kball** [comment]
Looks good!

**Comment by jeromelebleu** [comment]
Thanks!

**Pull request merged**
