### PR TITLE
chore: UMD module bundling

### PR DESCRIPTION
**Pull request by ncoden**
### Changes:
* re-enable main/plugins entries bundling as UMD modules
* bundle main/plugins entries in their own library for externals
* export the mutated `Foundation` object and the plugin in every plugin entry

From now, we use `__FOUNDATION_EXTERNALS__` in the global namespace for exported plugins. This is the only way I found to make UMD modules works with externals.

### Todo:
- [x] Reduce namespace pollution
- [x] Prevent `Foundation.Plugin` and `Foundation.Utils.core` to be duplicated across plugins

### Note
Note to myself: this PR made me better understanding how webpack and bundlers works, as well as different import and bundling methods and standards. Want go further the simple tutorials on the net? Assign yourself a difficult issue and learn things the hard way, inspecting your dependencies' source code and looking at how others projects solves this problem.

### See also:
* 🐞  Bug introduced in #10864
* ◀️  Re-enable UMD from: #10911
* ◀️  Previous PR: #10903 (dirty)

### CODE REVIEW

**Comment by ncoden** [comment]
So I'm trying to resolve:
>  - [ ] Prevent Foundation.Plugin and Foundation.Utils.core to be duplicated across plugins

### Before this PR
`Plugin` and `Utils.core` were not duplicated because they were imported once in `foundation.core.js` (which was generated with no externals), made public via `window.Foundation.*` (see [js/entries/plugins/foundation.core.js:10](https://github.com/zurb/foundation-sites/blob/477563de08ae39c69ebf40b87f10f871696956c4/js/entries/plugins/foundation.core.js#L10)) which were used as external for all others plugins.

So `import { X } from './foundation.utils.core'` in a plugin source would result in the browser in accessing `window.Foundation.X` defined by `foundation.core.js`. This is not intuitive at all, there's a problem somewhere ;)

### With this PR
Now we do not rely on `window.Foundation` for externals but on dedicated global variables, used to embed the whole exported file. So we cannot use as externals methods defined in a file other than the one we are including (and that's a good thing).

### Solutions
The simplest solution would be to export `foundation.utils.core` and `foundation.utils.plugin` in their own files to use them as externals. But this would be a breaking change, and very annoying for the user (which doesn't care about how our internal files are organized).

I would prefer the following solution:
- move `foundation.utils.core.js` to `foundation.core.utils.js`, consider it as a part of the core.
- move `foundation.plugin.js` to `foundation.core.plugin.js`, consider it as a part of the core.
- import these files in `foundation.core.js` to define `Foundation.*` like we are already doing.
- import in plugins `{ Foundation: { Plugin } } from 'foundation.core'` OR `{ Plugin } from 'foundation.core'` (same for the core utilities).

What do you think ? I need your advices on this @colin-marshall @brettsmason @IamManchanda @JeremyEnglert @abdullahsalem @andycochran

**Comment by ncoden** [comment]
>  [x] Reduce namespace pollution

Resolved by the last commit. All external "containers" are not exported in the global object `__FOUNDATION_EXTERNAL__`.

**Comment by DanielRuf** [comment]
> So we would now consider "Plugin" and "Core.Utils" as part of the core, include them inside the foundation.core.js dist file and import them from the foundation.core.js source file. I think this is more consistent.

Makes sense. And the treeshaking process will still clean up a bit in most cases.

**Comment by ncoden** [comment]
> * [x] Prevent Foundation.Plugin and Foundation.Utils.core to be duplicated across plugins

### Changes
* Moved `foundation.util.core` -> `foundation.core.utils`
* Moved `foundation.plugin` -> `foundation.core.plugin`
* Export `foundation.core.*` in the `foundation.core` entry

### Impact of this PR on files sizes

Comparison of [develop](https://github.com/zurb/foundation-sites/tree/develop) (ESM) against [fix/fix-es6-plugins-webpack-build-2](https://github.com/ncoden/foundation-sites/tree/fix/fix-es6-plugins-webpack-build-2) (UMD):

| File                                    |   ESM   |   UMD   |  Diff   |   %    |
|----------------------------------------:|---------|---------|---------|--------|
| `foundation.core.js`                    | 30.1 kB | 32.0 kB | +1.9 kB |  +6.3% |
| `foundation.responsiveToggle.js`        | 12.0 kB | 13.8 kB | +1.8 kB | +15.0% |
| `foundation.tooltip.js`                 | 42.6 kB | 44.6 kB | +2.0 kB |  +4.7% |
| `foundation.dropdown.js`                | 43.3 kB | 45.3 kB | +2.0 kB |  +4.6% |
| `foundation.slider.js`                  | 44.2 kB | 46.2 kB | +2.0 kB |  +4.5% |
| `foundation.responsiveMenu.js`          | 13.1 kB | 15.3 kB | +2.2 kB | +16.8% |
| `foundation.offcanvas.js`               | 38.8 kB | 40.7 kB | +1.9 kB |  +4.9% |
| `foundation.sticky.js`                  | 34.9 kB | 36.7 kB | +1.8 kB |  +5.1% |
| `foundation.reveal.js`                  | 37.9 kB | 39.8 kB | +1.9 kB |  +5.0% |
| `foundation.responsiveAccordionTabs.js` | 18.0 kB | 20.0 kB | +2.0 kB | +11.1% |
| `foundation.dropdownMenu.js`            | 23.9 kB | 26.0 kB | +2.1 kB |  +8.8% |
| `foundation.drilldown.js`               | 31.4 kB | 33.4 kB | +2.0 kB |  +6.4% |
| `foundation.equalizer.js`               | 18.2 kB | 20.0 kB | +1.8 kB |  +9.9% |
| `foundation.accordionMenu.js`           | 19.0 kB | 20.9 kB | +1.9 kB | +10.0% |
| `foundation.toggler.js`                 | 22.2 kB | 23.7 kB | +1.5 kB |  +6.8% |
| `foundation.tabs.js`                    | 22.0 kB | 23.7 kB | +1.7 kB |  +7.8% |
| `foundation.orbit.js`                   | 25.7 kB | 28.0 kB | +2.3 kB |  +9.0% |
| `foundation.magellan.js`                | 15.7 kB | 17.4 kB | +1.7 kB | +10.9% |
| `foundation.interchange.js`             | 13.4 kB | 15.0 kB | +1.6 kB | +12.0% |
| `foundation.accordion.js`               | 17.3 kB | 18.9 kB | +1.6 kB |  +9.2% |
| `foundation.smoothScroll.js`            | 11.0 kB | 12.4 kB | +1.4 kB | +12.8% |
| `foundation.abide.js`                   | 32.5 kB | 33.9 kB | +1.4 kB |  +4.3% |
| `foundation.util.triggers.js`           | 14.8 kB | 16.2 kB | +1.4 kB |  +9.4% |
| `foundation.util.motion.js`             |  7.2 kB |  8.6 kB | +1.4 kB | +19.7% |
| `foundation.util.keyboard.js`           |  9.8 kB | 11.0 kB | +1.2 kB | +12.4% |
| `foundation.util.timer.js`              |  5.1 kB |  6.3 kB | +1.2 kB | +23.4% |
| `foundation.util.nest.js`               |  5.9 kB |  7.1 kB | +1.2 kB | +20.3% |
| `foundation.util.mediaQuery.js`         | 10.6 kB | 11.8 kB | +1.2 kB | +11.3% |
| `foundation.util.imageLoader.js`        |  5.1 kB |  6.4 kB | +1.2 kB | +24.0% |
| `foundation.util.box.js`                | 12.8 kB | 13.9 kB | +1.1 kB |  +8.6% |
| `foundation.util.touch.js`              |  9.2 kB | 10.1 kB | +0.9 kB | +10.0% |
|-----------------------------------------|---------|---------|---------|--------|
| `foundation.js`                         |  437 kB |  438 kB | +1.0 kB |  +0.2% |

**Comment by ncoden** [comment]
@DanielRuf

**Comment by DanielRuf** [comment]
Looks good so far. Will try to check it this evening.

We might geht smaller file sizes with webpack 4 and uglify-es then.

**Comment by ncoden** [comment]
These are raw file sizes without any optimizations. They are increased because of the webpack UMD header (with tons of comments).

**Comment by DanielRuf** [comment]
> These are raw file sizes without any optimizations. They are increased because of the webpack UMD header (with tons of comments).

Right. Still interested to see the general differences between the current setup and a webpack 4 setup with the UMD wrapper applied ;-)

**Comment by ncoden** [comment]
Here is the diff between "root" (before) and UMD (now) bundling: http://www.mergely.com/2J4MzTGB/

@colin-marshall @DanielRuf @JeremyEnglert @SassNinja Would you have time to review this PR ?

**Comment by ncoden** [comment]
* 926b8e0  chore: prevent the main JS bundle to be exported as an unused external

Avoid to pollute the global namespace with `__FOUNDATION_EXTERNAL__` with the main bundle `foundation.js`. The external object is now created only with the core and plugin bundles.

**Review by DanielRuf — COMMENTED** [review]
Looks good so far. Will create a fresh sample project based on this later and test a few components in detail.

The Travis log seems fine and also the chunks and externals :+1:

**Review by SassNinja — APPROVED** [review]
Looks good to me!

I've used a custom plugin while testing which extends  the foundation plugin class. Had no problems after adjusting my imports (`foundation.util.core` and `foundation.plugin`).

I think this PR won't cause much work after updating one's project to v6.5.0 – we only need to mention the import change in the release notes

**Comment by ncoden** [comment]
Thanks @SassNinja :)

**Comment by SassNinja** [comment]
@ncoden one thing I've noticed: there's still a file in your branch that imports `foundation.utils.core` in `/dist/js/npm.js`.

Seems not to be used but should be adjusted as well or deleted imo.

**Review by DanielRuf — APPROVED** [review]
Also works here. LGTM.

**Comment by ncoden** [comment]
`/dist/js/npm.js` should be deleted.

**Comment by ncoden** [comment]
@danielck @SassNinja I removed `npm.js`, used the same build process for the customizer and resolved conflicts.

I'd like to update the documentation. The current approach for now is the following:

> All of Foundation's plugins ship both as importable ES2016 modules, and as individual precompiled "drop in" files, named foundation.tabs.js, foundation.accordion.js, and so on. These files are also combined into one big file called foundation.js, which allows you to get every plugin at once. The precompiled files live in the dist folder, while the importable modules live in the js folder.
> -- https://foundation.zurb.com/sites/docs/javascript.html#babel-required

So... we advice folks to rely on our _source files_. This is the best way to make projects break after any refactor (like moving a file around, reorganizing sources between them, using new ES features or changing the build process) even if no breaking change are introduced.

Also, this imply the following:

> Our JavaScript uses some features of ECMAScript 2015. If you use Foundation with a build system, you'll need to compile our code to ES5. We use Babel in our templates to do this. Babel has plugins for every build system imaginable, so integrating it into an existing setup is easy.

This is basically asking _the users_ to transpile by themselves the packages they are using. It's not a bad thing as it ensure that all the JS running on the browser is in ES5 without having to hope that packages maintainers well configured their build process. But making it _mandatory_ prevent a simple use of the library on any environment without loosing 2 hours setting up Webpack and Babel.

So now we can use ESM imports with the standard entry I would go for the classic "use the dist/entries files, don't touch the sources" approach and remove these paragraphs from the docs. What do you say ?

**Comment by DanielRuf** [comment]
> So now we can use ESM imports with the standard entry foundation.js I would go for the classic "use the dist/entries files, don't touch the sources" approach and remove these paragraphs from the docs. What do you say ?

Definitely. Go for it.

**Comment by ncoden** [comment]
I updated the docs.

**Comment by ncoden** [comment]
So I guess it's good to go now :D @DanielRuf One last check before merging ?

**Comment by ncoden** [comment]
Finally merged 🎉

**Pull request merged**
