### PR TITLE
Clearly indicate motion-ui css file is required for Orbit slider

### PR DESCRIPTION
**Pull request by seanmavley**
Although Motion-UI is required for proper functioning of Orbit Slider, wasn't clearly stated
http://foundation.zurb.com/sites/docs/orbit.html#using-animation

### CODE REVIEW

**Comment by brettsmason** [comment]
@seanmavley Thanks a lot for doing this, all looks good!

**Comment by seanmavley** [comment]
Will do soon

**Comment by brettsmason** [comment]
@seanmavley Sorry for the delay. Yes you would need to do a new PR and target the develop branch. Sorry I should of explained that. I'll close this but I'll merge the new PR when you get a chance to do it. Thanks :+1:

**Comment by brettsmason** [comment]
@seanmavley My fault on this, docs changes are actually fine on the master branch, so I'm merging this!

**Pull request merged**
