### PR TITLE
Make Grid Page Styling also like flexbox utilities!

### PR DESCRIPTION
**Pull request by IamManchanda**
@kball This is as per the discussion we had while working on flexbox utility page 
PS: Cant do a PR for master coz of 22 other commits!

This adds colors to XY Grid page to make it interactive same like 
http://foundation.zurb.com/sites/docs/flexbox-utilities.html

### CODE REVIEW

**Comment by rafibomb** [comment]
I agree - these follow brand colors and make it easier to visualize. I'd like to go a step further like: https://codepen.io/rafibomb/pen/XgZgNM?editors=1100 or https://codepen.io/SitePoint/pen/dPqqvN

Or something that shows padding/margin well https://codepen.io/marcolago/pen/lqGFb?editors=1000

**Comment by rafibomb** [comment]
You can merge master into your branch, then submit a PR

**Comment by kball** [comment]
Gonna turn around a patch today so will be merging develop to master anyway.

**Comment by IamManchanda** [comment]
@rafibomb I like it! I will think on this... this weekend and let you know with a PR!

**Pull request merged**
