### PR TITLE
Update `dist` folder path for `foundation.min.js`

### PR DESCRIPTION
**Pull request by flexbox**
The tree have changed 😉 

capture d ecran 2017-07-01 a 10 32 44

### CODE REVIEW

**Comment by IamManchanda** [comment]
Thanks Flexy, you are right 
but this section http://foundation.zurb.com/sites/docs/javascript.html#installing
doesn't explicitly means the Zurb Template here! 

I am not sure David... cc @kball for decision on this!

**Comment by kball** [comment]
@flexbox Awesome screenname. :) I concur with @IamManchanda that this does not explicitly apply to the way this is packaged, however if it is confusing as it stands perhaps we should make it explicit, maybe break out a couple variations based on how you installed?

This page in general could use some iteration and improvements... would happily take more submissions to improve it, else will attempt to find time for it. @flexbox do you want to take another pass on this maybe separating out explicitly a couple of install paths (download from site vs install via npm)?

**Comment by IamManchanda** [comment]
Hahaaa now @kball is excited with **Flexbox**

**Comment by flexbox** [comment]
@kball Challenge accepted! You can assign me on this 🚀

**Comment by IamManchanda** [comment]
Any updates @flexbox ??

**Comment by flexbox** [comment]
Hello @IamManchanda 
Sorry for the late answer I was on off-the-grid vacation 
🌞 and 🎵 Live event can't win against 👨‍💻 

I am back to work now so I can fix this issue next week 😉

**Comment by flexbox** [comment]
Hello @IamManchanda 
I tried to find some free time to work on this but I can't -_-
I am learning `react-native` and I can't work on open-source for now 
Sorry about that

**Pull request closed without merging**
