### PR TITLE
Update responsive-accordion-tabs.md

### PR DESCRIPTION
**Pull request by brockduncan**
changing the first example code to match the markup below

Before submitting a pull request, make sure it's targeting the right branch:

- For documentation fixes, use `master`.
- For bug fixes or new features compatible with the next version, use `develop`.
- For bug fixes incompatible with `develop`, use the support branch of the latest compatible version, which will be formatted `support/6.x`.

If you're fixing a JavaScript issue, it would help to create a new test case under the folder `test/visual/` that recreates the issue and show's that it's been fixed. Run `npm test` to compile the testing folder.

Happy coding! :)

### CODE REVIEW

**Comment by brock-duncan** [comment]
The first example code block has the data-responsive-accordion-tabs values in the wrong order.

**Review by IamManchanda — APPROVED** [review]
Correct, Thanks .. Approved.

cc @kball for merge!

**Comment by kball** [comment]
I'm confused... there's nothing wrong with the first example. It is demonstrating that you can do these in any order.  What am I missing?

**Comment by brock-duncan** [comment]
responsive_accordion_tabs___foundation_for_sites_6_docs
Oh okay, I just thought this was a typo and not intentional.

**Comment by kball** [comment]
Ah got it... makes sense. I'd like to show both cases, so I'd prefer we extend the examples to have both examples shown as HTML

**Comment by kball** [comment]
@brock-duncan did you want to extend this PR to do as discussed above?

**Comment by brock-duncan** [comment]
@kball yes please, I'll get this done today.

**Comment by IamManchanda** [comment]
@brock-duncan You should look to show both examples one by one 
Currently you are give of both ,,,, and later showing 1st code's example
This should be changed.

For reference => https://github.com/zurb/foundation-sites/commit/b3a39f5d09f327ae51d8bd0c6426b5b422731b8b

**Comment by kball** [comment]
Great, merging! Thanks @brock-duncan! And congrats on your first merged PR

**Comment by brock-duncan** [comment]
Awesome! Thanks @kball and @IamManchanda ! 🍻

**Pull request merged**
