### PR TITLE
docs: fix example for custom validator

### PR DESCRIPTION
**Pull request by lirael**
Foundation initialization was misplaced in the example, hence it was confusing. Discussed in #9773.

### CODE REVIEW

**Comment by DanielRuf** [comment]
I guess you have to rebase, and create the branch from master.

**Comment by DanielRuf** [comment]
Thanks for your contribution. But I'll close this one. Let me know if you need help and I'll give you the needed steps to create a new, clean branch.

**Comment by DanielRuf** [comment]
You have to use the master branch for the docs.

Try the following:
```sh
git checkout master
git checkout -b docs/abide-fix-custom-validator-foundation-initialization
git cherry-pick 10eeb3555ef087749bec7534adc642ced2bc4e51
git push -u origin docs/abide-fix-custom-validator-foundation-initialization
```

Then select the master branch as target.

**Comment by lirael** [comment]
@DanielRuf thanks for all your explanations and help! New PR #11035

**Pull request closed without merging**
