### PR TITLE
Prevent Tooltip from evaluating scripts, which may lead to XSS!

### PR DESCRIPTION
**Pull request by abods**

### CODE REVIEW

**Comment by TrevorBramble** [comment]
@abods This looks like it may have been fixed in v6. Could you re-target your patch against the `V5` branch?

@gakimball, @arthurzurb, @rafibomb is that all it'll take to get this patch in?

**Comment by gakimball** [comment]
@TrevorBramble @abods Yes, older pull requests need to compare against `V5` now.

**Comment by rafibomb** [comment]
Hi - thanks for the PR! We still want this to go into Foundation 5 and we'll be pushing a patch next week. Are you able to re submit on the V5 branch so we can get it in? Thanks!

**Comment by gakimball** [comment]
Closing in favor of #7359

**Pull request closed without merging**
