### PR TITLE
Set colors if values are not already set

### PR DESCRIPTION
**Pull request by timgremore**
## Description

SASS supports conditional variable assignment with the `!default` flag. Adding `!default` enables developers to assign project-specific values without editing foundation `settings.scss`.

[SASS variable defaults](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [x] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by SassNinja** [comment]
Thank you @timgremore for the PR!

But to be honest I don't see why this is necessary.

The settings file is not meant to be overridden but overrides the sass components (which use `!default`) itself.
It's an optional file for copy & paste to easily adjust the frameworks variables.

**Comment by timgremore** [comment]
@SassNinja I'm trying to avoid editing the settings file directly so future upgrades to Foundation can be made without the need to reconcile my settings with the new version. Generally speaking, maintaining my project settings apart from library settings is a helpful separation of concerns. And since there is no cost to using `!default`, I think it's worth considering.

**Comment by SassNinja** [comment]
> I'm trying to avoid editing the settings file directly

Then just don't use it!
It's just an optional file to make it as easy as possible to customize foundation.

Since your PR adds `!default` to some colors I assume you're overriding those colors in your own sass code?
If so just create your own settings file where you only specify / override the desired colors to be as future safe as possible.

It doesn't make sense to use `!default` in a file that is not meant to be overridden by other sass code.

**Comment by SassNinja** [comment]
> The colors defined in settings are referenced in other assignments in the same file 

It doesn't matter when you don't import that settings file yourself.
Foundation does **not** import that file!

If a component uses `$light-gray` it does **not** rely on the settings file but on a global variable (which already uses `!default`)
https://github.com/zurb/foundation-sites/blob/develop/scss/_global.scss#L37

For my projects I always use a settings file because it's easier to adjust some variables if you don't need to look them all up first. Upgrading is not much complicater bcz of it.
But if you prefer to not depend on such a settings file it's also fine.

Again, the settings file you've adjusted in your PR does not affect foundation unless you import it yourself.

**Comment by timgremore** [comment]
@SassNinja Thanks for pointing out `_global.scss` - I had missed that obviously. Thanks again!

**Pull request closed without merging**
