### PR TITLE
Fix auto in a way it doesn't break sizing classes

### PR DESCRIPTION
**Pull request by kball**
Fixes issues introduced by https://github.com/zurb/foundation-sites/pull/10139

CC @brettsmason @rafibomb

### CODE REVIEW

**Comment by kball** [comment]
Testing this further, this breaks Safari for vertical auto grids (Safari has a wonderful flexbug where if height is 0, even though flexbox resizes, all children are set to height 0), so this solution won't work... sadly I'm starting to think we might need to explicitly set flex basis in sizing classes

**Comment by kball** [comment]
Hmmm... digging into this more I realized - if auto is changing the flex basis, it means that to work properly responsively in interaction with auto, ALL of our responsive classes will have to change the flex basis.

Given what I was seeing above, I think we can limit this to the y-grid, which helps cut down our outputted CSS a bit, but... GRRR... would love to find a solution that lets us leave flex basis auto throughout.

**Comment by kball** [comment]
Ok, took another pass on this in a way that uses the `width:0px` approach on horizontal and resets flex basis for vertical... this appears to work across Chrome, Safari (major problem child on these grids), IE10, and Firefox. It increases CSS size (pre-minification) by about 9k, all of it in the vertical grid (so if you don't need vertical you can drop the weight)... applying the "right" flex basis change across the board increased weight by 30k pre-minification.

@brettsmason definitely need your eyes & thoughts on this one.

**Comment by brettsmason** [comment]
@kball Will take a look tonight - feel free to prod me then!

**Comment by brettsmason** [comment]
I'm wondering if we can do this a different way with some clever CSS... Not sure what yet, but I was thinking something along these lines (sizes generated from the breakpoints):
```
.grid-y > .cell {
  flex-basis: 0px;
}

.grid-y > [class^='small'],
.grid-y > [class^='medium'],
.grid-y > [class^='large'] {
  flex-basis: auto;
}
```
Also I think there might be a bit of confusion here, in that the base cell class uses the `full` attributes, rather than `auto` unless I'm misreading everything. Lets discuss later!

**Pull request closed without merging**
