### PR TITLE
Disable text-decoration on reveal-close

### PR DESCRIPTION
**Pull request by mik-laj**

### CODE REVIEW

**Comment by rafibomb** [comment]
Thanks! Can you describe the scenario where this change is helpful?

**Comment by mik-laj** [comment]
It is important for me, because I have set $anchor-text-decoration: underline. It looks ugly. This icon is sufficient information that the object requires action. Everyone knows that the button in the corner is used to close. Underlining the icon is very misleading.

**Comment by rafibomb** [comment]
👍Agreed - this should not be applied in a modal close.

**Comment by mik-laj** [comment]
pic related: http://imgur.com/tXodw78

**Pull request merged**
