### PR TITLE
chore: Update all zurb.com urls to get.foundation

### PR DESCRIPTION
**Pull request by joeworkman**
## Description

this updates all URLs in comments and links to use the get.foundation URL instead of foundation.zurb.com

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

### CODE REVIEW

**Review by DanielRuf — COMMENTED** [review]
How where the dist files updated? They should be only updated on release imo. Can you revert the dist files?

The rest looks fine.

**Comment by DanielRuf** [comment]
Please also resolve the code smell:

https://sonarcloud.io/project/issues?id=foundation_foundation-sites&open=AXATPDuA0vu5ZU3k4KCd&pullRequest=11987&resolved=false&types=CODE_SMELL

**Comment by joeworkman** [comment]
I didn't even think about the dist files. I can revert those. I did most of these changes via terminal commands. I just did pattern matches and blanket replaced most things.

**Comment by joeworkman** [comment]
This is only getting into the develop branch. Whenever they get merged into master, the dist branch will get rebuilt from scratch anyways. Its easy enough to revert those files though.

**Comment by DanielRuf** [comment]
> I didn't even think about the dist files. I can revert those. I did most of these changes via terminal commands. I just did pattern matches and blanket replaced most things.

They will be updated with the next build. We should never touch them =)

**Comment by joeworkman** [comment]
I reverted the dist folder changes. good catch.

**Review by DanielRuf — APPROVED** [review]
LGTM

**Comment by DanielRuf** [comment]
Just one thing left: https://github.com/foundation/foundation-sites/pull/11987#issuecomment-582255566 (touched files are checked)

We can safely remove this.

**Pull request merged**
