### PR TITLE
fix: finish running animations - closes #12044

### LINKED ISSUE #12044: [Bug][6.6.2] Accordion height for pre "is-active" accordion item not correct
## Expected Behavior

In previous versions (<6.6.2) the accordion works as expected.
We have a nested accordion where the first level is always closed but the second level gets an "is-active" css class at the accordion-item (on page load)  if the user has some filter previously activated. Before the upgrade to 6.6.2 if we open the first level accordion the second level was opened as expected but now the height and elements in the second level are broken.

6.6.2 with "is-active" on page load:
image

6.6.2 for all additional accordion items which has not set the is-active class on page load.
image

All versions before 6.6.2 shows our accordion correctly like the second case above. (Opened and correctly calculated height)
If i downgrade to 6.6.1 / 6.6.0 / 6.5.3 our accordion is working normal.

## Current Behavior

The height is not correctly if the "is-active" class is set before the page is rendered.
The accordion looks broken.

## Possible Solution

Currently i dont know how to fix it (expect to downgrade the version)

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/DarkStaRX/pen/VwvZBGx
I set the css class "is-active" above the headline "Test 1.1"
If you open the first accordion you will see height problems with the first (currently active) accordion. this just happens if you set the is-active class on the element by yourself. all other accordions working correctly.
 

How to reproduce:
1. Create a new accordion
2. Create a new nested accordion in the first one.
3. Set the active class on the first nested accordion.
4. Create a addition nested accordion below the active accordion
5. see the result ist broken for the active accordion

## Context

Nested accordions to provide links for different categories. Working currently on production in a lower version of foundation.

## Your Environment

- Foundation version(s) used: 6.6.2
- Browser(s) name and version(s):  Chrome 80.0.3987.163
- Device, Operating System and version: Windows 10 1809 (OS Build 17763.973)
- Link to your project: Private Repository

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

This Pr fixes the regression caused by using `stop()` instead of `finish()`.

- Closes #12044

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
@joeworkman we need a new release then as this fixes some issues caused by the last release.

**Comment by joeworkman** [comment]
Sure. do we need any others besides this one?

**Comment by DanielRuf** [comment]
Probably just this one here. Not sure about the download link https://github.com/foundation/foundation-sites/pull/12042 as the current zip download link throws an error.

**Review by joeworkman — APPROVED** [review]
I was not aware of .finish(). that is definitely better.

**Comment by joeworkman** [comment]
Do we want to get the browserstack build working?

**Comment by DanielRuf** [comment]
> Do we want to get the browserstack build working?

It works / runs after the merge ;-)
GitHub does not share the secrets with forks which is ok that it fails here. This is why we also should have master and develop for releases. So it will run on `develop` after this. And when you do a new release it should be fine then.

**Comment by joeworkman** [comment]
OK. So we want to release 6.6.3 with just this and the download fix?

**Comment by DanielRuf** [comment]
Exactly.

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-v6-6-3-released/2095/1

**Pull request merged**
