### PR TITLE
added extra searches for [data-tabs-target] when determining target tab…

### PR DESCRIPTION
**Pull request by lvl99**
I've added in extra selectors to target the `data-tabs-target` attribute when searching for a tab panel's link in the `data-tabs` component, to ensure that any use of public method `$('#example').foundation('selectTab', '#tab-panel-id')` can find the tab link to then show via the `_handleTabChange` method.

I originally reported on this here: https://github.com/zurb/foundation-sites/issues/10613

### CODE REVIEW

**Comment by kball** [comment]
Awesome, thanks @lvl99! I think this makes a lot of sense; I'd like to see an example of this new behavior in either the docs or in a visual test. Can you put that in? Here's a pointer to how to add a visual test: https://github.com/zurb/foundation-sites/wiki/Testing-Guide#visual-regression-tests Thanks!

**Comment by lvl99** [comment]
Hiya @kball, just only saw your message now. I've added the visual regression test for the tabs target issue.

**Review by ncoden — APPROVED** [review]
LGTM ;)

Sorry for the late review @lvl99. I don't know this component well so i'm not merging this right now, but we'll merge this soon.

**Review by Owlbertz — APPROVED** [review]
LGTM

**Comment by ncoden** [comment]
Thanks @Owlbertz.

@lvl99 Thank you for your first contribution ❤️

**Pull request merged**
