### PR TITLE
docs: remove unnecessary !default flag in button config examples

### PR DESCRIPTION
**Pull request by cdang3**
## Description

Docs: removed unnecessary !default flag in button config examples
...

- Closes 

## Types of changes

- [X] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] The pull request title and template are correctly filled.
- [X] The pull request targets the right branch (`develop` or `develop-v...`).
- [X] My commits are correctly titled and contain all relevant information.
- [X] I have updated the documentation accordingly to my changes (if relevant).
- [X] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @cdang3, thanks for your PR. Please amend it and change the title of the commit to describe what it does.

**Comment by cdang3** [comment]
Hi @DanielRuf, I have changed the title of the commit.

**Comment by DanielRuf** [comment]
What exactly do you mean with `typos`?
Do you ,ean that the `!default` is not needed?

Keeo in mind that this is standard Sass.

**Comment by DanielRuf** [comment]
https://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default

PS: The commit message is still not changed.

**Comment by cdang3** [comment]
Yes, when I had !default in my Sass file, it did not work for me so I thought it was a typo. If not, then please ignore.

**Comment by DanielRuf** [comment]
See https://foundation.zurb.com/sites/docs/button.html#custom-colors

> If you're using the **Sass version** of Foundation, you can customize the button classes **by editing the $button-palette map in your settings file**.

https://github.com/zurb/foundation-sites/blob/master-v6.5/scss/settings/_settings.scss#L298

But it seems we do not use `!default` anymore and just forgot to update this section.

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
Please run `git commit --amend`, change the commit message and do `git push -f`.

`Update button.md` is not helpful.
Also please fill out the issue template.

**Comment by DanielRuf** [comment]
You can use following PR title and commit message:

`docs: remove unnecessary !default flag in button config examples`

**Comment by cdang3** [comment]
Okay all updated :)

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
