### PR TITLE
known issue "Abide - custom validation slow" #6547

### PR DESCRIPTION
**Pull request by ghost**
I fixed some 4 spaces to 2 spaces and some spelling errors in the code.
nothing major there. But I also fixed the abide to be faster by lowering
the check time from 1second to 1/10th of a second. This resolves the
feeling of lag and does not seem to hinder any other function that I am
seeing. This does not resolve the 3 times execution as of yet. but as of
now does resolve the speed issue.

### CODE REVIEW

**Comment by caycek** [comment]
Trying to fix two problems here with abide... Speed was my first priority. Hopefully you feel this is fixed. I do not see any major drawbacks in the way that I'm using it,  but cannot think of an issue which would cause it to be a poor push. Also, the fix with the equalTo check.... I just realized as I was typing this an error that could happen so that is the Hot fix. The check now goes back and finds any elements in the same form that have the id value set to X if so then it checks their value and so on so forth. 

Questions or concerns please let me know.

**Comment by rafibomb** [comment]
Love the PR! Thanks! Only thing we think should be changed is the timeout. We added a little documentation for it just now, we think the default should be left at 1s. It's a useful feature and not that it's pointed out in the docs (when we deploy) people can set it themselves.

**Comment by caycek** [comment]
That's understandable. I thought that might be the case! Do you want me to change it back to 1s or would you prefer to do that yourself?

Also, I could look into building an option into this build if you wanted me to. Not sure how that would work off the top of my head, but if not it can be left for 6 later. Let me know!

**Comment by caycek** [comment]
@rafibomb Hey hope you're well. It has been some time since this was posted. I wanted to double check if / when you guys do accepting of pull requests. I did my branching incorrectly and only now finally understand how to do branching more correctly. If this has limited your ability to merge this request I can go through and reapply the changes or do what is needed on a separate branch.

Let me know when you can!

Thanks!

**Comment by rafibomb** [comment]
We just need the conflicts cleared and we're good to go!

**Comment by zurbchris** [comment]
Thanks for the contribution!

**Pull request merged**
