### PR TITLE
[WIP] fix: fix ES6 plugins webpack build

### PR DESCRIPTION
**Pull request by ncoden**
Bug introduced in https://github.com/zurb/foundation-sites/pull/10864

Changes:
* Export the mutated `Foundation` object and the plugin in every plugin entry

### CODE REVIEW

**Comment by colin-marshall** [comment]
@ncoden this fixed all but 1 of the `TypeErrors`. I am left with this one:
```
Uncaught TypeError: Foundation.Magellan is not a constructor
```

Because of this, the table of contents menu still doesn't work on the docs when I build them. The error traces back to this line:
https://github.com/zurb/foundation-docs/blob/master/js/docs.tableOfContents.js#L23

**Comment by ncoden** [comment]
Related to https://github.com/webpack/webpack/issues/4824

**Comment by ncoden** [comment]
So `develop` is broken because I am too stupid to test correctly a PR before merging it.

The problem in this issue is:
1. Webpack transpilation to UMD require a particular format for `externals` (see https://webpack.js.org/configuration/output/#module-definition-systems).
2. Exports in Foundation plugins are "named" (and not defaults), so importing them as  `external` require to make external targets objects (in which we can pick up the named plugin). (see https://github.com/zurb/foundation-sites/pull/9965/commits/abfd426baaeb510b9e2d06a82b902036402b1d39)
3. External format for UMD does not support the "object target".

**Comment by ncoden** [comment]
To do:
[ ]: temporary disable UMD bundling (#10911)

Then, there is multiple paths we can take to resolve this issue:
* switch to Rollup (but I'm not sure if it will resolve this problem)
* patch webpack (difficult!)
* create a plugin for webpack to add the missing feature (even more difficult!)

**Comment by ncoden** [comment]
So I was writting an issue to webpack, and explaining the problem helped me (as often) to understand what we're doing wrong.

On a side, we want to use **named export**, so we see each plugin file not as the whole plugin, but as a container for the plugin.
On the other side, we want to import externals as the plugin itself (stocked in `window.Foundation.*`). This was resolved by the `externals: { './foundation.core`: { Foundation: window.Foundation }, ...}` trick  because we were creating the "container" on the fly from (for this example) `window.Foundation`.

So: the solution is to bundle each generated file in its own webpack "Library": webpack embed all the file exports in a dedicated object. This is the container we want. So we use that "Library" as external instead of `window.Foundation.*`.

I have a solution that seems to work. I need to make some more tests and optimizations before commiting.

**Comment by ncoden** [comment]
Closing this in favor of https://github.com/zurb/foundation-sites/pull/10930

**Pull request closed without merging**
