### PR TITLE
Add options to unstripe Tables

### LINKED ISSUE #8237: [Tables] row stripes via class
Should the default style of table rows be striped? Seems like it'd be more useful as a `.striped` class, so it'd work just like `.hover`. 

As-is, if you want some (not all) tables striped, it takes a bit of custom work. 

I propose we ~~add `border-bottom: $table-border` to rows, remove the `border-bottom` on the table, and move the `:nth-child` styles to a `.striped` class~~ add a `$table-is-striped` variable that, if set to `true` creates an .unstriped class, and if set to `false` creates a .striped class. 

If :+1:, I'll PR.

### PR DESCRIPTION
**Pull request by andycochran**
Closes #8237.

### CODE REVIEW

**Comment by andycochran** [comment]
@brettsmason Do you have any feedback on this? I'm not sure I got the mixins right to be able to include them with `@include table($stripe);`.

**Comment by brettsmason** [comment]
Nice job @andycochran!
I've just pulled down this PR to check it over. One thing I noticed in the docs - you have `unstriped` and `hover` on the unstriped example. I'd suggest removing the `hover` class to avoid any confusion of what it should look like.

I also noticed this in the default css:
```
table.unstriped tbody {
    background-color: Blue;
```
Is the blue colour supposed to be there?

Finally this is the first time I've actually looked at the table Sass file. Wouldn't the internal mixins be better as public ones, so we could apply `-zf-table-stripe` (or just `table-stripe`) semantically to any table we wanted?

I might be wrong on all this as this is the first time I've really looked over this file.

**Comment by andycochran** [comment]
@brettsmason Ack! That `blue` is a holdover from some debugging I was doing. I'll nix that. The reason I put hover on the unstriped table was to make sure they still worked together, also checking it w/ ``$table-is-striped:false` and `striped`.

**Comment by andycochran** [comment]
@brettsmason Maybe I should just add the hover class to the code snippet so it matches the example.

**Comment by brettsmason** [comment]
Yeah as long as they match that's fine by me

**Comment by andycochran** [comment]
I decided to remove hover from .unstriped table example. Folks might use the copy button and unintentionally get the hover class. But hover and stripes do play nice.

**Comment by andycochran** [comment]
I wonder who wrote the table mixins. They're probably internal for a reason. @kball, any insight on this?

**Comment by kball** [comment]
@andycochran this appears to be the background: https://github.com/zurb/foundation-sites/pull/7454

Looks like it was more of a 'this is pretty messy and will probably change' rather than a more fundamental issue.

If you and @brettsmason are happy with this solution and think it is forward facing, we can absolutely make them public and document

**Comment by andycochran** [comment]
I'm atually not sure I see much value in any of the table mixins being public.

**Comment by kball** [comment]
ok... @brettsmason @andycochran are you happy with the state of this?  Is it ready to go?

**Comment by brettsmason** [comment]
I think the `_table.scss` file could use a bit of love in general, but the changes @andycochran made look good to go.

**Pull request merged**
