### PR TITLE
fix: remove top and bottom padding from select tags

### PR DESCRIPTION
**Pull request by DanielRuf**
This removes the unneeded paddings which conflicts with other fonts.

Closes https://github.com/zurb/foundation-sites/issues/7916

### CODE REVIEW

**Comment by ncoden** [comment]
Related to: https://github.com/TryGhost/Ghost/issues/1109

There's a lot of reports on Bugzilla about problems with line-height/padding in `<select>`, but none with this specific case.

**Review by ncoden — COMMENTED** [review]
The problem comes from a too-big line heigh (not sure if this is related an internal `line-height` property) conflicting with `padding-top`/`padding-bottom` and the `height` calculated for it.

Computed `line-height` + `padding-bottom` +  `padding-top` is too big for the calculated height, and the text overflow.

Removing `padding-top`/`padding-bottom` resolves this issue but is inconsistent with the `input`/`textarea` (`@mixin form-text`) properties (that we cannot change because `textarea` need  paddings). However I don't know if this is an issue. We can also consider top/bottom paddings as specific textarea/form elements with auto height.

TODO: report this to Mozilla.

**Comment by DanielRuf** [comment]
> TODO: report this to Mozilla.

Can you create a report at https://bugzilla.mozilla.org/enter_bug.cgi?

So should we not merge this and report this to Mozilla? Other browsers do not have this exact issue?

**Comment by DanielRuf** [comment]
This also breaks multiple select in Chrome as it changed the padding.

https://codepen.io/DanielRuf/pen/qxVOJQ

**Comment by DanielRuf** [comment]
Changed it a bit.

**Review by ncoden — COMMENTED** [review]
I don't like using `:not()` but do not have a better solution for now. I'll make some more tests across browsers before merging.

**Comment by ncoden** [comment]
The "padding" seems to work to fix the text alignement for all browsers, but it introduce a bug with the focus indicator height:

### Expected (IE 11)
screen shot 2018-04-11 at 23 34 32

### Actual

* **IE 11**
  screen shot 2018-04-11 at 23 33 08
* **IE 9**
  screen shot 2018-04-11 at 23 36 31
* **Firefox 56**
screen shot 2018-04-11 at 23 46 05

**Comment by DanielRuf** [comment]
How do you mean this? I see no wrong behavior as focus is like active / selected.
The line-height  / box height of the option has changed which is correct.

**Comment by DanielRuf** [comment]
Try native select without our styles and you see the same (as far as I remember).

**Review by ncoden — APPROVED** [review]

**Pull request merged**
