### PR TITLE
dropdown performance boost

### PR DESCRIPTION
**Pull request by dragthor**
timing went from ~65 milliseconds down to ~45 milliseconds for a long
list of items

An example: http://www.barenecessities.com/Bras_catalog_nxs,31.htm

Mobile view... the Size dropdown is now 20 milliseconds faster on desktop (even better on mobile).

### CODE REVIEW

**Comment by dragthor** [comment]
Utilizing the Chrome profiler it cuts down on recalculate style time.

**Comment by zurbchris** [comment]
This is a good fix, but, could you fix the indentation on lines 288 and 289? Also maybe set `window.innerWidth` to a variable, it's being read a few times, no reason to not save it. `windowWidth` perhaps?

**Comment by dragthor** [comment]
Okay working on it now.  I should just make another pull request?

**Comment by zurbchris** [comment]
If you work on your local fork and push to the branch you're submitting the PR from, it should auto-update the original PR.

**Comment by dragthor** [comment]
I also have similar changes to top, bottom, left, and right too that I will run through the profile, and then commit.

**Comment by dragthor** [comment]
On a related note... I am still trying to determine some calls to get height/get width that might cause invalidation/recalculation.  Not going to check in anything at this time until I am 100% sure, tested, and profiled.

**Comment by zurbchris** [comment]
Thanks for the contribution! Do send us another PR when you've tested anything new.

**Pull request merged**
