### PR TITLE
fix: keep a scrollbar on document when Reveal opens #7831

### LINKED ISSUE #7831: [Reveal] Background content width problem.
**How can we reproduce this bug?**
On reveal modal docs page
1. open any modal link

**What did you expect to happen?**
To open modal and nothing more

**What happened instead?**
When I open modal the width of content is changing

**Test case**
Open any modal link

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.
http://foundation.zurb.com/sites/docs/reveal.html

### PR DESCRIPTION
**Pull request by ncoden**
## Description

#11065 was intented to avoid double scrollbars from a Reveal modal, but removing all scrollbars when the modal opens changes the page content width and the content shift. This is a regression of #7831.

The current solution is a mix between the two previous fixes:
* Modal may have a scrollbar or not, following its content height
* Body has no scrollbar and prevent any scroll
* Document may have a scrollbar, following its content height (controlled in JS)

So the body content never shift, as the document has a scrollbar when a Reveal modal is open only if it already had one before.

## Changes:
* add the zf-has-scroll global html modifer and toggle it on Reveal opening/closing and on window resizing
* always prevent scroll on body instead of html tag like in #10583

### CODE REVIEW

**Comment by ncoden** [comment]
Poke @isapir for review

**Comment by DanielRuf** [comment]
This does probably not respect viewport changes.

**Comment by DanielRuf** [comment]
> Poke @isapir for review

Was the review request meant for @isapir or me?

**Comment by ncoden** [comment]
@DanielRuf Both

**Comment by ncoden** [comment]
> This does probably not respect viewport changes.

You're right, we should watch for viewport change. I don't like doing things like this in JS but this seems to be the only solution.

**Comment by ncoden** [comment]
Some comments to describe that "disabled scrollbar" behavior would be useful tho.

**Review by isapir — APPROVED** [review]
@ncoden @DanielRuf  It looks fine to me though I didn't test it by running.

IMO in the edge case that the viewport changes while the Reveal is open then it's OK to show a slight shift and/or disabled scrollbar.

**Comment by ncoden** [comment]
@isapir @DanielRuf I made the required changes and some refactor.

> 96141b743 docs: add doc for Reveal methods _addGlobalClasses/_removeGlobalClasses
> deda9dc3a refactor: rename Reveal internal methods for a better clarity
> 82a04933a fix: show/hide Reveal scrollbar on window resizing

**Comment by DanielRuf** [comment]
> fix: show/hide Reveal scrollbar on window resizing

I guess `orientationchange` is missing.

**Comment by ncoden** [comment]
> I guess orientationchange is missing.

Doesn't it count as a resize ?

**Comment by ncoden** [comment]
I got my answer https://stackoverflow.com/a/23996839/4317384

> Some devices/browsers do, some not.

Web development often sounds like biology classes. There's rule for everything and exception for every rule.

**Comment by ncoden** [comment]
@DanielRuf Actually I am using `resizeme` from `utils.triggers`, and the entire framework rely on this. So if we decide to use it (according to browser support), we'll not do it in this PR.

**Comment by DanielRuf** [comment]
Ok.

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
