### PR TITLE
Text inputs function with modifier (for classes and pseudo-classes)

### PR DESCRIPTION
**Pull request by michelts**
Permit to define a class or a pseudo-class for text inputs generated through the text-inputs sass function.

### CODE REVIEW

**Comment by kball** [comment]
Is this addressing a particular issue?  What's the driver?

@brettsmason and @andycochran as our sass expert yetinauts, what are your thoughts?

**Comment by michelts** [comment]
We wanted to define a custom shadow for focused text inputs but I can imagine a better situation. We could use this approach to show a hidden help text positioned after an input, like:

```
input:focus + .help-text {
    display: block;
}
```

**Comment by kball** [comment]
This seems reasonable to me. @brettsmason and @andycochran what do you think?

**Comment by brettsmason** [comment]
Yep this seems fine to merge to me 👍

**Comment by andycochran** [comment]
Nice. 👍

**Pull request merged**
