### PR TITLE
Flexbox utilities docs & Some Sass Changes!

### PR DESCRIPTION
**Pull request by IamManchanda**
This is a ~~WIP~~ PR for flexbox utilities and relating them to xy grid!

### CODE REVIEW

**Comment by IamManchanda** [comment]
@brettsmason @kball 
Just for this page i have add colors to make it interactive ... is it good idea or a bad one ??

make-flex-util-more-interactive

**Comment by IamManchanda** [comment]
@kball @brettsmason 
While moving flex helper classes i have a thought... we are having responsive classes
Why not make the responsive classes customizable by letting user disable it 
(by this we can disable it in later release like v7 also)

```scss
$flexbox-responsive-breakpoints: true !default;

.flex-child-auto {
  flex: 1 1 auto;
}

@if ($flexbox-responsive-breakpoints) {
  // Loop through Responsive Breakpoints
  @each $size in $breakpoint-classes {
    @include breakpoint($size) {
      @if $size != $-zf-zero-breakpoint {
        .#{$size}-flex-child-auto {
          flex: 1 1 auto;
        }
      }
    }
  }
}
```

**Comment by kball** [comment]
Honestly think that's probably too much, especially since primary context for this type of thing will be in the grid and it's already handled there.

**Comment by kball** [comment]
oop I misinterpreted - we have this already, and the question is to make it optional. I thought it was to add new... yes, by all means make it optional. :)

**Comment by IamManchanda** [comment]
Ohk @kball i am making it optional and also adding a **depreciation notice** in docs that responsive breakpoints will be disabled by default for these classes from 6.5 (though people can reenable it by that same var) ??

Is that sounds good ??

**Comment by IamManchanda** [comment]
Just for records, this closes https://github.com/zurb/foundation-sites/issues/10117 on merge!

**Pull request merged**
