### PR TITLE
refactor: fix mixed declarations warnings on sass-embedded 1.77.7+

### LINKED ISSUE #15506: Address sass 1.77.7+ warnings on mixed declarations with nested rules
## What should happen?

Compiling stylesheets that use foundation for sites shouldn't emit warnings.

## What happens instead?

Currently there are a number of warnings emitted due to ordering of declarations with nested elements, e.g

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
111 │ ┌   &:focus {
112 │ │     outline: none;
113 │ │     border: $input-border-focus;
114 │ │     background-color: $input-background-focus;
115 │ │     box-shadow: $input-shadow-focus;
116 │ │
117 │ │     @if has-value($input-transition) {
118 │ │       transition: $input-transition;
119 │ │     }
120 │ │   }
    │ └─── nested rule
... │
128 │       appearance: none;
    │       ^^^^^^^^^^^^^^^^ declaration
    ╵
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/forms/_text.scss 128:5  foundation-form-text()
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/forms/_forms.scss 26:3  foundation-forms()
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new_plugins/foundation_hax.scss 926:3  root stylesheet
    
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/forms/_select.scss
41  │       background-origin: content-box;
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/util/_mixins.scss
153 │ ┌   @media screen and (min-width: 0\0) {
154 │ │     @if lightness($color) < 60% {
155 │ │       // White triangle
156 │ │       background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAYCAYAAACbU/80AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAIpJREFUeNrEkckNgDAMBBfRkEt0ObRBBdsGXUDgmQfK4XhH2m8czQAAy27R3tsw4Qfe2x8uOO6oYLb6GlOor3GF+swURAOmUJ+RwtEJs9WvTGEYxBXqI1MQAZhCfUQKRzDMVj+TwrAIV6jvSUEkYAr1LSkcyTBb/V+KYfX7xAeusq3sLDtGH3kEGACPWIflNZfhRQAAAABJRU5ErkJggg==');
157 │ │     }
158 │ │     @else {
159 │ │       // Black triangle
160 │ │       background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAYCAYAAACbU/80AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAMBJREFUeNrEllsOhCAMRVszC9IlzU7KCmVHTJsoMWYMUtpyv9BgbuXQB5ZSdgBYYY4ycgBivk8KYFsQMfMiTTBP4o3nUzCKzOabLJbLy2/g31evGkAginR4/ZegKH5qX3bJCscA3t0x3kgO5tQFyhhFf50xRqFLbyMUNJQzgyjGS/wgCpvKqkRBpuWrE4V9d+1E4dPUXqIg107SQOE/2DRQxMwTDygIInVDET9T3lCoj/6j/VCmGjZOl2lKpZ8AAwDQP7zIimDGFQAAAABJRU5ErkJggg==');
161 │ │     }
162 │ │   }
    │ └─── nested rule
    ╵
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/forms/_select.scss 41:5  form-select()
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/forms/_select.scss 88:5  foundation-form-select()
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/node_modules/foundation-sites/scss/forms/_forms.scss 32:3   foundation-forms()
    file:///Users/chad/Projects/community/gocd/gocd/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new_plugins/foundation_hax.scss 926:3   root stylesheet
```

## Possible Solution

Moving the declaration above any nested declarations is usually sufficient, however if the nested declaration comes via an `@include` I believe necessary to check that the declaration isn't acting as an override for something inside the `@include` as I think this would change semantics.

If it would change semantics to move declaration higher, in that case one probably needs to use the "opt-in" syntax documented at https://sass-lang.com/documentation/breaking-changes/mixed-decls/ or refactor the way the `@mixin` is written.

## Context

No functional problems right now; just trying to keep on top of Sass deprecations as we approach 2.0.

## Your Environment

- Foundation version(s) used: 6.8.1
- Browser(s) name and version(s):  N/A
- Device, Operating System and version: N/A 
- Link to your project: https://github.com/gocd/gocd/tree/master/server/src/main/webapp/WEB-INF/rails

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by chadlwilson**
## Description

Where possible, moves mixins or declarations around in definitions or re-orders declarations where the order doesn't matter to avoid sass-embedded warnings with `1.77.7`+ as documented at https://sass-lang.com/documentation/breaking-changes/mixed-decls/

There is also discussion about this at https://github.com/sass/dart-sass/issues/2276 where a dart-sass developer refers to recommended approach being to re-order declarations where possible, and use `& {}` within mixins for behaviour that will be forward and backward compatible.

Accordingly also disables the sass-lint rule requiring mixins at the start. Without deterministically ordered mixins it's not possible to cleanly avoid interleaved declarations and nested blocks without using `& {}` everywhere. However, if maintainers would rather, this could prefer the ugly `& {}` opt-ins that will maintain the deterministic ordering, but in some cases lead to less efficient CSS as there isn't the implicit "hoisting" of declarations going on.

Methodology was to run `yarn run test` and correct all the sass-embedded warnings that appeared there.

- Closes #15506

## Types of changes

- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [x] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by chadlwilson** [comment]
@joeworkman Hi there - do you not review/accept PRs on this repo? it seems you have made other changes on master subsequent to me submitting this PR which probably makes this obsolete now.

Spent quite a bit of time on this as well as raising the issue at #15506 so would be good to know if not worth bothering in future.

**Comment by joeworkman** [comment]
Oh man, we were working on this at the same exact time! I am sorry. I was chatting about it a little on the Foundation discord channel. I will review your changes to see if there is anything that could have been different than what I did. 

I am working with the Sass team with some other enhancements. They would like to move away from `@import` to `@use`.  However, it's turning out to be a much larger change than I thought it might be. If you have any experience with this, I would love it if you could chime in on the discord chat.

**Comment by chadlwilson** [comment]
Ahh ok, this was a few days ago now.

You're certainly more of a sass expert than me so I'd defer to your judgment. In some cases I was looking for places where the declarations were overriding something in an include where reordering would change semantics (eg. some buttons). Probably similar to your approach I imagine although I did have to disable a lint rule as a result in some places.

**Comment by chadlwilson** [comment]
@joeworkman any chance of cutting a patch release with these fixes? 🙏

**Pull request closed without merging**
