### PR TITLE
getFnName unit tests ADDED

### PR DESCRIPTION
**Pull request by dragthor**
`Foundation.getFnName()` unit tests added.

### CODE REVIEW

**Review by ncoden — APPROVED** [review]
👍 LGTM, Thanks @dragthor

**Comment by ncoden** [comment]
@dragthor I seen your comment in https://github.com/zurb/foundation-sites/issues/8311#issuecomment-365765600. Do you plan to add any others tests in this PR ?

You can open/rename a PR with the [WIP] tag for all your tests.

**Comment by dragthor** [comment]
Separate PR.

**Comment by ncoden** [comment]
Ok then...

**Comment by ncoden** [comment]
Note: tests are being repaired in https://github.com/zurb/foundation-sites/pull/10943.
I tested in local, everything works great.

**Comment by ncoden** [comment]
@dragthor See https://github.com/zurb/foundation-sites/pull/10944

> I seen that failed in the tests. These tests were added today in #10941. It worked well with phantomjs.
> I'm not sure of what we should expect in this case. @dragthor do you have an opinion on this ?

**Comment by dragthor** [comment]
Let me figure this out.

Edge ""
IE11 ""
FF "B"
Chrome "B"
phamtomjs ""

**Comment by dragthor** [comment]
I need to remove the unnamed function expression test case.

**Comment by DanielRuf** [comment]
Seems some (newer) browsers use the variable name for automatic namespacing.

Is it safe to remove the unit test?

**Comment by ncoden** [comment]
As there is no consistent behavior we can expect (but just "we found a name", or "we were not able to get a name", and unless we find a polyfill (for new or old browsers), we should not test this case.

**Pull request merged**
