### PR TITLE
[Fixes #9709] Added a variable [Settings] button-hollow-border-width for border width

### LINKED ISSUE #9709: [Feature] Add setting for button hollow width
#### Current situation
Outline buttons with the `hollow` class have a fixed border width of `1px`:
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_button.scss#L151

#### What should happen:
This should be customizable with a variable in the settings. I'd recommend to introduce a `$button-hollow-width` setting.

### PR DESCRIPTION
**Pull request by IamManchanda**
Implemenation for #9709 
@kball for review 

Special Thanks: @christianseel

### CODE REVIEW

**Comment by kball** [comment]
Seems reasonable to me. @brettsmason @andycochran @ncoden any objections?

**Comment by brettsmason** [comment]
Seems reasonable to me. However I'm wondering if the variable should be `$button-hollow-border-width` just to make it absolutely clear it controls the border width. Other than that, good to go!

**Comment by IamManchanda** [comment]
You are right ..... me thought the same but after push!

**Comment by IamManchanda** [comment]
Ready to merge ? @kball @brettsmason

**Pull request merged**
