### PR TITLE
possible fix for #8690

### PR DESCRIPTION
**Pull request by designerno1**
possible fix for #8690
assign a this var with a function.bind(this) to off only the function on _pauseEvents();
@kball 
don't know if this way is best practice JS, would you please take a look

### CODE REVIEW

**Comment by kball** [comment]
@designerno1 thanks for pushing this forward, and for adding the visual tests.  I'd prefer we break these handlers out into individual handlers per events, but this approach of binding them is good practice.

**Comment by kball** [comment]
@designerno1 do you have time to take this PR and break the handlers into individual events so we can get this in and fix #8690?

**Comment by designerno1** [comment]
@kball 
really split the handlers? thats 1 more `this.var` for the bind and so for every on event to `off` we need a function
i would like to do this in vars so the _bindHandler and _bindfunctions won't be accessible from outside and don't stored on the this but i can't scope a var that's accessible from the functions, hmmmm

**Comment by kball** [comment]
I'm open to other opinions @colin-marshall @Owlbertz but from my perspective if the logic is different for each type of event we should have a handler per event, not a joint handler with a condition.  I'm more concerned with readability and maintainability than one more var on this, though if you want you could make this.handlers an object and have one per event.

**Comment by Owlbertz** [comment]
I think the second commit with the split makes it a bit more readable, and since it's now already there I guess we should go this way.

**Pull request merged**
