### PR TITLE
responsiveToggle slideToggle animation

### PR DESCRIPTION
**Pull request by pine3ree**
new js/data-attribute options:
- data-slide-toggle="true" (default: false)
- data-slide-speed="300"  (default: 250 as in accordionMenu)

### CODE REVIEW

**Comment by pine3ree** [comment]
triggering new travis-ci build for the usual npm install issue....

**Comment by pine3ree** [comment]
this could maybe be merged also into 6.3 (see https://github.com/zurb/foundation-sites/issues/8001) as motion-ui slide-in-down slide-out-up does not actually slide down/up the toggled menu in the "classic" meaning, it just moves dow/up the menu in a fixed height containing top-bar.

**Comment by ncoden** [comment]
Can we make these attributes more generic, as a way to control appear/disappear events for all utilities or components, instead of for this particular case ?

@kball Who are the Js pro Yetinauts ?

**Comment by kball** [comment]
Great question @ncoden.  @colin-marshall @Owlbertz would love your thoughts on how we can make this more generic

**Comment by DanielRuf** [comment]
Mh, can we not reuse Motion UI (classes) and use just classes which are bound to transitions / animations?

Triggering 1 event or 2 events makes much sense sense (toggle vs toggled) but the animation should be probably applied using a callback, class names or using the triggered events imo.

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback and there are conflicts.

**Pull request closed without merging**
