### PR TITLE
docs: spelling and grammar corrections

### PR DESCRIPTION
**Pull request by datatypevoid**
## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `support/*`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by DanielRuf — APPROVED** [review]
LGTM 👍

**Review by ncoden — APPROVED** [review]
Hi @datatypevoid. LGTM.

As your commits only fixes spelling mistakes in documentation, your commits should be prefixed by `docs: `.

Could you please squash them into a single commit ?

**Comment by datatypevoid** [comment]
Yeah let me pull it to my box real quick.

**Comment by ncoden** [comment]
Thank you @datatypevoid. Merging.

**Pull request merged**
