### PR TITLE
Update xy-grid.md

### PR DESCRIPTION
**Pull request by siwood**
Changing the example mixins for xy-cell to use $gutters: 0 instead of $gutters: none because none breaks gulp build

## Description

...

- Closes 

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] The pull request title and template are correctly filled.
- [ ] The pull request targets the right branch (`develop` or `develop-v...`).
- [ ] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @siwood,

Can you clarify that and provide a reproducible testcase where we can see that it fails? `gulp` an `gulp build` work for me.

**Comment by DanielRuf** [comment]
Hi @siwood,

Can you clarify that and provide a reproducible testcase where we can see that it fails?

Also please follow our commit lint rules (see contributing.md).

**Comment by siwood** [comment]
Sure, sorry about that. I'll go back and re-format this. I didn't correctly follow the contribution guidelines.

**Comment by siwood** [comment]
I'm closing this. I'm sorry i submitted this so quickly without doing more due diligence. I think this is an issue with the documentation being out of sync with the version of foundation the Drupal theme uses by default... Which I'll work on fixing from the Drupal side of things.

**Comment by DanielRuf** [comment]
Tahnks for the details (Drupal Foundation Theme).

If there is anything that we can do, please let us know.

**Pull request closed without merging**
