### PR TITLE
fix generated event name

### PR DESCRIPTION
**Pull request by DanielRuf**
As a sidenote, using the title for event names is not a great idea. We should use some variable `fn-name` or similar.

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
I don't get it. What is the link between the doc title and the event names ?

**Comment by DanielRuf** [comment]
> I don't get it. What is the link between the doc title and the event names ?

Well, run `npm run deploy:docs` and take a look at the build/drilldown-menu.html file.

**Comment by DanielRuf** [comment]
See `formatJsEventName` at https://github.com/zurb/foundation-docs/blob/master/lib/handlebars/javascript.js

**Comment by DanielRuf** [comment]
The change is already done in develop but not master where the current docs live and so the docs are atill wrong.

**Comment by DanielRuf** [comment]
Also see

https://github.com/zurb/foundation-sites/issues/9151

https://github.com/zurb/foundation-sites/pull/10555

**Comment by DanielRuf** [comment]
I hereby propose to add another frontmatter variable which is used if it is set. But probably in another PR.

**Comment by JeremyEnglert** [comment]
I thought the names were generated from the inline names/comments. Such as here: https://github.com/zurb/foundation-sites/blob/1c6ce2d69e976b8d0ead214c2b2619548466c858/js/foundation.drilldown.js#L302

If this isn't the case, the recently merged PR (https://github.com/zurb/foundation-sites/pull/10929) isn't correct.

**Comment by DanielRuf** [comment]
> I thought the names were generated from the inline names/comments. Such as here:

Unfortunately no.

**Comment by DanielRuf** [comment]
screenshot_20180212-192608 is the current status.

**Comment by DanielRuf** [comment]
And https://github.com/zurb/foundation-docs/blob/master/templates/partials/javascript-reference.hbs#L107

**Comment by JeremyEnglert** [comment]
Eeeek. Definitely something we need to address in F7. Contributing to the docs should be one of the easier things to do. 

Waiting for feedback from @ncoden, as we may have to address previous PRs as well.

**Comment by ncoden** [comment]
I'm investigating for a solution a bit cleaner.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-docs/pull/24/files

**Comment by ncoden** [comment]
See also: https://github.com/zurb/foundation-sites/pull/10933

**Pull request closed without merging**
