### PR TITLE
possible solution for #8257

### PR DESCRIPTION
**Pull request by DaSchTour**
taking first breakpoint and check if smallest and define it as zero-breakpoint

### CODE REVIEW

**Comment by gakimball** [comment]
Thanks for putting this together! My feedback:

- Name the variable `$-zf-zero-breakpoint`. The prefix emphasizes that it's a private variable—we don't need developers using it in their own code.
- You'll need to replace *every* instance of `@include breakpoint(small)` in the framework with `@include breakpoint($-zf-zero-breakpoint)`, so that if someone renames `small` in their breakpoint list, all of the internals of the framework are able to switch over to the new name.

**Comment by DaSchTour** [comment]
Thanks for the feedback. I hoped I already found all references to small, but I'll check again. I'll make the changes as soon as possible.

**Comment by DaSchTour** [comment]
I change the variable following your feedback and replaced all usages of small breakpoint. I wasn't 100% sure about one place. It's _rows.scss:83

**Comment by DaSchTour** [comment]
Is there anything more to do?

**Comment by gakimball** [comment]
Nope, looks good. Thanks for putting it together!

**Comment by proimage** [comment]
So what's the quick-and-dirty guide to implementing this change in our bleeding-edge code? Do we just add something like this to `settings.scss`:

```
$-zf-zero-breakpoint: 'small'; // or 'xsmall' or 'tiny' or 'smallest' or whatever
```

**Comment by gakimball** [comment]
@proimage That will probably work.

**Comment by proimage** [comment]
Thou assumest too muchly - I roll Foundation SCSS manually. :p

For the record, yes, after downloading the latest `develop` branch and using the `scss` folder therein, adding that one line above to my `settings.scss` appears to have brought things back to the way they were in 6.1.x. Much grass!

**Pull request merged**
