### PR TITLE
Abide hidden validation settings

### PR DESCRIPTION
**Pull request by hughkelsey**
Move the Abide validation filtering in to a setting which would allow users to specifically ignore (or not ignore) fields for validation.

Before this change ALL hidden fields are filtered out and in projects there are SOME hidden fields (those controlled by a range slider) that may require validation.

I've added specs which currently do not pass but I think that's because I'm not building the project correctly locally. I would appreciate an extra set of eyes on this and am happy to make any changes.

### CODE REVIEW

**Comment by rafibomb** [comment]
Wnat to test it for merge, can you look into the errors first?

**Comment by hughkelsey** [comment]
@rafibomb It looks like it's failing because the code is somehow incorrect. Can I ask for a more experienced set of eyes to look at the code?

**Comment by zurbchris** [comment]
This is for Foundation 5. If you were still interested in submitting this pr, please reopen and target the Foundation 5 branch.

**Comment by liyaodong** [comment]
think this is a very good solution, I think maybe we should reopen this issue.

**Pull request closed without merging**
