### PR TITLE
Drilldown feature scroll top

### PR DESCRIPTION
**Pull request by designerno1**
- adds feature ScrollTop to Drilldown Menu
  scrollTop
  scrollTopElement
  scrollTopOffset
  animationDuration
  animationEasing
#8617

### CODE REVIEW

**Comment by mesnitu** [comment]
Thanks. With the auto height feature , this drilldown is getting quite awesome.

**Comment by mesnitu** [comment]
However ( but I' quite new to foundation ) , when using a responsive navigation, say from drill down to dropdown, I'll get  

`Uncaught TypeError: Cannot read property 'trigger' of null`

But probably I'm doing it in the wrong way : 

`<ul id="mainMenuLeft" class="drilldown menu" data-responsive-menu="drilldown medium-dropdown" data-auto-adjust-height="true" data-animate-height="true" data-scroll-top="true" data-scroll-top-offset="-30">`

This is related to
` if (this == $('html')[0]) _this.$element.trigger('scrollme.zf.drilldown');`

And also the max-with. Rotating the device, the menu gets whatever first value he got.

**Comment by designerno1** [comment]
ce42487 fixes problem with destroy() thanks to @mesnitu 
havent tested it with responsive menu, this commit fixes the destroy problem on the attached handlers.
But i'am thinking of recoding the feature without attaching to the trigger handlers

**Comment by mesnitu** [comment]
That works. The only thing I had to do  was to add a 
`this.$submenus.css('height', 'auto'); `
to the destroy
For some reason, having the submenu with style height 100%, only the first <li> gets the background color. 
Not sure if this is the correct way to do it,  ( I'm not a developer ) , but now switching from drill to drop down, the submenu <ul> gets the proper background. 
Thanks

**Comment by kball** [comment]
This seems like a reasonable feature, but as it is a new feature please resubmit this PR against v6.3

**Pull request closed without merging**
