### PR TITLE
inconsistent use of active class #9657

### PR DESCRIPTION
**Pull request by jmp1548**
Change '.active' to '.is-active' for menu component.

### CODE REVIEW

**Comment by jmp1548** [comment]
The issue number from git was #9657 

Hope this is done correct. This is my first contribution. Looking for advice.

Thanks

**Comment by kball** [comment]
Thanks for putting this together! Heads down testing 6.3.1-rc1 but will dig into this as soon as we ship.

**Comment by kball** [comment]
Sorry it took me a while to get back to this. It's looking good... Can we update the visual tests for magellan with this as well? https://github.com/zurb/foundation-sites/blob/develop/test/visual/magellan/active-item.html and https://github.com/zurb/foundation-sites/blob/develop/test/visual/magellan/unordered-links.html still contain references to `.active`

**Comment by kball** [comment]
@jmp1548 will you have time to do the update mentioned above? Would love to get this in for 6.4, targeted for middle of next month

**Comment by jmp1548** [comment]
@kball yeah, I will look into it this weekend. been traveling a bit. Thanks for the update

**Comment by IamManchanda** [comment]
Just for references, we need to update this below pen once we get this to merge and release!

- [ ] https://codepen.io/IamManchanda/pen/XRYrKp?editors=1000

**Comment by kball** [comment]
All right! Going to merge this. Adding that this requires migration so we include a migration note.

**Pull request merged**
