### PR TITLE
tooltip performance (variable caching) - reveal, tab & tooltip tests added

### PR DESCRIPTION
**Pull request by dragthor**
added basic sanity tests for reveal and tab

### CODE REVIEW

**Comment by dragthor** [comment]
What happened with the Travis CI build?  It passed when I first submitted the pull request.

**Comment by dragthor** [comment]
It seems that these commits from @arthurzurb broke the build.  Looking to see what I can do about it (and this is what I get for making a pull request from master).

https://github.com/zurb/foundation/commit/d68f03fcee251e96553ffd335fa90f71b36d2ef6

https://github.com/zurb/foundation/commit/413f077ac1fe479d8dd8959a1ca6d9c04176560c

**Comment by dragthor** [comment]
Still unsure why the Travis CI build is failing on changes not related to mine.  Is it @a-dg with https://github.com/a-dg/foundation/commit/7b5d6b08cac39f1968546d1ab47bd035ce6858eb

**Comment by rafibomb** [comment]
We'll be testing this today for a merge. We'll let you know if any changes should be made. Thanks!

**Comment by zurbchris** [comment]
Great PR, thanks for the contribution!

**Pull request merged**
