### PR TITLE
Use $callout-font-color-alt in _callout.scss

### PR DESCRIPTION
**Pull request by IllusionPerdu**
Resolve problem with font color in dark background and use  $callout-font-color-alt ;)

### CODE REVIEW

**Comment by kball** [comment]
Seems reasonable to me - @andycochran what do you think?

**Comment by andycochran** [comment]
Nice, @IllusionPerdu! This is a good use of the new `color-pick-contrast()` function.

**Comment by andycochran** [comment]
I think this PR is okay to merge. But it makes me think of a couple things. 

- Default-colored links do not meet AA contrast requirements in Callouts with non-white backgrounds. The primary blue is just barely dark enough to meet AA requirements on white. 

- Links in Callouts should get an accessible color. @wolfgang-demeter pointed this out in #9098, for which @ncoden had some great insight.

**Comment by kball** [comment]
Ok gonna go ahead and merge this.  Do we think #9098 captures enough info to address these 2 issues?

**Pull request merged**
