### PR TITLE
fix: remove duplicate border-left-width:0 in drilldown

### PR DESCRIPTION
**Pull request by DanielRuf**
## Description

There is a duplicate `border-left-width:0` in the generated files. This fixes it.

- Closes 

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

### CODE REVIEW

**Comment by ncoden** [comment]
I don't think that it was needed to open 4 seperate PRs for that (it's the same fix: removing duplicate properties). Anyway, thank you!

**Review by ncoden — APPROVED** [review]
LGTM 👍.

@DanielRuf next time please open a single pull request for all similar changes.

**Comment by DanielRuf** [comment]
> @DanielRuf next time please open a single pull request for all similar changes.

Well, imo these should be atomic otherwise the description would be much longer and the changeset bigger and harder to review.

**Comment by ncoden** [comment]
> style: remove various duplicated CSS properties

**Comment by DanielRuf** [comment]
> various

Not what I expect from a self-describing commit message ;-)

**Comment by ncoden** [comment]
True. But it's still better than 3 micro-commits ;)

**Pull request merged**
