### PR TITLE
Fixed #10333

### LINKED ISSUE #10333: Error on `rounded` prototype when breakpoint is enabled
#### How to reproduce this bug:

1. `settings.scss`
```scss
$global-prototype-breakpoints: true;
```

2. Step two
```scss
@include foundation-everything($prototype: true);
```

#### What happened instead:
```
            @include rounded-radius;
                    ^
      No mixin named rounded-radius
```

#### Foundation Version(s) you are using:
6.4.1

### PR DESCRIPTION
**Pull request by hikouki**
Fixed #10333 🍣

### CODE REVIEW

**Comment by IamManchanda** [comment]
Thanks @hikouki ... let me dig in and merge it!

**Review by IamManchanda — APPROVED** [review]
:+1:

**Comment by IamManchanda** [comment]
Awesome work @hikouki 
See if you would want to take up #10106 also ??

**Comment by hikouki** [comment]
Thank yout for merge! ✈️ 

I'd like to contribute it.
But, I can't write English well. :bow:
I think it is difficult. Sorry...

**Comment by kball** [comment]
Awesome! Congratulations on first merged PR @hikouki!

**Comment by IamManchanda** [comment]
Not an issue @hikouki What we care is writting code instead of English :wink:

**Comment by IamManchanda** [comment]
You try once ... I am there to help you out @hikouki in english/code/etc!

**Comment by hikouki** [comment]
Okay, I'll give it a try.
Thank you for giving me a chance!

**Pull request merged**
